### ISSUE TITLE
Quoting is Broken

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1059]
If > is the first character, everything on that line should be green.

I often have cause to quote someone or something who used characters that the latest regex arbitrarily deems unquotable.

**Comment by dubslow** [comment]
It uses the \w group. Can you give an example of things that should be quoted but aren't?

The absolute rule that you state was deliberately changed due to #945.

**Comment by ProMcTagonist** [comment]
No longer stripping leading spaces allows non-green single-text-emoticon-only messages if you dislike the quote color. @zetok's solution to #945 was simple and didn't break quoting.

Quotes starting with . \* ; + = etc are common when discussing code, and they aren't allowed anymore. And quoting anything in quote marks is also broken right now.

It's just sort of silly to turn off quoting only for some symbols.

**Comment by dubslow** [comment]
At this point it's just a debate about what's more intuitive to how many people. I made the executive decision that adding a space before smileys, while certainly very intuitive to us here on GitHub, wouldn't make sense to the average user, where by average user I mean your neighbor's grandmother. It's also a good compromise for those who would prefer to remove green text entirely, of which obviously there are some.

I'm willing to change this again in the face of overwhelming support.

Maybe one thing you could do is try and come up with a standard for all Tox clients to follow. Such a standard would presumably have widespread support, or at least majority support. If that standard is as you suggest here, then I'll change it. (Or if tux3 overrules me lol)

**Comment by ProMcTagonist** [comment]
Adding a space isn't very intuitive, but it's also not necessary. The only person who got upset that text smilies are occasionally tinted green is stqism and he's probably just bored or trying to be funny.
Occasional green text smilies are not a problem; disallowing quoting of a large amount of things is. 

On top of that, by default users have graphical emoticons displaying instead of text emoticons, and those aren't affected at all by quoting. So quoting has been broken for a lot of users, for no benefit at all to our average grandma user, who happily sees cute yellow smiley faces no matter what.

Perhaps quote coloration will be customizable more easily once easy theming is implemented. I'm in favor of users choosing what they see and receive.

**Comment by dubslow** [comment]
The whole point of #945 is that green smileys were an issue. Grandma may use >.< and be confused why it's green. Though I admit I'm rather more persuaded now...

**Comment by stqism** [comment]
Howdy folks, if you don't mind I feel like I need to address an issue being ignored here.

The people we see who want features like green texting and other things like using Tox to replace IRC represent something called the vocal minority of Tox users. These represent a tiny subset of users who've been with us from early on and visit sites like 4chan where green texting may seem normal, but do not represent the bulk of Toxes users.

What we're doing here is ignoring the majority of our users. We're ignoring the people who put us where we are, make up the bulk of our users, the silent majority that is effected most by these decisions.

I've spoken to a good number of Tox users from a variety of places and often asked how they've heard of the project; I got answers like reddit posts, the Linux action show, and the FSF interview. Very few people outside of people who follow the project closely on Github and in threads actually use 4chan or understand concepts like green texting that I've spoken to in my almost 2 years of supporting users.

A little story on the idea of the vocal minority, when Microsoft made visual basic 6 it was pretty widely adopted all around and especially in Enterprise. A few years later the people who replied to blog posts, posted in discussions, and participated with Microsoft and the language demanded the language get tons of new features and abilities they could use. Microsoft followed suite with the voice they heard not understanding that this was the minority and effectively alienated the majority of their Visual Basic 6 users who enjoyed and appreciated the simplicity. To this day Visual Basic 6 apps run on Windows 10 out of box but Dot Net 1 apps don't work on 7.

I know it may seem like I'm trying to be funny by not supporting a feature that a vocal minority uses frequently, as summed up by "The only person who got upset that text smilies are occasionally tinted green is stqism and he's probably just bored or trying to be funny.", but I need you to understand that I represent the unspoken majority voice that makes up our users. I've spent a good deal from the beginning helping people use Tox, get started, and fix issues they have and I've seen first hand this majority we're hurting here.

I have a solution to the issue that would appease both the vocal minority and silent majority though. A setting to enable the feature that's left off by default gives both groups the best of both worlds without ruining the experience for both sides.

I appreciate your thoughts and feedback on my proposed solution.

Thanks as always, Sean

**Comment by suhr** [comment]
There's a simple compromise: greentext everything that starts with `>( |\w)`. So you can highlight any message by putting `>` and space before it, and highlight text just by using `>`. But messages that starts with a smile won't be highlighted.

EDIT: replace `\w` with something that doesn't match `_`

**Comment by zetok** [comment]
@stqism 

> (…) but I need you to understand that I represent the unspoken majority voice that makes up our users.

That's what you claim.

Even if claim is true, it still doesn't mean that you are right. Not so long ago you were opposed to replacing current groupchats. Why were you doing it? Probably because **you** were convinced that there isn't much of need for them.

Funny fact: you're almost never in groupchat, thus you don't see people coming there, saying that current groupchats suck… and would go away unhappy about how Tox works if not reassured that groupchats are being remade to include important features they should have.

While you may **think** that you represent unspoken majority, are you really doing it?

Even if people currently don't know about greentexting, it is no way implied that they can't learn about it, since is easy to do so, and doesn't require any effort. Not to mention that `>` is used in places outside of 4chan to quote things.

> (…) this majority we're hurting here.

Please stop.
How exactly greentexting is hurting anyone?
Eh. I get that you're trying to get your point in this issue, and that at the same time generally speak about why you're doing what you're doing. It may be the case in some other issues, but I hardly see how greentexting could do that. Mind providing a real example? Otherwise it would be just FUD…

If you're so concerned about features, you really should go brag about no screenshot/video streaming feature in qTox, since that's the feature people find really useful… So called "unspoken ~~minority~~EDIT: majority".

---

> A setting to enable the feature that's left off by default gives both groups the best of both worlds without ruining the experience for both sides.

Sadly, qTox already has plenty of settings, which IMHO should be limited as much as possible, since they're not user-friendly.

Thing with greentexting… yes, it could be an option, but an opt-out one. Presenting to user client with features turned off is more or less pointless, and would result in people wondering why some people lead their text with `>`. Effectively, you're just asking for greentexting to be turned off, just in a little bit different manner.
Then again, if it's an opt-out, user is confronted with either using it as it is, or try to find in settings option for it.

Another question that I would like to ask you is, why do you feel that making it harder for clients to have some nice text colouring in them is a good thing?

**Comment by zetok** [comment]
@dubslow please fix currently broken greentexting.

**Comment by krepa098** [comment]
Let me do another proposal.
I think we can solve this quite easily by putting quoted text between special characters like "¶This is a quote.¶ Text..." displayed as "&lt;green>This is a quote.&lt;/green> Text...". The special character being some unicode symbol that's not widely used. For ease of use we simply provide a menu entry "paste quote" (I assume it's safe to say that you don't actually type quotes) which generates a quote from the current clipboard content.

**Comment by suhr** [comment]
> I assume it's safe to say that you don't actually type quotes

In Linux the usual workflow is:
- Highlight text
- Type `>`
- Paste text by clicking middle mouse button

Also, short quotes can be instead just typed, yes.

**Comment by zetok** [comment]
@krepa098
Quotes are actually typed.
I often just type `> muh quote`, since it's much faster to re-type what someone wrote than copypasting, for which I would have to take my hand(s) off keyboard…

Your solution would be good, if not for simple thing, which is support by clients.
As it was proven many times, you can't expect clients to do something, even if it's a standard, if it's not in core.

Another thing is message splitting.

It has to be between 2 symbols to be "quoted", right?
I can already imagine problems with that.

Also, what if someone wants to "unquote"?
Legit case: someone copypastes something as quote, then edits it. Still a quote. What if one no longer wants it to be a quote?
Don't say that one shouldn't edit quote and send edited version as quote… if users want to do that, let them be.

That's why `>` type of quoting is handy, even though a bit bothersome when has to be applied for more lines. That's where pasting as quote (with `>` added automatically) would be good.

**Comment by tux3** [comment]
@stqism 
I think that you make a valid point that we might not be very representative of our actual userbase. That said I'm not sure in what way quoting support is actively confusing users, I'd love to hear their feedback if some of the users bothered by this feature may send a mail or leave a comment.
Please note that using > for quoting is not specific to "4chan", this is a fairly universal standard used notably in email, comment platforms like GitHub, and documented in various RFCs (like http://www.ietf.org/rfc/rfc3676.txt). Everyone uses email.

I agree that it's important to be friendly to the majority of users, but it's also hard to know what the majority has in mind, and without some sort of evidence, my opinion or yours is as valid as anyone else's.

When you say that the majority of users is being affected by this feature, is there something in particular you have in mind ?

I personally don't have a strong preference either way. 
I wouldn't mind an option, but the settings are getting a little bit cluttered.

**Comment by dubslow** [comment]
Settings being cluttered is only going to get worse, Skype still has ten times as many settings as qTox.

**Comment by stqism** [comment]
@tux3 @dubslow Personally I blame the menu clutter on taking a add it all perspective for general. 

To do it effectively we'd need to sit down and figure out what's most commonly used and add a new extras or advanced (improved) settings page where these minor things can be enabled/configured.

Like theme stuff is nice, but do we really need advanced timestamp formatting and proxy configuration on the same page?

You really have 2 approaches here, something like what Chrome does hiding the advanced stuff like ssl cert options unless advanced is chosen, or pagination like Firefox.

**Comment by tux3** [comment]
@stqism 
I agree completely with the need to redesign the settings, or at least be more organized in the future.

> Like theme stuff is nice, but do we really need advanced timestamp formatting and proxy configuration on the same page?

Yes, this makes no sense. The General tab is a mess.

**Comment by ProMcTagonist** [comment]
What are you talking about, Sean? Who gets "hurt" by quotes? As I already said...

> On top of that, by default users have graphical emoticons displaying instead of text emoticons, and those aren't affected at all by quoting. So quoting has been broken for a lot of users, for no benefit at all to our average grandma user, who happily sees cute yellow smiley faces no matter what.

Oh, and by the way, look at your scary-4chan-only-user-frightening quote technology.

![epic](https://cloud.githubusercontent.com/assets/4358079/5946109/34baffaa-a6e8-11e4-9ad8-8b98c6084cc6.png)

And the solutions getting thrown around are "Paste Quote" buttons with special Unicode characters. Because that'll make it better for grandma (who is unlikely to use quoting, and if she does, is much more likely to understand "put the arrow in front of every bit you want to quote" instead of "make sure the thing you want to quote is in the clipboard and then click this button and make sure you don't accidentally type in the invisible everything-is-a-quote-now area and make sure your friends' toxes support this")

Grandma doesn't care about any of this. It's just you, @stqism.

And make a separate issue about settings organization because I agree it should be better than Skype, not just slightly less cluttered.

**Comment by stqism** [comment]
Hey @ProMcTagonist,

Please take the time to actually read my post, quotes in email like that is normal, those quotes turning green is not.

This isn't removing your ability to use the > character for quotes as is normal for inline emails, and it's ignorant to assume so. This is removing the part where the inline email grandma is pasting suddenly turns green magically by default, giving users who want text to turn green the ability to do so while keeping standard behaviour standard for every other Tox user.

I hope my reply helped you better understand the actual issue at hand.

Thanks as always, Sean

**Comment by ProMcTagonist** [comment]
Quotes changing color makes them stand out, which is an ease-of use improvement. 

You have not demonstrated that a "silent majority" of users is angry that their quotes are green. You have an anecdote about about .NET and some disparaging comments about 4chan (which leads me to believe that this is mostly just based on your dislike of 4chan). 

I simply cannot imagine any "average user" getting upset that quotes are displayed green, except maybe to petition that they should get to choose more colors, because colors are fun.

I agree that users should be able to choose if this happens in their client or not, but it should be on by default. Bare > walls are confusing, and other formatting interferes with the plain text. Coloring them is a perfect, quiet, innocent solution that works, regardless of the implementation's origin on imageboards.
