### ISSUE TITLE
Settings rethink

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#1069]
I have seen talk about redoing the settings section so I am just going to post some ideas here. 

Tox is aimed at being a popular, secure, and easy to use chat service for everyone. The settings section in qTox does not reflect that. Now don't get me wrong, the client is in its early stages still and isn't stable but I think the settings need some design and simplification. 

One issue is there is a massive amount of stuff in the general tab which isn't really general. A lot of these settings won't ever be used by the basic consumer. This is where I propose a fix for all of the problems with the settings. 

Have a tab called "General" with the bare minimum settings, then have a check box that says enable "advanced mode". When the user enables this, make sure a warning pops up saying "HEY DON'T ENABLE THIS UNLESS YOU KNOW WHAT YOU ARE DOING!" or something, you get the idea. This keeps things a lot cleaner and simple. 

As for the design I'm not sure how much you can do with QT but hopefully you can style everything in the settings with some help from the original designer. 

Anyways, this is just a general issue with the settings, I am totally open for constructive conversation about improving the qTox settings.

**Comment by ProMcTagonist** [comment]
I agree that the settings should be reworked to be in line with the core goals of the Tox project.

The settings right now look a bit cluttered and claustrophobic. A few of the tabs require scrolling with standard window size and that's annoying because you have to use the scrollbar or else you randomize all your combobars and sliders.

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by ItsDuke** [comment]
@dcharles525 any chance you could take a screenshot of how it looks for you currently?

**Comment by suhr** [comment]
@ItsDuke This is how it looks for me:
https://img.bi/#/FhpkmIh!hQvjGZi3opTTBrazJUcfKE4hW95kpmqBLHNl6vZ9
https://img.bi/#/S2J0moL!8wIcOWEbzwui2hW8IdeNNyJCsiG9tCYiBj3RgY9r
https://img.bi/#/GM2MzHP!YHkPjGJt0BcUY9KHbEiDk3YC71TD29x81CUGOxiI
https://img.bi/#/QxY97Ei!X2X6Ml71HkmxNJ5FSgplzBW9BHVGR9JHilkiEnal (video preview is black because I have no camera)
https://img.bi/#/tnCYfto!YfIBHYLgFyT7XWXiOfzp0j90cuQ7AFEtn4zvfz53

**Comment by zetok** [comment]
![2015-01-31 qtox general menu redesign](https://cloud.githubusercontent.com/assets/3148759/5987286/1d28a732-a91a-11e4-9c66-5c2a8feb6345.png)
1. I think that everyone would agree on it? `UI/Visual` needs a better name though and to be placed somewhere else. Perhaps between `Privacy` and `Audio/Video` ?
2. Many may consider that kind of movement as questionable. Well it is. Tox has to be user friendly, and spamming general settings with lots of settings have opposite effect. What is needed instead of throwing it all in general, is to provide for target users sane defaults. Whatever sane default setting that would be, user shouldn't even need to concern self with going to options to change it.
   For those few people who don't feel like it's a sane default or needs something more… those kind of people always look into advanced settings anyway, so they're going to see it one way or another.
   \
   I'm not saying that it's the best, just that it seems like most sane move ATM. Perhaps options from 2. should be split and moved somewhere else?
3. Anything?

**Comment by dubslow** [comment]
^ +1

I'm not sure that group 2 should go into an "Advanced" tab. General is better than Advanced (though not by much of course).

Also, I think we'll need a "Notifications" tab at some point, either now or when desktop notifications work (and some of group 2 belongs there). There are a billion ways to do notifications, it probably needs its own tab.

**Comment by dcharles525** [comment]
Sorry I haven't been quick to respond, I haven't been around a computer and I guess Github's Android app doesn't load issues. Anyways I think @zetok idea is a step in the right direction a UI/Visual tab is becoming necessary with the amount of options that are in qTox.

I guess the next leap would be to organize them and style them, does anyone know if styling the settings like the rest of qTox is possible? I am not experienced at all in QT.

**Comment by NetworkJack2** [comment]
I was told to post this in IRC, the public key/user id needs to be more readily accessable. It needs to be so intuetive that someone with average to slightly below average intellegence, or even ingenunity/cunning needs to be able to figure it out within 5 to 10 seconds. Otherwise they are simply going to give up and not install it. Even for people who are intellegent, might be pre-occupied with other things and not give TOX full attention. Tox needs to wo

You should be able to access your public key/User ID from the main window, preffrably that little cluster that has online status, User ID, Status, and avatar. Perhaps a third row, with the begginning of the key in hex. a right click menu should have the functionality of the "profiles" that is now burried in the "identity" tab in settings:

Load(consider renaming "import"), Export, New Tox ID.

I also think qTox is doing fine for a rough draft, fairly impressed how relatively complete it is, a

**Comment by tux3** [comment]
This is more or less done.

**Comment by zetok** [comment]
@tux3 please reopen, since it's not even close to done, and `General` tab is bloated more than ever - aside from that, there's still no `UI` tab.

**Comment by ghost** [comment]
Maybe current "General" tag can split to:
"General"
"Network"
"Design" (themes)
