### ISSUE TITLE
[Regression] Broken quoting ( greentext )

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1099]
![broken greentexting](https://cloud.githubusercontent.com/assets/3148759/6039184/143612d2-ac5c-11e4-8ab3-3219eddf51d2.png)

Please fix.

**Comment by DanTheBritish** [comment]
#945 Isn't this intended behaviour?
Also related: #1059

**Comment by suhr** [comment]
Not a bug. It is not supposed to greentext everything.
Add a space after `>` to ensure that message will be greentexted.

**Comment by mindcombatant** [comment]
all of this discussion and disagreement about what should and shouldn't be greentexted makes me think it should be a per-user setting...

perhaps 3 radio boxes for greentext:
*OFF (default)
*ON
*CUSTOM [box for inputting your own regex] <link or hover-tooltip to description of how to format>

**Comment by zetok** [comment]
@LapFox it's not an intended behaviour, since `>_some_underlined_text_should_be_green_` is not being greentexted

**Comment by suhr** [comment]
But `> _some_underlined_text_should_be_green_` is greentexted perfectly.

**Comment by ProMcTagonist** [comment]
Basically everything I said in #1059 still ands. 

Occasional green text smilies are not a problem; disallowing quoting of a large amount of things is.

On top of that, by default users have graphical emoticons displaying instead of text emoticons, and those aren't affected at all by quoting. So quoting has been broken for a lot of users, for no benefit at all to our average user, who happily sees cute yellow smiley faces no matter what. 

I agree that users should be able to choose if quoting happens in their client or not, but it should be on by default. Bare > walls are confusing, and other formatting interferes with the plain text. Coloring them is a perfect, quiet, innocent solution that works.

@suhr 

> But > _some_underlined_text_should_be_green_ is greentexted perfectly.

That's nice, but irrelevant, unless The Messenger For Everyone's new suggested workflow is scanning every quote and manually editing every instance of deviation from its rules on what should and shouldn't be quoted.

**Comment by suhr** [comment]
> That's nice, but irrelevant

It is not. Consider `> text` as the true quoting syntax and `>text` just a syntactic sugar for 4chan'ers.

**Comment by DanTheBritish** [comment]
E-mails for example use `> text` instead of `>text` and has been the standard in clients for a long time.

Therefore, `> _my_quote` is correctly green'ed, but even if it isn't green'ed, it's not like they're impossible to read. Other e-mail and IM clients don't colour at all.

**Comment by Dirius77** [comment]
What don't we just make it not green text if there are no alphanumeric characters? Then >_> won't greentext. But >_some_green_text will

**Comment by zetok** [comment]
![muh greentext.. nope](https://cloud.githubusercontent.com/assets/3148759/6085893/8b738a98-ae35-11e4-8196-3695e6a892f5.png)

Clearly broken.

**Comment by suhr** [comment]
You're using it wrong.

**Comment by tux3** [comment]
@zetok I whitelisted [ since that's unlikely to be used in any emoticon.
Please use a space if you really want to greentext an underscore character.

**Comment by ProMcTagonist** [comment]
Why do all this for emoticons?

Again:

The supposed Average User will have graphical smilies on as they are by default, and thus will never have their emoticons affected by greentext. And users more on our level who don't want smilies greened are clearly in the minority compared to everyone else who just wants quoting to work properly.

It's relatively common to use > ... < and > _ < as faces. Are we going to start requiring two spaces instead of one for quotes to keep their smilies from being quoted?

**Comment by tux3** [comment]
@ProMcTagonist I've personally never seen > ... < and > _ < but that's a valid point. I'd personally love to see what the Average User™ thinks of this. I agree that too many exceptions and inconsistencies aren't good. But what do you suggest we do ?

**Comment by Dirius77** [comment]
I think it would be easier to have it say, if the text doesn't contain a-z,
A-Z or 0-9, don't quote it.

**Comment by suhr** [comment]
> a-z, A-Z

Hey, don't forget about non-english speakers.

**Comment by zetok** [comment]
@tux3 solution would be to just simply greentext everything after `>`, and if someone _really_ wants to avoid greentext, they can use leading space before `>` to avoid greentexting.

**Comment by suhr** [comment]
> solution would be to just simply not to greentext everything after `>`, and if someone really wants to enforce greentext, they can use space after `>` to enforce greentexting.

Fixed.

**Comment by zetok** [comment]
@suhr doesn't look like it's fixed
![nope](https://cloud.githubusercontent.com/assets/3148759/6093862/f7eca626-af09-11e4-8dac-e539bc96f02b.png)

@tux3 ↑ ?

(at least `:3` should be greentexted)

**Comment by dubslow** [comment]
@zetok He "fixed" your text. Read what's in his quote.

**Comment by Dirius77** [comment]
Or, OR! We could make greentext a setting in the options and just leave it
up to the user.

**Comment by zetok** [comment]
@dubslow It's not about my text, but rather you providing for users inconsistently behaving software. Are you going to tell _every_ single user that they should use space and explain reasoning behind that (is there any)?

Another case where quoting doesn't work:
![muh widcard](https://cloud.githubusercontent.com/assets/3148759/6097324/d0c3414c-afb1-11e4-8991-f90efc12d07e.png)

**Comment by tux3** [comment]
I agree that inconsistent behavior is bad. So I think we'll need to just offer it as an option. There's obviously no pleasing everyone.

Now, if we do that, should it be on or off by default ?
