### ISSUE TITLE
Please provide an OSX binary!

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#111]
Hello,

please provide an OSX binary. I just can't compile the tox core perfectly on osx. There are always issues (with a/v at the moment) which I can't resolve (Mavericks) and for noobs as me it would be really helpful.
The only available Mac build is the Poison app but it doesn't have voice support.

Thanks in advance!
toxxxer

**Comment by F1ynn** [comment]
Right now toxgui is pre-alpha software, there aren't any stable releases to provide binaries. I _almost_ have it building in a VM that could be used to provide daily updates, but neither the build system nor the application are ready on OS X yet (A/V is broken and there are layout issues everywhere).

**Comment by lance0** [comment]
@F1ynn can jenkins build osx binaries?

**Comment by ghost** [comment]
Ok I could compile it, the audio was weird, but chat worked!

**Comment by mouseym** [comment]
i think stqism was looking at getting toxgui OSX binaries building on jenkins again, since we can prove that toxgui does work on OSX

in the meantime i plan on trying to get some osx binaries on my vps, the first one i tried didn't work as all the locations were wrong, but i believe i should be able to create some working portable .app files

**Comment by tux3** [comment]
Done, closing.
