### ISSUE TITLE
Connection problem after encryption

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1123]
I tried to encrypt my chat history, after entering the password check box was displayed, after the restart it was not, and in the configuration file was false, after that the network connection is lost and status icon change to gray.

![screenshot at 15-48-58](https://cloud.githubusercontent.com/assets/5204968/6096718/17d1262e-afaa-11e4-8fc2-f381bbfb9363.png)

**Comment by dubslow** [comment]
There isn't even a gray symbol in qTox files. Wat

**Comment by InnocentLunatic** [comment]
I think these issues are unrelated and the grey status icon is caused by the latest update.  I had the grey status icon upon start up today as well, and I have not altered any settings.  I cannot confirm if there is no network connection or not as it may just be that none of my friends are online right now.  I use Ubuntu 14.04 64-bit.

**Comment by dubslow** [comment]
A good way to test true online-ness is to add `groupbot@toxme.se`, it should always be online.

**Comment by InnocentLunatic** [comment]
I logged in on the downstairs laptop that uses the 32-bit windows version(dunno if that updates itself or if it's an older version) but that does not have the grey status icon, and it displays my Linux laptop(that I have the issue with) as being disconnected.  I also attempted to add groupbot@toxme.se, it just has the key sitting on the list so it would seem that I am offline as far as Tox is concerned.

**Comment by soredake** [comment]
After some time it is connected, disabling encryption solves the problem of the connection. GroupBot have me as a friend, so check out my online I can.

**Comment by InnocentLunatic** [comment]
After restarting my computer(restarting the application alone yielded no results), and starting the application again, it flickered between grey and green a few times, and stayed green but continued to behave as if it were offline or groupbot has not accepted my friend request.  Closing the application and starting it again(after restarting pulseaudio to make sure it wasn't linked to the fact that apparently PA wasn't working) resulted in the grey status icon again and it will not even flicker to green.

I had keep chat history unchecked, tried checking it, but chat history settings and the grey status/offline issues seem to be unrelated for me.

**Comment by InnocentLunatic** [comment]
Or maybe enabling chat history(but unencrypted) actually did fix it.  Groupbot is online now.

Edit: I disabled chat history again, restarted tox, tox still behaved correctly.  Enabled encryption on chat history, rebooted Tox, entered password, tox still behaved correctly.  So it seems to be a random thing caused by something else that I'm not sure how to reproduce(unless if it was related to pulseaudio having malfunctioned earlier, which is quite possible as pulseaudio malfunctioning will cause skype to think it's still online but not recieve messages too... Don't know why or how though)

**Comment by dubslow** [comment]
Can you confirm that this is a connection issue, and unrelated to chat history encryption?

Have you tried uTox? That would be a good way to test if it's qTox or toxcore that's at fault here.

**Comment by DaoDezi** [comment]
same issue. Same gray icon
qtox has to be restarted several times before it connects
looks like qtox don't try to reconnect
netstat shows two connections in status "FIN_WAIT1"

**Comment by Talkless** [comment]
Same problem here. Tried disabling/enabling "Keep chat history", now it kinda works. Not sure if it actually helped, or it's just random.

**Comment by Talkless** [comment]
I just noticed, that even qtox shows that I'm online, messages are not delivered (fried is presumably "offline"), but when qTox is restarted with chat history off, it starts working!

**Comment by zetok** [comment]
@fenque @DaoDezi @Talkless would you mind providing more info? https://github.com/tux3/qTox/wiki/Useful-bug-reports

**Comment by DaoDezi** [comment]
OS: Win 8.1 Pro
Reproducible: Sometimes 
What happened: possible the computer lost internet connection (RU: возможно терялось соединение с интернет)

My log (current time - 11:28): http://pastebin.com/tfakbQug 
qtox screenshot: http://i.imgur.com/lxKzBlu.png
Tray icon at this time - Green 0_o

**Comment by DaoDezi** [comment]
OS: Win 8.1 Pro x64. qtox x64 too

**Comment by Talkless** [comment]
Kubuntu 14.04 amd64, qtox from ppa.

My log: http://pastebin.com/VqbSnwEc

Currently I cannot reproduce it manually, it just.. happens.
