### ISSUE TITLE
Contact grouping / categorization

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1125]
One should be able to sort their contacts into various categories.

```
Work
* contact
* contact
School
* contact
* contact
Friends
* contact
* contact
```

**Comment by ProMcTagonist** [comment]
#1018

**Comment by dubslow** [comment]
They're not the same, though they are very similar

**Comment by suhr** [comment]
I wonder how contact grouping with multiple ToxID could look like.
@ItsDuke

**Comment by dubslow** [comment]
Probably the same ui as #1018, the only difference would be the same vs different Tox ID

**Comment by ProMcTagonist** [comment]
Confusing.

**Comment by ghost** [comment]
@ProMcTagonist
This entails being able to re-arrange the default contacts list. Purely aesthetic stuff.

#1018 is having multiple Tox IDs active, with a corresponding sections for each separate ID's contact list.

**Comment by ProMcTagonist** [comment]
And keeping those separate and understandable would need a hell of a good UI.

**Comment by ItsDuke** [comment]
I don't see why we couldn't just use the base idea behind #1018 with this?

**Comment by ProMcTagonist** [comment]
#1018 is for using multiple accounts at once. This is about having contacts grouped within one account. They're very different.
And now imagine having multiple accounts with contacts grouped within each account. Yikes.

**Comment by ItsDuke** [comment]
@ProMcTagonist I know what @1018 is for, and I know this is different. That does not mean we can't take some of the ideas expressed in #1018 and use them here as well.

**Comment by ProMcTagonist** [comment]
My concern is how to handle both concepts without confusion. We can definitely do that, didn't mean to sound rude.

**Comment by srkunze** [comment]
@ProMcTagonist I agree. Implementation of both approaches could lead to confusion.

However, if a unifying concept exists and it is really good, why not implementing it? :)

**Comment by zetok** [comment]
So, it's going in `:3`

UI for grouping contacts will be based on @srkunze's mockup from #1018. With that being said, it's not yet set in stone how exactly it will look.

![20150527 qtox contact grouping - 3 variants](https://cloud.githubusercontent.com/assets/3148759/7842513/69b6bdb4-049b-11e5-95c6-38760d0e6605.png)

Currently 3rd one is used. Please consider which one is better, and whether some variant of these could be used (i.e. arrow `>` / `∨` / `<` moved to the left, in 1 and 3, etc..)

Even after relevant PR will get merged it will be possible to change how it will look, so that associated drama can be kept to minimum `;)`

Thanks to @TheSpiritXIII

**Comment by SkyzohKey** [comment]
I love the 2nd one but I don't understand what is the gray line ? :3.

**Comment by TheSpiritXIII** [comment]
The issue with the final one presented in #1018 is that this would make each grouping its own Tox profile, with its own ID (because that's the only way to run multiple instances). That's why zetok and I initially decided to go with this design. The line is to make it easier to see. When multi-profiles are in, there needs to be some distinguishing factor between groupings and profiles.

Furthermore, we need a name for this because "groups" would be ambiguous with group chats. tux3 and I like "Circles". Thoughts?

I'll be working on this in my local repository and will post a PR once I fix all of the bugs and we agree on a design.

**Comment by ProMcTagonist** [comment]
@TheSpiritXIII Thanks for being considerate of having both multiple identities (with the ui from https://github.com/tux3/qTox/issues/1018#issuecomment-72318782) and circles within each identity with an obviously different interface. 

I like 2 the best.

**Comment by DanTheBritish** [comment]
I also like 2 the best, my natural dropdown arrow position is to the left.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/pull/1879#issuecomment-114538172 ← opinions needed

**Comment by zetok** [comment]
Closing, since PR implementing it was merged.
