### ISSUE TITLE
Text color (with dark theme)

### ISSUE THREAD

**Issue by neko259** [qTox/qTox#118]
Chat uses system text color and hardcoded white background color. My system has a dark theme and the text color is light-grey, which makes it almost invisible in the chat. Please hardcode the text color as black instead of the system one, or use a system background.

Thanks.

**Comment by msteinbeck** [comment]
Can be closed cause of duplication with #148

**Comment by neko259** [comment]
Closing the older issue as a duplicate of the newer one? Looks like I have a time machine.

**Comment by tux3** [comment]
@neko259 they are both closed, and #148 is now marked as duplicate

**Comment by neko259** [comment]
@tux3 #148 is open as I see.

**Comment by tux3** [comment]
My bad, fixed now.

**Comment by xarinatan** [comment]
Hey, I hate poking old threads but is this still working? on my box with the KDE5 Breeze-Dark theme the text from in the textbox is basically invisible because it's light grey with the background seeming to be hardcoded white. 
![image](https://user-images.githubusercontent.com/1271027/49900984-633c1e80-fe60-11e8-92f2-edfafed25ac8.png)

Also, TBH if the background could be changed with the operating system color scheme that'd be even better than setting the text color to black..
