### ISSUE TITLE
Blue box makes highlighting troublesome

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1183]
http://a.pomf.se/tlejfl.mp4

**Comment by dubslow** [comment]
As long as you click sufficiently close to the text it works fine. I can consistently do it without missing either direction, and a lot of other software out in the wild has similar issues

**Comment by zetok** [comment]
@dubslow 

> I can consistently do it

You're not the only one using qTox. Maybe @dewbasaur doesn't have your extreme manual skills…
Aside from that, plenty of people have problems with proper coordination of their moves, and I for one don't see point in keeping it this way just because…

> a lot of other software out in the wild has similar issues

Saying that $other_software does it equally bad or worse sadly doesn't make qTox better…

I also have problem with selecting link manually at first try. Thanks @dewbasaur for pointing it out.

**Comment by dubslow** [comment]
@zetok The problem is unrelated to links

**Comment by sudden6** [comment]
This seems not to be an issue in current builds anymore.
