### ISSUE TITLE
Info lines need better stylization

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1184]
The icon looks cheap and the bold gets mixed up with my own name when scanning. They don't fit in well.

Info lines would be better back in their colored, centered boxes, in my opinion.

**Comment by dubslow** [comment]
@krepa098

**Comment by zetok** [comment]
@ProMcTagonist Maybe… or maybe not.

Initially I too wanted info lines to be brought back to be centred, but now I think that I would be against it.

There simple reason for it: if you're quickly scrolling through large backlog, it's easy to spot green info icon in one narrow column, rather than looking through message content to spot it.

Maybe I'm wrong about it.

**Comment by ProMcTagonist** [comment]
@zetok With the colored bars, as they used to be, info messages stand out really well from other content in my personal experience.

I can understand the grey ones being harder to see during scanning than red or green boxes or bold text, though. 

(Maybe if we find ourselves looking through backlogs too much we should implement Find functionality.)

**Comment by sudden6** [comment]
Info messages use a different design now, closing.
