### ISSUE TITLE
Merge NURUPOWILLSUEME into COPYING

### ISSUE THREAD

**Issue by CosmicToast** [qTox/qTox#1186]
Now that this project is quite a bit bigger, I think (properly) following GNU standards in terms of LICENSE would be preferable. (definitely low priority, but it's also very easy to achieve)

**Comment by CosmicToast** [comment]
License (since possibly wanted by windows users for clarity) could be a symbolic link to COPYING.

**Comment by ghost** [comment]
I'm just curious why you gave the license file such a strange name - so why did you?
What should NURUPOWILLSUEME mean? A secret code? :grin:

BTW it's also interesting that this issue wasn't "fixed" until now...

**Comment by tux3** [comment]
@blobgo 
When I created qTox, I got started by copy-pasting [a lot](https://github.com/nurupo/ProjectTox-Qt-GUI/blob/master/src/core.cpp) of code from @nurupo's [https://github.com/nurupo/ProjectTox-Qt-GUI](ProjectTox-Qt-GUI) without asking or really checking the license.
So since people kept bugging me to license things properly, this happened :)

We're all serious now.

**Comment by ghost** [comment]
I see. Thanks for your information.
