### ISSUE TITLE
Excessive activity in port 33445

### ISSUE THREAD

**Issue by unpollito** [qTox/qTox#1226]
Hi,

While using qTox at work, my Internet access has been blocked twice by excessive activity on port 33445 UDP; a very high number of petitions per second, which I think is rather odd. I am running Ubuntu 14.04 LTS and my qTox network configuration was the default one.

Incidentally, at least the second time I was disconnected, I'm fairly sure I didn't have any online buddies.

Please let me know if I can provide you with additional information that could be useful.

**Comment by dubslow** [comment]
@irungentoo

To stay connected to the Tox network, the client is constantly sending and receiving information, even if no one on your friends list is online. However, if you are being banned due to excessive traffic, that is something of a problem.

Just a quick question, do BitTorrent clients suffer a similar issue? Tox is based on the same distributed hash table technology.

**Comment by TheLastProject** [comment]
As a workaround, you could disable UDP in qTox' settings, but obviously it'd be better if we could figure out a way to lower how often these issues happen (we get reports every now and then from people who claim their router crashed due to Tox' heavy network issues at times).

**Comment by zetok** [comment]
I think that this issue should be closed, since there's nothing that qTox could do to fix it.

All network activity is basically managed by toxcore.
