### ISSUE TITLE
[Feature request] option to "Copy URL" when right clicking on a link

### ISSUE THREAD

**Issue by griffondor** [qTox/qTox#1236]
Seras t'il possible aussi que quand on fait un clique droit sur un lien dans un client tox d'avoir "copier l'url" ?
 car quand on fait clique droit sur un lien ça apparait pas

**Comment by ProMcTagonist** [comment]
+1

**Comment by ArchangeGabriel** [comment]
In english: is it possible to have “Copy URL” when right clicking on a link?

**Comment by Hasshu** [comment]
Frankly, I'm surprised this issue is still unresolved, as it seems like a trivial feature to implement.

I, for one, use Firefox's Private Browsing mode on a regular basis, so I often have to highlight, copy, and paste links in the browser manually. Which, needless to say, isn't the most entertaining pastime.

**Comment by zetok** [comment]
Actually, it's a duplicate of #927, thus closing.
