### ISSUE TITLE
missing tray support when using Status Notifier

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1265]
on fdb86ca7e924493a025e5a425701f81a2f67ed0b
When compiled with support for Status Notifier, qTox is missing tray icon.

```
SystemTrayIcon: Using Status Notifier backend
```

When compiled without, it's working as it is supposed to.

Happens under i3.

Also a regression that hits users of binaries.

**Comment by likwrk** [comment]
With the latest binary on Ubuntu 14.04 lxde or simply openbox with tint2 tray icon disappeared

**Comment by tux3** [comment]
Could both of you post the result of "echo $XDG_CURRENT_DESKTOP" ?

**Comment by likwrk** [comment]
I have nothing in that variable

**Comment by tux3** [comment]
@likwrk then please try again with the very latest version, it should work like it did before.

**Comment by agilob** [comment]
I have very similar problem on KDE4.

One commit completely broke support for tray icons in KDE4. Application starts hidden in tray, but no icon is visible. qTox is running in background without any possibility to show window or anything. I had to kill it by PID.

Removing lines: 40-63 from https://github.com/tux3/qTox/blob/master/src/widget/systemtrayicon.cpp#L40 fixed the problem here.

```
    #ifdef ENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND
    else if (desktop == "kde")
    ...
    ...
        status_notifier_register(statusNotifier);
    }
    #endif
```

**Comment by tux3** [comment]
@agilob that's very strange, I'm on KDE 4.12.2 right now and it works just fine. It also works on the official KDE 5 live cd.
Can you tell what exact version of KDE4 you use ?
Can you also post the content of $DESKTOP_SESSION, $KDE_SESSION_VERSION and $KDE_FULL_SESSION ?

**Comment by zetok** [comment]
`$ echo $XDG_CURRENT_DESKTOP` returns nothing for me.

``` bash
$ echo $DESKTOP_SESSION
i3
```

**Comment by likwrk** [comment]
@tux3 thanks. Latest binary version works know

**Comment by agilob** [comment]
kdease 14.12.2-1
qt5-base 5.4.0-3

```
➜  qTox git:(traykde4) ✗ echo  $DESKTOP_SESSION
default
➜  qTox git:(traykde4) ✗ echo $KDE_SESSION_VERSION
4
➜  qTox git:(traykde4) ✗ echo $KDE_FULL_SESSION 
true
```

**Comment by tux3** [comment]
@agilob @zetok does it work with the very latest qtox ? 
I only enabled StatusNotifier for KDE5.

**Comment by jgresula** [comment]
The systray icon still doesn't work for me with the latest binary (1.0-1328) in XFCE (Xubuntu 14.10).

**Comment by agilob** [comment]
```
         qDebug() << "SystemTrayIcon: Using the Qt backend";
```

This works on KDE4 and should work on XFCE (it worked before).

**Comment by jgresula** [comment]
The previous binary (not sure which version) printed:
`SystemTrayIcon: Using Status Notifier backend`

The latest binary outputs:
`SystemTrayIcon: Using the Qt backend`
but there is still no icon in the systray.

Is there anything else I should check?

**Comment by tux3** [comment]
@jgresula can you open a console and try this :

```
export XDG_CURRENT_DESKTOP=xfce
qtox
```

then this if it didn't work :

```
export XDG_CURRENT_DESKTOP=unity
qtox
```

Please make sure you have the latest version of qtox, though.

Could you also post a screenshot of your desktop so I can see what the system tray looks like ?
I tried XFCE yesterday and the Qt backend worked well, so that's a little strange. The GTK backend worked too.

**Comment by jgresula** [comment]
Thanks @tux3, it works now with the latest binary from the repo.

**Comment by tux3** [comment]
@zetok I tested and it did work for me, but does it work for you on i3 now ?

**Comment by zetok** [comment]
yep, seems to work, Qt backend is being used.
