### ISSUE TITLE
File Transfer History

### ISSUE THREAD

**Issue by jsmith000** [qTox/qTox#1300]
Hello guys,

Is it possible to store files history (received/sent) because I've got no idea who sent me what and which files I send where (If you can also add failed in it would be awesome)..

Thank you!

**Comment by ProMcTagonist** [comment]
![transfer sidebar mockup no sidebar](https://cloud.githubusercontent.com/assets/4358079/6423337/6e5f8410-be99-11e4-9675-eaa3b6229390.png)

![transfer sidebar mockup sidebar](https://cloud.githubusercontent.com/assets/4358079/6423336/6e42cee2-be99-11e4-9643-24514965be45.png)

A sidebar that shows all transfered media in conversation?

**Comment by zetok** [comment]
@ProMcTagonist no. It doesn't seem to be a good idea, and beside that it has nothing to do (AFAICT) with this issue.

**Comment by Zer0-One** [comment]
@ProMcTagonist looks weird, takes up too much space, and is redundant, since we have a window whose whole purpose is to tell you what files were uploaded and downloaded (the two arrows at the bottom left, at the bottom of the friends list)

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by TheLastProject** [comment]
@suhr Please don't cast a designer on a simple bug report about file transfers not being recorded in the chat history, it makes no sense.

**Comment by ProMcTagonist** [comment]
@zetok 

> nothing to do (AFAICT) with this issue

Keeping the bubbles in place in the chat form is practically useless (to the goal of figuring out who sent what) without a way to scan over them quickly per contact. That was my line of thinking. However I do understand if it's too specific for this issue.

@Zer0-One 

> looks weird

Entirely my fault. A real designer would help implement the real one.

> takes up too much space

It's meant to slide out/over.

> redundant

The transfers window doesn't let me quickly scan through what I've sent and received per-friend.

I think it's worth mentioning that iMessage on iOS recently added a feature that functions similarly, and people seem to love it and use images much more than they did previously. Anecdotal.

**Comment by anthonybilinski** [comment]
I'll start looking into this soon, it looks like a prerequisite for #1293 and #1532. I think OfflineMsgEngine needs to be reworked to generically store a message, instead of only chat messages. This way file transfers, action messages, and chat messages could all be stored through the same interface, be loaded in history, and be retried (or continued in the case of files) on re-connect.

This would probably require adding or modifying db tables, since our "history" table only stores key, timestamp, chat_id, sender_alias, and message. We could maybe add a fileHistoy and actionHistory table and join those to get total history, or add a type attribute for file/action/message to the existing history table with optional filePath/size whatever, and isAction.

I'm not sure if adding fields to the history table would break compatibility with other clients, or if they would just ignore them. If it doesn't break anything I think this would probably be a better architectural approach, but if it does then creating new tables and joining would be fine.

**Comment by anthonybilinski** [comment]
Oh never mind, compatibility is only for the tox profile, not for history. This seems pretty safe then.

**Comment by anthonybilinski** [comment]
File transfer history was implemented by @sphaerophoria in https://github.com/qTox/qTox/pull/5354, closing.
