### ISSUE TITLE
[feature] spell checking

### ISSUE THREAD

**Issue by tetraf** [qTox/qTox#1301]
It may be interesting to add spell checking on text input (with suggestions on right click).

**Comment by agilob** [comment]
Code ready to copy and implement:
http://qt-apps.org/content/show.php/Online+spell+check+editor?content=77339

**Comment by ProMcTagonist** [comment]
Would be incredibly helpful.

**Comment by zetok** [comment]
@redsteakraw mentioned something about some lib that could be used for it.. mind writing about it here?

**Comment by redsteakraw** [comment]
[KDE's Sonnet library has support for multiple languages and different spelling backends and it only depends on Qt and the spellchecking libraries](http://inqlude.org/libraries/sonnet.html) @tetraf

**Comment by redsteakraw** [comment]
[some more information if you are interested about sonnet](http://api.kde.org/frameworks-api/frameworks5-apidocs/sonnet/html/index.html) @tetraf  @agilob

**Comment by jamesrobb** [comment]
Would love to see this.

**Comment by ProMcTagonist** [comment]
Sonnet looks good.

**Comment by TheSpiritXIII** [comment]
[What about Hunspell](http://wiki.qt.io/Spell-Checking-with-Hunspell), used in Open/LibreOffice, Firefox and Chrome?

**Comment by suhr** [comment]
Btw it should be able to check several languages at once.

**Comment by redsteakraw** [comment]
Sonnet was created in part to spell checkultiple languages at onece.  It can do language detection and spell check blocks of text in other languages.  Sonnet also has back ends so it isn't tied to any one system which is nice from a mataitnence perspective.  It also is a 3rd party qt lib so it should fit in. @suhr @TheSpiritXIII

**Comment by tox-user** [comment]
Since Sonnet didn't work, we could try to use Enchant for spellchecking (https://en.wikipedia.org/wiki/Enchant_(software)). It can use multiple backends just like Sonnet. Here is a library for Qt that seems to make it very easy to use:
https://github.com/manisandro/qtspell
https://github.com/manisandro/qtspell/tree/master/examples

If that doesn't work, we could use hunspell (https://en.wikipedia.org/wiki/Hunspell):
https://wiki.qt.io/Spell-Checking-with-Hunspell
