### ISSUE TITLE
qTox forces dedicated GPU on OS X

### ISSUE THREAD

**Issue by LordHDL** [qTox/qTox#1320]
Launching qTox always changes the GPU from integrated to dedicated.  MacBook Pro 8,2, Intel HD 3000 and AMD Radeon 6750M.

To verify, go to "About This Mac" and click on Displays to see current GPU in use.  Close that window and open qTox.  Open "About This Mac" again and go to Displays to confirm the GPU switch.

**Comment by stqism** [comment]
This is an upstream Qt/OS X bug, you don't actually have the ability to pick and choose the GPU to accelerate something with with making an app and isn't something we could fix.

Apples bug reporter might be a start though, https://developer.apple.com/bug-reporting/

Potentially Qt's as well: http://qt-project.org/static/bug_tracker_faq

**Comment by LordHDL** [comment]
Did some research but couldn't find anything about it being a bug with Qt or OS X.

Instead I read that it happens when the software makes OpenGL calls, which prompts the OS to automatically switch.  I'm guessing the Tox core is doing something OpenGL-related at runtime?

**Comment by zetok** [comment]
> I'm guessing the Tox core is doing something OpenGL-related at runtime?

…
No.

**Comment by stqism** [comment]
@LordHDL Well, here's the fun part.

qTox uses OpenGL for displaying video in chats. Because of this Qt5 calls AGL (An Apple framework) which in turn causes the better GPU to be selected for hardware acceleration (like you discovered).

The problem is that it switches if it's been linked against the AGL framework, not if gl's init is called, so we can't actually fix it.... Without removing video support.

**Comment by LordHDL** [comment]
@stqism Ah, understood.  Thanks for the explanation. :)

**Comment by TheSpiritXIII** [comment]
Did you try running with "-graphicssystem raster" on the command line (without the quotes)? This forces Qt to use its software renderer.
