### ISSUE TITLE
Self messages not visible in groupchat sometimes

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#1342]
I don't know how to reproduce it.

Very rarely, my own messages will not be visible in the chatform of groupchats.

Messages are simply invisible with no warning, and the other people get them just fine. It's not fixed by switching to another contact and back to the group.

Since it's so rare and sporadic, I don't have anything else to show. But if anyone else experiences it, contribute here.

**Comment by zetok** [comment]
It sounds like a toxcore problem - i.e. the way things work with current groupchats, client sends message to other peers in groupchat, and displays message when it _receives it back_ from peers in groupchat.

What probably happens in your case is that other peers successfully receive your message, send it, but you don't receive it back.

Closing, since qTox can't really do much about it.
Comment for reopen / make a new issue if it will still be happening once new groupchats are in place.
