### ISSUE TITLE
Double en dash into single em dash replacement

### ISSUE THREAD

**Issue by kirillbobyrev** [qTox/qTox#1432]
qTox doesn't replace double en dashes ("--") with a single em dash ("—") yet, which would be a nice feature. So I thought it could be nice to make qTox handle this replacement as it seems pretty natural thing to me. It seems logical to create a setting to let user specify whether he wants this replacement or not.
This could be implemented relatively easy: for every occurrence of "--" it should be checked if it is not a part of an URL and (if not) then replace it with "—". And also, if there should be a checkbox showing whether a user wants such replacement or not, where should it be? `Settings -> General -> Chat -> (?) "Replace double en dashes with single em dash"` ?
I wonder if such feature would be welcome and if I could start implementing that.

**Comment by dubslow** [comment]
@zetok @TheLastProject Request for thoughts ^

**Comment by TheLastProject** [comment]
I suppose it would be nice visually, although I can't recall ever having used -- in any conversation, so I can't really think of any pros or cons.

I, however, do feel like voting against adding settings for such trivial things, as I feel the qTox settings screen is already way overcrowded.

**Comment by kirillbobyrev** [comment]
@TheLastProject well, I personally believe there shouldn't be a setting for this and all the replacement should be performed for every user. I do use it a lot and it's implemented in [VK](http://vk.com/) (popular social network) and I really feel like it's useful.
However, I think it would be also cool to add some basic markdown support (like making text bold with via surrounding it with *\* and many (but not all) syntax support like described in [GitHub guide](https://guides.github.com/features/mastering-markdown/)).

**Comment by suhr** [comment]
It's not a good idea, because not only text is sent with tox.

**Comment by ProMcTagonist** [comment]
I walk people through command-line operations quite a lot over Tox and would appreciate it not mangling my long arguments.

I'm not in favor of this at all. It's very specific and arbitrary. 

I recognize that I'm not the typical user, and this sort of thing is very impressive and nice, but I'd like to be able to send double dashes.

**Comment by zetok** [comment]
what @ProMcTagonist said, but..

Just to clarify, there's an issue with typing '—' on windows, or some other inferior to Linux os?
I can ~easily type that on Linux…

`Settings -> General -> Chat -> (?) "Replace double en dashes with single em dash"`
'No.' Doesn't belong in General.

I feel like anyone who wants to add new settings should just do #1069 first (how to do it properly is still an open question), and then later, based on that propose adding new settings/switches. Otherwise it looks just bad…

I'd be against that if not for 1 thing: it seems to be used. Question is whether people like it…

As it is, I'm on 'No'.

@arcadiaq if you could, please come back with better proposal when it comes to settings, and a proper description of what you mean, since as things are now, your words can be misunderstood. For one, you don't define what you mean by `replace` i.e. would it be global, `--` replaced everywhere to '—' ? Even in incoming messages?
That kind of things make your proposal look only worse..

So, `replacement` should take place only in input box for sending messages, and perhaps in nick and status input fields?

Also, user should have a way to "undo" replacement even when setting for it is checked, like it's done in e.g. LO (m$ office probably too) → make `ctrl + z` undo replacement, and replace only ' -- ' (spaces)  ← if you don't know what I'm talking about, look at how LO implements it, and when exactly replacement takes place.

Edit: oh wait, LO replaces ' -- ' to ' – ', not to ' — '

Edit2: oh, and text in input field should be replaced only if it's not a copypaste

**Comment by kirillbobyrev** [comment]
@zetok There's no issue with typing em dash in any OS I believe, but just typing " -- " instead of forcing user to find a way to type '—' is better in my opinion.

Thanks, I'll go through the mentioned "issue".

I believe it should be only in every sent message, not in status input fields or nicknames.

As for whether people like it: [VK](http://vk.com/) does the thing - whenever you send or receive a message " -- " is replaced with " — ". And it's very popular social network used by millions, so I believe they feel like it's cool, too.

However, it is also grammatically correct not to surround '—' with spaces ([Em dash - Spacing and substitution](http://en.wikipedia.org/wiki/Dash#Spacing_and_substitution)).

**Comment by zetok** [comment]
> As for whether people like it: VK does the thing - whenever you send or receive a message " -- " is replaced with " — ". And it's very popular social network used by millions, so I believe they feel like it's cool, too.

Just because something big uses it, it does not mean that it's liked. If VK's **only functionality** was changing '--' to '—', then yes, it would mean that people like it. As it is now, the only thing you get from it is that changing '--' into '—' is used, and it means that there's _possibility_ that people might **like or hate** it.

**Comment by zetok** [comment]
Quite possibly when qTox will have plugin system it could be achieved through it.

**Comment by agilob** [comment]
> And also, if there should be a checkbox showing whether a user wants such replacement or not, where should it be? 

Is this guy trolling us?

**Comment by kirillbobyrev** [comment]
@agilob why would I?

**Comment by agilob** [comment]
we are already flooded with preferences and several more are about to be merged, this issue is so minor and unimportant that, personally, I would close it. I can't imagine someone wasting time on it... I could be added to sending message: `messageToSend.replace("--", "—");` but anything over it is completely meaningless for me. Moreover, this setting should be shared between other clients, so behaviour of qtox is not different than µtox. From previous discussions (about stripping whitespaces) we decided not to modify **anything** that is being sent and received.

**Comment by kirillbobyrev** [comment]
@agilob I still don't catch why you accuse me of trolling

**Comment by agilob** [comment]
This issue and discussion looks funny ;)
Don't close it, maybe someone will implement it ;)

**Comment by Zer0-One** [comment]
I don't like the idea. If I type two dashes next to each other, I expect them to stay that way. 

Implementing this means that we need to provide a way to toggle it on and off, and until we have something like Firefox's "about:config", we are pretty much already out of real-estate on the settings window.

**Comment by ProMcTagonist** [comment]
This belongs in a general sender-side text modification plugin which would enable this, bluetext, and/or whatever else you want, without phlubbing everyone else's qTox.

**Comment by antis81** [comment]
Hm ... if we extend the idea to a real wiki-text parser (e.g. markdown like implemented in Github), that would actually become a useful feature. This would allow for sending also quick table and list mockups via chat-message.

**Idea:**
If a message starts with a command token like `.md` or better `.parse:md` followed by a space character - it could then be parsed with the selected parser. As Markdown supports HTML, it supports the `&mdash;` entity like &mdash; this one :).

This way we could also provide a drop-down box to select a parser and prepend it to the chat message (if not given by hand). Tokens could be (`.parse:text` == `NO-PARSER`, `.parse:md`, `.parse:html`, `.parse:xyz`, ...).

Would that be acceptable? If so, I'd close this issue in favor to a new one called **"Support text parsing"**. @omtcyf0 Would you be in for implementing this?

**Comment by suhr** [comment]
Isn't it too much feature bloat?

**Comment by antis81** [comment]
@suhr In the first place, you are right. So, this is meant as an idea for a future version. Why? - Because I'm strongly against just parsing each `--` as &mdash; (em dash) within any text. First thought was to just close this issue and thus, reject the idea (sorry @omtcyf0).

However, we already have a parser, that renders the chat messages. I don't know (q)Tox'es default text parsing/rendering mechanism from the inside and - unfortunately - I currently don't have time to have a deeper look into that. From the outside it looks like a "simple" text parser, that expects us to only write plain chat messages with inline smileys and probably a URL - that's it.

I know we can exchange files via qTox, but sometimes one wishes to be able to just copy an image from a website or a 10-line code snippet as plain (highlighted?) text. This is what we can do, when communicating via Github (by using the Markdown parser and some extensions), right?

So I thought: Why not implementing a small "command mode" (activated by a leading `.` (dot) character), that allows us to chose another (standard) parser?

It would actually be a nice feature to tell the Tox clients (not necessarily qTox) on "the other end", which parser to use, so that the message is rendered nicely. If no parser is given, the (existing) default parser is used.

I'm pretty sure, that there's lots of existing implementations out there - maybe even a maintained parser lib.

**EDIT** -- Almost forgot: The "command mode" would have to become part of the Tox protocol - maybe it already is?

**Comment by zetok** [comment]
> **EDIT** -- Almost forgot: The "command mode" would have to become part of the Tox protocol - maybe it already is?

It's not. toxcore transports data, and in case of messages, data happens to be text.
