### ISSUE TITLE
Allow the user to export/import its private key

### ISSUE THREAD

**Issue by tibounise** [qTox/qTox#144]
It would be great to be able to import and export my private key, so that I can use qTox on multiple devices.

**Comment by dubslow** [comment]
I have a plan for this, though project wide consensus is lacking. Give me a few weeks, I'll try and implement it.

**Comment by dubslow** [comment]
Important question: Do you (and by you I mean all users in general) want the ability to name the data file something other than your username?

**Comment by tibounise** [comment]
Currently my data file is named "data", does it mean that qTox will export my data file named as, say, "tibounise" ?

**Comment by ProMcTagonist** [comment]
Naming of data files is necessary for eventually managing multiple profiles online at once in a single client.

**Comment by tibounise** [comment]
Good idea, but why not using something like the last eight characters from our Tox ID, since we can our username whenever we want though the Tox ID will remain the same ?

**Comment by dubslow** [comment]
In my opinion, that would make it very hard to manage if you had more than one id, and I imagine a lot of people would.

My plan (which is largely implemented locally) is to designate the .tox extension to mean Tox ID/data files. Currently in my implementation, the base name is the current username (with some as-yet unimplemented sanitation for file system restrictions), but some people might consider that too restrictive, hence my question.

I'll try to have something preliminary posted in a few hours. (Note: the UI looks a little funny because I can't get the Qt incantations for spacing to work; hopefully someone else can pitch in.)

**Comment by dubslow** [comment]
Okay, until such time as tux3 returns and accepts pull requests, you can find the still-buggy first release  [here](https://github.com/dubslow/toxgui/tree/profiles). It turns out the GUI is fucked at the default size -- expand it a bit and it becomes usable however. I'll definitely need help getting that fixed.

**Comment by dubslow** [comment]
Oh snap, this can be closed!
