### ISSUE TITLE
qTox keeps chat history by default, should not

### ISSUE THREAD

**Issue by Piste** [qTox/qTox#1479]
This might be a discussion that has happened before but I could not find it by searching the repo. Feel free to close on sight if that's the case. I do not think that qTox should offer to save chat history by default. If we are aiming for a privacy-centric product then we should make sure that out of the box qTox keeps you safe.

**Comment by zetok** [comment]
> I do not think that qTox should offer to save chat history by default. If we are aiming for a privacy-centric product then we should make sure that out of the box qTox keeps you safe.

Wrong.
Not only you're missing point of Tox, but also you seem to not know what features qTox has that make your request look silly.

If you could, please read for what Tox is being made for and find out what features qTox has. If **after** doing that you still will want to have a discussion, I hope that your arguments will be really good…

If not, then please close issue.

(I'm not supplying you with any links, since what I'm talking about is shown in plain sight on main Tox website)

@tux3 how's that an 'enhancement' ?

**Comment by dubslow** [comment]
Yeah I have to disagree, I fail to see how keeping a chat history on your local hard drive is unsafe. If your hard drive is compromised, you have far bigger issues than your chat history being exposed.

**Comment by Piste** [comment]
@dubslow Two cases come to mind: work computer and public workstation but both can be summarized to "any computer that you are not the admin of".

@zetok "With the rise of government monitoring programs, Tox provides an easy to use application that allows you to connect with friends and family without anyone else listening in." 
I feel like disabling chat history persistence to disk will help reduce the attack surface, especially in cases where your computer might be seized. 
Thank you, however, for the quick response, all the while saving patronizing me and going straight for a more direct superior and condescending tone. I was foolishly expecting a kinder environment from this open source community.

**Comment by ProMcTagonist** [comment]
https://tails.boum.org/

unix philosophy

**Comment by dubslow** [comment]
@Piste If you are using your Tox profile (or any Tox profile) on a public computer, you'd need to clean up after yourself anyways, and using the delete button on a profile also removes any chat history.

@ProMcTagonist What?

**Comment by badumba** [comment]
@zetok I agree that this is an issue and don't understand where you are coming from - I wish you would explain your point.
    - "you seem to not know what features qTox has"
    - "find out what features qTox has"
What are you bringing up features? It's not a feature discussion

Tox allows encrypting data in motion.
When you want to encrypt data in motion, you _probably_ also don't want to store it on your drive. Not _always_ though, which is why having it as an option is nice.

**Comment by zetok** [comment]
@Piste 

> Thank you, however, for the quick response, all the while saving patronizing me and going straight for a more direct superior and condescending tone.

:3

All I can say is that I'm sorry, since it's just simply hard for me to deal with people who don't understand purpose of Tox. Sadly, your reply seems to confirm my assumption ↑.

> "With the rise of government monitoring programs, Tox provides an easy to use application that allows you to connect with friends and family without anyone else listening in."

Yes. This exact sentence ~sums up what Tox is about.

Now, simple question: how much time have you spent thinking about security aspect?

I'm sure that it was plenty, since not only you have bothered to remember about default settings qTox comes with, but you also spent time thinking how it could possibly affect security of user(s) in different scenarios. That's great, and it would be awesome to share it with people expecting that they'd admit that it indeed solves problem, if not for 1 ↓ thing…

Second simple question: how much time have you spent thinking about other, even more important aspect of Tox that was explicitly stated in quoted sentence?

“Tox provides an **easy to use** (…)”

How exactly what you propose **improves** qTox in that aspect?

…

What you are proposing is change of default settings every new qTox user would experience, in a **bad** way. While doing so, you don't give any proper arguments for that move..

Eh.
There is _plenty_ of software that provides security. Want encrypted video only between you and other party? Oh, it's _easy_. Just grab anything that does it without encryption and tunnel it through ssh/whatever. Easy right? No logs, no 3rd parties. Surely your friends and family will just love to use it, after all it's so _secure_.

Now, if I may let myself to loosen a bit my imagination, I'd say that exactly easiness of use and generally great UX OOTB[1] led you to committing yourself to at least think, and later on to making an issue about resulting from it idea.

It should be kinda obvious, but I still feel like I should say it: without being easy to use Tox would be shit.

# 

So feature thing. As you and @badumba have (probably?) failed to notice, qTox provides a way to encrypt Tox data and history stored on your hdd/ssd.
Another feature: it is possible to configure qTox to not store history on your hdd/ssd even when being launched in in "portable" way from usb stick or whatever (although this one is hidden and not user-friendly, so.. yeah that could be improved, and probably will be somewhere in the future; as of now there are more important things)

And since you seem to like my patronizing tone, go figure what it means `;-)`

# 

To sum things up:
There will be no change to stupid defaults.

If you want security, you either know what to do to get it, or you are miserably failing at it.

Tox aim is not to provide absolute security in every scenario, but easy to use real security.

# 

That being said..

@Piste it's great to hear what you think, especially part about how you were welcomed. :3

So, basically it shows that anyone who would like to contribute to Tox in some way is not exposed sufficiently to an idea that Tox has to be easy to use.. I will have to think about it further, but sadly, at least ATM I don't have any idea how to improve that aspect. So if you really would like to help with ideas, could you please help find a place (and a way how to do it right) where potential contributors could be exposed to what Tox is about, so that they wouldn't waste their time, like it was in this case?

Oh, and

> I was foolishly expecting a kinder environment from this open source community.

Sorry, bad conjugation. Not only things in places failed to expose and emphasize to you enough the idea of Tox being easy to use (~not your fault), but also @tux3 for some reason instead of closing this issue or labelling it as `discussion` marked it at enhancement (not your fault). Also, without good insight into situation you've proposed (sounded like insisting on) drastic and bad changes (~your fault).

If you feel like my behaviour was simply wrong given all of that (and more), feel free to say so ← I really could make some use of how people feel about things, so that they could be improved.

---

[1] User experience out of the box

**Comment by itsrachelfish** [comment]
Are you saying qTox logs chats by default? When I installed qTox last month it had the option to save chats but it wasn't enabled.

@tux3 Does qTox log chats by default now?

@Piste Or are you saying it shouldn't even offer the _option_ of saving chat history?

**Comment by dubslow** [comment]
It appears that chat history is still disabled by default, but in the future it will be enabled by default (probably around the same time that qTox gets a welcome wizard).

**Comment by dubslow** [comment]
Invalid because the title is factually incorrect, however the discussion in here is more than valid (and yes zetok your initial post was a little bit harsh and condescending, even if you meant it with good intentions as I believe you did)

**Comment by TheLastProject** [comment]
@Piste I just wanted to chime in here to say I feel that using Tox on a public computer is a horrible idea by itself, because doing so means putting your private key on the device, making it amazingly trivial for someone with even the simplest software made for this purpose to make a copy of your key and become able to impersonate you. Tox is really not something you want to use on untrusted devices.

The issue with disabling chat logs is that it isn't just inconvenient to not be able to read back, it also breaks pseudo-offline messaging through multiple sessions, as the old unsent messages get purged too. A much better solution that people could probably agree on is to, when we have a welcome wizard, make it very straightforward to password-protect your Tox data file and chat history, so that your history is saved in an encrypted matter (which currently is a single click under the "privacy" tab in settings).

**Comment by Piste** [comment]
Thank you, @TheLastProject. I understand better now. I really love this project and I hope it is as successful as we all hope it to be.

**Comment by agilob** [comment]
Marked as invalid and no active discussion is going on, so closing.
