### ISSUE TITLE
Look at #1520

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#1519]
Edit: removed previous content, since people didn't seem to be happy about it.
#1520 might be better when it comes to helping qTox.

**Comment by optimumtact** [comment]
Your hostile attitude is part of the reason why you have so few active client devs.

**Comment by dcharles525** [comment]
@zetok way to be a jerk about it.

**Comment by TheLastProject** [comment]
@dcharles525 Zetok's first language isn't English, which makes it very easy to get subtleties wrong. Add to that the fact that showing emotion in text is complicated and limited, and you have something that sounds way more sarcastic than intended.

Yes, Zetok definitely put some things wrong, and `Good job, dubslow, your ability to provide a way for people to help you do something is simply amazing.` was out of line, but I know for a fact that Zetok is posting this because he wants to gather attention that qTox needs help and preferably right now. Just because he messed up some wording doesn't mean he is being a jerk about it, he is trying to help.

@zetok I know you ran this past some others, but still, please choose your wording more carefully next time, some parts really are out of line, and @dcharles525 is quite right with the way your message comes across.

**Comment by optimumtact** [comment]
I talked to him in IRC and the intent was pretty damn clear. Don't try to change it after the fact.

**Comment by TheLastProject** [comment]
@optimumtact Indeed. After talking to him on IRC, his intend of wanting to get people to help qTox was pretty clear. Also, could you not attack me directly like that? There is absolutely no need for such a hostile attitude.

**Comment by optimumtact** [comment]
I didn't attack you, I merely stated that you're trying to twist the intent after the fact which is exactly what you're doing.

**Comment by TheLastProject** [comment]
I see #1520 put it way better. What about closing this in favour for the much more friendly sounding #1520?

**Comment by hexafluoride** [comment]
kek
