### ISSUE TITLE
Something wrong with debian package

### ISSUE THREAD

**Issue by Artiom-M** [qTox/qTox#1530]
Installed Qtox on a fresh Linux Mint Debian Edition 64bit Cinnamon from Qtox repository.
On start:
**qtox: symbol lookup error: qtox: undefined symbol: _ZN18QCommandLineParserC1Ev**

**Comment by Artiom-M** [comment]
INSTALL.md says require Qt  >= 5.2.0 but 5.1.1 is installed from dependencies.

**Comment by tux3** [comment]
@stqism

**Comment by ghost** [comment]
I can confirm this bug. The same error message on exactly the same OS.
And the version of Qt (e.g. libqt5core5) is 5.1.1+dfsg-5.

It was also reported here: hXXp://support.libtoxcore.so/help/discussions/problems/85-qtox-on-lmde-does-not-start (Removed link because website is not safe anymore, see issue https://github.com/tux3/qTox/issues/2033)

**Comment by zetok** [comment]
Should be fixed now - use static binaries.

**Comment by agilob** [comment]
Using static binary downloaded manually is not a solution, it must be fixed in .deb in repository.

**Comment by zetok** [comment]
@agilob in a repo that no one working on qTox has access to?

Edit: I know that downloading static binaries manually is far from being good, but thing is, I don't see how qTox maintainers could do anything with things related to repo `:(`

**Comment by antis81** [comment]
I'm also suffering from this one (surprise, surprise). It's not because of me - I'm trying out qTox and expect these problems. OTOH I maintain several systems for friends and would like to recommend qTox to others as a reasonable replacement for Skype. This is currently a dream still :stars: ...

Btw.: There are several (closed) issues addressing problems caused by the missing/old ppa repo. Do we have an open central issue, addressing the real problem?

If maintainers don't have access to the PPA repo, we have exactly the same problem we had with this very git repo only short time ago.

Question: I don't know anything about our package infra (yet). Did you hear about recent `dgit`? Would that be a reasonable way to go?

**Comment by zetok** [comment]
> Btw.: There are several (closed) issues addressing problems caused by the missing/old ppa repo. Do we have an open central issue, addressing the real problem?

Nope.

> If maintainers don't have access to the PPA repo, we have exactly the same problem we had with this very git repo only short time ago.

Well, the way things are probably going to be done, is no access to the repo, but there will be a post-build hook in jenkins job that would push qTox packages to repo.

Issues were closed, since keeping them open doesn't really help - I think that repo should be available again in a course of week or two. (I don't know any ETA though)

Though yeah, there should be a place where those issues would belong (other than qTox issues), where people could report problems and track progress.

> Question: I don't know anything about our package infra (yet). Did you hear about recent `dgit`? Would that be a reasonable way to go?

No, I haven't really heard about `dgit`.
Quick search didn't really answer with what it would help in context of packeges..?

**Comment by antis81** [comment]
> Well, the way things are probably going to be done, is no access to the repo, but there will be a post-build hook in jenkins job that would push qTox packages to repo.

Ok! :+1:

> Issues were closed, since keeping them open doesn't really help - I think that repo should be available again in a course of week or two. (I don't know any ETA though)

If people (qTox users) found only one open issue, stating the PPA is not set up yet after the migration to `tox.chat`, they probably won't continue creating new issues on this topic (I've seen the note added in qtox wiki though). A closed issue indicates a solved topic, which is not the case here.

> No, I haven't really heard about dgit. ...

As I wrote, I don't know if this is really the right tool for us. Seems, that it would simplify debian packaging. More information can be found on [debian wiki](https://wiki.debian.org/PackagingWithGit#Packaging_with_Git).
