### ISSUE TITLE
Video chat stops when sending 4.9mb file to friend

### ISSUE THREAD

**Issue by dcharles525** [qTox/qTox#1550]
Video chatting with newest update. Smaller files go through fine while video chatting, large file will stop the call and cause it to end.

Edit: Worked with a 8mb file...hmm

**Comment by tux3** [comment]
That very much sounds like a problem with toxcore, since that should be the only point (networking) where video calls and file transfers have any interaction at all. Perhaps a problem with your upload speed being maxed-out and timing out the call somehow?

I'll see if I can repro and maybe find a workaround.

**Comment by tux3** [comment]
Closing, because file transfers causing video call problems is very unlikely to be a problem with the qTox code. I don't think we can fix that on the qTox side.
