### ISSUE TITLE
qTox builds for mac os X are broken

### ISSUE THREAD

**Issue by jaceq** [qTox/qTox#1558]
Hi,

Currently builds for os X are broken: https://jenkins.libtoxcore.so/job/qTox%20OS%20X/

This currently quite annoying as version with new API for Linux and Windows was released but for Mac not. This makes it mac os X users unable to communicate with linux / Windows users...

It seems that building server is offline, I can provide a macbook with jenkins agent if needed...

**Comment by stqism** [comment]
I can't fathom a single reason as to why you're visiting Jenkins directly, this is internal and not something end users are supposed to just go and visit. The machine being off and not building is intentional because we've shifted focuses with the advent of the new API.

qTox for OS X moved to a semi-stable versioned model pushed out weekly and in iterations, this is codesigned, built against the latest API, and done offline.

To download it either click the download button on https://tox.im or visit https://wiki.tox.im/Binaries#OS_X

Thanks, Sean

**Comment by jaceq** [comment]
Hi Sean,

Okay, maybe a bit of a confusion from my side, as right after new one came out for Linux, I tested the one for mac and it was still with old API. But the fact it's a weekly release  might have something to do it :) Thanks for explanation, I will test again on Monday.

Regards,
Jacek

**Comment by stqism** [comment]
@jaceq I think you're missing the point, follow the instructions to download it like I listed above and they'll work perfectly and be the new API, forget Jenkins exists :)

Also, mind closing the issue?

**Comment by jaceq** [comment]
Hi,

Yes, that's what I meant, I will try on Monday with 'official' binary links and not jenkins ones :)

Thanks
