### ISSUE TITLE
qTox doesn't reconnect after internet connection breaking

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#1560]
Subj.

**Comment by agilob** [comment]
related to: https://github.com/tux3/qTox/issues/1369

**Comment by suhr** [comment]
Not really. That issue is a UI bug.

**Comment by agilob** [comment]
It's related in implementation, detecting when connection goes down is crucial for both issues. You want to reconnect? You need to know the connection is down, same applies for changing tray icon.

**Comment by tux3** [comment]
This is a toxcore problem. 

I suppose we could work around this toxcore bug by trying to detect when the connection is back up, then killing and creating a new toxcore instance, but that's really ugly and prone to creating more bugs if we misdetect.

**Comment by ovalseven8** [comment]
Is this still an issue? I can't reproduce it...

**Comment by zetok** [comment]
@ovalseven8 did your internet connection break?

**Comment by tux3** [comment]
Related to #2820, although there are more ways to lose connections than hibernation.
The problem is that as a client we have no reliable way to know if toxcore is stuck internally, if we incorrectly force-reconnect everytime there could be a connection problem, this'll just annoy people.
So this bug is going to be hard to work around without toxcore actually fixing things for once.

**Comment by ProMcTagonist** [comment]
Is there an open toxcore issue?

**Comment by tux3** [comment]
There's https://github.com/irungentoo/toxcore/issues/1349, the issue is relatively new but the bug has been known for a long time.

**Comment by zetok** [comment]
From #3241, thanks to @JohnMkainne:

# 

##### Steps to reproduce
1. qTox is running.
2. qTox is using network proxy(TCP only, no IPv6). e.g., 10.20.30.40:5678
3. Network proxy server's Internet is going down.
4. And up again after 5 minutes or so.
5. Open qTox's contact list.

##### Observed Behavior

a. All contacts are "red circle"(offline).
b. Open one of them show "XXX is now offline" in his chat window.
c. And my status is green filled circle(online).

Friends are ALWAYS online, so why they are offline?
(they become online once I close qTox and fire it up again)

##### Expected Behavior

a. Reconnect if the internet is down.
b. Show red circle if the internet is down(my client side)

**Comment by ghost** [comment]
This priority must be
- "P-medium"
- "P-high"

I can reproduce this bug everyday...
I wrote simple script to restart qTox everyday...
Please consider fixing this problem soon...

taskkill /f /im:qTox.exe
start X:/Tox/qTox.exe
exit

**Comment by ghost** [comment]
How about:
1. Ping to DHT sever every 1 minutes, if the user USE PROXY and TCP ONLY(not udp).
2. If the ping failed, try again immediately.
3. If failed again, initiate restart sequence.

This bug is very annoying, please fix it...

https://github.com/irungentoo/toxcore/issues/1349

**Comment by ghost** [comment]
oops, not "restart". "Reconnect".

**Comment by agilob** [comment]
That's a toxcore issue... You need to report it in toxcore repo and comment there.

**Comment by shalnoff** [comment]
> That's a toxcore issue.
This issue could be solved in qTox as well. Would be great to have something like checkbox in settings (maybe as temporary workaround)?

**Comment by sudden6** [comment]
Can't reproduce, qTox always reliably reconnects, even when switching networks or on spotty mobile connection. Please open a new issue if this is still a problem.
