### ISSUE TITLE
Allow stereo audio transmission

### ISSUE THREAD

**Issue by unfa** [qTox/qTox#1581]
I'd love to be able to transmit stereo sound throgh qTox's voice and video call.
I that feasible?

**Comment by tux3** [comment]
Yes, it should be possible. We just need to make a UI for it.

**Comment by agilob** [comment]
@tux3 please give some more details.

**Comment by tux3** [comment]
@agilob The logic of supporting stereo sound is already implemented and tested, because (IIRC zetok) had a patch in toxcore that enabled stereo by default.

Now in core/coreav.cpp in function prepareCall we do `calls[callId].codecSettings = av_DefaultSettings;` to use the default AV settings for calls.

If we add `calls[callId].codecSettings.audio_channels = 2;` we should be able to force it to become a stereo call. 

So maybe prepareCall could look at a settings and decide whether or not we want stereo.

**Comment by agilob** [comment]
When I do this I don't hear anything from echobot :<

**Comment by tux3** [comment]
Personally I never hear anything when calling echobot, mono or stereo.

But I just tested 2 channel calls and it works for me locally (with both clients using it).

**Comment by rugk** [comment]
Interesting, so currently qTox only transmits mono sound...
Is there any progress regarding this issue?

**Comment by tux3** [comment]
qTox is fully steoro by default now, the issue wasn't updated.
