### ISSUE TITLE
OSX: A damn huge hall for improvements

### ISSUE THREAD

**Issue by tucnak** [qTox/qTox#1594]
Alright, so I spent some time for satisfying all dependencies (since default osx packaging approach is broken bullshit) and finally got a debug build. So far, inb4 even actual chatting, but just using the app, I noticed a few points that make qtox an absolutely unusable product for end user:
- Tray icon just isn't working. Sometimes it appears, sometimes it doesn't, but the actual icon is not being drawn. Tbh, I haven't seen it there (in the tray), ever. Status icons in tray menu are misrendered (what you get when you scale a 16x16 icon up to 32x32 representation). After pressing the tray icon, first, application window raises and after 2s (with enabled osx animations) tray menu triggers. I suspect creepy `SystemTrayIcon` you guys have there. By the way, why would you want to write manual support for all the backends, such as Gtk/Unity/KDE when your functionality doesn't go beyond helloworld QSystemTrayIcon API?
- Sometimes after leaving app focus, you can't raise it with clicking the dock icon (can't really reproduce everytime.
- Global application style is Fusion, looks completely creepy in context of OSX

I understand that there haven't been any sort of serious development for OSX and would like to help you out, but I'd need some hints. Can you please comment on the points listed above?

**Comment by tux3** [comment]
First, thank you for trying things out.

> Tray icon just isn't working. Sometimes it appears, sometimes it doesn't, but the actual icon is not being drawn.

What is the tray icon backend you're getting, what does the qtox.log/stdout output say?
Unfortunately, I don't have a Mac available anymore so I can't do much testing on OS X.

> After pressing the tray icon, first, application window raises and after 2s (with enabled osx animations) tray menu triggers.

This makes it sound like you're getting the Unity systray backend, which is a horrible hack to work around some platform restrictions. If so, this'll need to be changed.

> By the way, why would you want to write manual support for all the backends, such as Gtk/Unity/KDE when your functionality doesn't go beyond helloworld QSystemTrayIcon API?

Because it turns out that QSystemTrayIcon doesn't actually work on several platforms. Including Unity (Ubuntu) and KDE5. We do have a QSystemTrayIcon backend to our system tray code, and we use it <a href="https://github.com/tux3/qTox/wiki/Tray-icon">where it works</a>. As Qt versions improve, we start using it more.

> Sometimes after leaving app focus, you can't raise it with clicking the dock icon (can't really reproduce everytime.

I can't really tell you more without knowing what systray backend your qtox is running, and without doing some testing on os x. The system tray icon has always been a headache.

> Global application style is Fusion, looks completely creepy in context of OSX

Can you see a more native style in the style drop down, in the settings? If so we could set it by default. Otherwise I'm sure there's a way to get a native style.

> I understand that there haven't been any sort of serious development for OSX and would like to help you out, but I'd need some hints. 

Much appreciated, thanks.

**Comment by tucnak** [comment]
> What is the tray icon backend you're getting, what does the qtox.log/stdout output say?

It's definitely Qt backend is being used here.

> Can you see a more native style in the style drop down, in the settings?

That's what I was talking about. In this particular case, in settings, Fusion is being used. A single place with OSX native style I've seen is a dropdown right below the nickname on the right. Seems like Fusion is being hardcoded somewhere. Settings page also has major issues, as well as the whole application ;)

I'll have some more time in the evening / tomorrow, so I can dig into the whole thing and catch some bugs.

**Comment by stqism** [comment]
We've deducted that the first point was a personal problem.

The 2nd is an issue.

The 3rd was fixed.

**Comment by zetok** [comment]
So.. were the issues fixed, and can this be closed now?

**Comment by tucnak** [comment]
Sure!
