### ISSUE TITLE
White screen when trying to take a screenshot on Windows

### ISSUE THREAD

**Issue by alexbakker** [qTox/qTox#1595]
I use Windows 8.1 with two 1080p monitors.
If I try to take a screenshot, my second screen turns completely white. If I move qTox to my second screen and try to take a screenshot the same thing happens.

**Comment by PKEv** [comment]
Win 7 32x
Really second monitor completely ignored when screenshoting

**Comment by agilob** [comment]
@Papierkorb

**Comment by Papierkorb** [comment]
Don't have a dual-screen windows machine where I'm currently, earliest for me would be this week-end.

**Comment by PKEv** [comment]
closed

**Comment by alexbakker** [comment]
I don't see how #1748 is a proper fix for this. My second monitor is positioned on the left so I'm still experiencing this issue. Can this be reopened?

**Comment by zetok** [comment]
Could someone using windows test https://build.tox.chat/view/Clients/job/qTox-testing_build_windows_x86-64_release/lastSuccessfulBuild/artifact/qTox-testing_build_windows_x86-64_release.zip , which should have it fixed?

**Comment by antis81** [comment]
@PKEv @Impyy Can you confirm this is fixed.

**Comment by zetok** [comment]
@antis81 why remove `A-windows` though, since issue seems to affect only windows?

**Comment by antis81** [comment]
@zetok No, it affects a multi-monitor setup with **primary screen on right side**. In this case the previous aproach uses wrong coordinates to take the snapshot. The code I wrote picks the right "panorama" of all screens now, no matter in which order they are. Now user picks the wanted area out of it and takes the screenshot. That's all… :)

**Comment by zetok** [comment]
I see. Thanks for explanation `:)`

**Comment by PKEv** [comment]
White screen on the second monitone
(primary screen on right side)
During selection:
![default](https://cloud.githubusercontent.com/assets/6053197/10096093/9795b4a2-6377-11e5-997b-b3b705959d70.png)
result:
![qtox-screenshot-olia2428](https://cloud.githubusercontent.com/assets/6053197/10096108/ac58663c-6377-11e5-864f-045164ecb730.png)

**Comment by antis81** [comment]
Sorry, I was wrong. Problem only exists with multi-monitor setup on old super duper Windows systems…

Unfortunately I cannot reopen PR #2289 -> new one required. 

@PKEv
Had a look into the very Qt5 code and found the solution:
1. In the first place, `QPixmap::grabWindow` just wraps `QGuiApplication::primaryScreen()->grabWindow(wid, x, y, width, height)` -> thus it is really obsolete.
2. `QGuiApplication::primaryScreen(0)` works on any platform, but Windows. Thus -> it's a Qt bug actually! If interested, have a look [here](http://code.woboq.org/qt5/qtbase/src/plugins/platforms/linuxfb/qlinuxfbscreen.cpp.html#_ZNK14QLinuxFbScreen10grabWindowEyiiii) and [here](http://code.woboq.org/qt5/qtbase/src/plugins/platforms/windows/qwindowsscreen.cpp.html#_ZNK14QWindowsScreen10grabWindowEyiiii)
3. Giving the dimensions teaches Windows to do the right thing.

Thus, the code you wrote is ok, but instead of the obsolete `QPixmap::grabWindow` use `QScreen::grabWindow`:

```c++
QPixmap ScreenshotGrabber::grabScreen()
{
    QScreen* screen = QGuiApplication::primaryScreen();
    QRect r = screen->virtualGeometry();
    return screen->grabWindow(0, r.x(), r.y(), r.width(), r.height());
}
```

Can you check that, please?

**Comment by PKEv** [comment]
from #2262:
my screen:
![my](https://cloud.githubusercontent.com/assets/6053197/10099609/e2ad8cf0-6393-11e5-9dd9-11a75240b22f.png)

The problem is not to give a picture of the screen with it copes well, a problem with the placement of the resulting image:
![in monent](https://cloud.githubusercontent.com/assets/6053197/10099611/e773aea4-6393-11e5-8e49-18012d64cb54.png)

**Comment by antis81** [comment]
@PKEv Thanks for the info! That changes situation.

**Comment by antis81** [comment]
@PKEv Can you check the new PR #2297 then, please? -> follow up to #2289

**Comment by PKEv** [comment]
closed
