### ISSUE TITLE
Organization - suggestions

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1617]
1 We need some kind of a list of people who implemented/changed stuff. Just in case a bug was found in a feature, we should be able to find person who implemented it easily. The author can be called to the issue to tell how difficult it is to fix it, and they should be aware of the problem. 

Proposal:

| author | feature |
| --- | --- |
| u/apprb | chat history |

2 Since we have versioning, we should add labels like '1st priority', '2nd priority' for issues.

**Comment by tucnak** [comment]
1. In fact, that's what "normal" people call a maintainer list. Basically, a table with fields: name, email, module (part of the source this particular dude is capable of); it's a terrific practice for a huge project, but is it worth introducing in qtox case? Imo, `git blame` would be enough so far, since we are not _that_ huge.
2. I'd just leave `grave`, `critical`, `important` for all crucial issues and no-label for all others. Kinda makes sense.

**Comment by Zer0-One** [comment]
I agree with @tucnak . If this project was larger, we could justify having a maintainer list for various features, but as it currently stands, I think that `git blame` will do the job.

**Comment by agilob** [comment]
You assume people have the same nickname on github, email and nick on tox (group chat), dubslow commited to qtox from at least 3 nicknames so far.

**Comment by tucnak** [comment]
Alright, anon is life, anon is life, but look, when you assoc your git identity with an email, it's kinda implying that you are _reachable_ that way. I can't see a problem, unless a particular commiter behaves weird.
