### ISSUE TITLE
Distance between settings icon and tabs is too damn far

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#1625]
@tucnak why did you move tabs from bottom to top? I doesn't make any sense. the distance is too far now.

![qtox](https://cloud.githubusercontent.com/assets/2544251/7574316/464acc72-f824-11e4-91f3-3bc0efbb241a.png)

**Comment by tucnak** [comment]
I agree that it kinda irresponsible in terms of quick access, but imo south-aligned tabs look weird, but again, that's my humble opinion. UX says that interface should behave as expected, and most people expect tabs to be placed right there, on the top. In the context of current problem, I think, it kinda overweights an idea to minimize the distance between the settings button and actual tabs.

**Comment by ProMcTagonist** [comment]
> most people expect tabs to be placed right there

I don't think that's a huge thing, it's very common to have them on the side if there are a lot and having them on the bottom makes for much quicker access. Sometimes what users are supposedly "used to" is worse, and this isn't a huge confusing change.

**Comment by tr37ion** [comment]
Having them on the top is better, because people are used to it. Especially for large sections like "General" it's more obvious to find the other tabs.

**Comment by Draako** [comment]
I need to agree with @tr37ion as for having tabs on the top. As a matter of fact I move the pointer straight away onto tabs once I hit Settings button without realizing what I am actually doing. So yes, with the newest build it was natural for me to look for tabs in the upper section.

**Comment by zetok** [comment]
I too like them being on top. Because reasons.

Edit: closeable, since question was answered, and most of people agree that it's better the way it's now?

**Comment by suhr** [comment]
I'd like to have them on the bottom or on slde.

**Comment by zetok** [comment]
On side doesn't sound bad, provided that it will not introduce a problem with labels of settings not being (fully) shown.

**Comment by agilob** [comment]
@suhr This will take a lot of effort, but I would love to see something like this in qTox. It's from gajim, every single thing is configurable.

![gajim](https://cloud.githubusercontent.com/assets/2544251/7752642/8400ee32-ffd8-11e4-8adb-491cc25692a5.png)

**Comment by ProMcTagonist** [comment]
I don't think having them on the side will look good, or leave much room for actual settings, if they're inside the normal window. 

@agilob I agree with sticking advanced settings into an about:config-type interface.

**Comment by tr37ion** [comment]
There are nice proposals, but ...
- Do we really get a benefit by redeveloping the settings pane - just because the mouse has to be moved a bit more in one direction - seriously?
- How often does the user actually open the settings dialog?
- At this stage of development, wouldn't it be better to put development time into new features like custom CSS skins eg.?

I see that there are nice suggestions, but I would rather see other issues on the priority list, than being concerned of _moving the mouse a bit more_ ...

**Comment by zetok** [comment]
@tr37ion moving your mouse a bit more is a serious issue, since it's about breaking workflow.

qTox is still in alpha, and thus breaking workflow isn't treated as such a big deal, but it will be treated much more seriously when qTox will be stable.

In this particular case, it's more beneficial to simply keep it at top.

That being said, it's good if users who don't feel comfortable with how things are could change them, even if there would be no "really easy" way, people who would really need it would have that functionality.

As I see it, @agilob's proposal is the only sane way of going about future of settings.

> I see that there are nice suggestions, but I would rather see other issues on the priority list, than being concerned of _moving the mouse a bit more ..._

…
Just so you know, I wanted to comment on that part, but perhaps it's better if I won't…
