### ISSUE TITLE
OSX: qtox is unaccessible after load

### ISSUE THREAD

**Issue by soredake** [qTox/qTox#1670]
After starting up and entering the password, the main window does not appear, by clicking on the icon it just does not appear. And the tray icon has become a very small.
![2015-05-17 21 59 48](https://cloud.githubusercontent.com/assets/5204968/7671599/1f66de5a-fce0-11e4-85b2-daa541c10a06.png)

https://gist.github.com/fenque/c1dd6652e046465283ff

**Comment by tux3** [comment]
@stqism 
The packaging is wrong. Note that it also has trouble finding the SSL library (:0 : Warning: QSslSocket: cannot resolve TLSv1_1_client_method).

Can you repro/fix?

**Comment by stqism** [comment]
@tux3
This isn't a packaging problem, that wouldn't actually be possible as those icons are embedded in the binary and not loaded from resources.

I too got annoyed by no icon so I looked in to the problem. Turns out reverting #1610 fixes the issue 100% perfectly and that @tucnak's PR is just a workaround for his/her's own broken or ancient system that breaks the feature for every single other OS X user.

I've released an update fixing this: https://wiki.tox.im/OS_X#1.1.20b

Regarding the ssl error, Qt calls Security.framework which is installed on the system and used by almost every app to use ssl so this is not a library loading issue but either a Qt bug/limitation or a qTox one.

**Comment by tucnak** [comment]
@stqism Well, I am building qtox with Qt 5.4.1 (from qt.io) with QtSvg installed and loaded at runtime. My OSX version is 10.10.3, which seems to be one of the latest. In fact, it turns out that Qt doesn't support svg icons in tray icons on OSX (well, at least for me) and I can't see a reason why would it draw a little icon there...

**Comment by agilob** [comment]
Qt is really buggy when it comes to tray icon, try starting qtox with gtk backend (I don't know how, sorry :P)

**Comment by stqism** [comment]
@tucnak 
Fresh install of OS X 10.10.3, with your PR:
![screen shot 2015-05-18 at 12 04 23 pm](https://cloud.githubusercontent.com/assets/11949584/7688013/28e82878-fd56-11e4-9af7-1e32865bf291.png)

Fresh install of 10.10.3 without your PR:
![screen shot 2015-05-18 at 12 04 39 pm](https://cloud.githubusercontent.com/assets/11949584/7688018/30fb2218-fd56-11e4-9775-cc2a322b69ad.png)

Yeah, that's a personal problem (as confirmed by my VM'd Mac, my own Mac, my usual testers, and this issues OP)

@agilob 
Usually, but only on Linux because of the lack of standardization or uniformity.

**Comment by stqism** [comment]
@tucnak Might I recommend a fresh install of OS X? It feels like something's broken in your stack somewhere

**Comment by soredake** [comment]
Also, white icon enabled 
![2015-05-18 22 29 20](https://cloud.githubusercontent.com/assets/5204968/7688480/5f5939e0-fdad-11e4-9700-220c907ea214.png)

**Comment by tucnak** [comment]
@stqism Fresh install is not a solution, anyway. Please, gimme a while, I'll do a quick research into the problem, seems like it's indeed an issue of my stack.

**Comment by stqism** [comment]
@tucnak Download qTox from https://wiki.tox.im/OS_X#1.1.20b and tell me if you get it.

**Comment by stqism** [comment]
@fenque Download qTox again and it'll magically work.

**Comment by tucnak** [comment]
@fenque Alright, it does work indeed. Why doesn't it work with my build then? Seems like a toolchain issue...

**Comment by stqism** [comment]
@tucnak Did you run macdeployqt?

**Comment by tucnak** [comment]
@stqism Not really!
