### ISSUE TITLE
Nearly all styles look the same on Windows 7

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1676]
On Windows 7 the only style which is acceptable is Fusion. All the Windows styles look the same - like Windows 2000.
Not even the Windows Vista style is displayed rudimentary like Windows Vista/7 looks.

There are only minor changes between WIndows/Windows Vista/Windows 7.
BTW a much more interesting (or different) style would be WIndows 8/IE 11, because it displays all controls flat and even the combo box behaviour is different (test it with IE 11 e.g. [here](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_select)):
![comboboxie11example](https://cloud.githubusercontent.com/assets/12105354/7672245/560e60da-fceb-11e4-82ca-1c6b7c28c49a.png)
(I think with Windows 8 this is similar)

**Fusion**
![styletestolive](https://cloud.githubusercontent.com/assets/12105354/7672194/a2241fe8-fce9-11e4-9f0f-c526a752de53.png)

**Windows**
![styletestwindows](https://cloud.githubusercontent.com/assets/12105354/7672195/a2243bc2-fce9-11e4-9f75-21a6f8e507b3.png)

**Windows Vista**
![styletestwinvista](https://cloud.githubusercontent.com/assets/12105354/7672196/a2249464-fce9-11e4-8fd2-3b1c1f75ab8e.png)

**Windows XP**
![styletestwinxp](https://cloud.githubusercontent.com/assets/12105354/7672197/a226caa4-fce9-11e4-9ab7-71a8848b9088.png)

**Comment by agilob** [comment]
Those styles are built-in in Qt, we have no effect on them. This setting will be removed (and only fusion will be used) after dark styles are merged and white style is 100% finished.

**Comment by ghost** [comment]
Okay, so then I think this issue is closed. Just deleting all styles is a solution of course. :smiley:

**Comment by agilob** [comment]
There is setting for 'useNativeStyle' in settings.cpp and in properties file, you can enable native style manually, but there is no GUI for this. The setting is removed in my darkthemes branch, and this 'style' combobox will be removed after dark styles are tested on all platforms and window managers.
The problem is, CSS for main window defines design, colours, etc of most widgets like checkbox, lineedit, but it doesn't define anything for combobox, so when you change style only those comboboxes look different, their theme is changed by Qt. I think it was supposed to be temporary solution, but it stayed with us for longer...

**Comment by ghost** [comment]
Okay, thanks for the explanation.
