### ISSUE TITLE
If I change my own nospam it isn't instantly reflected in the Tox ID

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#1680]
If I change my nospam (manually or by automatically creating) and switch to the Tox ID part there is still the old Tox ID shown. Only after a restart of qTox the new nospam will be displayed in the Tox ID.

**Comment by linux-modder** [comment]
Sounds normal to me, while can be annoying you have to restart the instance
to change the `runtime` settings to enable /reflect the change

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by ProMcTagonist** [comment]
That's terrible UX. It seems like nothing has changed. 

Pop up a dialog offering to restart now or later, and if later, make the relevant areas reflect that there's a new nospam that will be applied the next time you restart, with a button to do that. See: Firefox addons that require a restart.

**Comment by linux-modder** [comment]
Seems utterly redundant to make such a button or toast notification -- If
you make a new nospam and choose later and can't seem to remember that
fact, you have bigger issues to worry about in my opinion

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by ghost** [comment]
However it could be confusing for users if they know about the Tox ID and doesn't see it applied.

**Comment by linux-modder** [comment]
That is a un-informed user not a flaw in the program tho ....an idiot that
drinks and drives can kill people does that mean we stop allowing bars to
sell booze because some idiot drives drunk?

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by ProMcTagonist** [comment]
No, we make self-driving cars.

"The user should be smarter" is not how you design.

**Comment by ghost** [comment]
IMO it's the same like the language restart (https://github.com/tux3/qTox/issues/1671) - if there is a change which isn't applied immediately (only after a restart) let the user know about this.
If a question to restart is too "much" then maybe at least add a text line below the nospam edit box, whcih describes that a change to this setting will only be applied after a restart.

**Comment by zetok** [comment]
> IMO it's the same like the language restart (#1671) - if there is a change which isn't applied immediately (only after a restart) let the user know about this.

No, it's not. Nospam change should be reflected in the moment when you change it, anything other is a bug.

**Comment by linux-modder** [comment]
@zetok ,  If it takes tho does it truly matter if it takes a restart to
show graphically?

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Comment by zetok** [comment]
> @zetok , If it takes tho does it truly matter if it takes a restart to show graphically? 

um? sorry, but I don't understand what you're trying to say..

**Comment by ghost** [comment]
Any news about this old issue?
I mean I don't think that's so difficult to implement...

**Comment by zetok** [comment]
@blobgo while it may not be _too difficult_ to fix, amount of people who work on qTox code and the time they can spend on it is by no means sufficient - there simply are issues seen by people working on qTox as more important, given their time constraints.

Any help regarding fixing this, and other issues is warmly welcomed - since qTox is run by volunteers, often people don't have enough of time to fix every issue - if you, or someone you know could help with it, it would be greatly appreciated `:)`
