### ISSUE TITLE
[UI Enhancement] Possibility of pop out chats?

### ISSUE THREAD

**Issue by TapGhoul** [qTox/qTox#1705]
I think a good mini feature would to be able to right click on any user or group and open said chat in a pop out window. Maybe have it so if the pop out is open, selecting the chat in the main window focuses the pop out, but if it doesn't exist just show it in the main window.

This would be uswfu talking in multiple chats at once or even just organizing displays. The pop out status would NOT be saved, as each restart of the client would just have no popouts open.

Maybe have closed popouts refocus the chat in the main window (without focusing the window itself), and have that behavior togglable in settings.

**Comment by zetok** [comment]
Duplicate of #383

**Comment by TapGhoul** [comment]
Oh sorry, thank you.

**Comment by agilob** [comment]
Don't close, we keep duplicates open.

**Comment by zetok** [comment]
why keep duplicates open?

**Comment by agilob** [comment]
To not to forget, keep and eye on them, easier to find, more duplicates means more users are affected by an issue.

**Comment by zetok** [comment]
It's not easier to find things when there are tons of duplicates that are still open. Additionally, it's harder to keep track of things when they're spread across multiple issues that are just duplicates…

> more duplicates means more users are affected by an issue.

That doesn't mean that keeping duplicate open helps in substantial way - if it's an issue that affects many users, it should be tagged as such instead of keeping duplicates open.
