### ISSUE TITLE
[Feature request] Search in the chat history

### ISSUE THREAD

**Issue by SkyzohKey** [qTox/qTox#1734]
Hey, from now many days I'm thinking about a function to search for a word or an expression in the chat history (CTRL+F).

This could be cool ! :)

**Comment by ProMcTagonist** [comment]
+1

Right now I'm exporting and grepping a lot.

**Comment by Zer0-One** [comment]
+1

**Comment by Deleetdk** [comment]
I was looking for this today. I ended up exporting the chat history and searching in the file. This is a must have built in feature IMO.

**Comment by zetok** [comment]
@Deleetdk it's waiting for merge: #2013

**Comment by miltosc** [comment]
it is a must have feature +1

**Comment by g4jc** [comment]
+1 was just looking for this today, glad to see it's already being worked on.

**Comment by Deleetdk** [comment]
@zetok What happened to the merge with #2013?

**Comment by zetok** [comment]
@Deleetdk didn't happen, since pull request was introducing some problems and some changes were needed to be made.

Right now, there's a rebase of the PR (#2744) that someone could try to rebase again against newer master and make a PR with rebase. Note that rebase would need to have problems fixed/things changed in order to get merged.

**Comment by shinodem** [comment]
it this feature work?

**Comment by tele1** [comment]
+1

**Comment by Nadahar** [comment]
+1 This is still very much needed.

**Comment by tox-user** [comment]
Implemented in: https://github.com/qTox/qTox/pull/4955. Closing.
