### ISSUE TITLE
Notify if notification is outside of screen

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#1747]
With increasingly long friend lists, and friends sorted on name only, it's easy to sometimes miss notifications of friends because they fall out of the screen. qTox should display it if there are unseen notifications caused by contacts falling out of the screen.

Slack's "more unread" screenshot as reference:
![url](https://cloud.githubusercontent.com/assets/1885159/7844771/276f3856-04b3-11e5-813b-ff7c1ef13ef6.png)

**Comment by tux3** [comment]
Or we could sort friends with notifications first temporarily, so the most important/urgent conversations are what you see first. This way you wouldn't have to go search through your contact list for that one friend with a notification. Thoughts?

**Comment by TheSpiritXIII** [comment]
I'd rather have what tux3 mentioned. It saves more time than having to scroll all over the place.

**Comment by Zer0-One** [comment]
I still think we should have a separate "tab" where friends are sorted by activity.

**Comment by zetok** [comment]
@TheLastProject how is the way in which mockup handles this worse than what you're proposing?

@tux3 @TheSpiritXIII ↑ ?

**Comment by TheLastProject** [comment]
Randomly resorting the sorted friend list is a horrible hack. @Zer0-One says what we need too, but the alphabetical list should remain alphabetical.

@zetok The mock-up doesn't even show any case of new message notifications being invisible because the contact list is too long and the contact falls out of the screen.

**Comment by zetok** [comment]
@TheLastProject so? What you're describing is `default` view, and it should behave like that.

On the other hand, there also should be `Recent` view… Can you say what is worse about mock-up approach, compared to your proposal?

**Comment by TheLastProject** [comment]
Again, I can't compare the mock-up because it does not deal with this issue at all... Do you even understand the problem? The problem is that my friend list is so long that when someone whose nick starts with z messages me, I often don't notice because they, and therefore their new message ring, are not visible in my friend list until I scroll down

On 28 May 2015 10:32:12 CEST, zetok notifications@github.com wrote:

> @TheLastProject so? What you're describing is `default` view, and it
> should behave like that.
> 
> On the other hand, there also should be `Recent` view… Can you say
> what is worse about mock-up approach, compared to your proposal?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tux3/qTox/issues/1747#issuecomment-106231700

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zetok** [comment]
> Again, I can't compare the mock-up because it does not deal with this issue at all...

Except that it can deal with it:
Here you go:
![mockup](https://raw.githubusercontent.com/ItsDuke/Tox-UI/master/current.png)
**↑ `s/Online/Recent/`**
- `Recent` view shows contacts sorted by recent activity, in descending order. I.e. contact that just sent you message 2s ago will be on top of the list, while contact that sent you message 2h ago will be below.
- All contacts are shown in `Recent`, independently from their status.
- Small issues:
  - currently it's not possible to implement that for every activity in a way that would be persistent across qTox restarts, since `file transfers` and `calls` aren't saved in DB.

Basically what @Zer0-One was referring to.

# 

> The problem is that my friend list is so long that when someone whose nick starts with z messages me, I often don't notice because they, and therefore their new message ring, are not visible in my friend list until I scroll down

`Recent` seems to handle that, even in a case where there was so much activity from lots of different contacts that your whole contact list is "double-circled" - there you simply know to scroll down a bit in `Recent`, until you'll find a contact without activity.

With that being said I see your proposal as something that goes against what mock-up provides, i.e. either you'd have that notification telling you that there are unread messages, or mock-up implementation.

I realize that joining those two ideas can be doable, if that notification were to be extremely morphed into something that wouldn't be so invasive, but I'm not quite sure whether it's a good idea, since notifications are nice, make you feel warm and fuzzy, but they have downside in that they are a distraction, + they take up space.

Now, if you could give some reasons why it's actually a good idea to use it with/without what mock-up provides, it would be nice, and in case without what mock-up provides, why it's better than what mock-up provides? (what I've been asking whole time)

# 

@TheLastProject now, if we could avoid stuff like

> Do you even understand the problem?

it would be much better.

I realize that the way I went about asking what exactly advantage your idea has over what mock-up can provide was not the best route, and that partially I'm at fault here, since I've assumed that people are aware of what mock-up provides, which apparently isn't really the case..

**Comment by TheLastProject** [comment]
For the third and final time: The mock-up does not show any solution to this. A recent screen is another feature we should have too, but it doesn't fix this issue. Giving people the choice to have a list sorted on recent changes doesn't mean that people using the alphabetical list should have to miss notifications if their friend list is too long to fit on the screen.

Also, the Online thing is implemented differently in qTox than how you describe it in the mock-up, allowing you to switch between online/offline/friends/groups instead of alphabetical/recent.

Why would a "more unread" thing in the style of Slack even go against the mock-up? It's not even aggressive at all. Like, sure, it could have another colour or whatever fits qTox better, but those are implementation details, we're talking general design here.

I can't tell you why this is better than what the mock-up provides because the mock-up provides NOTHING in this case. The reason this is good is because qTox would show me that I have an unread message from a friend even if they're sorted all the way down in online contacts, which is currently not shown at all until I scroll down, and I shouldn't have to scroll through my friend list randomly every now and then just to see if I didn't miss any notification.

A few cases you will miss the notification in:
1. You have qTox open, but your sound off, and the out-of-screen friend sends you a message
2. You walk away from your PC for a bit, get a new message, come back to qTox and not see a new notification circle anywhere
3. You get a new message from two friends at almost the same time, and therefore only notice the friend that is visible

This literally happens several times a day, and is very frustrating.

**Comment by zetok** [comment]
> Also, the Online thing is implemented differently in qTox than how you describe it in the mock-up, allowing you to switch between online/offline/friends/groups instead of alphabetical/recent.

Not really. You already have ~alphabetical view, a.k.a `All`. This means that there has to be added just `Recent`.

Thanks for explanation @TheLastProject.

# 

@TheSpiritXIII , @tux3, @Zer0-One sounds like `unread notification` it is needed along with `Recent` "tab", right? `:3`

**Comment by TheSpiritXIII** [comment]
For purposes of demonstration, here is a better mockup of what zetok was describing:
![qtox-recent-mockup](https://cloud.githubusercontent.com/assets/4027687/7859563/32f1f238-0510-11e5-8023-48fd4670bcda.png)
Notice how all notifications are at the top. Furthermore, there are some offline users at the top and some online users below because the offline user spoke more recently than that online user. From looking at this, we should need some UI to distinguish how recent the activity is because looking at this is a bit confusing. Skype has a "toady" section for the most recent chats. What do you guys think?

@zetok I agree. That would fix the issues that @TheLastProject was having.

**Comment by ProMcTagonist** [comment]
What if I have so many recents they go off the screen?

We need a recent view for sure but the edge hint would also be helpful. Is there a reason we can't do both?

**Comment by ghost** [comment]
This got a bit confusing, so I'm not sure if someone proposed this, but shouldn't the contacts which have a notification (extra circle around them) be temporarily moved to the top? 

For example, say that you have an alphabetical list of contacts that goes off screen. Zetok sends you a message, but you are away at the time. Zetok is not visible on the list because he's somewhere at the bottom, but he gets temporarily moved at the top of the list. So when you come back, you look at qTox and see this:

(O) Zetok
O Anton
O Cyril
O Daniel
O Debra
...

This way, you kind of get two lists: The one on top has alphabetically listed contacts with notification, and the bottom one has alphabetically listed contacts without a notification. When you click the contact / read the notification, the notification disappears and the contact gets moved back into the 'bottom list', into it's proper place in the alphabet.

We already have few lists on top of each other, with each list hosting contacts with one online status (Online, away, offline). This way, we would just get one more at the top, this time for contacts with notification. This should fix the issue, without a need to build in another functionality (notification for notifications in the window).

**Comment by zetok** [comment]
@Tirifto 
“Randomly resorting the sorted friend list is a horrible hack.”

**Comment by TheLastProject** [comment]
I forgot to say what I meant with "a horrible hack". My point was that it'll make contacts jump around, which is quite awful to look at, and that the solution is mostly suggested because it's easier to code, not because it's a better user experience.

**Comment by zetok** [comment]
@ProMcTagonist 

> What if I have so many recents they go off the screen?

“`Recent` seems to handle that, even in a case where there was so much activity from lots of different contacts that your whole contact list is "double-circled" - there you simply know to scroll down a bit in `Recent`, until you'll find a contact without activity.”

I.e. just scroll down.. difference between `All` and `Recent` is the way in which contacts are sorted - in `All` they are sorted ~alphabetically with online/offline contacts separated, while `Rectent` would have sorting by time of last activity, in descending order.

**Comment by ProMcTagonist** [comment]
@zetok I don't think we can expect users to know to just scroll down. The edge hint would be helpful whether the user is in Recent or All.

**Comment by zetok** [comment]
Should notifications be shown also for groupchats?

**Comment by TheSpiritXIII** [comment]
My branch currently does notify for group chats only if the "Group chats always notify" setting is enabled. Group chats can become very active, so if you have OCD, you would not want to keep having to check the notification. :p

**Comment by ProMcTagonist** [comment]
It's as it should be that it follows the existing groupchat notification setting.

**Comment by zetok** [comment]
> My branch currently does notify for group chats only if the "Group chats always notify" setting is enabled.

Oh, then it's totally fine, don't mind me.

Edit: (I don't have that setting enabled)

**Comment by TheLastProject** [comment]
Fixed in #1843
