### ISSUE TITLE
qTox 1.0-1737 - has active microphone all the time (without a call)

### ISSUE THREAD

**Issue by jaceq** [qTox/qTox#1880]
Hi,

Looking through pulseaudio (on Ubuntu 14.04) I noticed qtox activates microphone when it's on ALL the time, even when there is no call in progress etc. I think this is bad and can give impression of being listened to / spied on ... Same is tru in fact for output audio device. 

proposed solution: Activate input / output audio device only when it's needed (so microphone during audio / video calls, and output device during calls and when some sound / notification is played)

**Comment by towlie** [comment]
I think this this can befixed in a similar way I suggested here: https://github.com/tux3/qTox/issues/1862
OpenAL should provide a function for mic devices, too.
Maybe this function can be used for input and output devices?

**Comment by tux3** [comment]
Last time I checked this wasn't really fixable due to a bug in OpenAL (couldn't restart the mic after stopping it for some audio cards), I'd have to check if the bug fix has reached enough people.

**Comment by agilob** [comment]
Microphone is always all the time, Steam has the same bug. It's not dependent on us, so I think it should be closed.

**Comment by suhr** [comment]
> I think it should be closed

Should it? This is yet a bug.

**Comment by agilob** [comment]
but it's not on our side.

**Comment by suhr** [comment]
Can we workaround it somehow (or consider using something else instead of OpenAL)?

**Comment by 0xf00f** [comment]
If the code is such to keep the microphone active, because of a bug in some other library (OpenAL), then it certainly is a bug in qTox.  This ticket/issue should stay open until properly fixed.

If the code is written properly, but OpenAL keeps the microphone open due to a bug, then this ticket can be closed with the note that it can't be fixed in qTox and with a link to where one should file complaints.

In the meanwhile, on startup a modal dialog should open indicating that "qTox will keep the microphone open at all times!!! Please don't be afraid, we are not doing it due to malpractice, but because we don't have other viable choice for the time being. This issue is well-known and will be handled in the near future. More info (link to the issue)"

**Comment by 0xf00f** [comment]
One side note: in some situations (certain audio system and certain configurations), audio is blocked for some applications (for example - when qTox is open, no sound is available in VLC)

**Comment by towlie** [comment]
This fixes the issue. I  tested it and didn't find issues. https://github.com/TheSpiritXIII/qTox/tree/mic
But it uses a hack to resume output devices for calls due to a strange bug.
Oh and this branch closes the input device (mic) and output device when it is not needed.

**Comment by zetok** [comment]
> Can we workaround it somehow (or consider using something else instead of OpenAL)?

From what I remember, @tux3 said that perhaps it would be good to remove openal completely in favour of just using ffmpeg.

**Comment by ghost** [comment]
Can you just check how "audio" part is done at other tox clients? Like uTox, etc. And do the same thing...

**Comment by zetok** [comment]
#2415 should close this.

**Comment by zetok** [comment]
Should be fixed by #2415, thus closing.

If you still have this issue, please comment for reopen.

Note that there is #2435.
