### ISSUE TITLE
Talk Recording

### ISSUE THREAD

**Issue by shalnoff** [qTox/qTox#1904]
Hi there. 
It's often necessary to record conversation for future interpretation or a lot of other purposes. It would be great to add Talk Recording feature in qTox interface (additinal button?). Maybe even without compression to avoid unnecessary porcessor loading (or with optional mp3 compression)

NB I was using uTox for 9 month as far as it anonced as "official client" and have install qTox today by curiosity and to try some features. I have to admit that IMHO It's the best (and far advanced) Tox desktop client on preset time. Thanks guys, it's great job!

**Comment by DanTheBritish** [comment]
Tox in general is focused around security and privacy, but at the same time is a Skype replacement.

Neither three of those call for call/video recording functionality built in, in my opinion.

Seems like feature creep.

**Comment by ProMcTagonist** [comment]
> future interpretation or other purposes

This user will have external recording software.

**Comment by Zer0-One** [comment]
@LapFox it's something that people can do anyway, so we might as well make it easy for the people that actually want to do it.

**Comment by DanTheBritish** [comment]
But recording a conversation without authorisation from the other party is illegal in a lot of states / countries, so better to make it difficult because we wouldn't want qTox to potentially encourage illicit behaviour.

**Comment by Zer0-One** [comment]
@LapFox i suppose a murderer could plot to kill someone over tox as well, but we aren't shutting the whole project down

**Comment by shalnoff** [comment]
(sorry for offtopic) LapFox, it's illegal to 
a) record 3d parties talk without permission
b) share / publish recorded talk without permission
however it's 100% legal to record _your own_ talk with anybody without permission and without publishing it. 

I.e. for interviewing people, for recording negotiations talks, for collective conversation recording and a lot of other things. You, by the way, have this feature in your cell phone by default and probabaly in landline phone as well :) I'm not sure about States (all states), but major of other countries law has zero problem with this procedure.

**Comment by shalnoff** [comment]
> > future interpretation or other purposes
> 
> This user will have external recording software.

Unfortunately It doesnt' works normally with Pulse Audio (nor even naked Alsa pseudo device), since the process eats a lot of resources. It's much simpler to stream both channels in single PCM file right after decoding.

**Comment by JFreegman** [comment]
@LapFox then it would be the responsibility of the recording party to inform their conversation partner that they are recording. It's not our job to police how people use our software. Moreover, Tox is not governed by any single nation's laws; it's both written and used by people who come from a large variety of countries, and it's everyone's own responsibility to comply with their local laws.

**Comment by ghost** [comment]
Audio recording would be a nice feature. Jitsi actually does have it built-in. The issue concerning recording without permission could be solved by making the recording work as a request.

When one person in the call chooses to record, the request will be sent to all other members of the audio chat. (Since the feature could be applied to group chats, too.) Now, I see three cases of what could happen next:
- Everyone approves of the recording and thus everything is recorded. No issues. (No ethical ones, anyway.)
- (Concerning groupchats only.) Only some people approve of the recording. Now I don't know how Tox internally works, but it could either not record anything, or it could record only those people who agreed to the recording. The latter seems a bit shady, though.
- C. Nobody approves of the recording. Following the example of previous case, Tox could either record nothing, or record only the person who requested the recording. And again, the latter seems a bit strange to me.

> (or with optional mp3 compression)

@shalnoff Please no MP3. If encoding, then with an open format, like OGG, or OPUS.

**Comment by agilob** [comment]
This could work as a 3rd party plugin to qtox, but should not be available in default package (see legal concerns).
