### ISSUE TITLE
Untrusted certificate for qTox binaries

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2047]
When I try to download the windows x64 qTox binary from your github site, or from https://wiki.tox.im/Binaries#Windows
My browser stops. It claims that the certificate is invalid and it will not proceed any further.
**The text I get:**

tux3-dev.tox.im uses an invalid security certificate.

The certificate expired on 09/07/2015 02:28. The current time is 31/07/2015 17:38.

 (Error code: sec_error_expired_certificate)

**Comment by ghost** [comment]
Maybe this has to do with: https://github.com/tux3/qTox/issues/2033

You should not use tox.im anymore. Use tox.chat instead.
However on tox.chat there are currently no Windows builds. You will have to wait until the Windows builds are released again.

**Comment by ProMcTagonist** [comment]
@slentzen 

The domain that you mentioned has been seized by a rogue third party and is NOT associated with the Tox project or its developers. Please use the real website, https://tox.chat, instead, where downloads will be available shortly. 

It would also be very helpful if you told your friends about this change as well, so that [the real website](https://tox.chat) can rise in Google search results.

Thank you for contributing this issue and for using Tox :)

**Comment by suhr** [comment]
Should be closed in favour of #2055.
