### ISSUE TITLE
qTox doesn't save window position

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#2063]
Windows 7 and 10
- It seems that it saves something but it is wrong. Every restart it moves it's position a bit more to the left and also moves a bigger step to the top.
- This is what it saves: https://gist.github.com/towlie/de3a3d270e111d6d83cb
- I saw that qtox starts in the middle of the screen on first start. but on second start it starts at coordinates 0;0
- qTox only saves a new position if you resize the window but it will move a few pixels to the left again after every restart

**Comment by towlie** [comment]
It seems that it saves something but it is wrong. Every restart it moves it's position too.

**Comment by rugk** [comment]
Do you possibly have the window maximized?
Because in this case I see this a lot of times (not only limited to Tox).

STR:
1. Open window and maximize it (e.g. on another screen)
2. Minimize it or close it.
3. Reopen it.

What happens: It will be showed nearly at the same position, but not maximized like it was before.
What should happen: Show it maximized.

**Comment by towlie** [comment]
No.

**Comment by towlie** [comment]
Updates in first post.

**Comment by towlie** [comment]
Update: it doesn't move to the left only, it also moves a bigger step to the top on every restart. (So it saves incorrect values for x and y)
