### ISSUE TITLE
New Windows released (finally)

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2085]
At first:
Do you somehow sign the Windows binaries? At least with PGP?

Otherwise it would at least be nice to publish some file hashes. The 64bit Windows ZIP has this hash here: 5DE11183D11EEAD7A50107BB0FBA8482DDA2BAAA

Remember that the old builds (the exe files) were code signed by Tox Foundation with a valid certificate (valid until 30.02.2016).

---

Secondly in the ZIP is only the Tox.exe. But the original qTox WIndows build was much more. It included many libraries and even had an uninstaller/installer and an updater.
FYI this is the complete directory structure of the qTox dir:

```
qTox
|   uninstall.exe
|   uninstall.log
|   
\---bin
    |   avcodec-56.dll
    |   avdevice-56.dll
    |   avformat-56.dll
    |   avutil-54.dll
    |   flist
    |   icudt53.dll
    |   icudt53.dll.bak
    |   icuin53.dll
    |   icuin53.dll.bak
    |   icuuc53.dll
    |   icuuc53.dll.bak
    |   libbz2.dll
    |   libeay32.dll
    |   libfilteraudio.dll
    |   libfreetype-6.dll
    |   libfreetype-6.dll.bak
    |   libgcc_s_seh-1.dll
    |   libglib-2.0-0.dll
    |   libHalf-11.dll
    |   libharfbuzz-0.dll
    |   libharfbuzz-0.dll.bak
    |   libiconv-2.dll
    |   libiconv-2.dll.bak
    |   libIex-2_1-11.dll
    |   libIlmThread-2_1-11.dll
    |   libintl-8.dll
    |   libjasper-1.dll
    |   libjpeg-9.dll
    |   liblzma-5.dll
    |   libopencv_core249.dll
    |   libopencv_highgui249.dll
    |   libopencv_imgproc249.dll
    |   libopus-0.dll
    |   libpcre-1.dll
    |   libpcre16-0.dll
    |   libpng16-16.dll
    |   libpng16-16.dll.bak
    |   libsodium-13.dll
    |   libsodium-13.dll.bak
    |   libsqlite3-0.dll
    |   libstdc++-6.dll
    |   libstdc++-6.dll.bak
    |   libtiff-5.dll
    |   libtiff-5.dll.bak
    |   libtoxcore-0.dll
    |   libtoxdns-0.dll
    |   libtoxencryptsave-0.dll
    |   libwinpthread-1.dll
    |   OpenAL32.dll
    |   Qt5Core.dll
    |   Qt5Core.dll.bak
    |   Qt5Gui.dll
    |   Qt5Gui.dll.bak
    |   Qt5Network.dll
    |   Qt5OpenGL.dll
    |   Qt5Sql.dll
    |   Qt5Svg.dll
    |   Qt5Widgets.dll
    |   Qt5Widgets.dll.bak
    |   Qt5Xml.dll
    |   qtox-updater.exe
    |   qtox.exe
    |   ssleay32.dll
    |   swscale-3.dll
    |   version
    |   zlib1.dll
    |   
    +---imageformats
    |       qgif.dll
    |       qico.dll
    |       qjpeg.dll
    |       qsvg.dll
    |       qtiff.dll
    |       qwbmp.dll
    |       qwebp.dll
    |       
    +---platforms
    |       qminimal.dll
    |       qwindows.dll
    |       
    \---sqldrivers
            qsqlite.dll
            qsqlodbc.dll
            qsqlpsql.dll
            qsqltds.dll
```

So do we need this still? Now I've just replaced the old qTox.exe with the new one and it works. However it would be good if you could clarify this.
Additionally the download gave me a nightly build, what I didn't expected. (hash: https://github.com/tux3/qTox/commit/aed6c25fda02c2aadeeb464cc7be2b79723cc641)
As qTox is now stable it would be good to switch to a release system with version numbers (well... you already did this) and offer these for downloading.

**Comment by zetok** [comment]
> Do you somehow sign the Windows binaries? At least with PGP?

Still has to be done.

> Otherwise it would at least be nice to publish some file hashes. The 64bit Windows ZIP has this hash here: 5DE11183D11EEAD7A50107BB0FBA8482DDA2BAAA

Yes, it would be. Thing is, binaries from jenkins are going to be rebuild on ~every push to qTox repo, which means that place where hashes would be published would need to also be updated on every new qTox build. Automatically. Hash could be made on jenkins, but thing is. you already download binaries from jenkins…

That aside, what you've pasted seems to be a `md5` hash, which is **not** secure. What you want to use for hashing, is at least `sha256`.

For signing stuff, first we would need to figure out who, when and how will be signing qTox binaries.
Preferably @tux3, but I don't know whether he will have time for it, so…

> Secondly in the ZIP is only the Tox.exe. But the original qTox WIndows build was much more. It included many libraries and even had an uninstaller/installer and an updater.

Current qTox `.exe` is supposed to bundle all needed by qTox libraries - i.e. you should be able to run qTox as a standalone binary, without any other files (spare for profile files, located in `%APPDATA%`).

> So do we need this still? Now I've just replaced the old qTox.exe with the new one and it works. However it would be good if you could clarify this.

You shouldn't need it any longer.
If qTox as a standalone binary doesn't work, then it's not a desired behaviour, and should be reported.

> Additionally the download gave me a nightly build, what I didn't expected. (hash: https://github.com/tux3/qTox/commit/aed6c25fda02c2aadeeb464cc7be2b79723cc641)
> As qTox is now stable it would be good to switch to a release system with version numbers (well... you already did this) and offer these for downloading.

No, qTox is not stable, and won't be for some time.

What may be possible in the (near?) future, are (bi?)weekly (or monthly?) qTox releases that may be a bit more stable than nightly builds.

# 

On a side note, I've told @tux3 that using `1.x.x` for qTox is not (yet) right, since it makes people think that qTox is stable, and they expect it to just work.. which it usually does, but it also has potential to unexpectedly break, which is not something that people would expect from `1.x.x`-release software.

**Comment by cjpit** [comment]
Well done all for getting things all updated on tux3's return so quickly.  I uninstalled qtox (old) and the new one worked fine.  Question will the automatically download new updates still work or should that be removed? Since there is no separate qtox updater etc?

**Comment by ghost** [comment]
Okay thanks for your reply.
So I can delete all this libraries, great.

1) About the hash: I posted a SHA-1 hash. No way I would post a MD5 hash. And SHA-1 is basically secure, but as I know SHA-2 is much better here you go:

```
d0bdb9637ddd12ddcba7a51e62749cbc2a59ae684940756928209b29d4f0d8b1
```

2) Only one thing which is missing now: (also an reply to @cjpit) The updater is missing. This way there are no automatic updates, but I assume this is linked to the signing part (as the updater has to get verify the downloaded file) and the Jekyll build system where you do not really have releases now.

3) 

> using 1.x.x for qTox is not (yet) right, since it makes people think that qTox is stable, and they expect it to just work.

Oh yes you were right, because exactly this is what I thought.
But that's how [semantically versioning](http://semver.org/) works, so I just see he has broken this. :cry: 
And I see there is no real plan at what time/how to release builds. And that's not bad because I can understand it - I mean you already have a Windows build released again, which is a good step to go on.

**Comment by zetok** [comment]
> Question will the automatically download new updates still work or should that be removed? Since there is no separate qtox updater etc?

Sadly, that part has to be yet worked out - i.e. currently there's no autoupdating.. `:(`

**Comment by tux3** [comment]
We don't have a signing certificate anymore, but we'll continue to provide qTox downloads under a secure HTTPS connection and sign every qTox updates with the project's key.
We don't need all the old files anymore as you've noted, just what's in the new release.
