### ISSUE TITLE
Default path selecor in general settings should set path ending with system-dependent slash

### ISSUE THREAD

**Issue by agilob** [qTox/qTox#2152]
folder path must ends with `/` on unix or `\` on windows.

**Comment by ezavod** [comment]
Note: One could use [`QDir::toNativeSeparators`](http://doc.qt.io/qt-5/qdir.html#toNativeSeparators) and [`QDir::fromNativeSeparators`](http://doc.qt.io/qt-5/qdir.html#fromNativeSeparators).

However I strongly doubt that there is a point in adding unnecessary complexity by converting slashes in paths (maybe only for display purposes so that windows users are not disturbed):
> Qt uses "/" as a universal directory separator in the same way that "/" is used as a path separator in URLs. If you always use "/" as a directory separator, Qt will translate your paths to conform to the underlying operating system.
[-- QDir Documentantion](http://doc.qt.io/qt-5/qdir.html#details)

Furthermore Windows already handles `/` correctly in paths (see [MSDN)](https://msdn.microsoft.com/de-de/library/system.io.path.directoryseparatorchar(v=vs.110).aspx?cs-lang=cpp) and [first Note](https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#paths).

**Comment by zetok** [comment]
So the issue can be closed?

**Comment by ezavod** [comment]
I think so, technically it is superfluous, except somebody has a good point why this is needed as a kind of visual improvement.
