### ISSUE TITLE
.deb file should contain .application entry for Unity/Gnome3

### ISSUE THREAD

**Issue by raver119** [qTox/qTox#2154]
Would be nice, if repository .deb file will contain .application entry for Unity/Gnome3 dashboard.

**Comment by FatCache** [comment]
Does this issue include the inability to create proper launcher of 'Qtox' by having the application "lock to launcher"? Because when you over over the icon on the Unity launch bar, it says "qtox-settings'. When you close/killall qtox and try to start from the icon, nothing happens. I have to run it via download executable file from tox.chat for 'unity-tray'.

Another thing to note is that I was running the nightly version, was having the same issue. Had to run it via terminal. Now learning there is a unity-tray edition of qtox or binary of it, I've been using it. But it has somehow corrupted nightly version which is no longer launching.

**Comment by raver119** [comment]
qtox-unity build allows "lock to launcher" feature, but first run should be done via terminal.

p.s. qtox-unity cant be found at debian repo :(

**Comment by FatCache** [comment]
Doing that seems to lock a 'wrong' portion of qtox which is 'qtox-settings'.

**Comment by raver119** [comment]
No, its worse. Using launcher bar to open previously minimized qtox opens minimized window, and 30 seconds later it opens new login window :)

So it definitely needs .desktop file to work properly

**Comment by FatCache** [comment]
The minimize to launch bar seems to work fine on my system. No delay or any new login window. It's not terminating it. But when you do terminate it and try relaunching from unity launch bar, it doesn't work.

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/deeb9b2308290e0404198a38a5d4c456ac39b328/INSTALL.md#community-builds ← could you check if it works for you?

**Comment by zetok** [comment]
Community builds provide `qtox.desktop`, thus closing.
