### ISSUE TITLE
qTox froze when I've clicked to open file dialog to send file (100% cpu usage)

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#2173]
Description:
qTox froze without opening file picker, using 100% CPU.

Info:
OS: Hardened Gentoo Linux x86_64
qTox version: aaf0774f356786a183c1ca48b9a1fc14586d9554
Qt version: 5.4.2

Reproducible: ~~Couldn't reproduce~~ Always

Steps to reproduce:
1. Use qTox for a long time without turning it off, with very active groupchat, and then try to send a file?

What happened:
qTox hanged, without showing file picker.

What should happen:
qTox should open file picker.

Additional info:
[![Flamegraph](https://d.maxfile.ro/yybitsaqyz.svg)](https://d.maxfile.ro/yybitsaqyz.svg)

**Comment by zetok** [comment]
Actually, scratch that, I couldn't reproduce on build with #2150 merged; it's reproducible on master 7796421f73b8be293817fa126e55be5af94e4048.

**Comment by agilob** [comment]
It's because something changed in Qt (or filepicker, I think), and since now, path selector (for accept directory) does not include slash at the end of the path, but to save a file **or** open directory (not file, directory( you need that slash at the end... #2152 and #2135 are related, #2150 fixes it by adding slash in source code. I couldn't reproduce it on KDE4, but always crashes on KDE5, even with the same version of Qt, so I'm not sure what causes it, but adding slash solves the problem.

In #2135 crash was caused by opening a path that doesn't end with slash.

https://github.com/tux3/qTox/pull/2150/files#diff-a775ed8850c5781a2c749c3cafbe4e10R480 Line that fixed it (at least for KDE5)

I don't know on which environments or Qt version filepicker will crash...

**Comment by zetok** [comment]
Closing, since #2150 got merged.

**Comment by zetok** [comment]
Reopening, since problem still exists on 99b5b092d964b634ce39cc4f452711602b38d467 in merge of #1938.

Happened when I've de-selected "Autoaccept files" and I've tired to select default save path for files.

Edit: backtrace: https://gist.github.com/zetok/fed0072b3124a6868a7f

**Comment by zetok** [comment]
So, qTox hanged when I've tried to open file picker to save the file someone wanted to send to me on 38c68658e032a10f792f225cc7eeb9c46cf4f504 . Original is about hanging when sending file, but I think that it's the same issue.

**Comment by tux3** [comment]
Ok, the backtrace makes it pretty clear what the problem is.

> #2 0x00005555556b1e0a in operator>> (dataStream=..., data=...) at src/persistence/settingsserializer.cpp:64
> #3 0x00007ffff479306e in QFileDialog::restoreState (this=this@entry=0x7fffffffc3f0, state=...) at dialogs/qfiledialog.cpp:501

There's this blatant ODR violation in settingsserializer.cpp that was never fixed, and the linker happily gave the "wrong" function to Qt, so that conflict just needs to be resolved.
