### ISSUE TITLE
qTox fails to link

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#226]
https://github.com/tux3/qTox/commit/95dedc37598cc31866dad60043e48abff41b11f5 ← good job

```
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lsodium
collect2: error: ld returned 1 exit status
make: *** [qtox] Error 1
```

Also, why trying so hard make things worse?
I mean https://github.com/tux3/qTox/commit/46fd073ba8c5c8bbcd6c714c27e27ae637e58d1d
Is there any **real** reason why would you want to make all users have build in qTox core and sodium?
Why changing something that works perfectly, were there any complains?
(also, you realize that you're making packagers to find out why shit is being linked statically, and patch source, because it's unacceptable?)

**Comment by tux3** [comment]
> why trying so hard make things worse?

The problem is, there are no official packages for Toxcore or libsodium, so if I distribute a qTox package that depends on them, who is going to provide /usr/local/lib/libsodium.so.10 or /usr/local/lib/libtoxcore.so.0 ? 
They are not even packaged! And I'm sure as hell not going to install those with qTox, otherwise if someone makes some packages later on, qTox will conflict with them. Hence the static linking.

> Why changing something that works perfectly, were there any complains?

People complained, several times, that there are no Linux build of qTox, and since qtox-linux on Jenkins will apparently never be fixed, I'm fixing it. I do realize that some people build from source, and this issue will be fixed.

I'll add some sort of ifdef for packagers and revert to full dynamic linking for everyone else.
