### ISSUE TITLE
Screenshoting while multiple windows mode

### ISSUE THREAD

**Issue by uxname** [qTox/qTox#2303]
I set option multiple windows mode, and when i doing screenshot i press "space" to hide chat-window, but only contact-list window is hidden.
That's effect you can see in attached gif
![qtox](https://cloud.githubusercontent.com/assets/2634142/10118113/25fb57c8-6478-11e5-9fa1-fd61d60428d3.gif)
.

**Comment by antis81** [comment]
This happens most likely, when the chat window is not correctly parented by the main window. I'll have a look at it.

**Comment by antis81** [comment]
Had a look at it. My guess was right, but I don't know how to fix it… Unfortunately we don't have direct access to the main window (should become the parent of all classes inheriting `Widget` - excluding itself of course). @PKEv Probably one for you? I can help on questions.

**Comment by agilob** [comment]
QApplication::allWidgets() -> foreach hide?

**Comment by antis81** [comment]
@agilob  Why such bullshit? Simply assign the parent correctly (the main window is the parent) and it will behave correctly in every situation! (100 exclamation marks :smile:)

**EDIT** Well… we could do `foreach(QWidget* w, QApplication::topLevelWidgets()) { w->hide; }`. Though the missing parent will cause other problems as well. Have a look at qthelp://org.qt-project.qtwidgets.550/qtwidgets/qapplication.html#topLevelWidgets

**Comment by antis81** [comment]
@agilob First, apologies for my somewhat rude language - I was really pissed that day (long story…).

My first thought also was, that the `foreach…` might work. In short: It doesn't! Why? Simply because it will make **every** invisible top-level widget (hidden dialogs, qTox settings, etc.) visible. Funny result… :smile:

Thus, the only solution is to actually clean up the code and make at least every `Widget` (actually each QWidget a child of the qTox main window). It will never work reliable otherwise. There also should be a static method (probably in Widget), providing the pointer to the qTox `QMainWindow`. This is achieved like so (you can find it in Qt docs as well):

``` c++
static QWidget* Widget::qToxWindow()
{
    foreach (QWidget* w, qApp->topLevelWidgets()) {
        if (w->isWindow() && w->objectName() == QStringLiteral("MainWindow"))
            return w;
    }

    // This must not happen!
    Q_ASSERT(false);
    return nullptr;
}
```

Think the `Widget::getInstance()` method is supposed to do that, but actually it doesn't. I'll fix it and provide a PR, so we can better discuss this.
