### ISSUE TITLE
Encrypt user data

### ISSUE THREAD

**Issue by suhr** [qTox/qTox#246]
Tox data should be encrypted. Toxcore discussion: https://github.com/irungentoo/toxcore/issues/939

Implement it when it's done (also, why don't we have `todo` label?).

**Comment by tux3** [comment]
"enhancement" is basically "todo". Otherwise if there's a consensus that we're not doing that I just close the ticket.

Regarding the encryption, this implies asking the user for a password everytime, otherwise that's just security by obscurity as someone helpfully pointed out.
I don't have a strong opinion for or against password prompts on startup by default, but I'm not sure if everyone will like that.

**Comment by dubslow** [comment]
I would be okay with optionally adding password encryption -- anything else would be pointless, since any access to the data would necessarily equate to access to the encryption key (excepting the password case).

**Comment by tux3** [comment]
But should we make that opt-in, or opt-out ?

**Comment by dubslow** [comment]
I would prefer opt-in, perhaps with a pop-up  suggesting it when a new ID is created.

**Comment by suhr** [comment]
@tux3 

> "enhancement" is basically "todo".

Not really, Enhancement means “implement Soon©” while “todo” means “implement later”.

**Comment by msteinbeck** [comment]
I think we should also add password manager support. The most used in Linux are kwallet and gnome-keyring. I'm pretty sure Windows will add an own manager in future versions. This would make things easier for casual users.

**Comment by fcore117** [comment]
i prefer internal solution if passwords comes because is is very good to move own profile and log in where i need independent from OS. Just a tiny vote.

**Comment by suhr** [comment]
Can't enable tox encryption in settings. Is it not implemented yet?

**Comment by tux3** [comment]
There were some issues and it was disabled temporarily.
@dubslow ?

**Comment by dubslow** [comment]
We're waiting on the resolution to agliob's issue, which reports that it is apparently broken. I've gotten the fundamental encryption working, and apprb has yet to find the issue with the code that actually uses the encryption...

**Comment by srkunze** [comment]
Another opinion: I actually would like to create encrypted profiles with qtox, too.

**Comment by dubslow** [comment]
This functionality is actually all done, except that one user reports a mysterious crash that no one else is able to reproduce...

**Comment by srkunze** [comment]
Thanks for the update. Just wondering where I can do that. I use the repositories referenced here: https://wiki.tox.im/Binaries#Apt.2FAptitude_.28Debian.2C_Ubuntu.2C_Mint.2C_etc..29

**Comment by srkunze** [comment]
Can I also change the password?

**Comment by agilob** [comment]
@dubslow: I was able to sucessfully use encrypted history months ago. I wonder why it's not possible to enable encrypted logs. Changing password, disabling/re-enabling also worked @apprb?

**Comment by dubslow** [comment]
It all works great on the encryption branch in my repo, but @zetok reported a consistent crash that no one else has been able to reproduce, see the only issue in my repo. @TheLastProject can you confirm whether or not https://github.com/dubslow/qTox/tree/encryption works on your gentoo?

**Comment by zetok** [comment]
@dubslow it's probably due to my hardened Gentoo. I've set in in a way that causes programs to crash when they do something in a really wrong way, so…

AFAIK @TheLastProject doesn't run hardened Gentoo, thus I doubt whether it would crash there..

Edit: ~~if you want, I probably could prepare my root btrfs subvolume to give it to you, provided that you'd have btrfs you could simply chroot into. I have no idea whether that would be enough to reproduce, but I guess it can't hurt too much to try~~ or maybe not, there's a lot of data there that would have to be removed manually, while preserving anything that could be relevant.. :/

**Comment by dubslow** [comment]
@zetok the issue isn't a crash in particular, but rather that the main thread is returning early and cleaning up while multiple other threads are still trying to do things, invariably leading to null/invalid data being used by the other threads. I don't see how the operating system could be responsible for this.

**Comment by srkunze** [comment]
Will https://github.com/tux3/qTox/issues/1034 be solved be this branch as well?

**Comment by srkunze** [comment]
Can be closed?
