### ISSUE TITLE
I can't type korean in linux.

### ISSUE THREAD

**Issue by kybin** [qTox/qTox#2501]
I could type korean in windows but not in linux.
Same problem is also happened in telegram (also linux).
So maybe it's more like Qt problem.
But please check if you could fix it.
Thanks in advance.

**Comment by aaannndddyyy** [comment]
I can confirm this.
I can type in Korean in my browser, in text editor, in the terminal, and other qt4 apps, but not in qtox.

@kybin: try utox, it works for me

**Comment by kybin** [comment]
@aaannndddyyy Hi, thank you for the suggestion. I've also tried it. But it didn't work for me. What input method do you use? I tried ibus/nabi in centos7.

**Comment by aaannndddyyy** [comment]
@kybin: ibus-hangul on *buntu

**Comment by quininer** [comment]
https://github.com/tux3/qTox/issues/2326

**Comment by agilob** [comment]
Qt problem, 4 or 5 duplicates so far.
 #2564

**Comment by aaannndddyyy** [comment]
Imho this is a major usability bug!!
If the version of qt you use is to blame, why do you require a broken qt version and not one where it works?

**Comment by agilob** [comment]
> why do you require a broken qt version and not one where it works?

If you compile qtox yourself then it's only your problem we can't test all qt version for all bugs.

If you get the package form a repo, it's repo maintainer bug. You can tell us more details about your problem like, qt compiletime version (find in about tab) and where did you get it, we might try doing something with that, like contacting repo maintainer. We don't enforce using any qt version above 5.4 (minimum due to screenshoter). And I can't reproduce and ArchLinux qt 5.5.1.

**Comment by aaannndddyyy** [comment]
I use the linux 64 bit versipn from tox' website
