### ISSUE TITLE
QTimer::singleShot

### ISSUE THREAD

**Issue by DejavuDmitry** [qTox/qTox#2567]
I have some troubles when i try to compile qtox.
/src/widget/tool/screenshotgrabber.cpp

```
QTimer::singleShot(350, this, &ScreenshotGrabber::reInit);
```

In this line 113 must be 3 arguments? Not 4?

**Comment by agilob** [comment]
what's the problem?

**Comment by DejavuDmitry** [comment]
QTimer in my system want 4 arguments... i just replace &ScreenshotGrabber::reInit with SLOT(reInit())
is it right?

**Comment by antis81** [comment]
Yep, looks like you're on Qt version prior to 5.4 -> from docs:

`````` c++
void QTimer::singleShot(int msec, const QObject * receiver, PointerToMemberFunction method)
… 
This function was introduced in Qt 5.4
```.
``````

**Comment by DejavuDmitry** [comment]
okay, and what can i do?

**Comment by agilob** [comment]
Update Qt.

**Comment by agilob** [comment]
You need newer version of Qt, it won't work for you otherwise.

**Comment by zetok** [comment]
> Qt version prior to 5.4

[INSTALL.md](https://github.com/tux3/qTox/blob/552155bd1f5824c536dd6d1bbc8d293f3f1d8499/INSTALL.md#dependencies) says that minimal supported Qt version is 5.2. IIRC this wasn't true for quite a while - now, what should be done, is bumping minimal version there, preferably by @tux3, or someone else who knows that there's no going back from 5.4 to 5.2. I mean, officially dropping support for it, rather than just having (bits of?) code that doesn't compile with older version.

**Comment by tux3** [comment]
We still support Qt 5.2, this issue was fixed recently while we were making packages for older distributions.
