### ISSUE TITLE
Add the ability to resend a friend request without having to delete the friend

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2571]
If you want to resend one you have to delete the friend and readd it

Is this is a toxcore limitation?

**Comment by zetok** [comment]
toxcore already does that, thus closing this issue.

Now, the way toxcore does it, it resends FR every `time interval * 2` - e.g. if first re-send would happen after 2s, second after 4s, third after 8s, etc.. Counter is being reset on toxcore "restart".

Constantly increasing time interval is not the best, and if you feel like it should be changed ~now, rather than later, please open issue for it on toxcore repo.

**Comment by ProMcTagonist** [comment]
Users don't know they automatically resend. There should be an interface where you can see pending sent friend requests.
