### ISSUE TITLE
When entering a wrong password, the password field doesn't get emptied

### ISSUE THREAD

**Issue by mikalehmann** [qTox/qTox#2584]

**Comment by agilob** [comment]
Yes.

**Comment by mikalehmann** [comment]
Well, I thought it's obvious, but that's not how password fields with an obfuscated password a la ***\* should behave. It's better to empty it and make the user retype it from scratch.

**Comment by zetok** [comment]
> It's better to empty it and make the user retype it from scratch.

Is it though?
There might be cases where someone typed just the last character wrongly, and they know it, since they have realized that just after pressing the enter button. If someone has a long password, it's way easier to correct just the last char, instead of typing again whole thing.

Wouldn't it be better to just have a button to clear field, like the one for contact searching?

**Comment by sudden6** [comment]
I think most password fields highlight all characters, so if you press delete everything is deleted, but you can also use the arrow keys to change just one character.

**Comment by ghost** [comment]
What sudden6 said.

**Comment by TheNain38** [comment]
I like @sudden6's idea

**Comment by mikalehmann** [comment]
sudden6's suggestion is good. Highlighting everything is perfect, because you don't even need to press delete, you just write the password again and the highlighted text vanishes. In case you know where you messed up, you can still correct it, though.

**Comment by giorgosioak** [comment]
+1 to @sudden6
