### ISSUE TITLE
Own Tox ID in the Settings panel of qTox not available anymore

### ISSUE THREAD

**Issue by bhlevca** [qTox/qTox#2611]
Own Tox ID in the Settings panel of qTox not available anymore

uTox has that but in qTox there is nowhere to be seen. 

I tried all the tabs in the Settings panel and I could not find it.  
I tried the nightly builds and I build my own version and the problem is the same.

Also it would be nice to be able to see the Tox ID of you contacts, but this is another bug report

**Comment by DanTheBritish** [comment]
It has been moved. Click your name, and it will bring up your profile where you can see your ID and a QR code.

**Comment by tux3** [comment]
So that's not really a bug, it's just a bit hidden.
But I've seen a lot of users that never found you can click on your avatar to go to the profile page, maybe we should make it more visible somehow? Or some sort of interactive GUI tutorial when you first start qTox maybe?

**Comment by bhlevca** [comment]
True, it is not a bug, but honestly I did not think about of clicking on my face. 
All the documents  floating around point to the setting panel and the fact that uTox still has it there does not help. Perhaps some sort of indication (small arrow like for the CD ejection, target, etc) on the avatar that would suggest clicking could help with the confusion.

**Comment by tux3** [comment]
Yes, I'm not sure what kind of indicator would look good though. If you have ideas, I'm all for it.

**Comment by ProMcTagonist** [comment]
I think it would be simplest and best if the Profile was returned to being a tab in general settings, and clicking on your avatar simply shortcutted you there.

**Comment by zetok** [comment]
> If you have ideas

Yes. `:3`

So, avatar can be highlighted. I.e. in similar way to how links in the browser are underlined when one hovers cursor over it, in a ~similar way avatar could be "highlighted" when mouse hovers over it.

![no highlight](https://cloud.githubusercontent.com/assets/3148759/12022631/7a15be7a-ad89-11e5-9f61-2778c22ca525.png) → ![highlighted avatar](https://cloud.githubusercontent.com/assets/3148759/12022636/88156f3e-ad89-11e5-90a9-342fb1914714.png)
With a different colour, perhaps green, probably slightly bigger, and with curved edges.

When user will launch qTox for the first time with a new profile, highlight should be pulsating until user clicks on it.

Edit: I guess that I'll make a new issue for it, since this one is closed
