### ISSUE TITLE
Crash after hitting audiocall or videocall

### ISSUE THREAD

**Issue by plus13** [qTox/qTox#2727]
On Arch Linux.

I get:
[16:40:00.182] ../src/audio/audio.cpp:468 : Debug: Opening audio output "none"
[16:40:04.451] ../src/widget/form/chatform.cpp:468 : Debug: onVideoCallTriggered
[16:40:04.451] ../src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[16:40:04.454] ../src/core/coreav.cpp:177 : Debug: "Starting call with 0"
[16:40:04.454] ../src/audio/audio.cpp:411 : Debug: Opening audio input "none"
[16:40:04.454] ../src/audio/audio.cpp:388 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[16:40:04.454] ../src/audio/audio.cpp:468 : Debug: Opening audio output "none"
qtox: ../src/audio/audio.cpp:752: void Audio::subscribeOutput(Audio::SID&): Assertion `sid' failed.
[1]    18370 abort (core dumped)  qtox

Solution:
Change the setting in capture devices to another then none it works.

**Comment by antis81** [comment]
Thanks for reporting and sorry, but I really couldn't reply directly. What you're seeing as a bug tells me, that you tried to start a call without having a configured audio device. This is not possible of course and qTox should display an error message instead of the assertion -> graceful exit. However, we're just about to implement a default behaviour.

@JacobHenner Could you open a PR to implement selection of a default device. I'll review.

**Comment by ovalseven8** [comment]
Well, that's definitely a bug.
Perhaps I just want to listen and because of that I won't select a capture device. Or I just want to say something and don't choose a playback device for some reason.

By the way: @JacobHenner implemented it already and it worked. No idea why it's broken suddenly.

It should possible that qTox can handle it.
P-high.

**Comment by antis81** [comment]
> Well, that's definitely a bug.

Yes, it is. I just showed a way how to avoid that bug, which gives us enough time to solve it. 

> Perhaps I just want to listen and because of that I won't select a capture device. Or I just want to say something and don't choose a playback device for some reason.

There are two buttons at the top right of your active call window (mute mic. / mute speaker), allowing you to exactly do what you ask for. However it is impossible to start an audio call without a valid input & output audio device available (we wouldn't even be able to hear the ringtone).

**Comment by ovalseven8** [comment]
@antis81:
Here you can find a backtrace concerning the crash: http://pastebin.com/raw/FHdyycjr

**Comment by sudden6** [comment]
This no longer seems to happen, thus closing.
