### ISSUE TITLE
qTox forcing to use "tox DNS" instead of direct DNS request via proxy

### ISSUE THREAD

**Issue by nikitasius** [qTox/qTox#2739]
Hello!

> qTox needs to use the Tox DNS, but can't do it through a proxy.
> Ignore the proxy and connect to the Internet directly?"

I have domain with 

> v=tox1; id=123456789myToxIdWasHere123456789

in TXT record.
So why qtox forcing me to disable proxy, send direct request to toxdns service which i do not run and don't want to install instead of simple request to server like toxv1?

**Comment by SkyzohKey** [comment]
Cuz ToxDNS is bloated/bullshit.

**Comment by nikitasius** [comment]
So, in such case there is no way to force qTox check directly TXT records on my domain directly as "tox1"?

I'm interrresting to hear opinion of qtox's dev about that.

I've seen that he told (or someone in issues) tox1 and tox2 "not secure", it's why they are using tox3 and waiting tox4 via DHT, but tox3 without proxy it;s much more shit and unsafe than tox1.

Same time there is DNSSEC, signed data.

**Comment by ProMcTagonist** [comment]
Toxdns/toxme is migrating to http instead of dns soon as far as I know, which should make it usable over proxies.

I've never heard of tox4 via DHT but it sounds more distributed so I'd like to know where you read/heard about it.

**Comment by nikitasius** [comment]
Ok, i've heard enought about migration, about toxdns, but newer about: WHY we CAN'T use tox1?

So: WHY we can't use simple tox1 DNS in qtox? Everyone speak about "tox is great, not central server, lot of nodes (i host 1 and helped many)" and what i see? I see that qtox force people to use toxdns services on another websites or run yourself.

But i don't want to run on my server toxdns, i want to use simple tox1 DNS TXT records with DNS SEC (yes, DNS SECURE) values.

Add again: how to add someone in qtox using tox1 "user@example.com"? Change qtox?

**Comment by SkyzohKey** [comment]
qTox/uTox have a "whitelist" of domain that can be used via ToxDNS (which is fucking stupid cuz it centralize Tox, again). I wanted to use my old domain to have a nice toxid (skz@3xpl0it.eu) but wasn't able to do it since uTox/qTox doesn't allow not-in-whitelist domains.

**Comment by nikitasius** [comment]
Yes, i see, they have 4 pinned servers (https://github.com/tux3/qTox/blob/1874c0ce4d878f1a179894900431c68f3c751eb9/src/net/toxdns.cpp)

So, hope, @tux3 will explain for us kindly "what the fuck is going on?" with qtox.

Why there is 4 servers hardcoded and why we can't use "tox1" dns requests.

**Comment by subliun** [comment]
> DNSSEC does not provide confidentiality of data; in particular, all DNSSEC responses are authenticated but not encrypted. 

Unencrypted is bad. Tox believes in forcing encryption wherever possible. toxdns1 should have been removed from qTox a long time ago. toxdns3 is a hack. toxdns as a whole is deprecated and toxme.io will soon be dropping dns and moving entirely to the https api for lookups. Antox and Toxic have already made this change and neither toxdns1 or toxdns3 works with those clients.

Calm down.

**Comment by nikitasius** [comment]
> Unencrypted is bad. Tox believes in forcing encryption wherever possible.
> All answers from DNSSEC protected zones are digitally signed

So.. _user@example.com_ it's nothing else like simple cheat to make life easier when your friend of someone else adding someone. If i posted this email it mean that **i've posted** this **email**. After my tox client should to make simple DNS request. With tox we can have unlimited amount of accounts and some of them you can run via **proxy/tor** and add people via _ABCDEF123.._ hashes, some of them you can ran as is, use for work and add users (or they will add you) via emails. And "current bullshit with tox3 via 4 servers" adds zero security and zero usability.

You speak about "encryption wherever possible" but you hide that **qTox** a **broken postulate** that system mustn't have a **core**. No central node or central point.

Today qTox provide **4 toxdns** servers and they are **hardcoded**. So you can say "calm down" for someone else who don't care about this shit what devs are doing.

**Comment by zetok** [comment]
@nikitasius

> So why qtox forcing me to disable proxy (…)

qTox doesn't force you to disable proxy. DNS requests simply wouldn't be routed through proxy, thus they're disabled when qTox uses proxy.

> WHY we CAN'T use tox1

Because plaintext.

> I see that qtox force people to use toxdns services on another websites or run yourself.

**qTox doesn't force you or anyone to use them - you can always use Tox IDs**.

When it comes to ToxDNS, you always had to run your own service or use someone's else.

Note though that using ToxDNS at all is constituted by no apparent way of doing it **well** via distributed/decentralized means.

Also, as always, PRs with additional servers were and will be accepted.

What has changed, is correct way of handling DNS requests (so that they won't be sent outside of proxy and instead are disabled if proxy is in use) and removal of totally insecure and _deprecated ~upstream_ toxdns1 and toxdns2. (ToxDNS is ~broken anyway..)

> So, hope, @tux3 will explain for us kindly "what the fuck is going on?" with qtox.

Can't say anything in @tux3's name, but the way I see things…

People are improving it `:)`

If you want to help with the situation, could you please create a distributed/decentralized, well-working way of finding/discovering ToxID by searching for "usernames" (or something) that would be implemented in toxcore, so that qTox, like other clients, could ~easily use it?

# 

On a side note, could you please try to keep things a bit more polite? I understand that you feel very emotional about this - I really can relate to that `;)` , but..

**Comment by LuccoJ** [comment]
ToxDNS is centralized in any case since no matter how many servers you have, they are servers, not just Tox peers, and they need to be trusted not to lie (and if they do lie, you can get a MITM).
Hard-coding a small number of "known-good" ToxDNS servers just tries to mitigate the intrinsic problem, I suppose.

I think ToxDNS should be replaced with something distributed, based on Namecoin for instance, or similar.

**Comment by nikitasius** [comment]
> DNS requests simply wouldn't be routed through proxy, thus they're disabled when qTox uses proxy.

Some of them (yes, except TXT in _current_ tor realisation) [can by-pass](https://gitweb.torproject.org/tor.git/tree/src/or/dnsserv.c?id=7a489a638911012069981702065b952a5809d249#n92) Tor.
And all of them can "by-pass" via VPN.

> Hard-coding a small number of "known-good" ToxDNS servers just tries to mitigate the intrinsic problem, I suppose.

Thats the problem. Hardcoded servers, thats the problem.
When tor1/tor2 it's a _weak_ point of Tox - i'm agree. If they wanna keep tox as "all encrypted" system, lets do it. But hard-coded servers - thats the _2nd bullshit_ (1st was no fallback on tox1 anymore, no more choice old users) about what i've spoken before.

> On a side note, could you please try to keep things a bit more polite? I understand that you feel very emotional about this - I really can relate to that ;) , but..

I feel myself like i've got pair of nice opensource shoes and now i see, that this shoes use only special cream from four another shops. Everyone tells me that if i don't like something, i can rewrite it, but it's not a solution and 14 years ago last time when i've coded something on C, so.. So i'm here in this issue, trying to understand "wtf is going on" with qTox.

P.S. No more tox1 fallback - it's exactly what microsoft does with their skype, same style with _"use it as is or go away"_.

**Comment by zetok** [comment]
> Hardcoded servers, thats the problem.

Actually, that's just a workaround.

The real problem is that there's no reliable way of making sure that servers are who they claim to be, thus something hardcoded.

If there is a good way of making sure of that, without hardcoding stuff, could you point to it?

I'm not saying that you have to code - pointing to some papers on the matter, existing implementation, or your own idea..

Note though that this is a problem that people have been scratching their heads on for years, so.

**Comment by tux3** [comment]
@nikitasius 
Hi! I was away this week, so let me answer your questions now.

> So why qtox forcing me to disable proxy, send direct request to toxdns service which i do not run and don't want to install instead of simple request to server like toxv1?

It's impossible to request DNS TXT records through a proxy. It's not possible, it can't be made to work.
So if you have a proxy, you CAN NOT use toxdns1 or toxdns3 with it, because they need TXT records.
So qTox asks if you want to do the request anyways, but it can only do it outside the proxy.

What we're going to do is deprecated (remove) toxdns1 and toxdns3, and replace them with a HTTPS version that always works, even through proxies. Toxdns1 has already been removed, and the replacement for toxdns3 is almost ready.

> So, in such case there is no way to force qTox check directly TXT records on my domain directly as "tox1"?

It used to be possible, but toxdns1 has been removed because it's not secure for our users. You should use toxdns3 instead, and soon the better HTTPS version.

> Yes, i see, they have 4 pinned servers (https://github.com/tux3/qTox/blob/1874c0ce4d878f1a179894900431c68f3c751eb9/src/net/toxdns.cpp)
> So, hope, @tux3 will explain for us kindly "what the fuck is going on?" with qtox.
> Why there is 4 servers hardcoded and why we can't use "tox1" dns requests.

The 4 pinned servers are toxdns3 servers, they are pinned so if somebody tries to compromise them and change the key, qTox will refuse to use them because it knows the real key.
It doesn't mean that only those 4 servers work, you can use any toxdns3 server with qTox, but we know the keys to these 4 ones and so we can pin them.

The 4 pinned servers have nothing to do with toxdns1, it's not possible to use toxdns1 anymore. Toxdns1 has been deprecated and removed because it's insecure.

> You speak about "encryption wherever possible" but you hide that qTox a broken postulate that system mustn't have a core. No central node or central point.
> Today qTox provide 4 toxdns servers and they are hardcoded. So you can say "calm down" for someone else who don't care about this shit what devs are doing.

Anyone can run a toxdns3 server and it will just work with qTox and with other Tox clients.
The hardcoded servers are servers who asked us to pin their keys, it's not necessary to do that, and anyone else can ask that we pin their key too, we'll be happy to do it if it's the right key.

> Some of them (yes, except TXT in current tor realisation) can by-pass Tor.
> And all of them can "by-pass" via VPN.

Toxdns1 and toxdns3 don't work through proxies like Tor, that's why we're trying to get rid of them (among other things). We're working on a HTTPS replacement that will work with proxies, Tor, VPNs, everything. It's almost there.

> When tor1/tor2 it's a weak point of Tox - i'm agree. If they wanna keep tox as "all encrypted" system, lets do it.

Cool, we agree on that :)

> But hard-coded servers - thats the 2nd bullshit (1st was no fallback on tox1 anymore, no more choice old users) about what i've spoken before.
> I feel myself like i've got pair of nice opensource shoes and now i see, that this shoes use only special cream from four another shops. Everyone tells me that if i don't like something, i can rewrite it, but it's not a solution and 14 years ago last time when i've coded something on C, so.. So i'm here in this issue, trying to understand "wtf is going on" with qTox.

Again, the hardcoded servers are just people who asked us to have their keys pinned. Any server will work with qTox even if it's not hardcoded.
We will **never** hardcode a list that prevents people from running their own servers, Tox is open and will remain open. 
If someone want to be in the list of pinned keys, I'll be happy to add them, but it's not at all necessary.

> P.S. No more tox1 fallback - it's exactly what microsoft does with their skype, same style with "use it as is or go away".

If the fallback is dangerous for our users, then there will be no fallback. We have a responsability to not ship with insecure protocols, even if it makes things harder for people who want to run ToxDNS/Toxme servers.

**Comment by nikitasius** [comment]
Thanks for answer, @tux3 . Good to hear, that tox developping and improving and, i hope, we'll see better future.
I'll wait toxdns(4) realisation.
