### ISSUE TITLE
qTox crashes when clicking audio/video tab in a second instance

### ISSUE THREAD

**Issue by TheNain38** [qTox/qTox#2788]
Version: 26019c20e20ff6a9f1177bd56b665543126fed26, Windows 8.1 64-bit. I think it happens since 0836c78551c40719b37677105bd951e90fd511b6, also I cannot do a regression test right now

**Comment by antis81** [comment]
We are actually not yet in a state where to talk about regressions. Anyway, I cannot start two instances at all with current master.

**Comment by ghost** [comment]
Can't reproduce in 05162a63b93aaa046567920a37fd64e9edfa05d4

`alice` is the first instance, `bob` the second. Scenarios tested:
- `alice` in chat window, `bob` opens video/audio settings
- `alice` in video/audio settings, `bob` opens video/audio settings
- `bob` in video/audio settings, `alice` opens video/audio settings
- `bob` in chat window, `alice` opens video/audio settings

Debian testing
Qt 5.5.1
Linux 4.3.0-1-amd64

**Comment by antis81** [comment]
@TheNain38 Closing, since the issue lacks urgent information and is otherwise not reproducible. I just fired up two qTox instances on debian and they behave quite friendly with each other. I do not have a Win8.1 version available to test. In case this behavior still exists, feel free to reopen. To proceed, we either need a core dump or at least the log to be able to investigate further on this.

Anyway, answering the following questions might help:
- Behavior still appearing with latest version (>=1.4)?
- Which of the qTox instances crash?
- Do they crash both?

**Comment by TheNain38** [comment]
It's not reproducible on latest master, so, it's fixed

**Comment by antis81** [comment]
@TheNain38 Thanks for the feedback.
