### ISSUE TITLE
old profile wont work

### ISSUE THREAD

**Issue by adrian-purism** [qTox/qTox#2789]
how can i reload my old profile in a new fresh install? it only allow me to create a new but i cannot logging with my old user and pass

**Comment by zetok** [comment]
Do you have your [profile file](https://github.com/tux3/qTox/wiki/Profile)?

Edit: also, how old is your profile, i.e. how much time has passed since you've used it last time? If you used it within last ~half a year, it should work, unless it was corrupted..

I mean, there's this other issue you've made (#2765), where qTox couldn't access encrypted DB any longer - it's quite likely that it happened due to some bug, but given that now your profile can't be loaded, it would seem to me like there might be something wrong going on in your system.

**Comment by tux3** [comment]
No replies, so I assume OP found a solution. Please leave a comment if you still experience this issue and I'll be happy to reopen.

**Comment by adrian-purism** [comment]
how i import my old profile if in the UI is just showing me "register a new one"

**Comment by tux3** [comment]
@adrian-purism Hi

**Comment by tux3** [comment]
@adrian-purism Hi, we need more information to help you, I can't tell what happened to your old profile otherwise.
Could you run "ls -lh ~/.config/tox" and post the result please?

**Comment by zetok** [comment]
No response for over a month, thus closing.
