### ISSUE TITLE
the size limit of the log file

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#2823]
At the moment there is no limit on the log file, so for example I have he has grown already to 30 MB.
Offer to limit its size and overwrite the file with new data

**Comment by tux3** [comment]
Related: #1615

gzip compression reduces the log size on the order of 200x times, but makes it harder for people to open it so they can put it in bug reports. So I'm going to change my mind and say it's better to limit the size instead of what #1615 says.

I don't think we'll ever want to sift through more than 1MB of logs, or more than the last 15 runs of qTox.
Running some stats on my own log file says 15 runs of qTox is ~300kB, so that leaves some margin in case of log spam too.

We could just run that function every time qTox starts, first truncate the file to 1MB then search for the line "qTox file logger starting" and keep only the last 15.

**Comment by sudden6** [comment]
> We could just run that function every time qTox starts, first truncate the file to 1MB then search for the line "qTox file logger starting" and keep only the last 15.

This seems like the best thing to do.
Implementing this sounds like an easy thing, maybe give it the "easy" tag?
