### ISSUE TITLE
toxcore version 0.0.0?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2858]
I recently went to the "About" section of qTox and found that it says that the toxcore version in use is `0.0.0`:

![toxcore_version_0](https://cloud.githubusercontent.com/assets/11575271/12563548/b5d9df84-c3a2-11e5-8a06-6aadb1dd79d6.png)

So I guess this is either a bug or something very strange...

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `462-3343645`.

**Comment by agilob** [comment]
That means toxcore doesnt have version yet.

**Comment by ghost** [comment]
Having some sort of version number displayed there would be useful for instance for debugging purposes, so I think that at least it should give a commit hash even if it cannot give a version number.

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon 
toxcore exposes only version number - using commit hash isn't really possible.

This is a toxcore issue, and if you want it fixed, you should open an issue on toxcore repo. With that being said.. toxcore was supposed to have versions since quite a while, and the only reason why it doesn't have it, is because @irungentoo didn't feel like it. So.. there isn't much that can be done about it, sorry about that.

**Comment by ghost** [comment]
@zetok, He "didn't feel like it"? He should give a proper reason otherwise we really should have them by now... That's not really acceptable just to say that you don't feel like it.

**Comment by zetok** [comment]
> That's not really acceptable just to say that you don't feel like it.

Well, good thing that he didn't do that :D

He said that versions will start when new A/V gets merged, which got merged like.. quite a few months ago?

As they say, actions speak louder than words.
