### ISSUE TITLE
Easier copy and paste ability when it comes to messages

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#2891]
It seems that qTox has very limited copy and paste abilities, and it is not very obvious (though I have sort of figured it out partly) how to use what's there. Because currently if one wants to copy a message, if one tried highlighting the part of the message the want to copy they can't use the keyboard shortcut <kbd>CTRL</kbd> + <kbd>C</kbd> to do so, in fact they have to then right-click and press "Copy", so I think that that should be changed so that you can use the keyboard shortcut as well.

And then the other confusing thing is that you have to select what part of a link you want to copy and then do the same, otherwise if you just right-click on the link and press "Copy", nothing happens...

I am running Ubuntu GNOME 15.10 with GNOME 3.18 and qTox version `472-3307855`.

**Comment by ghost** [comment]
> if one tried highlighting the part of the message the want to copy they can't use the keyboard shortcut `CTRL` + `C` to do so

Works for me.

> right-click on the link and press "Copy", nothing happens...

That's the correct behaviour, but a "Copy link location" shortcut in the menu wouldn't hurt.

---

I guess you can drop the "paste" bit in the title to improve future issue searches.

**Comment by zetok** [comment]
@kehugter

> > if one tried highlighting the part of the message the want to copy they can't use the keyboard shortcut `CTRL` + `C` to do so
> 
> Works for me.

Actually, it doesn't always work - i.e. input field (auto?)focus sometimes  interferes with keyboard shortcuts. Basically, in order to be able to copy the message via shortcut, you should not have focus set on input field.

E.g. when one has already focus set on input field and highlights whole message in order to copy it, input field stays focused, which makes `CTRL + c` pretty useless.

**Comment by ghost** [comment]
Right. A possible solution: redirect 
- plain text keyboard input
- `CTRL` + `V`
- middle clicks (Linux, Mac?)
- `right click -> paste`

to the input are when
- the text area or 
- the input area

is focused.

> input field (auto?)focus

Looks like it gets focus when something other than text is clicked.

**Comment by Doom032** [comment]
I actually came to add an issue specifically for

> ...a "Copy link location" shortcut in the menu...

I often use this to copypaste YouTube links people send me into VLC, so that's my use case. Should this be a different issue or could it fit in with the general copy interface improvements?

> Looks like it gets focus when something other than text is clicked.

Looks like it's when you switch focus to a different window and then alt-tab back to qTox. Focus should stay on the selected text in the log, but instead switches to the input field. That's not handy in this case. I think the best thing to do is to detect that if focus was on the log before you went away, and some text is selected in the log, qTox is smart and returns the focus on the log. Additionally maybe ctrl+c should automatically copy text from the log if the selected input field has no text selected. That's what I'd expect as a user.

**Comment by zetok** [comment]
@Doom032 

> I actually came to add an issue specifically for
> 
> > ...a "Copy link location" shortcut in the menu...
> 
> I often use this to copypaste YouTube links people send me into VLC, so that's my use case. Should this be a different issue or could it fit in with the general copy interface improvements?

That would be #1236.

**Comment by sudden6** [comment]
copy paste with shortcut and link copy is fixed AFAICT
