### ISSUE TITLE
Voice goes silent after some minutes of talking

### ISSUE THREAD

**Issue by octonet1** [qTox/qTox#2926]
I use 2 computers one desktop 64 bit with qTox the other 32 bit uTox all windows.
On the 64 Bit vista qTox there is under unknow conditions short the talking possible than is most time off, No ringing to hear from the partner
on the 32 Bit Windows 7 is the phone green and i can hear the partner but he hear me not after some minutes i can hear him also not more, the ringing is OK.
adjusting the volumes help also not 
What can i do we like to have a conference call next week with Tox
![tox kein audio](https://cloud.githubusercontent.com/assets/13781661/12820792/eae01156-cb60-11e5-8286-bb190a1935c9.jpg)

**Comment by sudden6** [comment]
did you setup the audio devices correctly?
Did you try to disable audio filtering?

**Comment by antis81** [comment]
@octonet1 Changed title to something useful. :)

**Comment by tux3** [comment]
@octonet1 Could you post the content of qtox.log in AppData please?

**Comment by zetok** [comment]
Thanks to @katamari1992 from #3150:

# 

##### Brief Description

OS: Linuxmint 17.3
qTox version: v1.3.0-138-g32ed2ac.

##### Observed Behavior

I'm having a call between tox and antox the call drops off after 15 minutes like clockwork
I'd like to know what's causing this (I believe I know) 
I believe the sip (re-call?) isn't being responded to but I don't know as I haven't done extensive testing 
merely idle chatting over the call

##### Expected Behavior

not to drop the call

---

@katamari1992 could you provide `~/.cache/Tox/qTox/qtox.log` ?

# 

~~I'm not able to reproduce with 15min call on 74ce4da48c6f6d52c910f50a47a0686027bfb8d6~~

I was able to reproduce, but it took 19 minutes(!).

**Comment by zetok** [comment]
`qtox.log`: https://gist.github.com/zetok/a7739a5b10ac148ebffe1a7ac69982a2

It might have something to do with me going to A/V settings tab.

**Comment by katamari1992** [comment]
##### Brief Description

OS: Linuxmint 17.3
qTox version: v1.3.0-138-g32ed2ac.
Commit hash:  
toxcore:  most recent
Qt:  unsure python-qt4          4.10.4+dfsg-1ubuntu1 

Reproducible: Always

##### Observed Behavior
I'm having a call between tox and antox the call drops off after 15 minutes like clockwork
I'd like to know what's causing this (I believe I know) 
I believe the sip (re-call?) isn't being responded to but I don't know as I haven't done extensive testing 
merely idle chatting over the call

##### Expected Behavior
not to drop the call

**Comment by katamari1992** [comment]
it's ironic that github doesn't support .log files
[qtox.txt](https://github.com/tux3/qTox/files/222093/qtox.txt)

**Comment by xenithorb** [comment]
I'm seeing this on the latest builds between 64bit Linux and Windows ( i did not try others ) 

I was talking with another person and it kept cutting out, 5 minutes, 9 minutes, 15 minutes 

The time was not consistent. Though I am unsure if the other party was on the Audio tab, but I kind of doubt it because they had just reinstalled ( and cleared out the settings folder in AppData due to another issue with it not upgrading properly!)

**Comment by xenithorb** [comment]
I just did a more recent test ensuring that no one was on the audio tab and it still cut out. To be perfectly clear the call doesn't actually  hang up, the audio just stops on both sides. The call stays connected.

**Comment by Diadlo** [comment]
Can't reproduce on 077a844 with EchoBot after 40 min.

**Comment by zetok** [comment]
Could someone affected retest with newest qTox?

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
