### ISSUE TITLE
[QUESTION] Would setting a proxy server decrease latency?

### ISSUE THREAD

**Issue by DeerSpotter** [qTox/qTox#2929]
Can i set up a proxy server on my LAN and have all the clients go through that proxy to reduce lag on bandwidth and just use the infrastructure  (localhost only)?

Or do i need to set up a Tox server locally and just use that in my clients?

**Comment by sudden6** [comment]
Setting up a proxy will certainly not reduce latency, because it adds another hop for the data.

I don't understand what you mean with the rest, please clarify.

**Comment by idanoo** [comment]
From what I understand, he means have one computer run toxcore, and the rest route via the one connection instead of all running separately.

**Comment by sudden6** [comment]
If I understand the code of the core, what you are trying to attempt is unnecessary and impossible. Because if the clients communicate only in your local network, toxcore should not generate any outbound traffic besides dht traffic, which is minimal.

And if you want to reduce the bandwith usage over your internet connection of a groupchat, with local and non local clients, I think it is technically possible to merge all traffic of local clients into one upstream and one downstream to the groupchat, but this would be a huge task to implement in toxcore.

If you have more questions ask them over at https://github.com/irungentoo/toxcore, because this really is an upstream issue.

If I already answered your questions please close this issue.

**Comment by DeerSpotter** [comment]
Okay Thanks. I'll see what i can come up with.
