### ISSUE TITLE
[feature suggestion] Ability to print a paper with the private key on it

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#2961]
The same feature as Bitcoin Armory has. Bitcoin Armory is able to print the paper with the private key on it, so that the user can print it and store it in the secure location, and later in the case of a computer crash an account can be restored.

Users of course should have a backup on the file level, but having a paper might be a more intuitive way for the less sophisticated users to preserve their account information.

This feature isn't as vital to qTox as it is to the Bitcoin Armory, but I think it is very much worth having for qTox to be on track of attracting the less technically savvy audience.

**Comment by LittleVulpix** [comment]
To be honest, just having the key wouldn't solve much; you'd need to somehow know the whole tox id of all of your contacts - because your key alone is just your private key - without any stored contacts or anything.

If you want to print your profile, the easiest way to do so -> take your *.tox file, compress it with 7zip (add a password!!) and then encode that in base64 (I used total commander for this but anything will do).

In my case, a compressed+subsequently b64 encoded profile with all of your info+50 contacts stored in it fits without any issues on a single A4 page of paper (font: courier, size ~8-10pt). It requires no implementation client-side - simply get the data off the paper in case of your utmost need; decode with b64 and unpack.

If you are the kind of person that wants to print out your personal data, then I believe you are the kind of person who won't mind this approach. It's how I did it :)

**Comment by yurivict** [comment]
Here is what prompted me: someone lost their phone with Antox on it, and the account is gone. Now this person needs to re-connect with every single person from the new account.

Besides the obvious file backup, tox doesn't offer the ability to recover an account. File backup isn't the easiest way too, in terms of the amount of clicks, etc, especially for a layman users. Another problem is how to transfer an account from the phone to say qTox? I don't think this is obvious or easy.

Such paper with a bar-code, if made to be a standard feature across all tox implementations, will simplify the account recovery, transfer, etc.

I believe if Tox was to become and every day, widely accepted messenger, it should have such feature.

**Comment by LittleVulpix** [comment]
I don't think you can fit all of the information in your profile into a QR code. Your private+public key alone is not good enough because then you do have your profile but you won't have any of your contacts on it anyway; you'd need to re-add all of them. I don't think it's possible to store a regular tox profile (even if you compress it) in a QR code.

There are no accounts per se, which is why you cannot recover one. There is no central storage. Your "account" and all of your contacts are stored in a single file loadable across all the tox clients (all of them should be able to load it, regardless of which one created it). The only way to backup or transfer your account is to have this file. Small ones with not that many contacts could (if compressed) fit into a qr code; but people with more contacts would run into issues. I guess it could be done with the use of multiple QR codes? :D

**Comment by yurivict** [comment]
Multiple QR codes - that's what I was thinking. Be able to convert the .tox file into a sequence of the QR codes and back. If both qTox and Antox could do this, I could just "take" my account with me by scanning the QR codes. Currently I am not sure how to do this.

(Totally understood that there is no central "account", by account I mean a pair of keys)

**Comment by sudden6** [comment]
If you already use a phone, why not bluetooth?
I agree with @LittleVulpix, integrating a print function into qTox doesn't seem like it's worth.

**Comment by linux-modder** [comment]
umm,  BT (especially  BT4.x) is very insecure kinda, and QR codes are already supported in both antox and qtox however not in a 'chained'  fashion as alluded to by the OP.  Also,  a backup aside would be using that paper or QR code as a password card related / or not to tox contacts as a QR code of  profile >  zipped >  base64'd will always hash the same.  While it would be a bit complex to implement I'm sure you could make that like the lastpass 4.x  TNO emergency access using such a paper  /qr code.

**Comment by yurivict** [comment]
@sudden6 LittleVulpix didn't exactly say he disagreed, and what does bluetooth have to do with this?

**Comment by yurivict** [comment]
The feature consists of two parts
- Create the emergency backup: it will compress the tox file and convert it into a sequence of the QR codes and hex numbers, nicely printed on the paper with an explanation.
- Restore the emergency backup: it will "scan" the QR codes using the camera, or allow the user to type the hex sequence in, and restore the keys and the contact list from this data.

**Comment by linux-modder** [comment]
the explanation would have to be  concise and  non topical to the passerby imo for security reasons.  If the casual passerby or  evil player has a idea what it for that  makes its less secure too no?

**Comment by yurivict** [comment]
> no?

yes

**Comment by zetok** [comment]
@yurivict this sounds like something that could and should be done using a separate, generic tools.

Splitting data, reassembling it, and printing are doable with generic tools.

Note: with small profiles (20 or so contacts), compressed data is still big enough to require 3 QR codes. With a bigger profile (>150 contacts) data after compression would be split into like 6 QR codes.

Btw, you can already print it yourself:

`tar cj profile.tox | base64 > print_it.txt`

(↑ recommended method of compressing if you want to make sure that data will be possible to retrieve in very long-term, don't use LZMA (xz) for it)

To get it back, just scan the paper, OCR, `base64 -d $ocr_text | tar x` with the data.

Small profile: 130 lines
Bigger profile: 269 lines

**Comment by yurivict** [comment]
@zetok How can a simple Windows user of qTox do this? Do you assume everybody has a computer science degree? It should be integrated, and easy to use for everybody.

**Comment by sudden6** [comment]
@yurivict I fully agree with @zetok, this is already possible with Tools available on the Internet and is out of scope of qTox. If you insist on using Windows you can use http://ollydbg.de/Paperbak/ (obtained via a quick Google search).

**Comment by yurivict** [comment]
I disagree. It should be easy to use the function directly related to qTox, and what you suggest requires OCR. OCR doesn't always work. You assume that all users are knowledgeable, resourceful, educated, etc, but most are not. As a result, Tox will remain a system for nerds and geeks.

**Comment by zetok** [comment]
> You assume that all users are knowledgeable, resourceful, educated, etc, but most are not.

Quite the opposite. This "feature" seems like something too hard for people to use, and people who would be able to use it easily can figure out how to use other tools.

What you would want, is proper documentation for those people on how to do those things.

**Comment by yurivict** [comment]
1. Press the button and produce the paper
2. Press another button and scan codes through the camera, one by one. How is this too difficult?

**Comment by zetok** [comment]
> Press the button and produce the paper

Doesn't work, 'cause printers.

> Press another button and scan codes through the camera, one by one. How is this too difficult?

Also doesn't work, given that there's little to no libs that support scanning QR codes, rather than creating them. One of reason why qTox doesn't support scanning QR codes with Tox IDs to add friends.

**Comment by yurivict** [comment]
You said "seems like something too hard for people to use". Now you are saying the opposite: "hard to implement". -)

There is https://github.com/zxing/zxing library, and here someone says he runs it on the Linux server: http://stackoverflow.com/questions/7202930/zxing-qrcode-decoding-issue

**Comment by zetok** [comment]
> You said "seems like something too hard for people to use". Now you are saying the opposite: "hard to implement". -)

Hard to do, and hard to use.

https://www.youtube.com/watch?v=pQGtucrJ8hM

What would work reliably, is producing images. If someone wants to print them, that's up to them.

There is still a question of how the actual UI should look & work like.

> There is https://github.com/zxing/zxing library (…)

Interesting, perhaps could be used.
Kinda bad that it isn't packaged anywhere, but oh well.

**Comment by yurivict** [comment]
Printers aren't that bad as they say. -) Surprisingly, they actually work most of the time. Besides, it doesn't really have to be printed. It can be taken photo of, etc. The concept of the QR code is key here, not the printer.

There is also a C++ fork: https://github.com/glassechidna/zxing-cpp
I will package it for FreeBSD.

**Comment by zetok** [comment]
@yurivict how UI for it should look like and how is it supposed to be integrated in qTox?

**Comment by Diadlo** [comment]
@yurivict There some problem. We have not protocol to transfer your key by image. I.e. one QR code is too big and I think it will be hard to read it from A4 paper (didn't test it). If we will split it on N smaller pictures => other client should support import from exactly N pictures. Or qTox (and other clients) should support export/import with custom N

**Comment by Diadlo** [comment]
I strongly against reopening this issue
Maybe I want to support play `.tox` file in [dial-up style](https://www.youtube.com/watch?v=GSRG0TqxLWc) and record in on another device (or aother export/import format). qTox can support all those. That's the reason, why this issue should be solver but external tool

**Comment by yurivict** [comment]
UI should have a button that can "print" the paper with the sequence of QR codes. The way "print" function works today is that it also offers people to save it as pdf.

"Recover from QR" button should be near a "Create new account" button. It should display the dialog box first prompting to scan the first code. From the first code it should determine how many codes are left, and it should keep prompting to scan the rest of them. It should show the check-list of remaining and finished ones. Once every code is scanned, it should enable "Recover the account" button, which should just restore the account and make it available.

**Comment by Diadlo** [comment]
> it should determine how many codes are left

It depends of your friend list

**Comment by yurivict** [comment]
I packaged zxing-cpp for FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214519 , so it is easily packageable. Not sure how does it compare to the scanning ability of ZXing on Android.

**Comment by initramfs** [comment]
@yurivict I still see several problems associated with this proposal, as below:
1. qTox should not attempt to access hardware devices not immediately essential to use. I don't have a printer, what exactly should qTox do if I don't have a printer? Similarly, if I don't have a capture device or my capture device resolution and/or quality is not up to the level that can successfully read QR codes, what then? How can qTox determine whether such hardware is available, and whether they are up to spec for such a task. The last thing I want from a secure/privacy-orientated application is for it to randomly turn on my webcam. Why should qTox take the responsibility of offering such a feature if it can't guarantee it will work properly. Imagine if I told qTox to print my profile out and on the day I try to recover it, realize my camera is not capable of reading the QR code properly. This also requires greater permissions (printer access) that qTox does not require currently and may cause problems with people using it on devices/platforms that have restricted permissions.
2. You're assuming the save format is stable over time. It is not and there are indications that the save format could radically change over time. Unless qTox aims to support all toxcore save formats from the introduction of the feature to the end of time (I'm not saying it won't be compatible between revisions, but across large timescales like years for which paper backups are usually used for), having such a feature is impractical if it requires the user to manually download/compile older versions of qTox/toxcore to be able to use the feature properly.
3. You're also assuming the save format is stateless and/or immutable, like a bare private key. As @Diadlo pointed out, it's not. It depends on your friend list. Unless you're okay with losing any changes made to your profile since the date of printing the key, such a feature is once again basically useless.

Consider this, does GPG offer to print your key? Or maybe openssl? AFAIK, they don't and for good reason. Such a "feature" would only increase code complexity needlessly and assumes responsibility that qTox cannot guarantee the success of.

The closest thing I can see is for qTox have some way to **display** a printable copy of something (perhaps a base64 encoded string). This will fall in line of how most secure/crypto-based programs are designed (e.g. gpg's --armor, output of openssl). But once again, this would require the tox save format to be immutable, which it is not at the present time.

**Comment by leafcutterant** [comment]
I'm new to Tox, but if it works similarly to solutions that use public-key encryption for identity, you are overcomplicating things.

Printing the private key is a worst idea* . You'll have to store the private key and what not in an unencrypted form to get it to the printer - which is a threat vector itself. Most new printers are closed little computers in themselves, have internal storage, files can remain retrieved in them, etc.

*If the private key is encrypted before being written into a file, this is not a weakness. But for this, you have to use a uniform way of encrypting it and then decide how to output it which makes reading it back into the software easy. QR code, maybe.

My suggestion is to use mnemonics.

1. Choose a word list. EFF's reviewed diceware (short/long), Bitcoin's BIP39, whatever fits this purpose best.
2. Define a way of representing the Tox private key in the form of a mnemonic word sequence (possibly with an extra word used for checksum),
3. When the user wants to export her private key, all she will see is a sequence of words and a prompt to write it down on a paper and keep it somewhere safe.

If I understand it correctly, friend's ID's are not sensitive infrormation. They could be exported as a PDF with names, IDs as QR codes and perhaps the IDs as text, broken into a few lines. I guess 15-20 of such ID boxes can comfortably fit on a page. Re-adding someone (e.g. after a system crash) would happen by reading the QR code in and copying the ID into Tox. Cumbersome if you have a lot of contacts, but compounding multiple contacts into one QR would require yet another feature to be added, and big QR codes can be problematic to read in.

This sheet could have a dedicated space for the mnemonic which could be written on the sheet after printing.

If the private key is such that storing it as a mnemonic is unfeasible, then encrypting it with the user password and printing it as a QR code is the only option i see.

**Comment by yurivict** [comment]
@leafcutterant You shouldn't assume that everybody is very computer-savvy and can deal with and navigate through all the concepts that you just mentioned. There will always be a lot of people who are very simple users, and need very simple, easy to understand solutions. If qTox is to become mature, it should appeal to those people too.

Paper backup is a very easy to understand concept for simple people. Please also see it implemented in the BitcoinArmory project. Think of the possible event of EMP, or nuclear war. All electronics is destroyed, paper survives.

**Comment by Diadlo** [comment]
@yurivict If you tried to give a real example -- it was a bad case. If all elevtronics will be destroyes => tox network doesn't work. Also, you need to backup tox client on paper (your friends need too). And the final one. I don't think, that in/after unclear war you will reall care about your tox profile

Sorry, but issue seems pointless, I will close it

**Comment by leafcutterant** [comment]
@yurivict, i'm not sure what's your point. I agree, most people are simple users. What I've outlined above is the simplest-to-use paper backup setup i could concieve. The user doesn't have to know any of the technicalities behind it to use it.

@Diadlo, I don't think it's pointless. Of course an EMP or a nuclear war is a bad example. A solution like this is useful rather in cases like these:
1. your storage is irrevocably damaged, your device is lost/confiscated/stolen, and such;
2. you need to cross check points (e.g. border or an authoritarian country) without electronics.

**Comment by Diadlo** [comment]
@leafcutterant 
1. Backup on another storage?
2. Backup in the internet?

**Comment by yurivict** [comment]
If paper backups were such a stupid idea, there wouldn't have been so many articles written about them, and so many software packages implementing them.

Articles:
* Document discussing how to back up bitcoin wallets on paper: https://en.bitcoin.it/wiki/Paper_wallet
* OpenPGP keys on paper: http://jpadilla.com/post/100355231982/backup-openpgp-keys-on-paper
* http://www.grant-trebbin.com/2015/05/encode-and-decode-file-backed-up-as.html
* https://www.extremetech.com/extreme/134427-a-paper-based-backup-solution-not-as-stupid-as-it-sounds

Software:
* Paperbak: http://ollydbg.de/Paperbak/
* Paperkey: http://www.jabberwocky.com/software/paperkey/
* paper backup in the BicoinArmory: https://bitcointalk.org/index.php?topic=152151.0
* scripts to store OpenPGP on paper: https://github.com/4bitfocus/asc-key-to-qr-code

**Comment by Diadlo** [comment]
It's what ~the @sudden6~ I mean. Most of your links it's a separate tool to print something
