### ISSUE TITLE
Notifications when message not sent

### ISSUE THREAD

**Issue by mouseym** [qTox/qTox#306]
When sending a message and having connectivity issues there is nothing to show that the message didn't go through.

This was found yesterday when Groupbot wouldn't invite me to the chat, only to discover that my first two messages hadn't actually gone through.

This is on OSX by the way.

**Comment by tux3** [comment]
Part of the problem is that qTox doesn't stop you from sending messages even if your contact is disconnected.
But I also don't remember seeing a way in toxcore to know if a message failed

**Comment by mouseym** [comment]
void tox_callback_read_receipt(Tox _tox, void (_function)(Tox *tox, int32_t, uint32_t, void *), void *userdata);

would a read receipt work?

**Comment by apprb** [comment]
uint32_t tox_send_message(Tox *tox, int32_t friendnumber, const uint8_t *message, uint32_t length)
return 0 if it message wasn't successfully put put into the sending queue. I don't know how many cases it may cover, but if you or your friend aren't online this function return 0 (just tested).

As for group messages:
     /\* send a group message
      \* return 0 on success
      \* return -1 on failure
      */
     int tox_group_message_send(Tox *tox, int groupnumber, const uint8_t *message, uint32_t length);

This may help.

**Comment by tux3** [comment]
Yes, checking that would be a good start. I'm not sure what happens if the network or peer goes down just after the message was added to the queue though, is there some sort of faux-offline messaging ensuring it'll be received ? Will toxcore give up and if so can it be checked ?

But yeah, checking this and disabling the buttons when the peer is offline first.
