### ISSUE TITLE
qtox: error while loading shared libraries: libwayland-cursor.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rugk** [qTox/qTox#3063]
Brief description: This error is shown when trying to start qTox: `qtox: error while loading shared libraries: libwayland-cursor.so.0`

Operating System: Windows / OS X / Linux (include version and/or distro)  
qTox version: 310-cb8b9dc (according to the apt-get package) - BTW: Who put the "best qTox client" into the description? :laughing: (reported: https://github.com/Tox/tox.chat/issues/94)
Hardware: x64

Reproducible: Always

**Steps to reproduce:**  
1.  [Install qTox](https://tox.chat/download.html#gnulinux)
2. [Use the "jessie" version](https://github.com/Tox/tox.chat/issues/93#issuecomment-201723338)
3. `$ sudo apt-get install qtox`
4. `$ qtox`

**Observed Behavior:**  

> qtox: error while loading shared libraries: libwayland-cursor.so.0: cannot open shared object file: No such file or directory

**Expected Behavior:**  
Start qTox.

**Additional info:**  
![libwayland](https://cloud.githubusercontent.com/assets/11966684/14065597/bd6524ac-f430-11e5-9979-e6edc097ec44.png)

**Related issues:** https://github.com/tux3/qTox/issues/2898, https://github.com/tux3/qTox/issues/2740

**Comment by rugk** [comment]
I installed `libwayland-cursor0`.

Now I get:

> qtox: error while loading shared libraries: libxcb-sync.so.1: cannot open shared object file: No such file or directory

But this is installed:
![libxcb-sync0](https://cloud.githubusercontent.com/assets/11966684/14065608/249e7a9c-f431-11e5-9978-05b1a779ab9d.png)

**Comment by sudden6** [comment]
@zetok #2747 duplicate?

@rugk use the builds from README.md packages are broken :(

**Comment by zetok** [comment]
@sudden6 yep, thus closing this one.

# 

Edit:
@rugk 

> BTW: Who put the "best qTox client" into the description?

:smirk_cat:

**Comment by rugk** [comment]
Now I used https://build.tox.chat/view/Clients/job/qTox_build_linux_x86-64_release/lastSuccessfulBuild/artifact/qTox_build_linux_x86-64_release.tar.xz (from the Readme) and got exactly the same error...

**Comment by zetok** [comment]
Huh. Can you show output of `ldd qtox_binary_name` ?

**Comment by rugk** [comment]
Here you go: https://gist.github.com/rugk/e77bff40ab0087fd8819

**Comment by zetok** [comment]
@rugk thanks.

It looks like someone has broken a static build.

Given that there's no one interested in fixing it, I wonder if it shouldn't be removed from INSTALL.md .. :/

**Comment by rugk** [comment]
And where should I get the build now?

At first the installation according to the official website [failed](https://github.com/tux3/qTox/issues/3030), then I could finally download it, but it could not be executed (I now get to hear that the builds there are broken). And finally when using the builds in the Readme I to hear that they are broken too... :angry: 

Do you have any working builds at all?
The only thing I wanted to do is to install this piece of software and it takes days to even find out that all of the builds are broken... Why do you have an Install.md at all if nothing which is described there works?

**Comment by zetok** [comment]
> At first the installation according to the official website failed (…)

It's an official site of tox.chat, not qTox (qTox doesn't really have one). Note that there is a difference.

> I now get to hear that the builds there are broken

Um, I might have exaggerated on that - in general, if something doesn't "just work" for the user, I consider it to be "broken". AFAICS those builds would work, provided that you would install required dependencies. On that note, it seems weird that qTox was compiled in a way that makes `libwayland` a dependency, since with my build on Gentoo `ldd $(which qtox) | grep wayland` doesn't return anything.

In INSTALL.md you can find all deps required for compiling (and by extension, also for running) qTox.

> Do you have any working builds at all?

Yep, builds just fine on Gentoo. And the real answer is that only @tux3 currently has access to the packages, and he's as usual absent.

> Why do you have an Install.md at all if nothing which is described there works?

Err, AFAIK only generic builds linked there got broken recently. Aside from that, "packages" in Arch, Gentoo and Slackware should work just fine.

Beside that, compiling according to instructions in INSTALL.md will work just fine, provided that you don't run old distro, or Fedora, on which compiling qTox might prove slightly more problematic, since it doesn't provide by default some of deps that qTox requires.

Back in the day when I was maintaining static builds, they worked. You might want to ask @tux3 why he decided to break things.

Note that people behind tox.chat didn't want me to maintain (among things) builds, so I'm not doing that any longer. And yes, that decision was entirely up to them, since they're providing the infrastructure for building & distributing builds.

Anyway, if you want to try, there's `simple_make.sh` provided along with qTox's source that you might run to try to compile qTox in case where you don't run Gentoo / Arch / Slackware. I say "try", since I run Gentoo, and that script wouldn't work for me, although generally it should work, since it seems to follow closely instructions from INSTALL.md.

Sorry to hear that you have so many problems with getting qTox :(
Dunno, do you have perhaps a (few) suggestion(s) on how things could be actually improved?

**Comment by rugk** [comment]
> Dunno, do you have perhaps a (few) suggestion(s) on how things could be actually improved?

Well... the first thing would of course that the package repositories get updated. 

And please...

> It's an official site of tox.chat, not qTox (qTox doesn't really have one). Note that there is a difference.

Yes I know. But you're one project and have one mission. And I am quite sure you can communicate to each other and make sure the website lists at least correct installation instructions. (Or a warning that builds are currently broken or whatever is the current state)
It is sad to see you distancing from this website so much - as if it would be some inofficial site set up by some random people, which just hosts download links to qTox.

The same applies to this:

> > > If you have problem(s) with those instructions, you should report that to the people who actually maintain them.
> > 
> > And who are that?
> 
> No idea, and I don't really care.

You don't care? :worried:
That's also not a good thing. Again: You are working on the same project (tox). You should really care about other contributors or creators of other tox things - whether this are websites or other things. That's a community and it is not limited to your repo.

And about my issue:

> AFAICS those builds would work, provided that you would install required dependencies. 

Well... as for `libxcb-sync`I have that installed. See: https://github.com/tux3/qTox/issues/3063#issuecomment-202065020

> Back in the day when I was maintaining static builds, they worked. You might want to ask @tux3 why he decided to break things.

As he got mentioned in this issue, I hope he'll comment here and (hopefully) fix the builds...
So as it seems I either have to compile it by myself or wait until the builds got fixed. If the latter happens please comment this issue, so I'll know it.

**Comment by zetok** [comment]
Well, there are a few misconceptions.

> But you're one project and have one mission.

Yes, it might appear that there is one mission. But no, Tox and qTox aren't the same project.
Personally, I'm not even convinced that Tox has the same "mission". If they do, then things they do seem rather strange and counter-intuitive to what one would expect. 

> And I am quite sure you can communicate to each other and make sure the website lists at least correct installation instructions.

Yes, I did try to communicate countless times. Typical reaction I was getting ranged from ignoring the issues, to outright kickbanning from `#tox` channels for stating differing opinion.
Aside from that, some time ago someone who seemed to lead "Tox" contacted me, probably wanting to make me slave away under his command, and when I refused to believe that "it's all good now" I was told to "never speak to him again".

> It is sad to see you distancing from this website so much - as if it would be some inofficial site set up by some random people, which just hosts download links to qTox.

Well, that kinda is the case. Slightly better than "just some random website", but only so much. Note that this is just my personal opinion.

> You don't care? :worried:

I did care in the past. Thankfully, I was cured from my blindness and realized that trying to improve "Tox" is not going to work at least in this decade. From that point on, I've moved on, and currently I'm trying to help with qTox.

> You are working on the same project (tox).

Nope, I don't work on "tox" any longer. I work on qTox and [zetox](https://github.com/zetok/tox), possibly also on [TokTox](https://github.com/TokTok/) (its tox protocol spec) if the silly CLA requirement will be removed.

> You should really care about other contributors or creators of other tox things - whether this are websites or other things.
> 
> You should really care about other contributors or creators of other tox things - whether this are websites or other things. That's a community and it is not limited to your repo.

About caring - look above. Repo - it's not just "mine" - I'd hope that everyone could feel welcome to help with it. With that being said, no one's perfect, and if I'm doing something wrong, I really would appreciate that being pointed out.

Community - yes, I agree that I should care about qTox community, and I'm trying my best to do so. One of things to be done - if there's a part of qTox that's rotting, it should be cut off and/or replaced. Sounds drastic, and might not be pleasant, but without "drastic" things there'd be no improvement.. and yes, there is light in the tunnel ;) ↓

> So as it seems I either have to compile it by myself or wait until the builds got fixed. If the latter happens please comment this issue, so I'll know it.

Thanks to @sudden6's suggestion, https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox most likely will be included in INSTALL.md, since it probably will work. If not, it can always be "copied", and improved (fixed), unlike what tox.chat provides. You might be interested in testing it, and sharing how well it works for you :)

**Comment by rugk** [comment]
Does @tux3 agree with your opinions? I mean does he also think qTox should be "cut of" tox?

**Comment by zetok** [comment]
> Does @tux3 agree with your opinions?

Yes and no, depending on the opinion ;)

> I mean does he also think qTox should be "cut of" tox?

Clarification: I don't know whether qTox should be "cut off" from "Tox", and I'm not lobbying for that. I think that having a safe distance to something that might prove damaging is preferable.

As for the part that that needs to be fixed/cut off - those are packages provided by tox.chat, and given that they haven't been fixed for months, it's time to cut it, and provide a replacement.

And about that I've emailed @tux3, and hopefully he'll respond soon, so that OBS repos could be linked to from the INSTALL.md.

As for the whole situation, I don't know what is @tux3's opinion.

Have you tried using those packages? :)

**Comment by rugk** [comment]
> Have you tried using those packages?

If they would at least provide their release key over HTTPS I would probably do...

**Comment by zetok** [comment]
I see. That's kinda a bummer, and I wonder if something can be done about it..

@sudden6 any idea on who would need to be contacted about https support for `downloads.opensuse.org` ?

In any case, here's the key I got by downloading it via http:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.15 (GNU/Linux)

mQENBFQIchQBCADoKMFnk3KCGdLSuVzds0KFU/j7HB889uakrIQRlmbfzgBtZcWD
3V4voBy9DTeF6EGRhTYt2Gey5AvRvkewZ8+ei9PXEwsieMSwHguAfNwTD1YJtkqt
bi1NrduUESHQsE4GYlztEkkfmZxb5Ji66T9CNXKj7JvLTE8ZmOEJZWbrAPMxR26R
gvpQ5+BZKupWbOm9TRCfjXLkGLw6a2POs6hVt6upuSXQXSvFpPE0q83ZCP6dak/k
pgzGuDT38rXzN9+rJjRiLyslRjCTdX7PSp7lkYT7o/HtdeW2aPG6JLhntP9p/WMD
CMRqvUqJGbjRXp38qf40XdTP47uWSv0HhKiLABEBAAG0RGhvbWU6YW50b25iYXRl
bmV2IE9CUyBQcm9qZWN0IDxob21lOmFudG9uYmF0ZW5ldkBidWlsZC5vcGVuc3Vz
ZS5vcmc+iQE+BBMBAgAoBQJUCHIUAhsDBQkEHrAABgsJCAcDAgYVCAIJCgsEFgID
AQIeAQIXgAAKCRDyqgseXvgwO1qOB/0TwApbSDTIh93fUld4/Fhx269ryTGqGhsu
IaAe3/QR9sqTyLiuSysFAmkT5XJlGLPKMKZyM/19f2y8CEoSrYi3JkHVwFTm9gn1
Jm6zHZnTFkz0jwtFBOeBLk5Pe5hNwmMX4vgr2onv66j+qkMe8uusWE8/7roIEisk
Bkrzcns5CbYbbz1kqkYsqJ3ulKjksIVrvw9rotd41l5SLjCtwwmVn/glmtTZwa/g
8ezetMATXG05K0TpFGKZykhwlMPorOp7frfc9q+WJoR5VflwbmZs8Pjtd8xH+yDE
H2Om6pEd7nBWER8oPBkJOcgOiylwSMB4uzXxpTbZfsQ1YvhARuuoiEYEExECAAYF
AlQIchQACgkQOzARt2udZSNbhQCfeAdB/TzYpGeq3BoXdM31J0uWeusAoLOEvUJu
5jnukiwIYzrUpsma0krT
=Agmm
-----END PGP PUBLIC KEY BLOCK-----
```

Also, note that you can get it by `gpg --search-keys antonbatenev`

**Comment by sudden6** [comment]
> any idea on who would need to be contacted about https support for downloads.opensuse.org ?

I have no idea if https support would be even possible with all the mirrors of downloads.opensuse.org

Maybe @abbat knows more?

**Comment by abbat** [comment]
downloads.opensuse.org owns by Novell and we can try to email to admin at opensuse.org to ask them to enable https (but I do not think they do it).

Also all packages signed by my GPG key (0x63E2FF3F ) which you can download from secure servers and check package integrity (apt do it for you automatically if you `apt-key add` my key).

**Comment by rugk** [comment]
> no idea if https support would be even possible with all the mirrors of downloads.opensuse.org

Well... optional (and with the wget copy&past command line changed to https) would be enough.

**Comment by rugk** [comment]
@zetok 
Your key differs from mine. I got this one:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.15 (GNU/Linux)

mQENBFNv95MBCAC1yB+kGNyHY4yvr5WEC0E7P2vW71Y2kJzVan1CVIjYJTEgyQn9
VNgjVW5CvTuA0jMmYTo29bNlSixsG6CNQFl0smOuN+VXETRVr5Rac7prB9wCCxZD
b+76UXNCYROcwrXMWoDg009MipfK32VZn9Obw/erBoPpCB8MyKEbfF+uRJinoj9M
qxGyiJZBY6l10UlSw/UZNiaNL59fPKxytJqRB01MLcDQHsEY4oUtPoYDTVPStR01
WCYuf00z+j6qFq4BtBJW7UEcqe0UaRTqno46bIRbvJAfUAPa7nfTbPJFLFsgnmbk
hoi4YIm7wa/+j0az5UouhuG5zxO9iH90jhmtABEBAAG0NmhvbWU6ZGcweXQgT0JT
IFByb2plY3QgPGhvbWU6ZGcweXRAYnVpbGQub3BlbnN1c2Uub3JnPokBPgQTAQIA
KAUCU2/3kwIbAwUJBB6wAAYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQzXsh
e3zgrmrvTQgAqM/Man9ekHuX5BTvcSBnZVfNvAhlFBoSxp1zHZk69mDBo+0ZJLkM
E0Y93mUgfMC3K9xZ5Yy7xaqoNnzpS4rOS4csLg6q5IAHcMnZb6IeSAvQPu68mjzy
ptRzgmEGzHpHZJ7paQABmbLoMOhKjr3CXasj1nCtPJEcaI34OzzreQLXZTXJylUZ
LtPT4nj0sSORG5TApX75CIsKVZOW1WK3ND9taS8RtGzExYb/l0ndQYNF3US5BLiB
3Ruyuu1biGFCgbUWm/JYBxT8S66yT54/Hk5D80DdW0eHJ9plybHafC+tdv85486G
jeo3cvCevNoe2aN4Uy+trd5vWxDDQB6UmIhGBBMRAgAGBQJTb/eTAAoJEDswEbdr
nWUj558AoKQq3qnvvcHY3HwT9wO7WtGW/5+4AJ4yRp41r8EjD/HQpcJFFLUC50/h
lw==
=D+49
-----END PGP PUBLIC KEY BLOCK-----
```

The beginning is the same, but at the end they are clearly different.... :fearful:
Can anyone else download the key and check it?

BTW I downloaded it again over Tor and got the same key, so I think mine is the correct one.
