### ISSUE TITLE
[Feature Request] Enable/disable blinking icon

### ISSUE THREAD

**Issue by bitboy85** [qTox/qTox#3064]
If you recieve a message, the icon in the window list and in the task bar blinks if you recieve a new message. Having an option to disable this behaviour would be nice.

**Comment by zetok** [comment]
What is the use case?

**Comment by roranicus** [comment]
I agree, an option to turn off notification would be greatly appreciated. I like to leave tox on, but blinking buttons can disrupt my workflow.

**Comment by bitboy85** [comment]
Yes, thats what i wanted to say. It could be irritating if something blinks on the screen when you need to concentrate.

**Comment by ProMcTagonist** [comment]
DND mode?

**Comment by zetok** [comment]
> DND mode?

I think that `Busy` status could act as such. I.e. setting `Busy` is supposed to turn off notification sound, and I wonder if adding to that blinking would be a good idea.

Although that might be overloading functionality that most people would find annoying, and instead an option setting what `Busy` is supposed to do should be provided... :/

Opinions?

Related: regression to `Busy` functionality: #2893

**Comment by roranicus** [comment]
Having to set a specific status for it is too specific. Speaking for myself, I like to appear as online and available, but still have no form of notification whatsoever. It's just a natural part of my workflow to keep tox on my second monitor and look at it ever 5 minutes or so. 

If you look at most irc clients, they have a wide variety of notification options. While a busy status turning them off is a good default, an option to always have them off regardless of status would be the best when it comes to adapting to a wide variety of users. Just have a box we can click off if we don't like notifications.

**Comment by zetok** [comment]
> If you look at most irc clients, they have a wide variety of notification options.

On general principle `IRC ≠ user friendly`. 

> Just have a box we can click off if we don't like notifications. 

Generally, the more options, the less user-friendly software is.

Perhaps one option to disable all notification wouldn't be bad.

**Comment by bitboy85** [comment]
In case of user friendly, there can be different points of view. Every software which steals focus, brings windows into foreground, blinks or plays sound forces the user to do something he may not want to do at the moment and stopping his workflow.
There are many examples. If you search for Win XP balloon tips, the first google results will tell you how to disable them. The sound "You have mail" was funny at the beginning of email, but today you may recieve hundreds of them and who wants to hear it many hundred times a day?
I agree with you that too many options are not user friendly, this is mostly for options which users cant understand what its doing. On the other hand if users want to change the behaviour of a program and cant find an option for it its also annoying.

**Comment by ghost** [comment]
Too many options => `about:config`-style manager. Anything beyond the scope of Average Joe gets buried there. That, of course, taking only the user perspective into account.

**Comment by Diadlo** [comment]
What about just painting in yellow once (without "annoying" blinking)?

**Comment by aaannndddyyy** [comment]
yes, the notification need not disappear altogether, just not blink anymore. Change of color would suffice.
In my case it would only be needed for DND mode, but it could also be a separate option under advanced so that it does not clutter the view of the other settings. 
I had originally though of having this option right under the one for switching sound on/off when in DND.
I would not generally want it to be always off. Blinking is a good notification and noticed faster than a simple change in color, so personally, I would like to be able to change the settings once, and then have the following behaviour upon receiving a message: blinking when online or away  and simple change of color w/o blinking when on DND.

**Comment by roranicus** [comment]
Seems like the sensible options would be 
- notify by blinking at all times.
- notify by blinking only when online
- notify by binking when online or busy
- never notify.

Different workflows require different behaviors.

**Comment by zetok** [comment]
@roranicus sounds way more complex than it needs to be.

What about having a `Do Not Disturb` mode that would result in:
- no notification sound for new messages
- blinks just once for new messages

`DND` – option in settings to turn on `DND` when `Busy`

**Comment by roranicus** [comment]
@zetok Because some people, like myself, dislike notifications at all times. I don't want to broadcast a status saying I'm unavailable, but at the same time I don't want any notifications. I just keep tox open on a second monitor and look at it once in a while. It's as much a reflex as looking at my mirror while I drive. 

My point is that there are a lot of different workflows, and software must be adabtable enough to work with all of them. Just because you or I likes to work a certain way doesn't mean that way works for everyone. I can tell you that having no notification is just as important as having my messages encrypted for me. Simply, I cannot work if anything blinks, changes icon, or changes color. 

Options shouldn't be limited just for the sake of simplicity. Too often, trying to make software user-friendly makes it unusable unless the user happens to have the exact same workflow as the dev.

**Comment by aaannndddyyy** [comment]
@roranicus : your four options can be reduced to two checkboxes.
[] notify
[] notify even when busy

meaning that if both are checked, it corresponds to your first option of "always notify",
if only the first box is checked, it is your option two, and if none is checked, it corresponds to four "never".
I see no point for having your option 3 different from option 1.

**Comment by ghost** [comment]
> What about just painting in yellow once (without "annoying" blinking)?

Or using the red-circle-with-counter-in-a-corner (does it have a name yet?) like any other modern chat app.

![qtox-notification-counter](https://cloud.githubusercontent.com/assets/6382342/19134113/53694a2e-8b5c-11e6-818d-6946ce368091.png)

**Comment by anthonybilinski** [comment]
fcd88d65b2875c06312374186fd9a08a9637dac7 added the "Notify" option to user interface settings, which allows disabling of the blinking icon. This seems to address the main point of this issue.
