### ISSUE TITLE
[Feature request]  Move button screencast in window chat

### ISSUE THREAD

**Issue by SergeyDjam** [qTox/qTox#3097]
Hello. 
There is an idea to place a video call button on the selection of variants with the broadcast desktop or webcams. This is done in jitsi and skype

**Comment by anoadragon453** [comment]
You're suggesting there should be a button for screenshare in the call window that would set your desktop as your webcam?

**Comment by ProMcTagonist** [comment]
+1

You should be able to select and control audio and video devices from within an active call's interface.

**Comment by SergeyDjam** [comment]
Yes, control AV in call's interface.

**Comment by zetok** [comment]
> Move button screencast

No, at least to proposal of moving video call button.

> This is done in jitsi and skype

No idea how that looks/works, but I suspect that it's not the best way to do things.

Could you provide good arguments in favour of moving & providing an unhelpful interface, as opposed to extending idea from #773 ?
↓
If there are no good arguments → #2102

**Comment by ProMcTagonist** [comment]
> No idea how that looks/works, but I suspect that it's not the best way to do things.

Well that's not sensible.

Managing AV sources from within the call interface, per-call, is a necessary feature. I'm not going to dive into settings and change the global default video source when I want to show one person my desktop for a few minutes.

#2102 sounds like it would solve this use case, though.

**Comment by zetok** [comment]
> Managing AV sources from within the call interface, per-call, is a necessary feature.

I'm not sure about that. Note though that `A/V` source for me is a webcam, and not desktop streaming.
I.e. IMO for webcam you set it in settings (if manual action is needed at all, since qTox preferably should just make it work automatically).

As for desktop sharing (a ~separate feature) you'd just push another button in chat in order to stream it. As for options in screen sharing - that could be done in chat.

> I'm not going to dive into settings and change the global default video source when I want to show one person my desktop for a few minutes.

Yeah, I agree with that, expecting one to go to setting in order to share screen is unreasonable.

Since #2102 seems to be a way to go, closing this issue.
