### ISSUE TITLE
Allow higher Volume / Gain

### ISSUE THREAD

**Issue by BenjaminVettori** [qTox/qTox#3109]
Operating System: Windows 10
qTox version: 1.3.0
Sound-Card: ASUS Xonare Essence STX Audio Device
Microphone: König CMP-MIC8
Headphones: Sennheiser HD 380 Pro

The person who I am talking to is also using qTox and has set the volume and microphone gain to maximum.

If i turn the microphone level and Volume to maximum, it is still quite low compared to other programs which have the same global volume in Windows. If i tune up the volume in windows such that the volume of qTox is normal, other programs are really loud.

A workaround would be to increase just the qtox volume in windows, since it is possible to adjust the volume for a single program. One problem of this workaround is, that the incrementation of the qTox volume also increases the global volume and every program has the same volume as the global volume when it gets started -> so every newly started program (e.g. a media player) is loud.

In Skype the volume is fine using the same Hardware and OS.

I'd like to have greater range for the volume and / or gain such that i can adjust the qtox volume to a higher level as the current maximum.

**Comment by zetok** [comment]
It was done in #2415, but then, later on, reverted, since (IIRC) it was causing some problems.

Edit: related:  #2422

**Comment by antis81** [comment]
@r3bel Try raising the mic. volume in your system settings. This works quite good and will improve the situation for you.

@zetok Yes, it was reverted, because the whole audio implementation was "pure crap" and we eliminated the most important disturbing code parts. The problem itself is: OpenAL was written with a focus on playback of 3D in-game sounds (e.g. a plane flying by or a gun shot). And this is exactly what it has excellent support for. OTOH the lib has lousy support for capturing audio data. It does not support control over the input Gain at all -> we faked it in the past and implementation was just as lousy. :)
