### ISSUE TITLE
After ungraceful shutdown qTox starts in persistent Away mode

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3122]
Observing this in a virtual machine with qTox ruining in it. When this machine is killed, next time qTox starts in Away mode.

I guess, qTox was in a temporary Away mode because user wasn't active. But after restart this turns into the permanent Away mode.

FreeBSD
qTox-1.3.0
toxcore-0.151112_1
qt-5.5.1

**Comment by zetok** [comment]
Well, there isn't anything that could be done about that. At least not in qTox. And I have doubts whether trying to fix that would actually lead to any benefits..

> I guess it qTox was in temporary Away mode because user wasn't active. But after restart this turns into the permanent Away mode.

Yep. Even with "temporary" one it gets saved on HDD – it's saved in format that toxcore provides, and it just saves current status. When loading profile qTox has no information on whether given status was temporary or not, it only knows that status is `Away`.

Closing, since qTox doesn't have a real way of "fixing" it, and it doesn't seem like thing that toxcore should actually take care of.
