### ISSUE TITLE
Make Close to tray default

### ISSUE THREAD

**Issue by franta** [qTox/qTox#3159]
People expect this feature because it's usual in other chat clients.
And thing about Autostart.

**Comment by GrayHatter** [comment]
pls no

![skype](http://i.imgur.com/n8ZHPhK.png)

**Comment by aizenbit** [comment]
It seems to me that many people do not like "Close to the tray" option. For example, there is a lot of pages named "How to close Skype", so many people do not like to keep Skype always running and minimized to the tray.

Autostart option is usually added to the last page of the installer, but I'm not sure that it should be enabled by default. It's usually enabled, but for me personally it is annoying.

**Comment by franta** [comment]
So, what about dialog during (first) closing:

Really close qTox?
Stay online for incoming messages | Really close

Please don't make tox complicated for users. XMPP was here, we need some user friendly thing if we   don't want closed protocols.

**Comment by GrayHatter** [comment]
@franta because I'm opinionated, I think: No, it should be a hidden button, buried deep into the settings page. But your solution is probably the best idea.

It doesn't force users into close to tray, and won't surprise users who are expecting and want that feature (so that they wont miss messages).

**Comment by franta** [comment]
For me, personally, it's should be a hidden button too. But I don't need chat program where in contact list is only my second account and echo bot.
I want make it available for more people, and this issue is based on first experience with non it user.

**Comment by zetok** [comment]
> I want make it available for more people, and this issue is based on first experience with non it user.

Good :)

**Comment by zetok** [comment]
Starting in tray will not be a default, since, lets face it, there are some shitty "DE"s out there that can't even get tray to work, which would make qTox unusable for the people that use those "DE"s.

**Comment by franta** [comment]
Thanks for commit.
What I mean by Autostart is option named Autostart in settings (gui), not option autostartInTray. Unfortunately, I don't know how it is working, because when I change it, nothing was changed in qtox.ini.

**Comment by ProMcTagonist** [comment]
My very frank experience is that most casual users think they want it to "close for real" because it's fun to be contrarian on the internet, then they grumble and moan when they have to reopen the program to get the messages you've had to text them about them missing.

Sane defaults for casual users, options and settings for power users.

**Comment by GrayHatter** [comment]
Making UX decisions because people are used to a 'broken' design is bad
policy.

Because people are used to clicking the close button to send an application
to the tray, is a poor argument for making that design choice.

Especially with Tox, which already uses 1GB daily.

**Comment by ghost** [comment]
I personally would not like autostart or minimize to tray to be defaults, by default I don't think a program should do anything extra special, though it should of course allow users to customize it as they want, but I think that giving people a base where the defaults haven't customized it too much in a certain way is good, and then just to allow people to configure it as they want.

**Comment by franta** [comment]
It's hard decision for application creators. Make application for people, or make application for clean design.

**Comment by ghost** [comment]
Well, I would consider minimize to tray and especially autostart to be very custom features, some people love them, some people hate them, but I don't think that they should really be enabled by default. It's like shipping a browser with loads of pre-installed plugins that make the browser customized for a certain use, when not all the users will want that use by default. I think it's good to give a default that doesn't go too much in any direction in terms of customization, and then just let the user decide what they want to enable.

**Comment by GrayHatter** [comment]
@franta no it's not. The big red button that says close/exit. Should
close/exit...

The question that's here is; Should qTox break the original intent of the
exit/quit button, or copy the broken implementation of other messaging apps
trying to help the user's peers by never quitting so that they can push
messages to the user's device?

**Comment by ghost** [comment]
@franta, I agree with @GrayHatter, by default the close/exit button should really close/exit, if people want to configure it to do otherwise then that is their call, but it should in no way be the default to have it all fully tweaked in one way. And definitely not autostart, that definitely should be not enabled by default because getting an application to startup at startup should really be something that the user configures so that it isn't a shock to them or imposing.

**Comment by zetok** [comment]
@GrayHatter 

> The big red button that says close/exit. Should close/exit...

Please. The button does exactly that in either case, i.e. closes the window.
As for whether the application is closed, there'll be a sane setting for it.

**Comment by ghost** [comment]
@zetok, Well, when I press the close button on a program I expect the program to close and not just the window (unless there is more than one window open), this should be something configurable, but I think that by default it should do the most expected and convenient option.
It may be convenient for it to work another way for others, but if they want a longer way about it, I think that's something which they should configure and not something on by default.

**Comment by ProMcTagonist** [comment]
@GrayHatter have you given up on utox?

Toxcore using lots of data isn't a factor that will affect frontend UX choices. It simply needs to be fixed in core.

@SeventhSonOfASeventhSon 

> when I press the close button on a program 

You don't click the close button on a program, you click it on a window. qTox runs in the tray as is standard for messaging services that are meant to stay open most of the time. When you close the window you can open another window to interact with the running qTox program with the tray icon. It's logically sound. Big, long-running programs have program exit/quit buttons not connected to each window's close button.

Skype, AOL, Yahoo Messenger, XMPP/Jabber/IRC clients, it's a nearly universal convention for messengers that no one had a problem with until they realized they could get more clicks by making comics about it instead of turning it off.

**Comment by GrayHatter** [comment]
@ProMcTagonist no, but if you click x to close Tox and instead, it goes to the tray and you lose data/bandwidth/monthly-transfer because of it the next step will be uninstalling. Plus, does qTox disconnect and re-encrypt it's data? Allowing ease of quit would be better security decision as well.

I've hated Skype for that feature LONG before anyone started making jokes about it. That's where the joke came from, someone being annoyed by that function.

If I press alt+f4 I'm sending the application a quit command. Not a go-to-tray command. If an application ignores quit commands, then **my** next step is the terminal to `kill` followed by `kill -9`. If you're running `kill` or `kill -9` on a GUI application, is it working correctly? 

edit: 

> You don't click the close button on a program, you click it on a window

you're using your window manager/desktop environment to send the application a quit command.

**Comment by zetok** [comment]
@GrayHatter 

> no, but if you click x to close Tox and instead, it goes to the tray and you lose data (…)

If that would happen, it would be a bug, those get fixed.

> Plus, does qTox disconnect and re-encrypt it's data?

If user wants.

> Allowing ease of quit would be better security decision as well.

This isn't about disabling a way to turn qTox off. And yes, it is easy to turn it off.

> I've hated Skype for that feature LONG before anyone started making jokes about it.

That's because skype is shitty. If you had used a real, good IM client that wasn't ~bad and worked properly in tray, your opinion could be different.

> If I press alt+f4 I'm sending the application a quit command. Not a go-to-tray command.

You can have that in qTox, and it's not going to change.

> If an application ignores quit commands, then **my** next step is the terminal to `kill` followed by `kill -9`. If you're running `kill` or `kill -9` on a GUI application, is it working correctly? 

Dunno about that – in my experience GUI applications in general misbehave. With that being said, you might want to improve your workflow, to first do `kill -3` instead of first sending `SIGTERM`, so that you'd give the application proper signal to quit.

# 

@SeventhSonOfASeventhSon 

> It may be convenient for it to work another way for others, but if they want a longer way about it, I think that's something which they should configure and not something on by default.

Yes, this is not going to change – it will be configurable. What does change, is that configuration will be set to `ON` by default.

# 

Anyway. There is a good reason to close IM application, and that is memory usage. Not really a problem on Linux, but some people run windows, and they suffer from their OS deficiencies. Use case is that they have some important thing to do that requires $some_memory. Since they don't have any free memory, and IM uses some of it, that they would want to close it when they need more free memory for something. Considering how bad windows is, they'd want to do it frequently.

And if the memory usage is a problem, it should be addressed.

**Comment by ghost** [comment]
@zetok, Right, well, I just ran into something slightly more disturbing for me at least... I decided I would give the minimize and close to tray a go just to see how it goes because I never really used them that much before... Turns out that my DE doesn't handle tray icons very well, and without actually closing it, I can't get qTox back! And right-clicking on the indicator icon (when that does work) does not seem to give me any option other than to exit it so I can't actually launch it back up again...
I've tried double-clicking/clicking the icon and clicking on the qTox launcher icon in my dock but that doesn't work... So if you are going to make this the default, you should at least make it function a little better...

**Comment by zetok** [comment]
> So if you are going to make this the default, you should at least make it function a little better...

qTox does what it can. What doesn't work, is your DE. With that qTox can't do anything.
https://github.com/tux3/qTox/wiki/Tray-icon

It's also possible that you're affected by #2449, which could result in trying to launch qTox not bringing up current instance. That bug though seems to happen when using qTox with Qt version that it wasn't compiled against – that would be a problem with distro..

**Comment by ghost** [comment]
@zetok, Well, you were the one who said this:

```
Starting in tray will not be a default, since, lets face it, there are some shitty "DE"s out there that can't even get tray to work, which would make qTox unusable for the people that use those "DE"s.
```

Anyway, I guess there is no swaying you, but I am against this change, and seemingly are the majority of people commenting on this issue... Maybe when one creates a profile they should be asked a few things like if they want to have it close and minimize to tray etc? Other IM programs do similar when one is creating a new profile for the first time...

**Comment by zetok** [comment]
@SeventhSonOfASeventhSon 

> Well, you were the one who said this:
> 
> > Starting in tray will not be a default

Yes, that's about starting in tray.

> Anyway, I guess there is no swaying you, but I am against this change, and seemingly are the majority of people commenting on this issue...

Oh, I can be swayed :)
I just need good reason(s) + overwhelming majority of people who'd share same view. Note that I need overwhelming majority only on for stuff that makes it harder/less sane for people to use qTox.

There's no majority here – out of 6 people who voiced their opinion here (including myself) only half of them is against. Furthermore, opposition didn't list reason(s) good enough to not change the default, while supporters did list good reasons to enable it by default.

> Maybe when one creates a profile they should be asked a few things like if they want to have it close and minimize to tray etc?

Maybe. Not a subject of this issue though, if you want, create a new one. An issue like that should include more than design for just this option. Look at each setting tab, and see which options users _absolutely must be forced_ to decide on, and how things could be done to make it as hassle-free as possible.

**Comment by GitAClue** [comment]
zetok: I came here for a different reason but when I stumbled on this issue I felt compelled to create an account just to add my NO vote. DO NOT MAKE THIS BROKEN BEHAVIOR DEFAULT! The NO votes now have a simple majority. I will re-iterate the good reason for not breaking the UI and note that there has been no good reason given for such a change to me made. NB: "Skype does it" is not a good reason but is the only one given thus far.

All the programs given as examples of closing to tray (Skype, AOL, Yahoo Messenger, etc) are total shit. Its funny that you say Skype is shitty and suggest our opinions would differ if only we had used decent IM clients. Guess what? Crap like close-to-tray is WHY Skype sucks and the programs I choose to use for IRC and IM do NOT have this crap. I can't say I've ever seen an IRC application hide in the tray, but I tend not to go for crap software. I had thought qTox had some promise, but initial impression may have been better than reality.

Expected behavior is clicking the close button on the last window closes the application. If it does not do that, there is a bug. If you want to minimize to tray (instead of wherever else minimized windows are stashed), that may be a sane option, but redefining the close button is insane and indefensible. Better would be an extra "Hide" button to hide in tray separate from minimize and close. The availability of the extra button could be an option that is on by default.

I am pleased to see there is finally a changelog for 1.4.0 release. It is unfortunate there was no changelog or release notes previously so I do not know if the change I observed in 1.3.0 is intentional or a bug. Prior to that version, it was possible to run multiple instances of qTox in order to have multiple profiles online. That is not possible since the previous release, executing qTox does nothing if there is an instance running. This is a severe problem that needs to be fixed.

If hide-in-tray-instead-of-close becomes the default, expect a fork. If I'm going to sink some time into improving this program I'd like to be adding essential features like the ability to choose audio devices and to specify separate output devices for call audio and ringing/notifications, but it seems I'll have to waste time unbreaking stuff instead.

**Comment by zetok** [comment]
@GitAClue 

> It is unfortunate there was no changelog or release notes previously so I do not know if the change I observed in 1.3.0 is intentional or a bug. Prior to that version, it was possible to run multiple instances of qTox in order to have multiple profiles online. That is not possible since the previous release, executing qTox does nothing if there is an instance running. This is a severe problem that needs to be fixed.

Well, yes and no. Currently it should be possible to run it with `qtox -p $profile_name`. Otherwise "launching" `qtox` should launch qTox, or if there is already an instance running, bring up that running instance. It's not optimal, and it could use some GUI – if you have an idea how to do the GUI, could you open an issue?

---

> I will re-iterate the good reason for not breaking the UI and note that there has been no good reason given for such a change to me made. NB: "Skype does it" is not a good reason but is the only one given thus far.

Err, no, there has been a good argument made by @ProMcTagonist:

> My very frank experience is that most casual users think they want it to "close for real" because it's fun to be contrarian on the internet, then they grumble and moan when they have to reopen the program to get the messages you've had to text them about them missing.

Amen.

In addition and extension to that, there's the thing with users that aren't that really good with computers – what they **need** is communication software that will work, regardless of what they do. _`“I've clicked on something and now it's gone. Halp”`_ – its a reaction you don't want to get. And having an IM that does it is really bad.

Or being in an important call, feeling a little nervous yourself, you've misclicked and your IM goes _`”Hell yeah, closing that useless call.”`_ – again, this is something you don't want. _Especially if it takes a minute or two to go back online._

There are reasons, use your imagination.

And maybe try to set things up for people who haven't really used computers for most of their lives, perhaps its a new & fresh experience for them – see how well it goes if you don't have autostart & close to tray for IM they'll be using to contact you.

> All the programs given as examples of closing to tray (Skype, AOL, Yahoo Messenger, etc) are total shit.

Err. The way I see it, those would be bad regardless of whether they would close to tray or not.

> Guess what? Crap like close-to-tray is WHY Skype sucks and the programs I choose to use for IRC and IM do NOT have this crap.

Oh, and here I was thinking that people didn't like skype because it's a proprietary piece of crap (PPoC).
Makes me wonder though – are you using CLI IRC? And if so, do you have some CLI IM?

> I can't say I've ever seen an IRC application hide in the tray, but I tend not to go for crap software.

Here you go :)
![dat IRC client](https://cloud.githubusercontent.com/assets/3148759/14908865/b2a55812-0dd4-11e6-9b5f-09cdab8c06a6.png)
I wonder – is the most popular GUI IRC client out there by your definition "crap"?
Then again, IRC usually ~sucks when it comes to UX.

> Expected behavior is clicking the close button on the last window closes the application. If it does not do that, there is a bug.

Actually, IM that closes and cuts you off from people you want to talk with is a bug. To not let that happen accidentally, there is `Close to tray`. Now, some users don't want that kind of protection, and for them there's an option to disable this behaviour, and simply close qTox once they click on the button.

> If you want to minimize to tray (instead of wherever else minimized windows are stashed), that may be a sane option, but redefining the close button is insane and indefensible.

That's your opinion, not a fact. :)

> Better would be an extra "Hide" button to hide in tray separate from minimize and close. The availability of the extra button could be an option that is on by default.

Sure. Oh wait, there's no such button on titlebar. Though luck. In any case, it still would miss the point, given that primary use case for `Close to tray` is avoiding accidental closing of IM + as an addition it minimizes it to tray making some use of otherwise useless button.

> If hide-in-tray-instead-of-close becomes the default, expect a fork.

Ok. I don't understand one thing though – why a default option would cause you to become so emotional, especially given that keeping it `off` by default would cause problems for a lot more people, and given that you still can easily switch it to `Off`?

If there was some IM software other than qTox that I would want to use and it had a default option that I thought changing would make it worse, I'd let people working on it know that IMO it's not a good change, change it for myself (<5s in settings) and move on with things.

And here we are, with you stating that you're going to make a fork out of one default setting. Colour me confused.

I'd prefer to hear your arguments, but if you prefer to seemingly work in your corner alone if people don't agree with you that's fine too – makes one a bit sad though :(
And since we already have images here.. :D (read from right to left)
![iknowtheressomepartofmethatsdying_zps9fc3ae20](https://cloud.githubusercontent.com/assets/3148759/14909547/bb51d294-0ddc-11e6-8706-9bda4b6a24b1.PNG)

> If I'm going to sink some time into improving this program I'd like to be adding essential features like the ability to choose audio devices and to specify separate output devices for call audio and ringing/notifications, but it seems I'll have to waste time unbreaking stuff instead.

Feel free to send PRs :)
Also, I'm not sure about the "waste time" – all that it takes is reverting a simple single commit, and that's not hard or time-consuming…

**Comment by GitAClue** [comment]
zetok: You'll just have to inline my replies in your head because I see no way to quote your post except by copy'n'paste and I'm not about to add the quote thingy to every line manually.

Prior to 1.3.0, it just worked to keep running qtox and choose a different profile each time. I don't know what would need to change in the GUI to restore that behavior. Popping the current instance forward instance of starting a new instance is just wrong behavior. I asked the app to execute, not find me a copy of itself. Imagine your terminal or file manager doing this when you wanted another instance; nuts.

The "argument" from ProMcTagonis doesn't even make sense so I can't consider it reasonable. People want to close but don't, WUT?

I think it more confusing to try to close something and have it hiding in the tray. You know you need to restart it (e.g. because it can't figure out anyone is online), so click close, then "start" it again and boom, it's right back where you were. WTF? I wanted to restart you bastard!

The call thing is even more absurd. Let's say I'm in a call and need to immediately hang up for some reason, but clicking hang up or close just hides the damn window. I'd be ready to stab someone about then... I've had to throw an iPhone across the room (and to its death) because it wouldn't mute or hang up a call at a very inopportune time.

Setting stuff up for clueless people makes it useless for anything non-trivial and does nothing to help them learn. Is the X a close button or a hide button? If you are just starting out and nothing closes when you click the X, you'd think there was no way to close things.

There's plenty of proprietary software that outclasses any open alternative, and there are things where you just need to see the code sometimes. Those programs were crap not because they were closed but because they where each examples of outstanding bad user interface design. qTox is not doing much better by mostly ignoring the system theme and colors. Don't think you're immune to being crapware just because it's an "open" project.

I'm not a masochist, I'm not using CLI clients and I miss the rich GUIs of some of the older IRC client that have fallen by the wayside when their platform died or the author moved on. The most popular GUI IRC client out there, mIRC, is total crap and certainly has does stupid things. I guess it should also be no surprise that the bastard child of the open-gone-payware crap client has stupid options too.

Note behaving as expected is a bug. The Close button is meant to Close, not to hide. Doing anything else is a bug and there's no way to claim otherwise without ignoring basic logic.

There might not be a hide button but there is nothing preventing you from adding one. qTox is certainly not shy about deviating from system norm for interface design. Add an extra button is much better than hijacking another button, especially the most important button of all those on the titlebar.

At first glance, qTox looks like a basic client that just needs fleshing out, but use it a bit and there's bugs that make it barely usable (nobody can see each other online until everyone restarts their clients). The development on it is only visible through the commits to github. There's no roadmap anywhere, barely any documentation, not even a changelog or release notes until recently, and no contact information for the authors, just links back to the little corner in github. Alas, I find critical bugs sitting for months to a year with statements like "yes this is really important but I don't have time to code a fix". Meanwhile, there's crap like this; a bad idea that leads to a bad commit accompained by bad grammar in the commit message. No time to make the app work, but time to bust up the UI more? Seems like the app isn't in good hands so I have no reason to expect improvement unless I do it myself. However, forking may be a waste of time, maybe I'll just find that it's a worthless mess and starting from scratch is faster than trying to beat that mess into shape. Forking instead of starting something from scratch would have a theoretical benefit of sharing future development efforts, but I'm not sure there would be enough quality commits to be worth the time it takes to sort through the garbage, plus there's the burden of git to even access those commits. I've seen this project go literally nowhere for half a year, one version after another and nothing improves but some things get a little worse (broken process starting, removal of audio filtering, broken close button, etc). 

If I wanted to work in a corner like y'all, I wouldn't mention a fork. Publicly stating I am contemplating an alternate effort is a means of gauging interest from (a few) others that may be in a similar position.

**Comment by zetok** [comment]
@GitAClue Hmm. You kinda sound like someone who doesn't quite get the point of volunteer, unpaid work in free time when someone wants to change something "because reasons", until the point:

> (…) I have no reason to expect improvement unless I do it myself.

Precisely how unpaid FOSS works :)

> There's no roadmap anywhere (…)

How would you make one in the first place?

> (…) barely any documentation (…)

Feel free to write some, or point out which documentation is missing, so that it could be written by someone willing to.

> (…) and no contact information for the authors, just links back to the little corner in github.

Dunno about that. Anyone capable of using `git` can get the emails of authors. I for one am not that interested in rest of "the internet" harassing me. If they have an issue with software, they can report it. And hey, there's even a handy link for it :)

> Alas, I find critical bugs sitting for months to a year with statements like "yes this is really important but I don't have time to code a fix".

Yes, this is a perfectly valid point when you're not paid to fix things and it works for you.

> Meanwhile, there's crap like this; a bad idea that leads to a bad commit accompained by bad grammar in the commit message.

Thanks, especially for the comment on my PR telling me that grammar sucks and I should fix it :3

> I've seen this project go literally nowhere for half a year, one version after another and nothing improves but some things get a little worse (broken process starting, removal of audio filtering, broken close button, etc). 

Well, yeah, there's been some tough time with people not having time/energy to review PRs & fix things. Perhaps you could help with that?

**Comment by Diadlo** [comment]
I'm against of `close to try` by default

**Comment by sudden6** [comment]
Me too

**Comment by zetok** [comment]
Seems like there is an "overwhelming majority" in favor of not changing the default, thus closing.

NB: for those who would want default to be changed, you probably would want some more public to take part in the "voting" – perhaps ask reddit or some other places for help to make this happen. I'm sure that you can think of something ;-)

**Comment by MHGhandour** [comment]
> Starting in tray will not be a default, since, lets face it, there are some shitty "DE"s out there that can't even get tray to work, which would make qTox unusable for the people that use those "DE"s.

I spent 3 hours trying to compile qTox again to make close to tray available, then i figured out that the option is in the settings. 
if i understand how tox work correctly, then tox won't send message if i am not online, so keeping the service on is crucial to make tox practical.
maybe you should put a dialog upon first launch to enable this option, or put a dialog upon first exit to choose default configuration.
