### ISSUE TITLE
Don't open chat window if the user "right"-click friend

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3205]
##### Brief Description

OS: Windows 8.1
qTox version: v1.4.0-2-g24a7f4d
Commit hash:  24a7f
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always
##### Steps to reproduce
1. In friends list, right-click friend.
##### Observed Behavior
1. A new window(friend chat) appears. Also, right-click menu appears.
##### Expected Behavior

Don't show/open friend chat window if the user 'right'-click it.
Instead, open only right-click menu.

[X] Multi Window - [X] Open each...

**Comment by ProMcTagonist** [comment]
you're double clicking or your mouse is broken

**Comment by zetok** [comment]
on r-click:
![on r-click](https://cloud.githubusercontent.com/assets/3148759/14807487/dc57933a-0b74-11e6-8618-e741ccf3ad6d.png)

**Comment by ghost** [comment]
@ProMcTagonist
Excuse me but my mouse is NOT broken.

@zetok
Looks like you're trying it on Linux. Try it on Windows 7. Can reproduce this issue on 3+ PCs.
Can you reopen this issue? Because this is NOT invalid.

**Comment by ghost** [comment]
https://i.imgur.com/Oxb3VnS.jpg

**Comment by ghost** [comment]
^ and chat window appears when I right-click (again, not LEFT click) red dot position.

**Comment by initramfs** [comment]
I can reproduce the issue on Windows 10 64-bit, looking into it.

**Comment by initramfs** [comment]
I think I may have fixed it but I have no way to test it (I haven't figured out how to compile under windows). Could someone either guide me how to compile under windows (I'm trying to use MSYS2 instead of MinGW) or help me test the fix? I don't want to commit/submit a PR yet since I have absolutely no idea if it works (all I know is that it doesn't break anything under Linux).

**Comment by Chiitoo** [comment]
**initramfs**,

I have some sort of a Windows build-system going, so I should be able to give it a go, if I get the change(s).  :]

**Comment by initramfs** [comment]
@Chiitoo If possible, clone my fork of the qTox repo from [https://github.com/initramfs/qTox.git](https://github.com/initramfs/qTox.git) and checkout the `fix-open-window` branch. Compile and test.

**Comment by Chiitoo** [comment]
Works for me.

A difference to Linux build: a subsequent right-click will open a new context-menu, on what ever is right-clicked (the empty space of the contacts are, or a contact), instead of only closing the previously opened menu (which is what happens on Linux).

Not a grave problem, but an inconsistency to say the least.  ^^

**Comment by initramfs** [comment]
@Chiitoo Thank you very much. Though that problem doesn't happen with me (the additional context menus in Linux) at least I know I'm on the right track.

**Comment by Chiitoo** [comment]
I meant that on Linux, when right-clicking for example contact 1, the menu appears.  If the next action is right-clicking contact 2, the 1st menu disappears and nothing else happens.

On Windows, when right-clicking contact 1, the menu appears, and when right-clicking contact 2 as the next action, the 1st menu disappears and 2nd opens immediately.

**Comment by initramfs** [comment]
@Chiitoo Right, I see what you mean now. Regarding that my commit didn't change a thing (checking out 5045c46 [master branch `HEAD` as of right now] yields the described behaviour in Linux). Anyways, I'll look into disabling the context menu from immediately appearing on Windows or enabling it on Linux.

**Comment by initramfs** [comment]
The inconsistent behaviour between windows/linux seems to be due to [QTBUG-5797](https://bugreports.qt.io/browse/QTBUG-5797) which affects Qt 5.6.0 and seems to already have been fixed in the upcomning revision. As such, I'm submitting a PR now that commits the fix I proposed earlier.

**Comment by Chiitoo** [comment]
I wonder if that was the link you meant it to be?  It's about a bug from 2009, affecting 4.6.0.  ^^

That I'm actually using the 5.6 development branch right now (reported as 5.6.1 by qTox) on Linux, while the Windows builds get 5.5 (5.5.1), so that could certainly explain some things... should have mentioned that earlier.  Sorries!

Definitely shouldn't hold back the pull request in any case.  :]

**Comment by initramfs** [comment]
Oh my, I didn't notice at all (thought it said 5.6 in the link). Anyways, is it possible to build qTox under Qt 5.6 for Windows (from the current master branch) and verify that the bug is still present?

**Comment by Chiitoo** [comment]
If only I had not been procrastinating and had the Windows builds on Gentoo already...

Currently, my Windows builds come from Linux Mint (Debian Edition), and I'm not sure I'd dare setting up Qt-builds there.  :V

I'll let you know if I get it done, though, if no one else gets to it before me.
