### ISSUE TITLE
Please add a "thumbs-up" button close to the message editbox area

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#3233]
Because it is the easiest thing to send to okay something (look at Facebook).

For example, it could be right next to the "smileys" button.

**Comment by zetok** [comment]
![already there](https://cloud.githubusercontent.com/assets/3148759/14934058/7d3d450e-0e9c-11e6-83b2-77fe3244191e.png)

Perhaps it needs to be moved?

**Comment by yurivict** [comment]
Move, that's what I mean. Need to be much easier to find.

**Comment by zetok** [comment]
Would the first "page" of emoticons be good enough?

Should only :+1: be moved, or perhaps :-1: too?

**Comment by yurivict** [comment]
I was thinking more like a floating button right over the "screenshot" floating button.

**Comment by sudden6** [comment]
I'm against giving the thumbs up emoji it's own button, I think it would clutter the interface.

Moving it to the first page of emojis would be good idea IMHO.

**Comment by yurivict** [comment]
This is a common situation. Someone sends something you just want to okay. Instead of 1. clicking on emoji button, 2. locating thumbs up 3. clicking it, I wanted to see just one button. Easy to use, and makes sense because this is an extremely common situation.

**Comment by Hasshu** [comment]
@yurivict No offense, but this is bloat.

If you just want to "okay" something, you can always use your keyboard.

**Comment by yurivict** [comment]
I didn't say that you can't. It's the number of clicks that is different.

**Comment by Chiitoo** [comment]
While I can somewhat understand the want for this, I do not personally feel it would be useful more than it would be clutter.

Then again, I have no use for the Send message, Smileys, Start video call, Start audio call, volume, and mic buttons, nor the Search area in the main window.  All they are to me, is waste of space, and I might even go so far as to remove them from my personal builds, but I probably wouldn't suggest removing them from everyone... and I know people hate options, so that's not an option either... heh...

Even though my view might seem quite extreme, I feel I can imagine a dedicated 'thumbs-up' button being a bit too much even for the general user as well (I did ask for some opinions that speak towards that, too).

Just my opinion, though.  ^^

**Comment by ProMcTagonist** [comment]
You can see Facebook chat for an example of the feature @yurivict is talking about. The thumb also blows up like a balloon if you hold down on it. 

I can tell you that if we implemented that the first thing users would think is that we ripped off a uniquely Facebook feature, because the thumb is a Like and that's why they implemented it. 

Something to consider.

**Comment by sudden6** [comment]
Very outdated and majority of comments seems to be against this.
