### ISSUE TITLE
Update mechanism in windows 10 fails every time

### ISSUE THREAD

**Issue by BackuPs** [qTox/qTox#3268]
##### Brief Description

I have Qtox on windows 10 version. The update message occurs.... the download occurs.. then the restart and then a error..

very annoying.

Pls fix

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce
##### Steps to reproduce
1. 
2. 
3. …
##### Additional Info

(links, images, etc go here)

---

E.g., include log located in `~/.config/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

More information on how to write good bug reports in the wiki:
https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
Could it be #3255 ?

**Comment by rodolpheh** [comment]
Did you try to launch qtox as an administrator before updating it ?
I will try tomorrow at work and will keep you updated.

**Comment by zetok** [comment]
> Did you try to launch qtox as an administrator before updating it ?

Well, it's supposed to work without that, but perhaps it would help.

**Comment by tux3** [comment]
It would help to know what the error message actually is, a log would be nice too if possible.

**Comment by rodolpheh** [comment]
Well, I just tried with the qtox portable I installed in February on Windows 10. I can't find anywhere to search for a new update and I don't have any message telling me there is a new update, even though the version I use is from February. It seems that the portable version doesn't update itself.

**Comment by BackuPs** [comment]
Hi

It is the same as #3255 ?but i am using 64 build. Your application is not signed for windows which is probably causing the issue.

Best regards,
BackuPs

**Comment by BackuPs** [comment]
Running as admin does not change anything. But i am running that version ! So it does not make any sense.

But i had the same issue with version 1.30. Could not update either with the same messages.

![qtox-update](https://cloud.githubusercontent.com/assets/6078370/15106115/56eec882-15c7-11e6-8c8c-ae73c34537e0.jpg)

See attached image for the error messages.
![after-restart](https://cloud.githubusercontent.com/assets/6078370/15106038/c990767a-15c6-11e6-8c21-b8e7993871b1.jpg)

Could you please create a correct working latest build so we can install it manually? Thank you !

**Comment by LittleVulpix** [comment]
Same thing here. Question is - why is C:\Program Files\qTox\qtox.exe even being launched? The actual qtox.exe file is in the 'bin' subdirectory. If you launch the qtox.exe in the qtox directory, it'll fail because it's missing all the DLLs around it (those that are in bin). The desktop shortcut that qtox installer creates also points to the bin\qtox.exe instead of just qtox.exe. So why is this one being launched?

**Comment by tux3** [comment]
This is probably fixed by #3279

**Comment by BackuPs** [comment]
is there a  new build then? I just downloaded the laste windows 64 installer and i have the same issue. Its telling me to update whereas i have the most recent update installed.

**Comment by tux3** [comment]
We'll release a 1.4.1 build today with the fix

**Comment by BackuPs** [comment]
Thanks ! Keep up the good and great work  !

**Comment by rodolpheh** [comment]
Good news then. I will try with the latest version tomorrow but it seems that the portable version doesn't check for a new update. At least, my old version from February (v1.2-353-gef5b9b8) doesn't. I may open a new issue for this since it's unrelated to the current issue.

Dirty edit : I just looked at the latest commit (1 hour ago) and it seems that some of the code for the portable version have been changed so i'm pretty optimistic about solving the issue raised above ;)

**Comment by tux3** [comment]
@rodolpheh If you have an old version, it's possible the updater had some different problems at the time, so I'd recommend using the v1.4.1 installer to be sure you have all the fixes.

**Comment by rodolpheh** [comment]
@tux3 Yes you are right but I did download the latest version this morning and it wasn't updating either. I did not mention that because, as it was the latest version at this time, it could have been a normal behavior. As you said (and also in my comment above), this must now be fixed with the 1.4.1 commited one hour ago.

I just tried the latest build (632) from build.tox.chat and the version shown is v1.4.0-63-ge5d146f. Is a new one coming up ? I may stop spoiling the thread now and will come back with more useful informations as soon as I get some.

**Comment by tux3** [comment]
@rodolpheh 1.4.1 is currently building, I'll push it to the update servers by the next hour if everything goes right, but it's not online yet :)

**Comment by tux3** [comment]
1.4.1 is out now in the usual places.

**Comment by LittleVulpix** [comment]
Worked here on (previously broken) w10 and w7!

**Comment by zetok** [comment]
Well then, since it works, closing.
