### ISSUE TITLE
Malicious user can send a virus through qTox.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3271]
1. Set infected JPG file(e.g., code inside JPG file,'1') as a avatar.
2. Peer user will get it.

To counter this issue:
qTox need to filter(remove EXIF and return clean file) avatar image file.

1
http://php.webtutor.pl/en/2011/05/13/php-code-injection-a-simple-virus-written-in-php-and-carried-in-a-jpeg-image/

**Comment by sudden6** [comment]
The case linked doesn't really apply for qTox, because there has to be a bug in the qt image library for this to work (Of course could be, but it's more unlikely ). In your sample case the image is being processed by the language interpreter directly, which is much harder to achieve in C++.
I'm still letting this open tough, if someone can better explain this, or has a different opinion.

**Comment by tux3** [comment]
Since we don't use PHP in qTox, putting PHP code inside your images is harmless, we won't interpret it, so nobody gets hurt :)

**Comment by tux3** [comment]
Ah, if this is meant to be a discussion, let's keep it open.

**Comment by sudden6** [comment]
@tux3 If we aren't already removing EXIF stuff (didn't look yet) I think we should do so. Else I think this Issue can be closed.

**Comment by tux3** [comment]
For avatars we already lose EXIF just by the mere fact or having to rescale, convert, and send them through toxcore, so I think this is taken care of.

**Comment by sudden6** [comment]
yep, just checked, PNG doesn't store that much metadata.

**Comment by zetok** [comment]
re: metadata: #1912
