### ISSUE TITLE
Same profile running on different PCs.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#3277]
1. Running qTox with portable mode.
2. Zip it, and transfer it to another PC.
3. Run qTox.
4. 2 qTox with same profile are running via internet...

Question.

a. Isn't this a security problem?
b. How about alerting user if the same qTox is detected on the qTox node network? (compromised!!)

(about "b"; possible attack)
0. She invited attacker(BF?) to her house.
1. Attacker steals her qTox profile to his USB, while she's far away from her PC.
2. Attacker gone home.
3. When she's using her qTox, attacker opens her qTox using his USB on his trashable PC.

**Comment by ghost** [comment]
or
c. When new qTox session connects to the network, disconnect harshly older qTox session, and show alert to old qTox session, starting with "Someone is using your ID".

**Comment by ghost** [comment]
(I found this issue when I'm moving my data to my another PC.)

**Comment by zetok** [comment]
> a. Isn't this a security problem?

If you want security, use an encrypted profile.

> b. How about alerting user if the same qTox is detected on the qTox node network? (compromised!!)

Not doable, and it's not considered to be wrong. I.e. someone might want to run multiple instances of the same profile.

> c. When new qTox session connects to the network, disconnect harshly older qTox session, and show alert to old qTox session, starting with "Someone is using your ID".

Not doable.

Thus closing.

**Comment by ghost** [comment]
Let's say I encrypted qTox profile, and someone steal it, and cracked it by bruteforcing.
I call this a security problem because this person can read my message when I'm using qTox.

> Not doable

Really? Isn't qTox is a P2P?
Only "one" peer/"one" real ID should exist in 1:1 chat.

**Comment by zetok** [comment]
> I call this a security problem because this person can read my message when I'm using qTox.

No, they can't. They can receive messages for you, but then again, you won't see those messages. Note that this works this way currently, and it's possible that support for multiple devices will change current behaviour.

> Really? Isn't qTox is a P2P?

Yes. Precisely because it's P2P.

**Comment by zetok** [comment]
> Let's say I encrypted qTox profile, and someone steal it, and cracked it by bruteforcing.

Oh, and this too isn't happening. :)

**Comment by tux3** [comment]
> Isn't this a security problem?

The security problem is really if you let untrusted people get access to your computer and copy your files, because if that happens there is nothing qTox can do to protect you – we can't know if it's you using your computer or a bad guy.
You should use an encrypted profile with a password if you don't want people to be able to steal your account.

> How about alerting user if the same qTox is detected on the qTox node network? 

Unfortunately there's no straightforward way to do this in qTox, unless toxcore starts to support this feature, so we currently can't do that.
If you want to check that nobody stole your profile, you'd have to create a new friend account or ask your friends, if they see you online while you're not connected it must be someone else.
You should try opening an issue on the toxcore repo.

**Comment by zetok** [comment]
@tux3 except that this can't even be reliably solved in toxcore – if someone would have a will, they'd just modify their toxcore in a way that would simply disable that functionality.

Also, due to the way in which DHT works, that kind of "feature" would cause false-positives all the time…

And scarring users for no reason wouldn't be a good thing.

**Comment by ghost** [comment]
I'm a programmer but I'm not familiar with P2P programming.

> They can receive messages for you, but then again, you won't see those messages.

This means,
1. Anyone(Y') can become "you" by stealing your qTox account files(Y).
2. When your friend, B, send a message, Y' or Y will receive a message. (not "and" but "or")
3. B doesn't sure he's talking to Y' or Y.
Am I right?

> Yes. Precisely because it's P2P.

"Because" it's P2P, why qTox can't detect duplicated ID?

For example, Tor(current version):
1. A advertise his xxxxxxxxxxx.onion.
2. B stole A's keys, and advertise himself as xxxxxxxxxxx.onion(same).
3. C access to xxxxxxxxxx.onion.
4. Tor route it to "B", cutting off "A". (no access goes to A)

Another example, BitTorrent:
1. Download Linux ISO via torrent.
2. You'll see peers from "peer" tab.

> Let's say I encrypted qTox profile, and someone steal it, and cracked it by bruteforcing.
> Oh, and this too isn't happening. :)

Yes, I'm talking about possible "if" story.
But cracking password with highend GPU is very easy nowadays...

**Comment by tux3** [comment]
> except that this can't even be reliably solved in toxcore – if someone would have a will, they'd just modify their toxcore in a way that would simply disable that functionality.

That's probably true, but I couldn't say since I don't know the toxcore internals well enough :)

> Am I right?
1. is right only if you assume that the files are not encrypted, otherwise, that's correct.

> "Because" it's P2P, why qTox can't detect duplicated ID?

There are many different ways of doing "P2P", as I understand it the architecture we use currently doesn't allow this.

> But cracking password with highend GPU is very easy nowadays...

We don't allow passwords shorter than 6 characters, and we use a fairly expensive key-derivation function, so unless your password is exceptionally weak or in a dictionary, cracking it would be very expensive.
I highly recommend you use an encrypted profile with a strong password/passphrase if having your account stolen is something you're afraid of.

**Comment by zetok** [comment]
> This means,
> 1. Anyone(Y') can become "you" by stealing your qTox account files(Y).
> 2. When your friend, B, send a message, Y' or Y will receive a message. (not "and" but "or")
> 3. B doesn't sure he's talking to Y' or Y.
> Am I right?

Yes.

> "Because" it's P2P, why qTox can't detect duplicated ID?

That's up to toxcore, and toxcore doesn't have a reliable way to do it given the nature of DHT.
https://zetok.github.io/tox-spec/#different-ipports

> But cracking password with highend GPU is very easy nowadays...

Again, not really doable :)

Wealthy governments/corporations could do it, provided that they would pour millions of dollars into brute-forcing a single password, but then again, they have way better methods of "cracking" the passwords:
![xkcd security](http://imgs.xkcd.com/comics/security.png)

Edit: oh, and ↑ is only possible if you use only shortest password possible – provided that your password is long enough, even that wouldn't work…
