### ISSUE TITLE
[How?] Add "Friendly Network Peer"

### ISSUE THREAD

**Issue by newnym** [qTox/qTox#3357]
I have 2 PCs. Both are running qTox with restrictive firewall.
Currently, both PCs connect to the internet via Tor.

A--->Tor--->B

If I could add B's IP:PORT(which is qTox listening port, if exist. And changing B's PORT will be gr8) to A, it will be

A=====>B

and this will greatly improve my file sharing speed.
So, how can i do it?

My Strict firewall rule(i can't):
1. I accept only TCP connection. If the PC connect to the internet, it must use Tor(iAmA Tor non-exit node supporter!!!).
2. I can open a hole for network. Not for internet(incoming always close).

**Comment by newnym** [comment]
- absolutely no uPNP support. Just allowing plane TCP with acceptable port.

**Comment by zetok** [comment]
> So, how can i do it?

You can't. That kind of stuff isn't supported by toxcore. With that being said, toxcore tries to automatically connect to peers on LAN.

> Currently, both PCs connect to the internet via Tor.

Working around your internet setup doesn't seem like a good idea. You should either adjust your firewall rules so that qTox could connect directly automatically, or use it as it is.

Thus, closing.
