### ISSUE TITLE
[Feature request] pw field when adding / changing password should indicate whether CAPS-LOCK is on

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3378]
##### Brief Description

Currently only login page shows indicator of CAPS-LOCK being on when typing password – it should be available also when changing / adding a password on profile page.

Reproducible: Always
##### Steps to reproduce
1. Turn on CAPS-LOCK
2. Click on `Add` / `Change password` on profile page
##### Observed Behavior

Password filed doesn't have caps-lock indicator
##### Expected Behavior

CAPS-LOCK indicator should be shown
##### Additional Info

Related: #3245

**Comment by b4n** [comment]
Same applies to the "load profile" login screen field.  Only the "New profile" fields show a capslock warning.

**Comment by b4n** [comment]
I've got a fix for that, but I made it on top of #3383 because it changes API, so I'd rather wait for that one to be dealt with first.

However, it's not as pretty as I'd wish it would be.  Ideally, I guess we should have a custom QLineEdit widget for passwords that does it itself, but:
1. I don't know if it'd be possible to use to from _.ui_ definitions?
2. I failed to find an encapsulated way to get notified when capslock changes.  Current way (from #3257) is on the `::event()` virtual method on the top level (window), so that's not very encapsulated.
   
   Encapsulating would be interesting even without 1 above, because it would avoid the need for a caller to manually call `::updateIndicator()`.

But as I'm totally new to Qt, maybe someone more experienced would know.
