### ISSUE TITLE
New option in Preferences for the format of screenshot pictures

### ISSUE THREAD

**Issue by Saaaam** [qTox/qTox#3395]
Hello,

The functionality to send a screenshot is quite good. But it could be even better if the user could have the choice to select if the picture is sent as a .png or a .jpg, depending how wanted is the quality (png : good quality, "big" size / jpg : less quality, "little" size).

This option could be chosen in the Preferences…

**Comment by zetok** [comment]
Is there a use-case for cluttering settings with an option for lower quality screenshots?

**Comment by Chiitoo** [comment]
I have been meaning to suggest (or try and implement) this as well.

A common use-case could be a user simply preferring smaller file size (either due to slow connection speed or just because they prefer a smaller file size).

I can't say how common such a use-case actually is, but it has been something I've discussed with a friend while using qTox and thinking of improvements for it.

**Comment by zetok** [comment]
Depends on #1069

**Comment by zetok** [comment]
How much bandwidth/space would be saved with/without jpg?

Wouldn't using webp be better than jpg for lossy format?

**Comment by zetok** [comment]
Needed info not provided for over a month, thus closing.
