### ISSUE TITLE
Put a link to the new jenkins in the README pls

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#347]
So we can continue to distribute qTox

Also I dunno if it would help, but stqism uses https://github.com/jordansissel/fpm for utox

**Comment by tux3** [comment]
It's not quite ready yet, and the idea would be to have Jenkins make automated releases on GitHub directly.

The 'new jenkins' actually runs on my laptop, since I don't have a dedicated server for Tox (anymore), so it's not exactly up at all times (but it's up everytime I commit, so I believe it should work as a CI).

**Comment by tux3** [comment]
The first version of Jenkins's automated releases is ready.
For the moment all the releases can be found at https://github.com/tux3/qTox/releases, but there isn't a link to the latest version for each OS yet.

My jenkins is temporarily reachable at mlkj.bounceme.net:8080
