### ISSUE TITLE
Change base font settings/behaviour

### ISSUE THREAD

**Issue by ovalseven8** [qTox/qTox#3474]
At the moment, if someone changes the base font in the qTox settings, the changes are only active for new communication. Because of that, the appearance is inconsistent.
It's required to restart qTox for full consistency.

I don't think this is a nice solution concerning UX.
So, I have two suggestions:
1. Change font immediately and completely
2. Change font **only** after restart (Popup like "To make your changes active, please restart qTox)

**Comment by antis81** [comment]
> I don't think this is a nice solution concerning UX.

First of all, it is a solution! And it sports absolutely predictable behavior! So, if you like it or not: That's the way it is!

The problem here actually is:
The basis implementation for qTox chat messages (and pictures, and file transfers, etc.) copies the same default style sheet over and over with each chat message! Someone has chosen for an "item based" implementation - i.e. each item also contains its complete rendering information. What you're asking for requires actually to reimplement basically each and every single line of the chat message code and transform it into a chat model. This requires a whole day for a rewrite.

So the question is:
Who has actually time to implement a chat model and provide information through the `data` methods?

**Comment by zetok** [comment]
> Someone has chosen for an "item based" implementation - i.e. each item also contains its complete rendering information. What you're asking for requires actually to reimplement basically each and every single line of the chat message code and transform it into a chat model. This requires a whole day for a rewrite.
> 
> So the question is:
> Who has actually time to implement a chat model and provide information through the data methods?

Before that, it would be good to consider performance side. I.e. current chatform was made this way in order to be somewhat able to handle abuse by users (e.g. sending hundreds of messages over some period of time).

Currently, it should be able to handle at least a few thousands messages, perhaps way more on a powerful box.

IIRC previous model treated messages as chat, rather than separate items, so.

**Comment by antis81** [comment]
@zetok 

> Currently, it should be able to handle at least a few thousands messages, perhaps way more on a powerful box.

In this context, I like to point to a self-made demo and shamelessly state, that there probably isn't a better example out in the wild:
Please, have a look at the [table model example](https://github.com/antis81/QtModelViewDemo). It allows a direct comparison between the techniques, while showing, how it is done right. The builtin `QTableModel` used in the example is mainly meant to quickly get started. Usually it is much faster (yet a bit effort to code it), to inherit and implement a `QAbstractItemModel`.

FYI: this can easily handle 100.000 items and, if optimized, even millions.

And the `QGraphicsView` isn't any problem btw. It actually can be mapped to the model and everything's fine.

**Comment by jessica181920** [comment]
Changing base font is now retroactive and applies to all previous communications. No longer an issue and can be closed.
