### ISSUE TITLE
Inform that other qTox instance is already running, and how to launch another

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#3483]
##### Brief Description

When user tries to open second qTox instance when there is already one running, it doesn't launch and user doesn't know that it's possible to run multiple instances, or thinks that there has been a regression in qTox.

Thanks to @antis81, from https://github.com/tux3/qTox/issues/2449#issuecomment-230706166:
# 

Anyway the behaviour irritating and users expect that "simply to work". So we should at least display a `stderr` message and dialog, that another qTox is running - for example:

```
"Another qTox instance is already running. If you want to start a second instance, please start with a profile (qTox -p <profile name>). 
```
# 

Note: should be `qtox -p <profile name>`

**Comment by anthonybilinski** [comment]
This is a strange one for me, because I was initially confused when I tried to open a second instance and couldn't, and I don't think this stdout message would help me if I was running qTox launched from GUI, as most users normally would be. This made me think the behaviour was wrong, but after talking to a friend who uses qTox by having it exit to tray, and clicks buttons on his sidebar in gnome which would normally open a new instance, he finds the current behaviour perfect since clicking the icon or searching and opening qTox just pops up his trayed instance. So I applied the recommended logging, input welcome if there's a better alternative.
