### ISSUE TITLE
Add web services to chat context menu

### ISSUE THREAD

**Issue by abbat** [qTox/qTox#3511]
What do you think about to add some services like "[Google](https://www.google.com)/[Yandex](https://yandex.com)/[Bing](https://www.bing.com)", "[Google Translate](https://translate.google.com) / [Yandex Translate](https://translate.yandex.com)", "[Wikipedia](https://en.wikipedia.org)" to chat context menu? Use case: user see unknown word or phrase, select it and on right click can search term, translate (qtox knows current user locale) and so on.

**Comment by zetok** [comment]
Sounds like something that could be done via plugins once there'll be support for that.

Things like that come and go, and it might not be the best idea to bake into qTox stuff that relies on ~centralized services that rely on revenue generated from scrapping user metadata.

Aside from that, translation services usually don't like when one uses them in software – there's e.g. [`translate-shell`](https://www.soimort.org/translate-shell/), which breaks from time to time, since services it is using don't like stuff actually using them.

**Comment by sudden6** [comment]
I'm also not a really fond of the idea of integrating this directly into qTox. With plugins yes, directly no.

**Comment by sudden6** [comment]
Probably wont be implemented without plugins, closing for now.
