### ISSUE TITLE
build.tox.chat 502 Bad Gateway

### ISSUE THREAD

**Issue by DX37** [qTox/qTox#3677]
What happen?

**Comment by Diadlo** [comment]
~~How it related with qTox?)~~
Better ask https://github.com/Tox/tox.chat/ or on freenode IRC

**Comment by zetok** [comment]
> How it related with qTox?)

windows builds

cc @nurupo

**Comment by chileaus** [comment]
How come I get 502 Bad Gateway when trying to download the software

**Comment by nurupo** [comment]
Should be fixed now. Jenkins sometimes (rarely) goes 502 and I'm not sure why.

**Comment by nurupo** [comment]
Ok, the issue was that Jenkins broke itself after an automatic update. It's more of an upstream issue with Jenkins than an issue on our end, but I will try to see what I can do, since having Jenkins down for any reason is bad for us. A simple watchdog would likely do the trick.

Thanks for emailing me about the issue (through github notifications).

**Comment by Diadlo** [comment]
@nurupo Thanks for fix
