### ISSUE TITLE
Video calls show no video

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#368]
When video calling I cannot see the other person's webcam and vice versa, video previews work fine.

**Comment by tux3** [comment]
I assume you're on windows ?

**Comment by bricky149** [comment]
Always on Windows I'm afraid. :P

**Comment by agilob** [comment]
Same on Linux. Video call qTox <-> qTox, both clients had blank video window.

**Comment by dubslow** [comment]
Some camera changes were just merged, could you guys report if they fixed anything?

**Comment by agilob** [comment]
Works perfectly \o/

**Comment by zetok** [comment]
On 4e9d802d1fa622890ead911a861bd3e7f2b2955c I can't see any image in video preview.

After launching qTox I have seen for a short time video from cam, part of it was cut off. Then I've tried to change resolution, which didn't seem to go well, since that there was just black square where video should be.

When launching qTox a lot of:

```
VIDIOC_QUERYMENU: Invalid argument
```

then:

```
(QSize(160, 120) ,  QSize(320, 240) ,  QSize(960, 544) ,  QSize(640, 360) )
```

probably after this I couldn't see any video:

```
VIDIOC_QUERYMENU: Invalid argument
ASKED  11  VAL  0.336842
Core: Got same avatar info from "GroupBot"
ASKED  10  VAL  0.734375
ASKED  12  VAL  0.56
ASKED  13  VAL  0.555556
Creating pbo, program
Change resolution  QSize(-1, -1)  to  QSize(0, 0)
Resize pbo  57600 bytes (was 0 ) res  QSize(160, 120)
Change resolution  QSize(0, 0)  to  QSize(160, 120)
Suspend
Resume
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
```

**Comment by dubslow** [comment]
Just pushed some video changes. Can anyone comment on this?
