### ISSUE TITLE
Public key length is limited in "Show details"

### ISSUE THREAD

**Issue by Kron4ek** [qTox/qTox#3688]
##### Brief Description

OS: Arch Linux (also occurs on Windows)
qTox version: 1.5.1
toxcore:  3747
Qt:  5.7.0

Reproducible: Always
##### Steps to reproduce
1. Open "Show details" window
2. Look at the length of the public key
##### Observed Behavior

Public key length is limited to 64 characters, but the real length may be longer (for example, my ID have 76 characters).

**Comment by zetok** [comment]
Nope. PK is 64 chars long. PK ≠ ID.

**Comment by Kron4ek** [comment]
Oh, ok.

**Comment by ProMcTagonist** [comment]
@Kron4ek You need the Tox ID to add someone, which includes the Public Key, NoSpam, and a checksum. Toxcore doesn't share the Tox ID to friends, just the Public Key, because people can change their nospam at any time, and since it's to change your Tox ID, automatically sending it to people wouldn't be a very good idea. 

There will be a way to share friends among friends at some point.
