### ISSUE TITLE
Debian repo still being updated?

### ISSUE THREAD

**Issue by Fred-Barclay** [qTox/qTox#3698]
Hello mates! I used to get qtox updates from https://software.opensuse.org/download.html?project=home%3Aantonbatenev%3Atox&package=qtox every couple of days, but I just noticed that qtox hasn't been updated on my machine since about August 17. Is this still the correct repo to use, and is `201608172222~f05b7e0` the latest version?

I also see there's a `qtox-alpha` package in the repo; what's up with that?
Cheers!
Fred

**Comment by zetok** [comment]
#3470 – basically `qtox` is now a stable, release package, and `qtox-alpha` was made to follow current master.

Generally, things on current master are stable, but sometimes there might be regressions. Stable release is for people who really don't like encountering regressions, and they're fine with waiting a bit longer for fixes that are already on master.

@abbat could version on `qtox` package be changed to something like `1.5.0`, since current shown version confuses people?

**Comment by abbat** [comment]
If I set only `1.5.0` it breaks upgrade process because `1.5.0` < `201608172222~f05b7e0`. I can set version in tail instead git revision (for example `201608172222~1.5.0`). Also stable release needs update time to time (updating statically linked libtoxcore, ffmpeg and so on) - version need increment part to each build.

**Comment by zetok** [comment]
I guess tail would be fine.

> Also stable release needs update time to time (updating statically linked libtoxcore, ffmpeg and so on) - version need increment part to each build.

Is something like `201608172222~1.5.0-0` → `201608172222~1.5.0-1` an option? IIRC Debian seems to be doing something like that?

I just wonder though – are really binary package managers too stupid to be able to handle a "downgrade"?

**Comment by abbat** [comment]
> Is something like  201608172222~1.5.0-0  →  201608172222~1.5.0-1  an option? IIRC Debian seems to be doing something like that?

We can just increment date `201608172222~1.5.0` → `201609081444~1.5.0`

> I just wonder though – are really binary package managers too stupid to be able to handle a "downgrade"?

Managers do exactly you want. If you want to upgrade package and no package with newer version in repository → nothing to upgrade (but you can specify exact package version to install / downgrade). 

However Ubuntu Launchpad rejects packages with lower version than already exists in repository.

**Comment by zetok** [comment]
> We can just increment date `201608172222~1.5.0` → `201609081444~1.5.0`

Oh, this way. Why not.

> Managers do exactly you want. If you want to upgrade package and no package with newer version in repository → nothing to upgrade (but you can specify exact package version to install / downgrade). 

Err. Portage handles version downgrades just fine (at least when it comes to package itself, there's a little bit more of problems when it comes to packages that depend on versions, but not much, and that's something that only people maintaining affected packages would be concerned). So if a newer version with lower version number came out, portage would make no fuss over it.

**Comment by abbat** [comment]
[qtox_201609091622~v1.5.1](https://build.opensuse.org/package/show/home:antonbatenev:tox/qtox) - OK?

**Comment by zetok** [comment]
Yep, thanks :)
