### ISSUE TITLE
Roadmap (feature freeze?)

### ISSUE THREAD

**Issue by iphydf** [qTox/qTox#3742]
qTox should have a roadmap outlining priorities and in what order things will be done by whom. The roadmap should be to roughly 2-4 weeks granularity. I would suggest making code quality a high priority, meaning no additional features should be implemented before that is done. (This is just a suggestion though, and your leadership can decide otherwise).

TL;DR: qTox needs a plan.

**Comment by zetok** [comment]
@antis81
@Diadlo 
@initramfs 
@sudden6 
What do you plan to get done in next 2-4 weeks?
Anyone else?

**Comment by Diadlo** [comment]
1. Finish toktok/toxcore migration, 
2. If ui/redisign will be done, start refactor with removing standalone classes
3. If 2. will be done, create unit tests

**Comment by initramfs** [comment]
1. clang-format (and general coding guideline rules)
2. A/V code overhaul (not sure if I can get this done in 2-4 weeks though)
3. Add traditional chinese translations to qTox (done concurrently with 2)

**Comment by sudden6** [comment]
1. finish #3737 and see if it's possible to ship qTox without emoticons compiled in
2. help with toktok/toxcore migration and ui/redesign if I can

**Comment by zetok** [comment]
Ok, so things that can be achieved this month:
1. clang-format (and general coding guideline rules) – https://github.com/qTox/qTox/milestone/8 , deadline 1 month from now
2. Add traditional chinese translations to qTox (done concurrently with 2) – https://github.com/qTox/qTox/milestone/11 , deadline 1 month from now
3. finish #3737 and see if it's possible to ship qTox without emoticons compiled in – https://github.com/qTox/qTox/milestone/12 , deadline 1 month from now

Other things:
- [UI refactor](https://github.com/qTox/qTox/milestone/6) – doesn't sound like something that could be done in a month – I've set deadline 2 months from now.
- [TokTok/toxcore migration](https://github.com/qTox/qTox/milestone/7) – perhaps could be done within a month if there will be a release without delays – for now, deadline is set to 1 month.
- [Unit tests](https://github.com/qTox/qTox/milestone/9) – no deadline, since work on this will begin once UI refactor is done
- [A/V overhaul](https://github.com/qTox/qTox/milestone/10) – analogous to the point above

People who are to work on milestones that are yet to be, set appropriate deadlines – minimum 1 month long, if you finish earlier just close the milestones :)
Also assign relevant PRs/issues to the milestones – I've assigned PRs, but didn't do it for the issues.

**Comment by agilob** [comment]
I just took a look at qtox again, I think now a major problem is number of open PR awaiting. Most of them are basically frozen, not being merged, not being updated, some of them require merge/rebase on master to fix conflicts. I think the priority should be to merge or reject them asap.

**Comment by zetok** [comment]
> (…) I think now a major problem is number of open PR awaiting.

Right. What is a real problem though, is not enough people reviewing PRs, which can lead to slower merges.

> Most of them are basically frozen, not being merged, not being updated, some of them require merge/rebase on master to fix conflicts. I think the priority should be to merge or reject them asap.

ATM out of 9 PRs that could possibly be merged only 3 have valid LGTM – as such they'll be merged quickly.

It doesn't hurt to keep PRs open until something that could deprecate them gets merged.

**Comment by sudden6** [comment]
This roadmap is outdated by 2 years
