### ISSUE TITLE
[Feature request] Multiple chat windows

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#383]
User should be able to use many chat windows at once. "Detach" and reattach chat windows to main qTox window.

Idea:

There's main window, which has contact list and beside it chat window. Chat window can be "cloned" into separate window. Both windows would display same content of chat, "cloned" window would show only content of chat with one peer selected at time of cloning. Main window would still allow to freely switch between chats.

When there will be support for minimizing to tray, user should have an option to either minimize just main window, or main window and all "cloned" windows to tray.

**Comment by msteinbeck** [comment]
+1

**Comment by iav** [comment]
And a way to set something like "remember separated status and widow size and position" on a per-contact basis - to not drag all chats by sides on every new program start

**Comment by Chiitoo** [comment]
Teegrins!

Been meaning to suggest something similar for a long time!  Just got registered, finally, so I'll add my thoughts here, as it's almost the same thing (but not quite; let me know if it should be a separate issue).

Not only would I like to be able to have the main-window (contact list) separate from the chat-windows, I would also like to have the option for a tabbed chat-window.  I've used KMess since 2010, which I can get to pretty much just as I want it, and have gotten quite used to it indeed!

I do not want the main-window (that has the contact list) to have a chat-window at all.

Does this seem like a possible thing to do, or should it be left for another project?  (I have the want to start creating this vision myself, but it will probably take at least ages, if not longer, to get to anything useful!)

Thanks!

**Comment by dubslow** [comment]
It's probably possible, but at the moment there are so many features to add and bugs to fix that it's not particularly a priority.

**Comment by tux3** [comment]
Qt being Qt, this should actually be fairly easy to do.
We'd just need to modify GenericChatForm to not add itself to the main layout. (Note that we can't have two cloned widgets displaying the same thing as described in the OP with this method.)

Proof of concept, with just two lines of code changed:
![pic12](https://cloud.githubusercontent.com/assets/5155966/4756185/880f1c2c-5acb-11e4-8ba6-3fab9d19eda6.jpg)

Although, @dubslow is right that this isn't exactly a priority at the moment.

**Comment by Chiitoo** [comment]
I figured it should be relatively simple (Qt being Qt), and was already poking around a bit the other day (well actually I was poking at Qt GUI by nurupo; perhaps I'll take a whack at qTox next!).

Thanks for that.  I agree with it not being a top priority, as there certainly are more important things to get done!  Just knowing that people aren't at least /against/ the idea is reassuring, and will possibly help me with deciding where to tinker as well.

**Comment by zetok** [comment]
Closing, since #1938 was merged.
