### ISSUE TITLE
Groupchat invites don't work on Windows

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#394]
I have multiple reports of this from people using Github releases, at least one of them was the most recent as of now, and I assume the other was since he also DLed it in the last 12 hours. I don't know what the issue could be.

@sergeevabc

**Comment by dubslow** [comment]
@tux3, it occurred to me that this is exactly the symptom fixed by https://github.com/tux3/qTox/commit/8aba636c638732541af0cde7a4996b3172b777ce, is it possible that something related to that isn't working on Windows? Even more drastically, is it possible that the core in the Windows binaries is out of date?

(Also unrelated, but you can delete the newsettings branch)

**Comment by tux3** [comment]
> is it possible that the core in the Windows binaries is out of date?

Yes, that's very much possible. 
The Windows toxcore isn't currently updating automatically.

**Comment by tux3** [comment]
This should be fixed in the latest qTox Windows release but I haven't had the time to test it yet

**Comment by dubslow** [comment]
@darkman088

**Comment by darkman088** [comment]
@dubslow Hello, it is not a problem to run qtox from terminal, what shall I do ? Open cmd.exe and simply launch qtox.exe there ? Let me know...

**Comment by dubslow** [comment]
Yes please. :)

You'll find it convenient to find your qTox directory in Explorer, right click and choose "Open Terminal here" or maybe "Open command prompt here" or whatever similar option.

**Comment by darkman088** [comment]
Hello, sorry, but I see no output, it gives me back the prompt and doesn't show any messages! Sorry, it is not like in Linux...

**Comment by dubslow** [comment]
Got a report that it's not working on OS X, as well as a report that it works fine on Windows.

So now I'm really confused.

Edit: They're being sketchy for me too now, though I've never had to try more than twice. I blame @irungentoo. (I'd be willing to assist debugging.)

Edit2: Turns out the OS X report was someone running toxgui from way back when. I'm still needing to reinvite though.

**Comment by darkman088** [comment]
Just a small comment from my side - it's quite hard to find the latest release of a tox client. The guys from uTox for example, FINALLY made this damn ringtone !! BUT I had to ask especially from where to download that version, in order to get it. At the official download link they still have (or had) an older version...

**Comment by dubslow** [comment]
Could this be related to the fact that the widget isn't created until the first group message, rather than on invite?

When I've noticed being required to be invited twice, I don't get the error message that Widget is supposed to throw on failing, which means it's working.

But it is supposed to be created on namelist change, which should immediately happen on joining...

**Comment by dubslow** [comment]
I just had issues with GroupBot. The invite that worked was when I did "invite 0" instead of "invite". Others have reported that even "invite 0" fails however.

https://gist.github.com/dubslow/659cb8dce3d3cca2122b

@irungentoo It would seem that the core issue (no pun intended) is sometimes never getting any namelist callbacks upon joining. Do you have any idea why this might be?

**Comment by dubslow** [comment]
@darkman088 can you confirm one way or the other if invites failing happens with groups other than groupbots'?

**Comment by darkman088** [comment]
Hi dubslow,

kindly describe the exact scenario and what do I need in order to simulate this with groups other
than groupbots and I will try it out and report back... How to initiate this with groups other than
groupbots' ?

**Comment by dubslow** [comment]
Just create your own groupchat, and invite people to it. Or have them invite you to their own groupchats.

**Comment by darkman088** [comment]
Hi dubslow,

I have created a groupchat and invited somebody to it, who is using uTox. He was able to see the
Groupchat #0 contact on the left side, but it doesn't have a green point and he didn't receive anything I wrote him there. He can't write me either...
So, that's the result, if I can do something more, just let me know!

Now I would like to say a few words about qTox. You guys, are making INCREDIBLE progress !!
Last time I downloaded qTox was maybe a week ago and now you have added SO MUCH functionality !!
The Settings Window is now tabbed, with so much more features! I have tested the ringtone and it is 
working indeed!!! Just one more small point - it just rings something like a few tones and then there is silence and shortly afterwards, the call drops. It would be nice, if you could make it sound for a longer time. Also, when dialing somebody, he has to be really quick in picking up, because in a few seconds, the call ends automatically and causes a missed call...
I already described that situation and the answer was, that it is a toxcore problem. Can you please have a look into it and if you really can't do nothing, let me know where can I open a new issue about toxcore. One more point - when somebody is calling me and I can't take the call, it would be nice to be able to click some button and reject the call...

Many many thanks and if I can do something again in order to support you - don't hesitate to let me know :-)

**Comment by msteinbeck** [comment]
-> and if I can do something again in order to support you - don't hesitate to let me know

User experience is one of the most important input :). Thank you for using qTox.

**Comment by darkman088** [comment]
Yeah this is why I am spending so much time in writing here and I was soooo persisting on the issue with the ringtone!! And it IS worthy, I see how much this program grew just in a week! Imagine in 1 year!!!!
JUST KEEP THE GOOD WORK GOING !!! RESPECT !!!!!

**Comment by dubslow** [comment]
> it just rings something like a few tones and then there is silence and shortly afterwards, the call drops. It would be nice, if you could make it sound for a longer time.

Like I said earlier, the ringtone I added was a just a hack -- upon receiving call, ring once, where ideally it should ring until the ringing time is up, like Skype... but that's a bit more involved.

And about the groupchats, what about the reverse, where he invites you to a groupchat? Do you see a new groupchat when he invites you? Although the other way failing is also a problem... please add dubslow@toxme.se, and though I can't help at the moment, when I have some time in a few days I'd like to try some things with you when we're both on.

**Comment by darkman088** [comment]
Hi dubslow,

when the other party, who is using uTox intiates a group chat, it works. I see the new window and we can really chat there... Thanks!

**Comment by dubslow** [comment]
Really? So you're having the exact opposite problem from what this thread is about... (still an appropriate place to talk though)

**Comment by darkman088** [comment]
Looks like this, sorry if it's a mess, but this is what the experiments showed...

**Comment by zetok** [comment]
Invite just failed for me, so it may be an indicator that it's not system specific, although for some reason may seem to happen more frequently on wondows(?)

Log, first invite fails, then second one is successful:

```
"Core: Group invite by 5"
"Trying to join groupchat invite by friend 5"
"Core: Group invite by 5"
"Trying to join groupchat invite by friend 5"
"Core: Group namelist change 1:0 0"
"Core: Group namelist change 1:0 2"
"Core: Group namelist change 1:1 0"
"Core: Group namelist change 1:1 2"
"Core: Group namelist change 1:2 0"
"Core: Group namelist change 1:2 2"
"Core: Group namelist change 1:3 0"
"Core: Group namelist change 1:3 2"
"Core: Group namelist change 1:4 0"
"Core: Group namelist change 1:4 2"
"Core: Group namelist change 1:5 0"
"Core: Group namelist change 1:5 2"
"Core: Group namelist change 1:6 0"
"Core: Group namelist change 1:6 2"
"Core: Group namelist change 1:7 0"
"Core: Group namelist change 1:7 2"
"Core: Group namelist change 1:8 0"
"Core: Group namelist change 1:8 2"
"Core: Group namelist change 1:9 0"
"Core: Group namelist change 1:9 2"
"Core: Group namelist change 1:10 0"
"Core: Group namelist change 1:10 2"
"Core: Group namelist change 1:11 0"
Widget::onGroupNamelistChanged: Group not found, creating it
"Core: Group namelist change 1:11 2"
```

I think it's not a qTox bug, but a core one..

**Comment by dubslow** [comment]
Indeed, that's what I was wondering about some days ago. https://github.com/tux3/qTox/issues/394#issuecomment-59930271

Maybe if I have some spare time next week I can throw some extra prints into toxcore and see what's going on...
