### ISSUE TITLE
"Away" status doesn't revert automatically

### ISSUE THREAD

**Issue by Diadlo** [qTox/qTox#3992]
##### Brief Description

OS: Arch Linux
qTox version: v1.6.0-113-g9c325638
Commit hash: 9c3256386d0b28b5f9a24b2a3979f7326722970a
toxcore: 0.1.0
Qt: 5.7.1

Reproducible: Sometimes

##### Steps to reproduce

1. Setup small auto-away time
2. Setup "Online" status
3. Wait unitl your status will be "Away"
4. Disable network without any UI activity (take out the wire or use ssh to stop demon)
5. Enable network
6. Wait some time to make tox reconnect
7. Do an activity

##### Observed Behavior
Status still "Away"

##### Expected Behavior
Revert status

**Comment by zetok** [comment]
Can't reproduce on 9c3256386d0b28b5f9a24b2a3979f7326722970a

Qt 5.6.2
libXScrnSaver 1.2.2-r1
Xorg 1.18.4

**Comment by Diadlo** [comment]
I think, it forget something in steps, but can't remember. Or it's rare

**Comment by antis81** [comment]
@Diadlo Have a look, how/where that user status is generated. You will probably find, that it Is not the right place to generate such an event in the UI (a widget)… and then look how it's done in `ui/redesign`… :)

**Comment by Diadlo** [comment]
@antis81 Ok, thanks. Maybe someday I will understand it and cherry-pick right part

**Comment by antis81** [comment]
What I am trying to say is:
Just like with the call status, the status is not reflected correctly and sometimes it takes a minute or two, until a suspicious timer comes by and hopefully sees the right state. This is rather random and barely controllable. Instead, generate an event after (!) the status variable has changed (see `Friend::userStatus / Friend::connectionStatus`).

In the first place, something like:

```c++
void Friend::setUserStatus(newState) {
  if (newState != userStatus) {
    userStatus = newState;
    emit userStatusChanged(friendId, userStatus);
  }
}
```

Now there's a problem:
As we noticed in the `ui/redesign` discussion, we have two (!) friend databases, that actually should be one -> the one from toxcore. And in no way it should be even possible to set a member from qTox. This is what I have solved in `ui/redesign` by privatizing the setters! This enforces developers to do the right thing: Set the status in toxcore, which is then reflected by a `tox_user_status_changed` callback "internally". Those copied variables have to be completely removed and read/write always must happen through toxcore API. Otherwise it will never function correctly.

**Comment by shinodem** [comment]
have same issue with my friend

**Comment by eagle500** [comment]
On windows x 64 1.7.0 version it happens all the time.

**Comment by anthonybilinski** [comment]
I have this non-stop on commit b392e2c320800c38f44370dd7deee53e7497b167
I'm using Ubuntu 16.04 and have installed qtox and qtox-alpha with the same behaviour.

To reproduce: I lock my desktop, leave for ~30 mins, come back, unlock, send messages, wiggle mouse etc. and status stays as away. Need to manually set as "Online"

Debug log doesn't show anything interesting.

**Comment by anthonybilinski** [comment]
Seeing the same thing on Ubuntu 16.04.
I have my timeout at 1m to try to characterise this a bit, and it definitely doesn't get stuck in "away" consistently. It seems to usually auto-away and auto-available on mouse movement / when unlocking computer, but occasionally does not auto-available, and then seems to get stuck like that until I force available manually.

I see this about once a day, walking away from my computer probably a couple dozen times, usually by locking the screen.
version v1.6.0-91-gb392e2c-obs hash b392e2c320800c38f44370dd7deee53e7497b167
Qt version: 5.5.1

**Comment by Diadlo** [comment]
Ok. I found the reason of the problem. Steps updated
