### ISSUE TITLE
TODO: refactor autoupdater code to make it work with multiple sources

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#4032]
##### Brief Description
Currently only a single URL is used for distributing updates, and only single key is allowed for signature verification.

Refactor should make qTox check a list of URLs for binary and a list of PKs for correct signature.

OS: Windows
qTox version: 1.7

Reproducible: Always

##### Additional Info
https://github.com/qTox/qTox/blob/master/src/net/autoupdate.cpp

**Comment by tux3** [comment]
If we have to manage several domains and keys instead of one, there is a higher risk of accidentally losing control of a domain (forgetting to renew) or worse, losing control of a key.

The updater could use some improvements, but as it is I'm not sure if adding more sources of trust is a good idea.

**Comment by zetok** [comment]
>The updater could use some improvements, but as it is I'm not sure if adding more sources of trust is a good idea.

That's a good point. Trust should be removed/minimized.

The scenario where domain owner could create a situation where qTox gets downgraded should be fixed.

**Comment by sudden6** [comment]
We could use the number of commits in qTox as a monotonic increasing version number and only allow upgrades. Then trying to fetch qTox from multiple domains should be feasible and will actually be a good idea.

**Comment by sudden6** [comment]
Autoupdater was scrapped
