### ISSUE TITLE
Mac build Crashes

### ISSUE THREAD

**Issue by Derq** [qTox/qTox#408]
the mac build not using the homebrew version crashes when you press the exclamation point button, it would light up red and then crash for seemingly no reason

I use a OS X 10.9.5

**Comment by dubslow** [comment]
Where did you get this mac build? If you got it from Jenkins, then it's unfortunately at least a month out of date...

@stqism, how's the progress getting Mac builds to work again?

**Comment by Derq** [comment]
no i built it myself using this repo

do you want me to post a crash log?

I used the compiling instructions from the os x info, everything else looks fine

**Comment by dubslow** [comment]
Yes please. Is it possible for you to `gdb` it maybe and get a backtrace?

**Comment by Derq** [comment]
this is incredibly coincidental, the same crash no longer happens it still turns red but it doesn't crash anymore, I  forgot to test the newest build, this morning though it was crashing but now it doesn't anymore this is a false alarm it might happen again but i have no way of replicating it

**Comment by dubslow** [comment]
Well I guess leave this open for now and if it happens again certainly let everyone here know. :) Thanks for the report regardless!

**Comment by Derq** [comment]
no problem!

**Comment by Derq** [comment]
As of the current commit the mac build on 10.9.5 hangs on pressing the Audio/Video tab

**Comment by dubslow** [comment]
@krepa098

**Comment by krepa098** [comment]
I really need more data. Please provide the console output.

**Comment by dubslow** [comment]
@Derq Can you confirm this on the official binary? (!!!)

Edit: fsck. NikolaiToryzin confirms. Apparently it hangs, doesn't crash.

**Comment by stqism** [comment]
qTox OS X now works officially, and I can confirm that happens

**Comment by dubslow** [comment]
#stal reports https://i.kirara.ca/pired.raw

Edit: I have no idea what it is he's reporting, may be unrelated to the hang

>  <bunslow> stal: that's the hang I take it?
> <stal> who knows
> <stal> i'm going to watch anime
> <zetok> stal++
> <stal> also QTKit is deprecated

**Comment by tux3** [comment]
stal's report looks like a normal deadlock but I can't tell if that's internal to qTox or upstream
Unfortunately I don't have the time to look at the code right now, but without a mac to test I'm not sure how long it'll take to fix.

> 2719 CameraWorker::getProp(int)  (in qtox) + 326  [0x10a1674d6]
> ...
> 2719 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff90cea132]

  

> 2719 CameraWorker::_resume()  (in qtox) + 410  [0x10a1661ea]
> ....
> 2719 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x7fff90cea132]

**Comment by krepa098** [comment]
~~_getProp() is using subscribe() instead of _subscribe() maybe that's causing it. I'll post a patch tomorrow.~~ 

Forget about this.

**Comment by tux3** [comment]
Ok, I think I got it.

This is a deadlock because of the Qt::BlockingQueuedConnection in CameraWorker::getProp(int), as you might have guessed. 

Here's the scenario :
- We click on the video tab, this calls CameraWorker::getProp(int)
- CameraWorker::getProp(int) makes a blocking queued call to _getProp, blocking the calling thread
- This is a blocking queued call, so it generates a QEvent added to the event queue, and we start processing the event queue immediately
- BUT someone called CameraWorker::resume() earlier, wich called MetaObject::invokeMethod(this, "_resume"). And with "this" living in another thread, the call was actually a Queued (non blocking) call, so it added a QEvent on the queue and returned. Just before ours. This only happens on mac.
- We're now processing the events, starting with _resume
- We're now in the blocked thread, in CameraWorker::_resume(), wich calls subscribe(), wich calls cam.open(camIndex), wich tries to use events in a blocked thread
- Boom, deadlock

So, we should probably remove that blocking queued connection, it's just asking for trouble, and replace it with something else. 
If we don't do that, as a bad dirty workaround, we could call also qApp->processEvents just before our blocking queud call to clean the event queue and pray that nobody decides to make a race condition from another thread two weeks from now. But that's sloppy.

**Comment by dubslow** [comment]
How does that only manifest on Macs? Or is it just coincidence?

**Comment by tux3** [comment]
@dubslow I have the bad habit of posting comments before I'm done writing them, and then editing for half an hour.

I don't know why it only happens on mac, and it's possible I'm actually completely wrong since I couldn't test this, but that's what I'm reading from stal's report and looking at the code. I blame scheduler magic, or inconsistent library implementations. But anyway that blocking queued call is asking for trouble.

**Comment by dubslow** [comment]
Oh.

**Comment by tux3** [comment]
So I pushed the dirty workaround to confirm if that's the issue, I'll need to make a real fix out of this later if I'm right. If someone with a mac can test, please tell me if it worked or not.

**Comment by krepa098** [comment]
> We're now in the blocked thread, in CameraWorker::_resume(), wich calls subscribe(), wich calls cam.open(camIndex), wich tries to use events in a blocked thread

Could you please elaborate this one? Where does it need event processing? Maybe I'm just too tired right now :)

**Comment by tux3** [comment]
> psynch_cvwait: This system call is used for psynch cvar waiters to block in kernel.

My guess right now is that you're not supposed to call psynch_cvwait twice on the same thread, this is some sort of mutex you acquire on a thread to do _something_. Qt called it when blocking the thread, and opencv called it through QTKit, this deadlocked since Qt was already using it.

Or maybe I'm completely wrong. Maybe this is just a bug in QTKit/opencv waiting for something that will never happen. I can't know without testing.

But this is wild speculation, I have no idea what I'm talking about because I don't own a mac and can't reproduce.

**Comment by krepa098** [comment]
Camera was calling CameraWorker::probeResolutions from the camera thread instead of the worker thread. Maybe that was confusing QTKit... Well let's first see whether your workaround works or not.

**Comment by tux3** [comment]
If you have a real fix, I propose we get rid of my workaround asap.
Can anyone test ?

**Comment by jbshirk** [comment]
Watching this thread.

**Comment by dubslow** [comment]
@jbshirk Does the issue still exist in the very latest qTox build? tux3's hack should be in latest, and right now this thread is waiting on knowing whether or not it makes a difference.
