### ISSUE TITLE
Build macOS Release on Cloud Service

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4095]
The [service](https://www.macincloud.com) allows you to rent time on a real, physical Mac with complete XTools etc. qTox will no longer need its own Mac to ship macOS binaries in a timely fashion.

**Comment by zetok** [comment]
>(…) allows you to rent (…)

Who is going to pay for it?

**Comment by ghost** [comment]
If you're pretty sure you could build public macOS releases of 1.7.X series then I can mail you the first $30 cash, just say where to send (I do not use PayPal or Flatter or anything like that, just cash).

**Comment by zetok** [comment]
Thing is, to build OSX release this service doesn't need to be used – travis does the job just fine: https://github.com/qTox/qTox/releases/tag/v1.8.1 , and it's free for FOSS projects.

The only problem is making sure that what is build is actually working – that's something that someone who has a osx license can check.

Closing, since what you seem to want (release build) is provided for newest 1.8.1 release.

Btw, there's a build script that will try to build newest qTox for you. You might want to check instructions in INSTALL.md.

**Comment by ghost** [comment]
OK by me to close, but here are minor corrections.

1. Cloud service can be used for testing qTox on macOS (not just building it).
2. If you want free help testing qTox on Mac, try Mac forums.
3. I do not own a Mac. I just want people who do to get tox. Pitch as secure Skype on forums.
4. Release builds must update link at https://tox.chat/download.html or Mac folks won't find them. Currently that URL offers a stale 1.5.1 macOS binary that crashes.
