### ISSUE TITLE
Which is better: qTox and Wire? And why?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4125]
I was using qTox for a long time. I used "Wire" today and it was impressive.
It support desktop, android, iOS, and webapp. "Tox" support only desktop and android
and Antox is unusable condition(crash instantly, see their issues).
Why not collaborate Wire development instead? If you really think qTox is way better than Wire, then tell me, I want to know(not insulting, just for discussion).

https://wire.com/en/
https://github.com/wireapp

**Comment by sudden6** [comment]
The main difference is Wire is a hosted service (somebody provides servers) whereas Tox is a decentralized peer to peer network (everybody takes part in helping the network).

The advantage that most popular messengers (including Wire) have, is that with a centralized server infrastructure it's easy to implement things like offline messaging and multiple devices with one account. Also with centralized servers it's easy to reduce battery usage on mobile, because the server can "tell" the phone to wake up and check for new messages (extremely simplified).

The advantage of Tox is, that in theory it's very reliable, because there are no servers that can go offline. Also since there are no servers, it's hard to shut the network down (it can probably be blocked through packet filters though) and it should be very reliable (no servers, no server outages :) )
On the other hand, having no part of the network be always online, makes it hard to implement things like offline messaging and syncing of multiple devices, since the parties involved have to be online at the same time. These things are being worked on over at https://github.com/TokTok, but it's though.

The only things I see where Wire and Tox could collaborate are client UI design and maybe hosting of bootstrap nodes.

**Comment by yurivict** [comment]
Besides of what sudden6 said, Wire uses NodeJS. npm doesn't have package signing, and routinely picks package versions from github without any review. These practices are very insecure. NodeJS is currently very popular, but it isn't big on security.

Additionally, Wire is based on electron. electron generally doesn't build on anything but major OSes. For example, not on BSD. This is due to the extreme degree of convolution of electron's codebase. So it immediately causes the portability problem, which qTox just doesn't have.

**Comment by Diadlo** [comment]
I think, there enough answers. Thus closing.
