### ISSUE TITLE
[suggestion] Tox should be able to decrypt/encrypt the existing db on disk

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4217]
Currently qTox creates the encrypted db when it is first run. Some users might not want to type the password every time. They should be able to decide that their local system is sufficiently secure to not require encryption. Users should also be able to encrypt db when they decide so.

* There should be buttons "decrypt database"/"encrypt database", warning the user about the security consequences and asking him is he is sure.

**Comment by sudden6** [comment]
Storing only the db unencrypted makes no sense, since one needs to enter the password anyway to decrypt the `*.tox` file for an encrypted profile.

Additionally the password to encrypt the profile and `*.tox` file is optional and should therefore allow the user to decide his system is secure enough.

I hope I understood you correctly, but I think the thing you're asking for is already provide.

**Comment by zetok** [comment]
Since what you're asking for has been in qTox for years now, closing.

**Comment by yurivict** [comment]
Sorry, maybe I don't see the obvious. But where is the button to decrypt?

**Comment by yurivict** [comment]
Ah, sorry, I found it!
Never mind!
