### ISSUE TITLE
Question: RawDatabase::execLater is actually synchronous?

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4225]
This function calls ```QMetaObject::invokeMethod(this, "process");```
The default ```type=Qt::AutoConnection``` uses ```Qt::DirectConnection``` when the thread is the same. When I am trying to run some more complex queries, I keep getting DB errors in ```OPEN;``` statement because in opens embedded transactions.

Shouldn't it be ```QMetaObject::invokeMethod(this, "process", Qt::QueuedConnection);``` in ```RawDatabase::execLater``` so that it is really run "later"?

**Comment by sudden6** [comment]
Yes and No. If called from outside the class it's definitely asynchronous, since the db lives in it's own worker thread. If called from for example the `open` function it can be in the same thread and use a `Qt::DirectConnection`.

I think explicitly using a queued connection can't hurt, mind open a PR?

**Comment by yurivict** [comment]
I think execLater should just use ```QMetaObject::invokeMethod(this, "process", Qt::QueuedConnection);``` to eliminate any other factors any assumptions.
Will create a PR.

I am trying it, qTox works fine this way.

**Comment by yurivict** [comment]
https://github.com/qTox/qTox/pull/4230
