### ISSUE TITLE
Times should be in UTC

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#4231]
Currently times are generated with ```QDateTime::currentDateTime()```, which returns local time.

If I travel to different location and change system timezone, all displayed times in message history will be wrong.

Times should be obtained with ```QDateTime::currentDateTime().toUTC()```, and then converted to local time only for the display purposes.

There should be one function in Core that does this. If this is implemented, existing DB data should be converted to UTC.

**Comment by tWido** [comment]
Looked a bit into this issue. Most probably there's no need to change anything. Dates are already saved as milliseconds since epoch. So  `QDateTime::currentDateTime().toMSecsSinceEpoch() ` equals `QDateTime::currentDateTime().toUTC().toMSecsSinceEpoch()`

Code:  https://github.com/qTox/qTox/blob/master/src/persistence/history.cpp#L205
Doc:  http://doc.qt.io/qt-5/qdatetime.html#toMSecsSinceEpoch

Reading such timestamps is performed with function that automatically adjust the time according to the local time zone. 
http://doc.qt.io/qt-5/qdatetime.html#fromMSecsSinceEpoch

**Comment by yurivict** [comment]
Thanks for verifying this!

I must have misread the code when I created this bug report.
