### ISSUE TITLE
Qtox focuses window on new messages, irrespective of settings

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4301]
Commit hash: 2e4ac3c6ac88639967f3015854ccdf63c322af48
qTox version: v1.9.0-22-g2e4ac3c
Qt version: 5.5.1

Qtox focuses chat window when receiving a message. It does this repeatedly, whether or not I tell it not to. It seriously complicates multitasking for me. I'm guessing this is a recent regression, as this behavior just started a day ago or so ago.

Edit: tried removing qtox.ini in case it was some settings corruption issue. This did not fix the problem.

**Comment by anthonybilinski** [comment]
I can't reproduce this on 2e4ac3c or on c4995971 (tip) with messages, calls, or file transfers.
EDIT: it looks like maybe focus just doesn't work at all on Ubuntu 16.04

I CAN reproduce this on tip on Linux mint 18.2

**Comment by anthonybilinski** [comment]
it looks like we're correctly checking the relevant settings, but the alert() call is popping the window forward regardless.
```
        if (inactiveWindow) {
            QApplication::alert(currentWindow);
            eventFlag = true;
        }

        if (Settings::getInstance().getShowWindow()) {
            currentWindow->show();
            if (inactiveWindow && Settings::getInstance().getShowInFront()) {
                currentWindow->activateWindow();
            }
        }
```
alert's behaviour is OS specific and from this description http://doc.qt.io/qt-5/qapplication.html#alert sounds like it's what we want to make the icon bounce and or highlight, but obviously also brings it forward in at least some cases.

**Comment by ghost** [comment]
Compiled git and can verify it's an issue on Linux Mint 18.2 w/ Cinnamon.  Verified with a new profile, too, and that the focus config setting doesn't make a difference.  Sounds like that has already all been verified though!

All chat messages make it focus for me.  Is this a qt standards issue or a problem with Cinnamon's Muffin window manager doing something it shouldn't and not following proper qt standards, do you think?  Let me know if I can do anything to help!

**Comment by anthonybilinski** [comment]
I believe it's due to general Cinnamon notification handling. There's an almost identical report for Qt creator here, using the same Qt alert() method: https://bugreports.qt.io/browse/QTCREATORBUG-7184.

There's a cinnamon bug report here, which I believe is the same issue: https://github.com/linuxmint/Cinnamon/issues/233
With a workaround here: https://scott.cm/skype-auto-popup-with-cinnamon/

@Swiftpaw can you test if the workaround linked fixes the behaviour, and if it has any negative side-effects, like other apps not notifying?

**Comment by ghost** [comment]
@anthonybilinski Unfortunately, that post is from 2012 and the config files referenced don't exist.  That may be why the notification-style value doesn't exist for me, or it's due to the newer version of Cinnamon, or they moved it.  To rule out the latter I grepped through dconf and verified that it doesn't exist.

**Comment by anthonybilinski** [comment]
Forget all that, I think this might be intended behaviour on Mint :P

If you open the application "Windows" in Mint, then go to the "Behavior" tab at the top and turn "Prevent focus stealing" from OFF (default) to ON, it resolves this for me, and the qTox icon still lights up with a sound notification on message, like it does in other OSes.

@Swiftpaw does this resolve the issue for you?

**Comment by ghost** [comment]
@anthonybilinski Yes, that setting fixes it.  So Muffin is mistreating Qt calls in a way that was not intended?  If that's the case then this should be brought to the attention of the Mint developers.  You'd think Qtcreator should definitely be making the correct calls, so perhaps this is a misinterpretation of Qt calls by Muffin's or Mutter's devs (at least I think Muffin is based on Mutter), or Mint's devs?

**Comment by anthonybilinski** [comment]
Using the "prevent focus stealing" option also blocks Qt's intentional focus stealing from activateWindow(), which corresponds to the "Focus window" on new message setting in qTox. This is definitely not ideal.

I opened a ticket with Cinnamon and will see what they think https://github.com/linuxmint/Cinnamon/issues/6926

**Comment by ghost** [comment]
@anthonybilinski Way to go, thanks!

**Comment by anthonybilinski** [comment]
Duplicate of #2168, closing to track issue there.

**Comment by andriusign** [comment]
This is very annoying issue. Confirmed on:
Brief Description

qTox window focuses when new notification received, despite of focus being turned off. This is very annoying since qTox opens and covers other windows.

OS: Linux Mint 19.1 Cinnamon 4.0.10, Linux kernel 5.0.0-23-generic
qTox version: v1.16.3.
Commit hash:
toxcore: 0.2.3
Qt: 5.11.3
Hardware: Intel© Core™ i7-7500U CPU @ 2.70GHz × 2

Reproducible: Always
Steps to reproduce

    Go to Settings -> User interface. Uncheck "Focus Window" and "Open window".
    Open different window, e.g. text editor.
    When someone sends message to qTox, its window get focused.

Expected Behavior

Only notification sound is played (if it is turned on) and qTox window is not focused.

P.S. looks like very old issue: "Deleetdk opened this issue on Sep 3, 2015". When is this gonna be fixed??

**Comment by anthonybilinski** [comment]
Like the last comment says, this issue is a duplicate of https://github.com/qTox/qTox/issues/2168. Please continue discussion there instead of here.

Also please don't copy paste comments across multiple issues, it just creates extra bureaucratic work.
