### ISSUE TITLE
No "Ban" or "Report" button

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4353]
##### There are no safety buttons

OS: Linux Mint Cinnamon 18.1 Serena
qTox version: v1.6.0-obs  
Commit hash: 5648106b34fc7dc3ad4e169651a0cbbd0139170a
toxcore: 0.0.0 
Qt: 5.5.1

I am testing qTox on my Linux computer and I have seen who there are no "ban" or "report" button.

How to report a user with annoying or dangerous behavior ?

**Comment by ProMcTagonist** [comment]
I have personally witnessed a lot of both annoying and dangerous behavior on Tox. I believe the only way this can be resolved is immediate integration of a government-maintained SSN (or equivalent)-linked user list so that users exhibiting any behavior deemed dangerous by the community can be removed permanently, and potentially tried and jailed for their disruptive actions. This is the classical way of regulating behavior in human societies, and the only way to protect our children. 

Facebook login flow would be an acceptable start.

Furthermore Tox needs to hire fulltime staff to monitor the Report lines and be available for general support. Some client-integrated commercial partnerships should be able to cover that handily. I have some ideas concerning this and I think we can get a lot of steam out of our campaigns if we use targeted methodologies to ensure we're delivering maximum value.

I think it's important we as a community have a serious discussion about the problems caused by the Tox architecture, namely the amount of harassment that it can generate. We have to remember that the ultimate goal of any project is to create a harmonious community around developing it. Remember, there are **plenty** of fully distributed and p2p, encrypted, accountless VOIP messaging networks out there, so what Tox really needs to focus on is a pleasant UX, which mandates removing unsavourables promptly.

Just some thoughts.

**Comment by ezavod** [comment]
@Mago7891 
Banning people would be a great feature. However there is already a proposal on how this could be done (see #1958), but sadly this is not yet implemented.
At the moment it is possible to get rid of people by removing them from your friend/contact list and change your [NoSpam](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#nospam). Then they are unable to add you again with the id they used in the first place.

Reporting people would fundamentally break the concept of (q)Tox, I think.
Have a look at the [qTox webpage](https://qtox.github.io/):

> Nowadays, every government seems to be interested in what we're saying online. qTox is built on a "privacy goes first" agenda, and we make no compromises. Your safety is our top priority, and there isn't anything in the world that will change that.

> qTox takes your privacy seriously.
With leading-class encryption, you can rest assured knowing that the only people reading your messages are the ones you send them to.

If you report a user, some form of staff or maintainer needs to review the messages send by this user (so the message is read by someone else than the intended recipient).
I would say it is obvious that this conflicts with the main goal of private and secure messaging.

@ProMcTagonist This really sounds like a better world to live in...

**Comment by SlugFiller** [comment]
Can't tell if trolling, or actually serious... In the interest of future readers, however, I will try to explain, as politely as possible, why this is so fundamentally wrong.

Tox is, first and foremost, a decentralized network. That is, no single entity or group can control Tox. Furthermore, being open source means that even the developers have limited control, as there is nothing preventing anyone from forking the client.

This is by design, as Tox's stated goal, and its very reason for existing, is to prevent oversight. Even if oversight is done by a non-governmental group, it is still possible for governmental or other interest groups to put pressure on that group. Every aspect of Tox is designed to prevent any form of oversight. Even if there was some aspect of the design that would allow oversight of some form, it would immediately become a priority to remove that aspect. It would be seen as a flaw, by the very paradigms that make Tox what it is.

Once you understand that central control is not possible and will not be possible by design, you can understand why actually removing any element from the network would require a unanimous agreement from all peers. Because it's enough that any two peers wish to communicate with each other, and no one can stop them. Any peer can "break the boycott" and interact with a "banned" user directly. However, let's assume we don't care about those cases, and only want "rule abiding" peers to be "spared". This simply reduces the unanimity requirement down to needing a consensus. It still leaves a question of how that consensus is reached.

Obviously, using a central entity to broadcast a filter list is a no-go, due to the above mentioned foundational paradigm of Tox. A blocklist maintained in a non-centralized way would be vulnerable to abuse and false reports, effectively blocking everyone on the network. One might suggest a majority vote based system instead, and protocols for such exist. But since there's no way to ensure that each peer belongs to a different person (due to the lack of oversight), fabricating a majority vote simply comes down to computing power, rather than an actual majority opinion. Even if that problem didn't exist, you'd still need at least 50% of the people on the network to interact with a certain peer and come to an equal judgement about that peer, even while not being privy to how that peer interacted with other people. And even if that problem didn't exist, the person behind the peer can just make a new account at no cost. And even if ALL of those technical problems didn't exist, you'd still be banking on the majority of people being in your favor. And you'd be setting yourself up for being kicked out over not matching the most popular opinion.

Ultimately, even if you could get a large part of the network to agree to block out certain peers, all it would do is fork the network, as those peers continue to have access to each other and anyone not "playing ball". You're not gaining anything you wouldn't have already gotten by simply not accepting such peers into your contact list in the first place. Tox is ultimately a personal platform, not a public one. It is your personal responsibility to choose with whom to interact. If you choose to paint a big "Welcome" sign in front of your house, while leaving the door unlocked (e.g. Posting your public ID in a public platform), then you shouldn't be surprised that every bum off the street comes marching in.

What you CAN do, however, is give your fate to some "trusted group" which would act as a gate-keeper for you, allowing random people to enter after taking whatever vetting process they choose. In essence, group chats already achieve just that, as they are managed by a trusted peer, while allowing untrusted peers to enter so long as they are vouched for by a trusted one. Contact sharing can achieve similar. These are much simpler way to open up to people beyond your immediate trust circle, without being completely open to the world, at the cost of having to relinquish control of your trust circle to a trusted peer.
