### ISSUE TITLE
update 1.9.0 -qtox.exe not working 

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#4358]
##### Brief Description

OS: Windows10
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  
Hardware:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by zetok** [comment]
cc @tux3 ?

**Comment by aldude999** [comment]
Same here, Windows 7 x64, neither 32 bit, 64 bit, or portable is working. No logs created, no command line output, or anything.

**Comment by Hasshu** [comment]
Alas, ditto.

**Comment by cfilgit** [comment]
I noticed that the last version 1.9 after installed in the control panel to uninstall it shows 1.8, could be related to this info that the 1.9 version dont work?!

**Comment by tux3** [comment]
So something very strange is going on with the windows builds of qTox, the binary produced by the compiler doesn't actually run qTox, it starts and then immediately there is an unconditional return instruction stopping it:

![snap-25](https://cloud.githubusercontent.com/assets/5155966/25774767/6c97ec62-3296-11e7-9319-c19614307b53.png)

I'm still trying to understand what could possibly have caused this.

EDIT: It seems to be some sort of insane linking error or similar, as simply changing the entry point from 0x401000 to 0x4014D0 makes qTox run correctly. It's as if the compiler saw an empty stub somewhere and decided to use it as a start function.

EDIT2: I don't have time to go fix this in depth right now, so I'm pushing the current nightly build as the new temporary stable, since it seems almost ready for stable and doesn't have this problem.

**Comment by g4jc** [comment]
Was about to open a new bug report, but spotted this.
Is this the reason why there are no 1.10.x releases for Windows?

In any case keep up the good work, great program. 👍

**Comment by tux3** [comment]
The last 1.10 has been released, and this shouldn't be a problem anymore :)
