### ISSUE TITLE
qTox does not open gui on windows 10 creators update

### ISSUE THREAD

**Issue by nyakowint** [qTox/qTox#4362]
##### I'm running the latest Windows 10 update, and cannot run qTox. I don't think you can chat between qTox and uTox, so i **really** need this to be fixed

OS: Windows 10  
qTox version: 1.9.0
Commit hash:  ? what does this mean ?
toxcore:  ? what does this mean ?
Qt:  don't know what this means either...
Hardware:  See picture attached [![https://gyazo.com/9a482c9dba2533bbe2b636a1063768f7](https://i.gyazo.com/9a482c9dba2533bbe2b636a1063768f7.png)](https://gyazo.com/9a482c9dba2533bbe2b636a1063768f7)
…

Reproducible: Sometimes

How to reproduce: 

1.  Get a lenovo desktop with 10 touch points
2. download qTox
3. try to open it,  it will say it's open in Task Manager but GUI will not open

Observed Behavior:

qTox runs process, but does not open GUI. 
shows in Task Manager, but then closes.

Expected it to run, i would add friends to purchase items

**Comment by ezavod** [comment]
I can reproduce this with Win10 (up to date) using the 64bit installer from Readme page. Does not show up at all, not even logs or the like.

@ItzOnlyAnimalYT Try to use the [nightly](https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86-64_nightly_release/lastSuccessfulBuild/artifact/setup-qtox.exe). This works for me.

Edit: You could use whatever tox client you like, so uTox should work as well.

**Comment by nyakowint** [comment]
also wtf is with this message? [![https://gyazo.com/f6ca71b1b9ee25197e31581f5f12b4ce](https://i.gyazo.com/f6ca71b1b9ee25197e31581f5f12b4ce.png)](https://gyazo.com/f6ca71b1b9ee25197e31581f5f12b4ce)

**Comment by ezavod** [comment]
I am not an expert on Windows, but this looks like a warning that you are going to install an unsigned or untrusted package. This is because the nightly builds are not signed.
Maybe I should say more clearly that using the nightlies is just a quick fix and is not recommended at all. First they are test versions which are not tested to be stable, second they are not signed.

If you do not trust this unsigned installer you have to compile yourself or wait until the link in Readme gets fixed.

Edit: One could use https://build.tox.chat/fingerprintCheck to verify the md5 of your download, if one trust the webpage.

**Comment by sudden6** [comment]
cc @tux3

**Comment by cfilgit** [comment]
I noticed that the last version 1.9 after installed in the control panel to uninstall it shows 1.8, could be related to this info that the 1.9 version dont work?

**Comment by Hasshu** [comment]
Duplicate of #4358?

> what does this mean

@ItzOnlyAnimalYT Change your settings -> About -> Version.

**Comment by sudden6** [comment]
Duplicate of https://github.com/qTox/qTox/issues/4358
