### ISSUE TITLE
qTox on mac not saving settings

### ISSUE THREAD

**Issue by Mattel88** [qTox/qTox#4416]
I'm using the current version. After installation and changing settings it seems like that the changed settings are not being saved. If I try to disable chat logs and enable connection over Tor with Socks settings the same issue occur.

If I close Tox (red dot) the app is not being closed completely. I have to right click the app icon in the dock and close it again. It is annoying. Anything I can do in order to fix that?

**Comment by ghost** [comment]
Yes, same here. Are the older version free of this bug?
- Tox doesn't save anything of the settings (Chats are saved)
- The app close not correct (red dot or <kbd>CMD</kbd> + <kbd>Q</kbd>)

**Comment by sudden6** [comment]
Can you please post the complete version string of your installed qTox version? Do you have "Close to tray" enabled in the settings?

**Comment by ghost** [comment]
"Close to tray" is disabled (default settings, because reset problem).
- qTox-Version v1.10.1.
- Commit-Hash: 981953ef140e6c11a83078ac80647f912de1e07d
- used device: Macbook Pro 13" Late 2016 (Touch Bar)
- used operating system: Mac OS X Sierra
Do you need more information?

**Comment by Mattel88** [comment]
Where can I find the complete strong of my installed version?

no I did not had the setting to close it in the tray enabled.

Edit: you have to close the APP again (right click close) because it is not being closed probably. Using macOS Sierra

**Comment by ghost** [comment]
1. Click on the settings gear in the lower left corner
2. About section
3. It will be displayed to you above

**Comment by Mattel88** [comment]
You are using qTox version v1.10.1.
Hash 981953ef140e6c11a83078ac80647f912de1e07d
toxcore version: 0.1.0
Qt version: 5.8.0

**Comment by Mattel88** [comment]
Seems like nothing is happening.

**Comment by ghost** [comment]
The described problem continues to exist.

**Comment by Diadlo** [comment]
Yes. Nothing happens. No one took this issue

**Comment by ezavod** [comment]
@Mattel88 
It would be nice if you could provide a [log](https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports).
Or try to start qTox from command line (you should see a log there). Look for lines like `persistence/settings.cpp:612 : Debug: Saving personal settings at  <path>"` and `persistence/settings.cpp:453 : Debug: "Saving global settings at <path>"` when you close qTox.

Do you see any errors near that output and does these files exist?
Maybe you do not have sufficient permissions to write settings file.

**Comment by ghost** [comment]
Okay thanks, here is my log:

```
Last login: Wed May *** on ttys001
*** /Applications/qtox.app/Contents/MacOS/qtox ; exit;
[19:41:36.921 UTC] platform/install_osx.cpp:101 : Debug: OS X: Old settings directory not detected
[19:41:36.921 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /Users/***/Library/Application Support/Tox/qtox.ini"
[19:41:42.056 UTC] widget/translator.cpp:52 : Debug: Loaded translation "en"
[19:41:42.056 UTC] widget/translator.cpp:62 : Debug: System translation not loaded "en"
[19:41:42.056 UTC] ipc.cpp:62 : Debug: Our global IPC ID is  ***
[19:41:42.057 UTC] ipc.cpp:74 : Debug: Attaching to the global shared memory
[19:41:42.057 UTC] main.cpp:218 : Debug: built on:  13:01:23 May 13 2017 ( *** )
[19:41:42.057 UTC] main.cpp:219 : Debug: commit:  *** 

[19:41:42.057 UTC] ipc.cpp:126 : Debug: postEvent  "activate" to 0
[19:41:43.262 UTC] main.cpp:272 : Debug: Event "activate" was handled by other client.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

I dont't see any errors. Problem exists...

**Comment by ezavod** [comment]
That looks pretty normal to me (it is interesting that osx logs look that different than Linux or Windows logs).
It seems there is already an other instance of qTox running, but I doubt that this would break thinks.

**Comment by blewIT** [comment]
Hi, I experience the same problem on Linux Mint 19. 
My System:
Linux NAME 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 19 Tara \n \l
You are using qTox version v1.16.3-80-g7ff1d605.
Commit hash: 7ff1d6053a57a29ee6fcc062feb32894c848f415
toxcore version: 0.2.7
Qt version: 5.9.5

Description:
I opened qtox on the Desktop, and changed the settings under General -> System Tray Icon to "don't close to tray", and under user interface to "activate multiple windows mode". Then I changed it back because I didn't like it, and during the session it stayed that way. After restarting qtox it went back to don't close to tray and multiple windows mode. Even the restore to default button didn't work, neither did several restarts. Then I checked the debug logs, went to this folder: sudo vim /home/user/.config/tox/qtox.ini
and fixed one of the settings (close to system tray) and saved it, and suddenly all settings were saved correctly, in the GUI and after restart.

Debug Log (Before I changed it manually, what was logged afterwards does not seem relevant, it concerns only video and audio):

[00:01:39.639 UTC] network.c:881 : Debug: Bound successfully to [::]:33445
[00:01:39.728 UTC] msi.c:135 : Debug: New msi session: 0x55bd60530cf0 
[00:01:39.834 UTC] persistence/settings.cpp:336 : Debug: Loading personal settings from "/home/user/.config/tox/username.ini"
[00:01:39.834 UTC] nexus.cpp:86 : Debug: Starting up
[00:01:40.131 UTC] Messenger.c:513 : Critical: Friend 1 is not online
[00:01:40.135 UTC] Messenger.c:513 : Critical: Friend 1 is not online
[00:01:40.845 UTC] :0 : Debug: D-Bus system tray: no
[00:01:40.846 UTC] widget/systemtrayicon.cpp:62 : Debug: Using GTK backend
[00:01:41.345 UTC] core/core.cpp:374 : Debug: "Connecting to node.tox.biribiri.org:33445 (nurupo)"
[00:01:41.350 UTC] core/core.cpp:374 : Debug: "Connecting to 130.133.110.14:33445 (Manolis)"
[00:01:45.841 UTC] core/core.cpp:374 : Debug: "Connecting to 104.223.122.15:33445 (ru_maniac)"
[00:01:45.842 UTC] core/core.cpp:374 : Debug: "Connecting to 2607:ff48:aa81:800::35eb:1:33445 (ru_maniac)"
[00:01:49.352 UTC] core/core.cpp:343 : Debug: Connected to the DHT
[00:01:49.353 UTC] persistence/profile.cpp:353 : Debug: Saving tox save to  "/home/user/.config/tox/username.tox"
[00:02:50.158 UTC] widget/form/settings/advancedform.cpp:115 : Debug: Found debug log for copying

(I replaced my info with NAME and username)

Cheers

**Comment by Yalman** [comment]
bump

Hello. I use the Debian Version of qtox  v1.17.3-1-debian.
If i set some settings, specially a socks5 proxy, the setting would not be saved.

**Comment by anthonybilinski** [comment]
Regarding the original issue, testing on High Sierra with qTox v1.16.3, I see the same issue where closing it just brings it to the dock, where right click -> show window says "no windows to show", and the only option that works is to quit. After quitting this way and reopening qTox, no settings are saved.

qTox v1.17.3 doesn't support High Sierra as it is EOL.

qTox v1.17.3 on Mojave both closes correctly when clicking the red button, and settings changed are saved and correct on next open. I'd guess the issue was we were never closing cleanly and so never saved settings, but it doesn't seem worth digging into if it's no longer an issue.

@blewIT where did you install qTox from? The only place I see qTox available by default on Mint 19 is the flatpak package, but that's at qTox version v1.17.3 with Qt 5.15, and that appImage which is v1.16.3 but uses Qt 5.7.1, so it doesn't seem like either of those. Regardless, testing the appImage on Mint 19 to get the matching qTox version of v1.16.3, I'm not able to reproduce the issue. Launching it, disabling notify, send typing notifications, and setting a SOCKS5 proxy, then closing qTox and restarting it shows all three settings correctly loaded to what they were set to.

If you're still able to reproduce this, could you check where your version is from and see if either flatpak or appimage demonstrate this problem? If you've upgraded your OS since, could you check if the repo-installed version has this problem?

@Yalman presumably this is Debian 11 (Bullseye) to have qTox v1.17.3 in Debian repos.
Testing myself, every setting I tried including SOCKS5 proxy was correctly saved. I unchecked notify, unchecked "send typing notifications", and changed proxy type from "none" to "SOCKS5", and added an address as 127.0.0.1 then closed it and restarted, and settings all matched. Could you double check your repro, and if still present could you please open a new issue?

I'll close for now since the original qTox mac issue seems to be resolved, but if there's follow up to the mac issue, please comment, or if there are other issues please open new issues to discuss them.
