### ISSUE TITLE
Patch: Fix crash when setIcon is called on settings window when it isn't yet opened.

### ISSUE THREAD

**Issue by aasimon** [qTox/qTox#4430]
When the account name in the rooster window is clicked to open the settings dialog the application often crashes. Possibly due to an race condition in the creation of the settings window and the call to setIcon on it.
The attached patch seem to fix the problem for me, but might not be the ideal solution...

[fix_settings_widget_set_icon_crash.patch.txt](https://github.com/qTox/qTox/files/1040674/fix_settings_widget_set_icon_crash.patch.txt)

**Comment by ezavod** [comment]
Can reproduce with qTox 65b1463933869db2d24d43d80e07c6013454bc18, Qt `5.7.1` and toxcore `0.1.2` on Linux 64bit.

It only crashes if one starts qTox in multiple windows mode. Does not crash in single window mode or if started in single window and then switched to multi windows mode then.
It just dies with segmentation fault.

**Comment by sudden6** [comment]
I submitted the patch for you, next time please directly create a pull request

**Comment by aasimon** [comment]
The patch wasn't intended as a pull request, but rather a hint about where/what the problem is.
I'm pretty sure that the solution is not simply to check the value of the pointer but rather fixing the race-condition itself.
I am not familiar with the code-base myself so I'd rather not try to figure out why exactly there is a race-condition in the first place...

**Comment by ezavod** [comment]
It is not a race condition it is just a null pointer.
`settingsWidget` is null, because settings were not opened yet (this explains why it works after settings were once shown). `settingsWidget` is _wrong_ at this place, it should have been `profileForm` (which makes sense, because we do not use `settingsWidget` in `showProfile`).

However I do not think that `onShowSettings` and `showProfile` should use `setWindowIcon`, because it is already handled by `retranslateUi` of the open `Dialog` (also in `widget.cpp`).
It would be sufficient to remove the two `setWindowIcon` and let `retranslateUi` do the magic.
Or even better move `setWindowIcon` into the Constructor to minimize disk reads.

I could open a PR if this is a reasonable solution.

**Comment by sudden6** [comment]
@aasimon sorry, then I misunderstood your intent.

@ezavod I didn't look into the details, but your explanation makes sense, a PR would be great.
