### ISSUE TITLE
qTox hangs when importing profile

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#445]
a3beb991e12ce6794d5e7c50feaf2ae91db6a1f9

```
[Thread 0x7fffdd78c700 (LWP 15608) exited]
Core: switching from "_3" to "11-In Pieces"
Settings: Saving in  "/home/zetok/.config/tox/settings.ini"
Core: writing tox_save to  "/home/zetok/.config/tox/_3.tox"
QObject::killTimer: timers cannot be stopped from another thread
Qt: Dead lock detected while activating a BlockingQueuedConnection: Sender is Core(0x555555e51780), receiver is Widget(0x555555a17010)
[Thread 0x7fffde11c700 (LWP 15546) exited]
```

Steps to reproduce:
1. Click on import
2. Select your favourite *.flac
3. Click open
4. qTox hangs

**Comment by dubslow** [comment]
Christ... zetok why would you even import a flac....

Anyways, the root of this issue is that I converted onLoadClicked to use signals to switch profiles, and then promptly forgot that I had onImportClicked switch-on-import as well, and left it the old way, causing the hang.

Having said that, it never occurred to me that someone would try and import a .flac... come on zetok, lol. You certainly put the software though fire and hell :). The simplest solution is just to disable switch-on-import, and instead let the user decide to switch to a newly-imported profile. At least this way, since .flacs don't show up in the combobox, they won't try to tox_load something that isn't related to tox... which is bad because we can't even trust the error mechanism from it.

Finally, zetok, your file dialog is only supposed to show .tox files; is that correct? As in, did you have to change the filter from .tox to all files to be able to import a .flac?

Edit: I just realized I can at least check the file extension, if not that it's _actually_ a tox save file.

**Comment by zetok** [comment]
I wasn't able to change file filter from *.tox. Fear not though, I've found a workaround. :3

Reason for importing it..
Since I haven't been able to quickly spot any handy *.tox file, I thought about using something else. And it just so happened that I was listening to music :3. So I've copied path to file from music player to file selecting dialog and clicked open.

**Comment by dubslow** [comment]
...

.............................................................................

(Next time just export one of your profiles first)
