### ISSUE TITLE
Win qTox Automatic Upgrade Fails

### ISSUE THREAD

**Issue by ElLamparto** [qTox/qTox#4461]
qTox upgrade 1.8.1 --> 1.10.2
Win 7 32bit

During the automatic upgrade's download, qTox was taking 100% CPU, stopped download at about 50%.
Finally I installed v1.10.2 manually.

**Comment by minger0** [comment]
Some time back I did 1.8.1->1.9  win8 64bit auto upgrade first seemed ok, while it was left unfinished
It resulted in using the 1.9 executable, while the firewall settings were still on 1.8.1, so it was blocked.
I did not want to report it as a separate issue, because I could not reproduce it in lack of the old installer. However, I want to give a signal now that this may need to be tested in newer versions.

**Comment by ghost** [comment]
In my case it downloads new binaries but does not update the program.
So it constantly download package each time when restarted.

**Comment by sudden6** [comment]
Auto update was replaced with an update notification, thus closing.
