### ISSUE TITLE
Download folder isn't persistant

### ISSUE THREAD

**Issue by ShoelessSmith** [qTox/qTox#4505]
##### Brief Description

OS: Windows 7
qTox version: v1.10.2
Commit hash: b73603b45a32e63a649294537a62a9f11176c73d
toxcore: 0.1.8
Qt: 5.6.2
Hardware: 
…

Reproducible: Always 

##### Steps to reproduce

1. Change the download folder
2. Restart qTox
3. …

##### Observed Behavior
The download folder has done back to the original

##### Expected Behavior
The download folder is changed to what the user has asked for

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anoadragon453** [comment]
This is due to `QDir::homePath()` used in the `QFileDialog::getOpenFileName(s)` calls, which you can see an example of [here](https://github.com/qTox/qTox/blob/master/src/widget/form/chatform.cpp#L248).

Simple fix, just need to store the directory where the last file was opened from in qTox's config and use that in the future. If it's not available, use home instead.

**Comment by sudden6** [comment]
Two ideas:

* It could be interesting to see what happens if we pass an empty string as filename, maybe the dialog does the saving itself? I think I have seen this sort of behavior.
* IMO it would be sufficient to save the last directory per session, ie in RAM. Any different opinions?

**Comment by anoadragon453** [comment]
@sudden6 Apparently it's common practice to use `QFileDialog::saveState()` and `QFileDialog::restoreState(state)` [1] and storing the state in [QSettings](https://doc.qt.io/qt-5/qsettings.html) to use later.

[1]: https://doc.qt.io/qt-5/qfiledialog.html

**Comment by sudden6** [comment]
@anoadragon453 this is exactly what I was looking for, thanks.

**Comment by anthonybilinski** [comment]
@ShoelessSmith @anoadragon453 are you two talking about the same issue? It sounds like @ShoelessSmith is talking about the download directory, i.e. "Default directory to save files" under settings->general not being saved across restarts after being manually set, and @anoadragon453 is talking about the default directory opened when you go to attach a file not being being the same as the previous directory that you selected a file from. Please correct me if I'm wrong.

**Comment by anoadragon453** [comment]
@anthonybilinski Ah, didn't know that was an option. I assumed not since it was just set to the user's home directory in the code rather than anything from a settings file.

I think the settings file is still useful, but mostly just for when auto-saving attachments. Perhaps the setting should be changed to reflect that, and the folder for downloaded files that are saved manually is just remember from where the last file was saved to.

@sudden6 You still working on this?

**Comment by sudden6** [comment]
@anoadragon453 Sorry, now that I read it again my comment wasn't quite clear, I was never working on this, I just wanted to make it clear which Qt functions should be used.

**Comment by ghost** [comment]
This bug don't reproduce in newest version.

**Comment by tox-user** [comment]
I can't reproduce it either, so I will close this.
