### ISSUE TITLE
Do not force avatar (daily builds)

### ISSUE THREAD

**Issue by fcore117** [qTox/qTox#4741]
I just tested daily build and found out that avatar is forced, please do not force avatar when you have not chosen own avatar. This feedback message is meant for upcoming versions.

**Comment by sudden6** [comment]
To confirm I understand you correctly: You want a setting that disables the Identicon which is now displayed instead of the default avatar?

**Comment by fcore117** [comment]
yes just no icon like before and like other clients has when no avatar in use.

**Comment by tox-user** [comment]
Does that mean not forcing a generated avatar for your own profile only or do you want all avatars to be like they used to? 

I understand why someone would want to use a blank avatar for their own profile instead of a generated icon but is there a reason to not show them in other people's profiles?

**Comment by fcore117** [comment]
tox-user: not for myself and no icon propagation to others too, like it was before. I could see other icons but when i turn off my icon then it wont be sent to others over tox network. In short, like it was before.

**Comment by tox-user** [comment]
Why do you not want to see other people's avatars? Shouldn't users only have control over their own avatar?

**Comment by fcore117** [comment]
tox-user: i did not say i do not want to see other avatars, i just did not want myself send out any avatar if not set.

sudden6: if you see that this feature is must have for future then just close this issue and let it be.

**Comment by nurupo** [comment]
My comment is probably a little offtopic, but there was an identicon discussion brought up in #utox and someone asked me to write my thoughts about it in this issue, so here it goes, hopefully someone finds it useful.

---

The thing about identicons is that users might rely on them to uniquely identify contacts, something like Tox Id fingerprint, since they \*are\* Tox Id fingerprints, as they are uniquely generated from Tox Ids or public keys. A client allowing displaying of both identicons and avatars at the same time might cause issues, as once you allow a custom image as avatar you can't rely on identicons anymore, a user might set their avatar to someone else's identicon in attempt to impersonate that someone else. For example, say a user has Alice and Bob in their contact list. Alice has red dot identicon. Bob has a cat picture as avatar. Bob can "impersonate" Alice by changing his name and status to that of Alice, as well as changing his avatar from cat to a red dot.

Of course, even before identicons were added to qTox, with just avatar pictures, Bob could copy Alice's avatar in attempt to impersonate her. But the thing about the identicons is that they have this uniqueness property of being a Tox ID fingerprint, so I claim that it's a different matter from avatar impersonation before qTox had support for identicons.

In order to avoid any possible identicon-avatar confusion a user might have, I suggest having a on/off switch in Settings which switches between two modes:

- Mode 1 (Classical)
  - For users with avatar images set, display their avatars images.
  - For users with no avatar set, display the same image for all of them. Either just a blank image or some [stock person silhouette](https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/user.png) image. The point is that it should be the same thing for all of users with no avatars.
- Mode 2 (Identicon-only)
  - For users with avatar images set, don't show their avatars, show their identicons as avatars instead.
  - For users with no avatar, show their identicons as avatars.

Well, in any case, even if you ignore me and decide to mix avatars with identicons, an identicon-only mode still sounds useful, so maybe you will consider at least this part.

**Comment by fcore117** [comment]
nurupo: excellent explanation.

**Comment by sudden6** [comment]
@nurupo I think implementing this is a very good idea.

I wonder though, if the Identicons provide any protection against an attacker that tries to brute-force a public key that results in a similar/equal Identicon, by generating tons of new ToxIDs. I have no idea how hard it is to generate new ToxID's, but the Identicons provide at most 72Bits of entropy, which doesn't sound much.

I think one could counter this attack by switching the hash function of the identicons from SHA256 to something like PBKDF2 or scrypt.

**Comment by nurupo** [comment]
>72Bits of entropy, 

Entropy?

Tox public key is 32 bytes, so 256 bits, 2^256 possible keys. You just need an identicon generator that can generate unique images for 256 bit data. You could use a sha256 identicon generator, but instead of calculating sha256 digest of anything, just give it Tox public key as if it was sha256. The real question is whether a sha256 identicon algorithm can really generate 2^256 unique images.

**Comment by anthonybilinski** [comment]
For "Mode 1" of allowing user set avatars, I don't see the harm in allowing use of identicons over silhouette, since a user could manually set an identicon if they went through the work. I think it's a nice feature that generally looks nicer, and if the icons already aren't reliable for cryptographic identity since they are set-able, then why not?

If the user wants some cryptographic identifying feature, they can use "Mode 2" without the availability to manually set instead.

**Comment by tox-user** [comment]
This doesn't make sense to me. Shouldn't every user by responsible and in control only of their own avatar? What if I want my avatar to be my identicon and I want it to be seen (because it's my avatar)? I get it that someone might want to use the default image instead of an identicon for their own profile, but why give them an option to not see mine? Also how does such option add any value, why is it important?

Identicons can be stolen just like any avatar can be stolen. Those who actually know how identicons work know the fact that they are supposed to be unique, so it's true that they might falsely assume that identicons can't be stolen. Similar thing could be said about avatars. Some non technical people might not think of the fact that they can be easily copied and will wrongly think of them as a unique identifier. I don't think this is an issue with qTox. It's a problem of user's approach to security. Perhaps there should be a guide somewhere (maybe on the website?) explaining how to verify that the person is who they claim they are. This reminds me of a similar problem with exchanging PGP keys when you need a web of trust to verify someone's identity. Only "mode 2" as an optional feature proposed by nurupo seems logical to me, because it gives user a chance to increase security.

I think identicons are a very nice feature, but perhaps they shouldn't be implemented by a client but in toxcore. The reason for this is that every client might do them differently which would be very confusing for the users. For example if Alice is using uTox she might see a different identicon than Bob who is toxing on qTox.

**Comment by tox-user** [comment]
One more thing. Client could protect the user if it notices that multiple contacts on their friends list use the same name. If there are two users named Alice, it could change one of their names to Alice (2). Some programs actually do that. Maybe it could also somehow detect if there are multiple friends using the same avatar?

**Comment by sudden6** [comment]
@nurupo maybe entropy was the wrong word, 2^72 possibilities would have been better

The key point is:

Tox PKs have 2^256 possibilities while Identicons with our approach have at most 2^72 (I guess in practice it's more around 2^50) possibilities.

I think with this amount of possibilities it's possible to create "Identicon collisions" and find a ToxID which generates the same Identicon as a given ToxID. Thus this system is not secure, to verify the key, while in practice it's an easy way to distinguish contacts with out a username or avatar set.

@tox-user If this implementation works out, I certainly plan to try and publish it to TokTok so everybody uses the same algorithm.

Comparing usernames and avatars isn't trivial I think. For usernames you have Unicode symbols that look the same and for avatars you have to account for similar colors. Certainly doable, but not that easy to do it in a secure way.

**Comment by tox-user** [comment]
@sudden6 you are right about that. There was a similar problem with domain names that used unicode characters. I don't know any details, but I think web browsers managed to solve it with punycode: https://en.wikipedia.org/wiki/Punycode

**Comment by ProMcTagonist** [comment]
If you need to differentiate between qTox-created identicons as unique visual identifiers, and a copycat trying to set a similar-looking image avatar in order to impersonate, just give identicons some phenotype in the client UI that avatars are not able to express.

**Comment by nurupo** [comment]
This might be a little offtopic again, but I just noticed that some client devs seem to have decided on an identicon standard for tox clients, thought qTox devs might want to know of this https://github.com/TokTok/c-toxcore/issues/617.

**Comment by zoff99** [comment]
i see no difference between somebody using anothers Identicon or anothers avatar and name.

**Comment by sudden6** [comment]
@nurupo That spec is the algorithm I wrote for qTox ;)

**Comment by nurupo** [comment]
Good, would be confusing if clients had done identicons differently.

**Comment by sudden6** [comment]
Fixed by the linked PR
