### ISSUE TITLE
[Feature] Auto accept (video)calls from certain friends (babyphone)

### ISSUE THREAD

**Issue by spongioblast** [qTox/qTox#4887]
Hi

It would be great if its possible to set auto accept of video calls for certain friends. That way I could use Qtox on an android device to check up on our baby. 

I am truly concerned with those baby cameras everywhere with very dubious security standards.

Cheers

**Comment by sudden6** [comment]
Hi,
cool to see such interesting use cases :)

Currently auto-accepting video/audio calls is supported in the [contact details](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#contact-details) menu. Since it seems to be undocumented, a PR fixing that would be appreciated :)

> Qtox on an android device

Unfortunately, I'm not aware of qTox running on any Android device, or did you somehow make that work?

**Comment by tox-user** [comment]
It's always great to see people looking for secure alternatives! I was thinking of using the same method to make something like a security camera.

You can enable auto accept of calls when you right click on your contact and select "Show details".
![qtox auto accept call](https://user-images.githubusercontent.com/32248732/34542923-80fa24b4-f0d6-11e7-9ef5-f9834179e8a7.png)

On Android you can install Antox or some other client for that platform. Then use it to call your PC that is running qTox.

**Comment by Diadlo** [comment]
You maybe interested in https://github.com/zoff99/ToxCam

**Comment by tox-user** [comment]
Is it better than video calling with auto accept?

**Comment by Diadlo** [comment]
At least ToxCam is more lightweight

**Comment by sudden6** [comment]
Question seems answered.
