### ISSUE TITLE
Gain just introduces distortion, does very little to bring audio volume up to a usable level.

### ISSUE THREAD

**Issue by zorilya** [qTox/qTox#4893]
##### Brief Description
OS: Windows 7 SP 1 (6.1)
qTox version: v1.13.0
Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore: 0.1.10
Qt: 5.9.3
Hardware: Intel i7 930 running an out board audio interface.

The gain control introduces significant distortion despite have no audio read outs (including those is qTox) anywhere near peaking

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce
1. Log into and start an audio conversation through qTox using an audio interface with gain set at a nominal level for any voip chat normally.
2. observe the volume readout only barely hitting 1/8th of the meter 
https://i.imgur.com/ULGA1j5.png

3. set gain from default 50% up through to max and hear the distortion kicking in.

##### Observed Behavior
audio levels that one strains to hear or make sense of (well below the -30db mark)
while the gain just makes distortion

##### Expected Behavior
Audio levels that reflect the norm when using an audio interface at normal settings for other voip clients
A basic software compressor to raise levels as the threshold is set closer to the normal audio level.

An image of the average level during speech with a mic gained at the desk to the point just before peaking occurs. (so hitting -20db  to -15dB on normal speech). This is both with and without gain. (gain just introduces distortion, seemingly no volume increase).

**Comment by sudden6** [comment]
Did you try to increase the volume via the windows volume application?

**Comment by anthonybilinski** [comment]
as part of my PR https://github.com/qTox/qTox/pull/5068 for https://github.com/qTox/qTox/issues/5039 the volume display bar is changed. Previously the volume bar does not show volume after gain is applied, which would explain why "no audio read outs (including those is qTox) anywhere near peaking".

I'm guessing "set gain from default 50% up through to max and hear the distortion kicking in." is just sample clipping once you're at +30dB gain, despite it not being shown in any useful way to you (it is actually being applied to your contacts). With my PR clipping still isn't super obvious because some samples may clip but the overall average of the frame might still not quite be maxed, but from my testing the bar will be at at least 80% before you hear distortion from clipping. The display was also changed from sum of abs(samples) to RMS, which expands it more completely across the range.

Also a note re: "audio levels that one strains to hear or make sense of (well below the -30db mark)", the volume display is not in dB unlike the gain bar, so it being pinned to low end (especially before this RMS change) doesn't necessarily mean it's very quiet.

@zorilya can you give that PR a try and see if it's more what you expect?

**Comment by anthonybilinski** [comment]
@zorilya this is now merged into master, I'll re-open this ticket and let you see if your issue is resolved.

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
