### ISSUE TITLE
[Feature request] Sound on call end

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#4905]
##### Brief Description

A friend suggested to add a sound when a call ends, so you can hear when the connection drops or the other end hangs up even when qTox is in the background.

##### Steps to reproduce

1. let other end hangup audio call

##### Observed Behavior

Call ends silently

##### Expected Behavior

"Bling" sound to indicate the call has ended.

##### Additional Info

The sound has to have an open source license.

**Comment by tox-user** [comment]
Maybe this one (the second one)? :)
https://freesound.org/people/deraj/sounds/218083/

**Comment by sudden6** [comment]
Personally I'd like something more similar to the existing notification and call sounds.

**Comment by tox-user** [comment]
It would also be good to get a desktop notification on call end if the window isn't focused. Just like when somebody calls you.

**Comment by anthonybilinski** [comment]
I decided to not add an alert() like we do when you get a call in my PR. I feel like call end isn't really actionable for the user like receiving a call is, so there isn't really a need for them to switch to the window like there is when they're being called.

**Comment by tox-user** [comment]
My idea was that when someone is in an audio call and is not looking at qTox's window, but doing something else might not notice they got disconnected and keep talking for a while. Disconnects can be random sometimes.

**Comment by anthonybilinski** [comment]
Toxed with tox-user for a while, we can't come to an agreement and need some outside input.

I feel like a disconnect while they're not looking at window should still be handled by the end call sound since they'll have speakers on and everything during the call. If they're AFK when their friend hangs up, they can check their friend is still there or check qTox chat log. Any kind of notification/popup seems overly intrusive for a (normally) expected, non-actionable event.

Please contribute some opinions about where this should go

**Comment by tox-user** [comment]
I think that the end of the call is an important event and the user might want to know about it. It might or might not require user's attention. When someone doesn't have their speakers plugged in, went AFK or don't have their headphones on, they might not hear the sound and not realise the call has ended. It is similar to how we have desktop notifications for messages (and not just the sound).

The call can end for two reasons (that might require a notification):
- the caller hung up (call ended)
- we or the caller got disconnected (call was interrupted)

Both of those should get different sounds. I also think that we should improve our current desktop notifications and they should get a proper title and description, unlike they are now (https://github.com/qTox/qTox/issues/4979#issuecomment-370197274).

**Comment by sudden6** [comment]
I mostly agree with @anthonybilinski here, if you're in a call with someone you almost ever have speakers/headphones and can hear the call end sound.

I find the idea of different sounds for call ended and call was interrupted a good idea, maybe we can implement that easily.

The notification in #4979 aren't really notifications, but rather the gnome way to handle `alert()`. Real notifications (with more info) are a feature that was often asked for, but there was never a notification backend that supported all the needed platforms. Could be available now?

**Comment by tox-user** [comment]
> if you're in a call with someone you almost ever have speakers/headphones and can hear the call end sound.

If you are watching a video/playing a game/listening to music you might miss the sound. The notification should be optional - with a setting to turn it off.

> Real notifications (with more info) are a feature that was often asked for, but there was never a notification backend that supported all the needed platforms. Could be available now?

Maybe this: https://doc.qt.io/qt-5/qsystemtrayicon.html#showMessage ?

**Comment by anthonybilinski** [comment]
Going to leave notification as is for now (i.e. no notification on call end). I'm in favour of the idea of having a nice notification on call end, but don't think alert() is the right way to do it, and anything else seems way out of scope for this issue.

I think an error sound on call fail is a good idea, but it turns out I don't really like doing sound design and I don't want to keep https://github.com/qTox/qTox/pull/5056 pending for weeks more. Hopefully we get someone more interested in design and can drop in a nice sound for error(s) later.

Also RE: multiple sounds for different things, I was talking to @tox-user a while ago and he was apprehensive about having _too_ many different sounds, like how [Skype has at least 25](https://www.youtube.com/watch?v=HdsOP8FycHs) since it adds confusion for the user about what each sound means. IMO if the sounds are well designed users can usually tell what they mean even never having heard them before, but we should maybe put some thought into where we want to re-use sounds (i.e. a generic error sound) and where we want unique sounds (call failed, disconnected, device not working, etc).

For reference, here are our current sounds, with the new one being "ToxEndCall.pcm". The three can be played with VLC: [sounds.zip](https://github.com/qTox/qTox/files/1952764/sounds.zip)
