### ISSUE TITLE
Unable to send messages via qTox

### ISSUE THREAD

**Issue by old-m-offen** [qTox/qTox#4960]
##### Brief Description

OS: Windows 7 SP 1 (6.1)
qTox version: v1.13.0
Commit hash: 531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore: 0.1.10
Qt: 5.9.3
Hardware: 
…

habe qtox schon zweimal neu geladen. Kann leider keine meldungen empfangen oder senden. hinter gesendeten meldungen dreht sich immer die verbindung. was muss ich machen. gibt es eine genautsch Anleitung für den richtigen download. Wo kann dre Fehler liegen?

Translation by sudden6:

I have downloaded qTox twice. I'm not able to send or receive messages. Sending messages always show the turning circle (message in pending messages state). Is there a guide for the correct download? What could be the problem?

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

**Comment by sudden6** [comment]
Als erstes: Wenn möglich schreibe bitte auf Englisch, damit alle devs das lesen können, ich werde auch auf Englisch weiter schreiben. (for the non-German speakers, that's request to write in English if possible).

It's highly unlikely the qTox binary is broken, since it seems to work for others.

Things you need to check:
- Are you online? Your own status circle in the top left should be green.
- Is your chat partner online? qTox only works if both of you are online. To test, add `echobot@toxme.io` it's pretty reliable.
