### ISSUE TITLE
drop when importing the contact list

### ISSUE THREAD

**Issue by PKEv** [qTox/qTox#4962]
##### Brief Description

OS: Windows 64x
qTox version: 1.13
Commit hash:  531defd0aa66af1b128f7293bc08718ce2cc064f
toxcore:  0.1.10
Qt:  5.9.3

Reproducible: Always 

##### Steps to reproduce

1. try import contact list like this:
25925602206E214F7282647233DD2530....
F5FB05866A60C47CF29A6D7F521C5E88..
B931AED50AAE998BA7BED57A352CA56.
2AA55A6C53EBE57925603B4FD2BFF889....
BF4078493B03B4109181ED61820E442.
A7C55BA3A4FD8599FB0B118E270486....
C228A51AC7632C2DBA1F5F12C052....
D63BB66EE6D83D0476C22415D20....
5BEE775A33A80F97CC9E45BF789...
4260D93239E54233FA48EECF888B.....

##### Observed Behavior
crash

##### Expected Behavior
must send to all contacts request 

If to send on one that works

**Comment by sudden6** [comment]
> If to send on one that works

Can you reword that? I don't understand.

**Comment by Diadlo** [comment]
@sudden6 Probably "If send by one that works"

**Comment by PKEv** [comment]
@Diadlo yes, thank you

importing by list does not work at all,  the program is crash when you select file

**Comment by anthonybilinski** [comment]
https://doc.qt.io/archives/qt-5.8/qlistiterator.html#QListIterator
>Constructs an iterator for traversing list. The iterator is set to be at the front of the list (before the first item).

https://doc.qt.io/archives/qt-5.8/qlistiterator.html#details
>The next() function returns the next item in the list and advances the iterator. Unlike STL-style iterators, Java-style iterators point between items rather than directly at items.

So it looks like our iterator is invalid and will always crash on first access (gdb shows it crashing on .value() on first iteration). I can't see how this would have ever worked in the year since it was added..
Solution to continue using java-style iterators is to call next() at the top of the loop instead of at the end. I PRed with C++-style iterators instead, since they don't have this wacky "iterator is between elements" thing.
