### ISSUE TITLE
Profile not loading automatically

### ISSUE THREAD

**Issue by Kron4ek** [qTox/qTox#5025]
##### Brief Description

OS: Gentoo Linux
qTox version: 1.14.0
toxcore:  0.2.1
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce

1. Check Load automatically checkbox
2. Restart program

##### Observed Behavior

Profile not load automatically.

##### Expected Behavior

Profile should load automatically.

##### Additional info
Here is log. But looks like nothing interesting there.

[qtox.log](https://github.com/qTox/qTox/files/1832154/qtox.log)

**Comment by anthonybilinski** [comment]
I just tested this locally and can't reproduce the issue.

Is your profile encrypted (has a password)? If so, starting automatically isn't possible since entering the password is required.

Otherwise, can you provide more detailed instructions for reproducing?

**Comment by Kron4ek** [comment]
@anthonybilinski, no, profile is not encrypted. I compiled qtox 1.14.0, started it, created an unencrypted profile and checked "Load automatically" checkbox. After restart profile not loads automatically, but checkbox stays checked. Thats all steps to reproduce.

**Comment by Kron4ek** [comment]
Btw, it loads profile if i specify -p profile_name argument.

And i just found that after i specify -p profile_name argument once time, the second time profile loads automatically even without -p argument. So thats the workaround.

**Comment by Kron4ek** [comment]
And i just found that after i specify -p profile_name argument once, the second time profile loads automatically even without -p argument.

**Comment by Kron4ek** [comment]
Also i found that when i create profile without password in the way just not touch password forms, this profile auto loading bug i described is appears. But when i fill some characters in password forms and then remove all characters (so the profile will be unencrypted) that bug is not appears.

**Comment by anthonybilinski** [comment]
A few things about qTox's login behaviour:
1. When qTox runs, it tries to run the last run profile.
2. The last run profile isn't updated when you select a new profile form the login screen (bug: #4948)

Given that, I have the following repro case locally:
1. Run qtox with an encrypted profile, i.e. `qtox -p encryptedProfile`, exit.
2. Run qtox, `qtox`, taken to login screen. Select "Load automatically", select an unencrypted profile from drop down list, load. Exit.
3. Run qtox, `qtox`, taken to login screen.

What's happening is in the first run, the "last run profile" is set to the encrypted profile. In the second run, the "last run profile" is not updated, since the profile is selected from the login screen (bug). On the third profile, it attempts to run the first profile, and takes you to the login screen since it's encrypted. The login screen's initially selected profile is alphabetical, not indicative of the selected profile.

This would also explain why running with `qtox -p unencryptedProfile` seems to fix the problem for you, since that correctly updates the "last run profile", unlike the login screen.

Can try running with the change from https://github.com/qTox/qTox/pull/5008 (which updates last run profile after login screen selection) and see if it resolves this issue as well?

**Comment by Kron4ek** [comment]
> Can try running with the change from #5008 (which updates last run profile after login screen selection) and see if it resolves this issue as well?

Just tried. Yes, this commit resolves this issue.
