### ISSUE TITLE
[OS X] accessing audio config tab goes to spinning pizza

### ISSUE THREAD

**Issue by jbshirk** [qTox/qTox#505]
accessing audio config tab goes to spinning pizza

**Comment by krepa098** [comment]
Duplicate of #408

**Comment by zetok** [comment]
if it's a dup, can it be closed?

**Comment by tux3** [comment]
Well, it's still a valid bug. Either open or closed are fine imo.

**Comment by suhr** [comment]
Can be closed.

**Comment by zetok** [comment]
Closing, since it's about a very outdated qTox build.

Currently there are no binaries of recent qTox for OSX available - I've talked to @TheSpiritXIII , and thankfully he agreed to try to make builds for OSX after GSoC will end.

If problem will still persist even with new builds, please comment for reopen / make a new issue.
