### ISSUE TITLE
Waiting to pickup duration

### ISSUE THREAD

**Issue by darkman088** [qTox/qTox#507]
Hello,

currently, when initiating a voice call with uTox, the call keeps ringing just for a very short time (maybe around 10 seconds). I would kindly like to ask you, whether it would be possible to increase this time.
As stated here:

https://github.com/irungentoo/toxcore/issues/1130

It is a client issue, hence I am opening a new issue both for uTox and qTox. Many thanks!

**Comment by tux3** [comment]
We're currently ringing for 15s. Would 45s be reasonnable ?

**Comment by msteinbeck** [comment]
Maybe add an option in settings dialog?

**Comment by agilob** [comment]
> Maybe add an option in settings dialog?

Or no limit?

**Comment by darkman088** [comment]
45-60 seconds would be perfect. No limit can cause harm, like draining the battery of somebody who is on a smartphone but can't hear the ring in order to pick up... An option in the caller's interface impacts also the one being called, so I am not sure that this is fair...

**Comment by tux3** [comment]
No limit isn't possible by design of toxcore, or at least the documentation doesn't mention it.

imho an option wouldn't do much harm, after all the people calling you are supposed to be your friends and you can cancel the call to stop the ringing, but I'll just change it to 45s for the moment.

You can make a new issue for the option, if you want (or not).

**Comment by darkman088** [comment]
Hello tux3 and THANK you so much for setting it to 45 seconds !! Kindly let me know when will I be able to download the version with the implemented modification and from which URL.
Also you mentioned something, that made me really curious! You said "you can cancel the call to stop the ringing" - can you kindly enlighten me how to do that, because this is an option that I've been missing, but according to your statement, it is possible !!

Thanks a lot once again!

**Comment by tux3** [comment]
> Hello tux3 and THANK you so much for setting it to 45 seconds !! Kindly let me know when will I be able to download the version with the implemented modification and from which URL.

If you are on Windows, you can download the new version here : https://github.com/tux3/qTox/releases/download/qtox-windows-1414094096.94/qTox-win32.zip
If you're on Mac, a new version should appear here today or tommorrow : https://jenkins.libtoxcore.so/user/tux3/my-views/view/qTox/job/qTox%20OS%20X/
If you're on Linux, a new version should appear here today or tommorrow : https://jenkins.libtoxcore.so/user/tux3/my-views/view/qTox/job/qTox-Linux-pkg/

> Also you mentioned something, that made me really curious! You said "you can cancel the call to stop the ringing" - can you kindly enlighten me how to do that, because this is an option that I've been missing, but according to your statement, it is possible !!

Oh you're right, it's not actually possible right now. Well, I'll make a new issue because that should definitely be possible! Sorry!

**Comment by darkman088** [comment]
Hey, you don't have to apologize :-) You are the super master here, you changed the ring duration just within a few hours after I requested it :-) You really rock on that !!!
May I please ask you how do you intend to implement this ? Add a red button in the interface for rejecting calls or how exactly ?
Also I would kindly ask you to let me know, once it has been implemented, so I can download the release, containing that :-) It is sooo COOL to have new versions on a daily basis!! Thanks !! :-)

**Comment by tux3** [comment]
> Hey, you don't have to apologize :-) You are the super master here, you changed the ring duration just within a few hours after I requested it :-) You really rock on that !!!

No problem :)

> May I please ask you how do you intend to implement this ? Add a red button in the interface for rejecting calls or how exactly ?

It's not decided yet, but we can discuss that here : https://github.com/tux3/qTox/issues/515

> Also I would kindly ask you to let me know, once it has been implemented, so I can download the release, containing that :-) It is sooo COOL to have new versions on a daily basis!! Thanks !! :-)

Sure, I'll try to remember. You can subscribe to #515 in the meantime if you want to be updated on the progress.
