### ISSUE TITLE
segfault before sending first video frame

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5108]
##### Brief Description

OS: openSUSE Leap 42.3
qTox version: v1.15.0-10-gf7345e4d
Commit hash: f7345e4db264a5681490b9094981a65cac68d317
toxcore: 0.2.2
Qt: 5.6.2
Hardware: Thinkpad T440p

Reproducible: Always

##### Steps to reproduce

1. ensure video camera is displaying a picture in settings
2. videocall echobot@toxme.io

##### Observed Behavior

qTox crashes

Backtrace: https://gist.github.com/sudden6/fab3b3f70c49edf876f47420a9c84ab2

Source Line of crash: https://github.com/qTox/qTox/blob/master/src/core/coreav.cpp#L426

##### Expected Behavior

Videocall works

**Comment by sudden6** [comment]
Could someone please try to verify? I think this could also be a problem in my video setup which happened before.

**Comment by sudden6** [comment]
I'll give this low priority since it doesn't happen on a different system.

OS: openSUSE Tumbleweed
qTox version: v1.15.0-14-g3f00e854
Commit hash: 3f00e85486280099951b22b39a9fa676b9545b02
toxcore: 0.2.2
Qt: 5.10.0

**Comment by anthonybilinski** [comment]
I can't reproduce this on 9cd9da4a5360028bab32bb7f04d95e67e895cc0d, and running under ASAN shows no dangerous memory. We also haven't gotten reports about it. It seems like this has been fixed in the last few years or was some version specific dependency issue on your first system.

Feel free to re-open if you disagree.
