### ISSUE TITLE
use unique_ptr for groupChatForms

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5115]
from #5113 by @anthonybilinski :
>If we delete the GroupChatForm* anytime it's removed from groupChatForms, it would be a great place to use std::unique_ptr. It would save this ordering issue and also remove the need for looping over the map in ~Widget. This fix is still fine as is.

**Comment by ghost** [comment]
@sudden6 Hello.
May be replace raw pointer to QSharedPointer instead of std::unique_ptr? 
Beacuse:
- or Qt containers better use a Qt smart pointers (https://stackoverflow.com/questions/16263117/qmap-and-stdunique-ptr) 
- QMap (maybe other Qt conteiners) don't have a move insert implementation
- in widget.cpp for connect (socket) used a groupChatForms elements

**Comment by anthonybilinski** [comment]
Fixed by https://github.com/qTox/qTox/pull/5415.
