### ISSUE TITLE
Camera crashes qTox

### ISSUE THREAD

**Issue by marconat** [qTox/qTox#5119]
quand je lance la caméra sur Qtox le programme s arrete automatiquemet a chaques fois

OS: Windows 10 (10.0)
qTox version: v.1.14.1
Commit hash: fe552f28b63c7e7ae8159d2b55cb921dd45d9c1d
toxcore: 0.2.1
Qt: 5.9.3
Hardware: 
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. 
2. 
3. …

##### Additional Info
(links, images, etc go here)

----

More information on how to write good bug reports in the wiki: https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by mschilli87** [comment]
Please translate your question to English/Traduire votre question en anglais, s'il vous plaît:
["when I run the camera on Qtox the program stops automatically every time"](https://translate.google.com/#fr/en/quand%20je%20lance%20la%20cam%C3%A9ra%20sur%20Qtox%20le%20programme%20s%20arrete%20automatiquemet%20a%20chaques%20fois)

I would translate 'lancer' with 'to launch' instead of 'to run' but I wanted to make the point that no knowledge of English or French is at all required to make this issue more understandable for the majority. :wink:

**Comment by sudden6** [comment]
You are using an outdated version of qTox, download the newest release, it contains many camera fixes for Windows. If that fixes your problem you can close the issue.

**Comment by Schweineschwarte** [comment]
Hello,
if I do a Videochat (with camera or sharing desktop) qTox crashs. If I configure "no camera" in the options, qTox Videochat runs fine (but I see onyl the profilpicture).

My system:
openSUSE 42.3 64bit
KDE/Plasma (Qt-Version: 5.6.2)
qTox-Version v1.14.0
Toxcore-Version: 0.2.1

**Comment by zetok** [comment]
No response for over a month, assuming it was fixed, thus closing.

If issue is still not fixed, please comment for reopen.
