### ISSUE TITLE
Tagged v1.15.0 Release Missing Signature

### ISSUE THREAD

**Issue by quantumpacket** [qTox/qTox#5125]
My automated build script failed during git tag verification due to the [latest release](https://github.com/qTox/qTox/tags) missing a signature. :cry: 

> $ git tag --verify v1.15.0
object 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
type commit
tag v1.15.0
tagger Anthony Bilinski <me@abilinski.com> 1524171597 -0700
>
> qTox v1.15.0 release. For details see CHANGELOG.md.
error: no signature found

**Comment by anthonybilinski** [comment]
Confirmed:
```
git tag -v v1.15.0
object 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94
type commit
tag v1.15.0
tagger Anthony Bilinski <me@abilinski.com> 1524171597 -0700

qTox v1.15.0 release. For details see CHANGELOG.md.
error: no signature found
```
I must have dropped the signature when moving the release tag for the hotfix from 3c15cd2b10dc084416ead98eb9c270578642d436 to 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94 right after pushing the first tag =/

I can sign a new tag and overwrite the current one in the same place which will update our download artifacts. Does this sound like it would break anything (@sudden6 @Diadlo)?

**Comment by sudden6** [comment]
@anthonybilinski I don't think that's the best idea, because the release is out for pretty long time. Maybe create a v1.15.1 tag and release?

**Comment by anthonybilinski** [comment]
I'm fine either way, but since we wouldn't be changing the git commit or any files, does it matter that v1.15.0 has been out a while? If none of our build artifacts change hash and all that's changed is adding a signature to the tag, then IMO a new release isn't required. I'll test locally and make sure changing the tag does indeed not change artifact hashes. Does anyone object and think v1.15.1 is required?

**Comment by sudden6** [comment]
ok for me

**Comment by anthonybilinski** [comment]
Testing locally, it looks like signing and replacing the tag doesn't change
1) qtox hash of linux build
2) tarball hash

but both
1) appImage
2) windows cross compile

change hashes every build. Since hash of non-signed artifacts was enough to create issue in https://github.com/qTox/qTox/issues/5140, and new build artifacts will probably be triggered since we would be pushing a new tag, I think making a v1.15.1 release is required. If we're going to go through release work-flow, might as well include some bug fixes in the patch release, I think.

**Comment by quantumpacket** [comment]
Is there a step in the release process to verify signatures are present and valid before releasing? So to avoid accidental unverified releases in the future. :)

**Comment by anthonybilinski** [comment]
Apparently not, but I agree there should be. I'll look into that as part of this release.

**Comment by tox-user** [comment]
>Does anyone object and think v1.15.1 is required?

Audio group chats don't work and there have been a few important bug fixes that we could include.

**Comment by tox-user** [comment]
It's not necessary to have 1.15.1, but I think we should release this month.

**Comment by quantumpacket** [comment]
closing as newer releases available
