### ISSUE TITLE
SHA-256 changed for version 1.15.0

### ISSUE THREAD

**Issue by gtmgianni** [qTox/qTox#5140]
##### Brief Description

OS: macOS
qTox version: 1.15.0 

The SHA-256 hash for the `.dmg` file for version `1.15.0` has changed, despite there being no increment in version number.

[For the purpose of this pull request](https://github.com/caskroom/homebrew-cask/pull/47107), could a developer please verify that this change was legitimate, and not malicious? Thank you in advance.

(verification is required due to [these Homebrew-Cask guidelines](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256))

**Comment by sudden6** [comment]
@anthonybilinski is this maybe fallout from the one force push?

**Comment by anthonybilinski** [comment]
I moved the v1.15.0 tag from 3c15cd2b10dc084416ead98eb9c270578642d436 to 02d6c63acaac0ae95fa8be3a1b9301657e6a4a94 within about 1hr of the release to include a typo fix in some build config. This would change the .dmg file hash as our git hash is included in he build. The .dmg hash should not have changed since then (about 25 days ago from today.)

Does this make sense from when you got your first and second hash of the .dmg file?

**Comment by gtmgianni** [comment]
@anthonybilinski I believe it does – the previous pull request used a SHA-256 that was calculated just under an hour before you moved the v1.15.0 tag. Thanks for the confirmation.
