### ISSUE TITLE
Rejecting an incoming call

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#515]
Maybe right clicking could reject an incoming call. Or maybe another button/a menu on hover?

**Comment by agilob** [comment]
I think I can do that in notification, but this will have to wait, I got a lot of work from univ.

**Comment by darkman088** [comment]
I think that adding a new red button, as on all the cell phones will be the most elegant solution.
By right clicking, it might be the easiest to implement, but it won't be intuitive - one would need to know
about the feature, otherwise it's quite hard to discover... And for the Mac users you can forget the right click for sure :-D

**Comment by TheLastProject** [comment]
What about a drop down menu on the "incoming call" button, giving you an option to reject?

A bit like this but much less ugly: 
![snapshot69](https://cloud.githubusercontent.com/assets/1885159/4769355/ba4d73ac-5b78-11e4-9201-6775e22d7503.png)

Of course, a reject button in the notification would also be good.

**Comment by darkman088** [comment]
I do not like the drop down menu option. It is too cumbersome... I have seen software like that, I do not remember the exact example but I do not like it...

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by ItsDuke** [comment]
@darkman088 I'm inclined to agree. Ultimately the user should be able to accept or deny a call with just one click. Making them go through a dropdown just means extra work for the user, and we don't want that.

The main question I have is, are you currently viewing this person's chat window and they initiate a call, or are you in a chat with someone and a completely different contact initiates a call? Only asking because each one needs a different handling.

**Comment by agilob** [comment]
Let me show my vision:
![stage1](https://cloud.githubusercontent.com/assets/2544251/4885855/8d064890-6377-11e4-9a78-3f02305fe0f6.png)
![stage2](https://cloud.githubusercontent.com/assets/2544251/4885854/8ce460b8-6377-11e4-9d49-85ec9444967b.png)

After call is ended it comes back to the first stage where both buttons are green.

I have it implemented and it works but needs CSS some polishing and more opinions.

**Comment by ItsDuke** [comment]
How do folks feel about something like this?

![ring](https://cloud.githubusercontent.com/assets/7714365/4890594/6b18824c-63a0-11e4-9b2d-bc875be41a3d.gif)

**Comment by tux3** [comment]
I like the idea. 
It looks like a tooltip, so does it only appear when the mouse is over the call button ? Should it stay here until you dismiss it ?

**Comment by darkman088** [comment]
@ItsDuke:
The main question I have is, are you currently viewing this person's chat window and they initiate a call, or are you in a chat with someone and a completely different contact initiates a call? Only asking because each one needs a different handling.

-> The first possibility is the one that is more likely to occur. But the second one is NOT handled in qTox/uTox at all !!! If a completely different contact initiates a call, it is VERY cumbersome to find out WHO that exactly is. As I have already recommended here:

https://github.com/tux3/qTox/issues/590

the best would be to make a context independent area in the client! Meaning that if someone calls, it should be possible to pickup immediately, and not first having to search who is calling, meanwhile it easily turns into a missed call, bearing in mind that the ringing duration is only 10 seconds!! Similarly to a cell phone - you don't need to find who is calling in the phone book, before being able to pick up!
Your black incoming call window looks nice, just, IMHO, it HAS to popup no matter who is calling! And the place you are showing it is a little bit confusing - maybe if it comes out of the notification area it would be better...

@agilob - honestly, I like your proposal better! Just the red and the green buttons should be the same size as the video call button, is that a problem ? As you are showing them only half-size. And they SHOULD work no matter who is calling, but that might be more difficult to implement... Kindly let me know, also, once again, please read my ideas from the link above!

**Comment by ItsDuke** [comment]
@darkman088 Good feedback, let me make a few edits.

@tux3 no, it would display until an action is selected, or until the call auto-terminates.

Also, does it really not show up immediately when a non-selected contact calls? Ouch.

**Comment by suhr** [comment]
> the ringing duration is only 10 seconds

@darkman088, it was fixed a long time ago: https://github.com/tux3/qTox/issues/507

**Comment by tux3** [comment]
> Also, does it really not show up immediately when a non-selected contact calls? Ouch.

It shows up in the contact list and you should get a ringtone.
![image4](https://cloud.githubusercontent.com/assets/5155966/4897290/c618226a-6404-11e4-83f5-1efb814576b6.jpg)

**Comment by agilob** [comment]
@tux3 maybe the circle could be replaced by phone when someone is calling?

**Comment by suhr** [comment]
Also, what about showing someone calling on the top of the contact list?

**Comment by darkman088** [comment]
Yes, it is really not shown! Showing someone calling on the top of the contact list - I do not think that this is a good idea. Other chat programs are doing like that and I do not like it.
What is so wrong in a bubble popping up and saying - this contact is calling and 2 buttons to accept and reject the call ?
Replacing the green dot by a phone does not help, when the person calling is at the bottom of the contact list, and one have to scroll until he gets there.
I really think and I am standing for one of the following solutions:
1) A bubble, as said above, this has already been implemented for chats (at least in uTox) and I REALLY LOVE this feature, because when I browse the net for example, just the bubble shows up and I can read my messages without even switching to the Tox client !!!
2) As soon as someone calls, the context on the top icons should change to the person calling. Although I think that this will be harder to implement and I do not want to force in this direction. So maybe 1) would be the best way to go... 
But anyway, there is for sure the need for a red button, in order to be able to cancel wrongly dialed calls!

**Comment by suhr** [comment]
> What is so wrong in a bubble popping up and saying - this contact is calling and 2 buttons to accept and reject the call ?

Well, what if two or more contacts are calling it the same time?

**Comment by darkman088** [comment]
I think that it is not possible to call absolutely at the same time. Just the first in the line should get through and a busy message should be shown for the others. I am although curious about the current situtaion as I did not test this...

**Comment by tux3** [comment]
> What is so wrong in a bubble popping up and saying - this contact is calling and 2 buttons to accept and reject the call ?

Notifications (bubbles) are a different thing, we'll have those eventually. But we still need something in the chat window, what if you miss the bubble or don't want to enable notifications ?

**Comment by agilob** [comment]
@darkman088  My (working) prototype is available [here](https://github.com/agilob/qTox/tree/reject_call) I'm able to reject calls from uTox. Works for audio and video calls.

**Comment by darkman088** [comment]
Hello agilob! I am amazed how fast you deliver! Please help me a bit what exactly to look for "here". I did not see windows binaries "here", just an icon for windows :-D Or I am supposed to build it myself ?
Come on, don't be so harsh on the poor admin :-D

**Comment by agilob** [comment]
Yea, it's a branch which you're supposed to build yourself. Basically what I did:
1. Incoming call
1.1 Button answer call is 25px wide instead of 50px, new 25px button appears. My idea was to make those two buttons look like one, right side rejects call, left answers
1.2 the red one, yellow button answers the call, the red one rejects the call
1.3 during call the red button disappears, the yellow button is again 50px wide, click it to end call
2. after the call button "answer" is green again

It needs some css polishing like, rounded corners when reject button is visible and some more, more details, check it out, tested with µTox: https://upload.agilob.net/qtox.mkv sorry for the mkv, will record with different codec next time.

Tox me if you need help: 7119F8F3B55FCA07F78CC78003F9F9FCE70B2C0AEF3649F3A84C87EA56BE927FB2D2D62ADEE0

**Comment by darkman088** [comment]
Hello agilob! Thanks a lot, but I am not sure how exactly build a program on windows, the chances for me to succeed are better on Linux or some unix. Kindly let me know, once this gets accepted into a 
normal daily release, then I will install and test it. Bye :-)

**Comment by darkman088** [comment]
Hello,

can you kindly update me what happened with this one ? This thread looks like... kinda dead...

**Comment by darkman088** [comment]
Hello agilob,

I really miss your enhancement, which looks soooo good on the screenshot! I have added your Tox ID to my buddy list a few days ago, but I never saw you online...

**Comment by agilob** [comment]
@darkman088 I'll back to qtox development on Tuesday. Recently I only read what's going on here, but I don't respond, don't have time for that now. I'll try to make ready PR before end of next week.

**Comment by darkman088** [comment]
Hello agilob! That's fine, thanks for the information! Wish you all the best and good luck!
