### ISSUE TITLE
Provide the AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [qTox/qTox#5151]
https://github.com/qTox/qTox/blob/64a7c24b2b5ad11a6df5dbb11da6e3aa7c0fd6f3/appimage/build.sh#L132

Please provide the AppImage for download on GitHub Releases. This way, we can add it to the AppImageHub central directory of available AppImages. Thank you.

**Comment by sudden6** [comment]
We will, starting with the next release.

**Comment by sudden6** [comment]
This is now done as of v1.16.1

**Comment by probonopd** [comment]
Thank you very much. Please consider adding `-x86_64`after the version to the filename to indicate the platform.

**Comment by probonopd** [comment]
`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`, please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and especially https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

References:
* https://github.com/AppImage/appimage.github.io/pull/687
* https://travis-ci.org/AppImage/appimage.github.io/builds/401919227#L606

**Comment by sudden6** [comment]
I'll reopen until it is fixed.

**Comment by sudden6** [comment]
I have renamed the files and modified the build scripts to include `x86_64` in the future.

For the other thing you mention, do I understand you correctly that this is happening only when running the AppImage on a system before the one we built it for? (Debian 9 - Stretch)

If that's the case, I think we can live with that for now, because building qTox for older systems is probably not worth it.

**Comment by probonopd** [comment]
Yes, a Linux binary is expected to run on systems _newer_ than the system it was built on, but not on systems _older_ than it was built on. So in order for a binary to work on all currently supported releases of a distribution, it is good practice to build on the oldest still-supported distribution. In the case of Ubuntu, the oldest still-supported LTS release is 14.04 at the moment, which is why we are generally recommending to target this one (and also test using this one in our automated tests for AppImageHub).

**Comment by sudden6** [comment]
Ok, I don't have plans atm to support back to 14.04 because that would mean building a lot of the dependencies too. For now Debian 9 will be the oldest supported distro then.

Is there any way to indicate the oldest supported distribution in an AppImage? Or show a more useful error message to the user?

**Comment by probonopd** [comment]
> Is there any way to indicate the oldest supported distribution in an AppImage? Or show a more 

Unfortunately we don't have this at the moment, so the only error is what the user sees when the AppImage is executed at the command line. Somehow catching this and displaying a GUI notification would be a good idea but I have not found yet a way to do this. Possibly we could do it using libnotify.

**Comment by sudden6** [comment]
Ok, thanks then I don't have further questions at the moment and will close this issue.

**Comment by tox-user** [comment]
libnotify is for desktop notifications. I think you need a popup window instead?

**Comment by probonopd** [comment]
I don't think there is an easy cross-desktop-toolkit way of showing these...
