### ISSUE TITLE
size of array ‘_GStaticAssertCompileTimeAssertion_1’ is negative

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [qTox/qTox#5153]
##### Brief Description
Cannot compile qtox from source on opensuse tumbleweed

OS: openSUSE Tumbleweed
qTox version: master
Commit hash:  master
toxcore:  0.2.2
Qt:  5.10
Hardware: Dell t3500 
…

Reproducible: Always 

##### Steps to reproduce

1. run make in qtox source

##### Observed Behavior
It doesnt compile. Error
size of array ‘_GStaticAssertCompileTimeAssertion_1’ is 

##### Expected Behavior
It should compile

##### Additional Info
Whole compile log is here http://paste.opensuse.org/59312060

**Comment by ezavod** [comment]
@Michal-Szczepaniak Would you mind to post the output of single threaded make (use `make` instead of `make -j12`)? This would be easier to read.

Have you checked #1521?
Seems to be a similar error. In general this is probably caused by a mix-up between 32bit and 64bit libs (at least all the results of an internet searche suggest this).

**Comment by Michal-Szczepaniak** [comment]
I just found out that opensuse does have precompiled binaries so im closing this issue
