### ISSUE TITLE
[Q&A] I tried your software 2 years ago; does qTox improved since then?

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#5157]
Hi there.

Can anyone answer this question: does these thing improved/fixed?

- Online contacts shows "offline" in contact list
- Use too many bandwidth, and no option to force bandwidth limit
- Unable to disable debug log files

Do you think qTox is better than Ricochet? Am looking for an alternative atm.
https://github.com/ricochet-im/ricochet/issues/579

**Comment by ilovelinux** [comment]
- I never had similar issues recently
- The bandwidth it uses is the bandwidth it needs to work, for this reason you can't limit it. Anyway it's a toxcore "issue" and toxcore's development goes on during two years.The answer to your question is: yes, they solved some bandwidth issue but it still uses more bandwidth than a centralized-based messaging app because of P2P.
- Why should you disable debug log files? If you hate them so much you can create a symlink to /dev/null :P

qTox it's not better nor worst than Ricochet, it's different. They work in two different ways. Anyway qTox supports group chat, audio/video calls and so on.

**Comment by sudden6** [comment]
> Online contacts shows "offline" in contact list

This bug has been fixed in toxcore

> Use too many bandwidth, and no option to force bandwidth limit

For me qTox idles at <10KB/s, which is background noise in my bandwidth consumption. Depends on how many friends/groups you're in,...
There are no plans to implement a bandwidth limit, because this would severely hurt usability and be a huge task.

> Unable to disable debug log files

Still the case, I see no reason why one would like to disable them though.

I'll leave the discussion of ricochet vs qTox to others as I'm obviously biased ;P

**Comment by tox-user** [comment]
>Use too many bandwidth

It's been improved. Disabling UDP mode might also help, but then TCP nodes can see who you talk to (not the contents of your messages though because Tox is always encrypted).

>Unable to disable debug log files

Why would you want to disable that?

**Comment by tox-user** [comment]
> Do you think qTox is better than Ricochet?

qTox is a Tox client. There are many of them. I've never used Ricochet and there is no much information on it's website, but I can see that Ricochet uses Tor to connect you to your peers. Tox does not use Tor (works over clearnet), but you can run it through Tor, if you want to be anonymous. You should read this:
https://tox.chat/about.html
https://tox.chat/faq.html

**Comment by tox-user** [comment]
It has been answered, so closing.
