### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5166]
When qTox is started, its process size is ~250MB.
When I click on each tab in Settings (one after another) and come back to "General" its size grows to ~290MB.
When I click on each tab in Settings again, its size grows again, and then again. Now it is ~317MB. Webcam gets engaged on its tab, but this shouldn't matter.

I strongly suspect that it loses memory. Process size shouldn't increase every time some action is performed and then the state is brought back to the original.

------

Related suggestion: Add the option of using google perftools malloc library (https://github.com/gperftools/gperftools). When perftools is enabled, display the current memory consumption (perftools has this function) somewhere on the Settings screens.

This will allow to catch memory leaks as small as 1 byte. Also perftools allows to profile leaks, find what code leaked memory.

perftools does provide libtcmalloc.pc.

**Comment by tox-user** [comment]
What version are you using? There have been some memory usage improvements not that long ago. ~~Are you sure it's the settings that cause the increase in memory usage? The reason why your qTox uses so much memory is messages. If you have a lot of them for multiple contacts it can have that effect. So maybe you received new messages in that time which caused the increase in memory usage?~~ I confirm that it happens.

**Comment by tox-user** [comment]
Confirmed in 1.15.0 22f7f958edbb213cf5e9e86da5083c1813ea916f.

**Comment by yurivict** [comment]
Version 1.15.0, no messages were received at this time. Only switching between tabs caused the process size to go up.

**Comment by ghost** [comment]
Tried reproduce on newest version:
- on windows: don't see a leek. 
- on linux: see increase mem size process from ~100Mb to ~160Mb but no more 160.

**Comment by tox-user** [comment]
@QweEwq2016 have you used exactly the same version of qTox on both?

**Comment by ghost** [comment]
@tox-user i used compiling from clone for linux and v1.15.0 for windows.

**Comment by anthonybilinski** [comment]
If the memory increases then doesn't decrease, that may not be a leak. A leak should keep increasing each time the action is repeated.

I saw memory increase with history being loaded and not decrease when cleared as part of https://github.com/qTox/qTox/issues/5078, but it doesn't seem to continually increase if loaded again. The root cause of both issues might be the same, maybe some buffer/cache/something that grows and doens't shrink, but isn't actually losing memory.

**Comment by ghost** [comment]
@anthonybilinski maybe you give this issue?

**Comment by anthonybilinski** [comment]
Testing on d19ae1ead0db730a800af1e24a7683ca5a08bd79 on a profile with some but not very much history,
1. Memory when starting is 126M
2. After cycling through each setting page, memory is 137M
3. Cycling through the tabs again, memory is 140M
4. Again, 142M
5. Repeat like 10 more times, memory grows to 158M, but then drops to 157M, and doesn't grow past 158M

It seems related to the A/V pane, which initializes a videos/audio devices to show previews. I'm guessing this growth is just the cost of first time setup.

Checking with a leak detector (ASAN=ON from cmake config), no leaks are found after opening, cycling through settings tabs, and closing.

I think this is probably just some audio/video first time initialization that's creating buffers etc that are reused on subsequent runs.

Our memory use has been decreased since this was opened, and leaks have been fixed, so it could have possibly been a leak in the past, but based on the behaviour on d19ae1ead0db730a800af1e24a7683ca5a08bd79 I'm going to close.
