### ISSUE TITLE
Settings not saved after Windows shutdown without clean exit

### ISSUE THREAD

**Issue by zl3ai** [qTox/qTox#5179]
Brief Description

OS: Windows 10 (10.0)
qTox version: v.1.14.1
Commit hash: fe552f28b63c7e7ae8159d2b55cb921dd45d9c1d
toxcore: 0.2.1
Qt: 5.9.3
Hardware: Toshiba Netbook
…

Reproducible: Always

Steps to reproduce

1.  Set font size to e.g. 24px.
2.  Shut down computer
3.  Restart it

Observed Behavior - Font size has reverted to 12px

Expected Behavior - Font size should be remembered as e.g. 24px.

**Comment by sudden6** [comment]
Your qTox version seems to be outdated, can you check if this also happens on the newest version?

**Comment by zl3ai** [comment]
I've just installed v1.15.0 and it still happens.

**Comment by ezavod** [comment]
@zl3ai Does changing the font size and quiting qtox normally work?
Maybe similar to #4470.

**Comment by tox-user** [comment]
I can't reproduce by closing normally. It must be that we only save this on quit.

**Comment by sudden6** [comment]
A log file could help.

**Comment by HoraceBianchon** [comment]
I can reproduce it always. After shutdown machine not saving all (global, personal) settings.

OS: Windows 10 (10.0)
qTox version: v.1.14.1
Commit hash: https://github.com/qTox/qTox/commit/58dfd834784dc376d971cab51a70d896fb7efd89
toxcore: 0.2.3
Qt: 5.9.6

**Comment by zl3ai** [comment]
Just browsed back though older issues and found a similar one at https://github.com/qTox/qTox/issues/1969

**Comment by anthonybilinski** [comment]
I can't repro by:
1. open qTox
2. change font size
3. close qTox

in which case font is saved and restored properly.

So it sounds like the problem is specifically with shutting down the computer? @zl3ai can you test without shutting down, just my closing to qTox (not to tray, fully closed) and see if in that case it's saved?

**Comment by zl3ai** [comment]
For the purposes of experimentation, in Settings>General I have only ticked Autostart, Show system tray icon, Start in tray, Faux offline messsaging, Autoaccept files.

Test 1. In Settings>User Interface>Base Font, change to 20px. Close qTox by clicking the X in the top right corner of it. Launch qTox by double-clicking Desktop icon, click green dot icon, font setting has stayed as 20px. Good.

Test 2. Change font to 30px. Without 'manually' doing anything to qTox, restarted computer.
qTox is 20px, didn't save the 30px value.

So it seems that closing qTox 'politely' by either clicking its own 'X' or right-clicking its icon is OK, but if you have qTox running when the computer is shut down then changes are not saved.

**Comment by anthonybilinski** [comment]
Thanks for the info. The problem is then either that qTox doesn't save in time when the system is shutting down, or doesn't even realize that the system is shutting down until it is killed. This makes sense because qTox doesn't save settings to disk when they are changed, only when qTox is closed. I'll rename the issue to capture this.

**Comment by anthonybilinski** [comment]
Looking closer, this is a duplicate of https://github.com/qTox/qTox/issues/1969 which has the same root cause and is a few years older. Going to close this ticket and track progress there.
