### ISSUE TITLE
the popup-menu  enabled/disabled behaviors are not acting normally

### ISSUE THREAD

**Issue by jakieoymj-github** [qTox/qTox#5223]
##### Brief Description

OS: Linux (Ubuntu 18.04 LTS)  
qTox version: (v1.16.1)  
Commit hash:  4921b8868f02ddcfc06d617be886547d59a388d6
toxcore:  0.2.3
Qt:  5.10.1
Reproducible: Always

##### Observed Behavior
When the popup-menu item is invalid,it's text still black color.

##### Expected Behavior
The text color may be change to gray.

**Comment by sudden6** [comment]
What popup-menu do you mean exactly? Can you include a screenshot?

**Comment by jakieoymj-github** [comment]
![popup](https://user-images.githubusercontent.com/11205777/42551016-9d7847a4-8507-11e8-8cba-807f7878445c.png)
Just like that.When you right clicked within ToxID editor or Message editor,if there was nothing in clipboard and in editor,the popup-menu's item should be disable/invalid,it's icon acting good but the text not.The text colour may be gray i think.

**Comment by tox-user** [comment]
We do it for some menus but apparently not all of them. I assume the problem is with CSS, because some menus use their own hardcoded styles.

![qtox disabled menu items](https://user-images.githubusercontent.com/32248732/42724211-cf38ce14-875d-11e8-9e01-2c43dfc678c8.png)

![qtox disabled menu items 2](https://user-images.githubusercontent.com/32248732/42724212-cfe23134-875d-11e8-907c-895b0a9f2ec5.png)

**Comment by jakieoymj-github** [comment]
yup,I have searched and read the source codes extensively these days.Using a lot of CSS here and there,I suspect no full consideration of QT class inheritance.The previous CSS definition affects the one behind.I have revised some places in my working directory.It looks good :).
![image](https://user-images.githubusercontent.com/11205777/42773772-da866e16-8960-11e8-9e4e-f31dc69fb0d6.png)

**Comment by jakieoymj-github** [comment]
Thanks for merge. Fixed.
