### ISSUE TITLE
Provide nightly builds on GH releases?

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#5251]
Since our infrastructure for Windows, Linux and Mac deployments to GH seems to be quite stable now, should we provide nightly builds via Travis CI cron jobs?

@tox-user @anthonybilinski @Diadlo what do you think about this?

**Comment by tox-user** [comment]
I don't know the difference, so I have no opinion.

**Comment by sudden6** [comment]
@tox-user nightly builds would be built once a day (night) from master and then pushed to releases

**Comment by zetok** [comment]
Deploying nightlies to gh releases doesn't sound like a good idea.

Back in the day nightlies were being deployed to gh releases, and that resulted in hundreds of date tags on the repo, each having an attached nightly. I still have those tags in my repo.

Here's some of them:

```
$ git tag | head -n 50
1.2.2
qtox-1412168537.87
qtox-linux-1412168574.4
qtox-linux-1412169700.89
qtox-linux-1412171229.4
qtox-linux-1412173041.52
qtox-linux-1412174508.44
qtox-linux-1412175690.8
qtox-linux-1412184607.12
qtox-linux-1412276066.41
qtox-linux-1412291316.09
qtox-linux-1412337621.84
qtox-linux-1412621109.23
qtox-linux-1412621388.34
qtox-linux-1412632666.27
qtox-linux-1412696939.47
qtox-linux-1412705024.75
qtox-linux-1412710004.59
qtox-linux-1412711221.8
qtox-linux-1412712104.55
qtox-linux-1413493439.44
qtox-linux-1413494230.22
qtox-linux-1413495330.48
qtox-linux-1413496908.1
qtox-linux-1413560732.58
qtox-linux-1413562096.17
qtox-linux-1413565389.94
qtox-linux-1413566449.78
qtox-linux-1413567049.24
qtox-linux-1413573057.66
qtox-linux-1413626937.37
qtox-linux-1413627777.83
qtox-linux-1413628699.09
qtox-linux-1413629498.69
qtox-linux-1413630215.38
qtox-linux-1413642454.92
qtox-linux-1413645634.03
qtox-linux-1413651206.89
qtox-linux-1413651944.29
qtox-linux-1413653020.07
qtox-linux-1413656132.89
qtox-linux-1413658574.68
qtox-linux-1413662412.08
qtox-linux-1413663873.98
qtox-linux-1413664573.11
qtox-linux-1413711413.4
qtox-linux-1413751474.57
qtox-linux-1413755250.89
qtox-linux-1413803313.44
qtox-linux-1413805500.57
```

What you're proposing would do the same. Alternatively instead of creating hundreds of nightly tags you would end up pushing hundreds of nightlies to release tags. Either way, it's not what tags/gh releases are for.

@sudden6 
In the issue on TokTok repo about organization you said that you don't see with what money would help. Well, having a place to deploy & keep hundreds of nightlies available for people to test is precisely the kind of thing that stops being an issue if you throw money at it.

**Comment by sudden6** [comment]
@zetok this seems to be very well possible, example: https://github.com/AppImage/AppImageKit/releases

**Comment by zetok** [comment]
Well, that would work for providing latest build, but wouldn't provide quickly accessible builds for regression testing.

**Comment by nurupo** [comment]
>@zetok this seems to be very well possible, example: https://github.com/AppImage/AppImageKit/releases

[AppImage uses](https://github.com/AppImage/AppImageKit/blob/f7e3cb01d066128c902aa3992db85709a0bc8f8a/.travis.yml#L37) [uploadtool](https://github.com/probonopd/uploadtool) which seems to have [race condition issues](https://github.com/probonopd/uploadtool/issues/34).

I have been slowly working on a proper solution for publishing nightly builds made on Travis-CI to GitHub Releases. A solution which would handle race conditions and not only provide the latest build but also N last builds for easier regression testing and to avoid [cases like this](https://github.com/opengapps/x86_64/releases) where people don't limit how many releases they create on GitHub, resulting in several TiBs of data being stored on GitHub Releases.

I present you with [`ci-release-publisher`](https://github.com/nurupo/ci-release-publisher), freshly released as of few hours ago. I suggest we set it up for qTox nightly builds.

[Here are example releases](https://github.com/nurupo/test/releases) made by that script. In that instance it was configured to create a Latest Release and a Numbered Release that keeps last 3 releases, both for just the test3 branch. This particular setup creates 4 extra tags: one `ci-<branch>-latest` and three `ci-<branch>-<build_number>` since GitHub Releases are just additional data associated with git tags, you can't create a non-draft GitHub Release without creating tags, but CI Release Publisher script makes sure to only keep the latest 3 Numbered Releases around, deleting older Numbered Releases and their associated tags, so the repo won't get littered as much as in zetok's example.

How does that sound? We can discuss what kinds of releases we want for qTox (Latest Release and/or Numbered Releases and what their retention policy should be), if we want them croned to run once a day or on every git push, and in which GitHub repo we want them to be published to, and I can start working on a PR for it.

**Comment by quantumpacket** [comment]
I don't know the current status on reproducible builds, but unless that is solved I'd be hesitant to be making automatic nightly builds for download.

**Comment by nurupo** [comment]
qTox already has automatic nightly builds available for download, it had them for many years now. There are direct download links in [README.md](https://github.com/qTox/qTox/blob/1ebcac446081c6fc2dbaad8da0ac525162a7858d/README.md), [qtox.github.io](https://qtox.github.io) links to the README.md for downloads and [tox.chat](https://tox.chat/download.html) links to them directly too.

Moving nightly builds from Jenkins to Travis-CI would be an improvement because the nightlies produced by Jenkins are not really a good representative of what the release binaries would be like, when the nightlies created by Travis-CI would be very much just like the release binaries. This is because Jenkins doesn't run [the same script that is used to create release binaries of qTox](https://github.com/qTox/qTox/tree/a91c70b0c041cc6d974e10fd1c55eb70cb1f754a/windows/cross-compile), because Jenkins doesn't support running the script in Docker with root privileges inside (well, we don't allow it to as that's a big security risk), so [Jenkins does things a bit differently](https://build.tox.chat/view/qtox/job/qtox-cmake-build-script_src/lastSuccessfulBuild/artifact/qtox-cmake-build-script_src.sh/*view*/) and the nightlies it produces might use different versions of dependencies -- Qt, opus, vpx, libsodium, openssl, ffmpeg, etc. -- than what the release version would, not to mention different builds options if no one bothered to update qTox build script on Jenkins to replicate changes made to the Windows build script used on Travis-CI.

Having reproducible build would indeed be nice, to verify not only the nightlies but also the releases, however reproducible builds is a separate issue altogether, and given how Travis-CI is already trusted enough to automatically build the release versions of Windows qTox binaries without any reproducible build guarantees (see [this](https://github.com/qTox/qTox/blob/acb99f8327531e82de99cdd3d27bfa4c4d2eaf13/.travis.yml#L44-L117) and [this](https://github.com/qTox/qTox/blob/acb99f8327531e82de99cdd3d27bfa4c4d2eaf13/.travis.yml#L182-L204)), it's not a big stretch to build nightlies on Travis-CI too.

**Comment by sudden6** [comment]
Wow, nice tool @nurupo, I have been looking for exactly this a few times already.

> How does that sound?

Great!

> We can discuss what kinds of releases we want for qTox (Latest Release and/or Numbered Releases and what their retention policy should be), if we want them croned to run once a day or on every git push

I think to start 3 latest releases built daily would be a good start. As for cron vs. on every push, I'm not sure, I think I'd prefer daily for now, because when stuff is merged, it's often multiple PRs in one day and thus people could go back if the batch of the day breaks master.

> and in which GitHub repo we want them to be published to, and I can start working on a PR for it.

What would be the possibilities here? Having a separate repo just for nightlies sounds like a good idea.

@quantumpacket I fully aggree with @nurupo on this matter, qTox has non-reproducible nightlies on self hosted infrastructure since years. In my opinion moving to Travis will actually make things a bit better. Additionally doing everything on one setup will make it easier to provide reproducible builds.

**Comment by nurupo** [comment]
>I think to start 3 latest releases built daily would be a good start. 

Ok, that sounds like you want 3 Numbered Releases then, e.g. `ci-master-<build_number>`. Do you want a Latest Release `ci-master-latest` too? It will be identical to the latest Numbered Release. The benefit of it is that you can link to it directly as the git tag doesn't change, e.g. https://github.com/nurupo/test/releases/tag/ci-test3-latest, when the `<build_number>` part in Numbered Releases will keep changing as it follows `$TRAVIS_BUILD_NUMBER`.

>What would be the possibilities here? Having a separate repo just for nightlies sounds like a good idea.

Yep, that's possible. Please read the [README](https://github.com/nurupo/ci-release-publisher) to see everything that is possible. For this particular part you want to start with the [Usage section](https://github.com/nurupo/ci-release-publisher#usage) which talks about security considerations.

You can:

1. Build releases on qTox's Travis-CI and publish them to qTox's GitHub Releases
2. Build releases on qTox's Travis-CI and publish them to some different repo's GitHub Releases
3. Build releases on some different repo's Travis-CI and publish it on that different repo's GitHub Releases (basically the application of (1) but with a different repo instead of qTox)

Those different options are discussed in the README from the security standpoint since Travis-CI would need to store `GITHUB_ACCESS_TOKEN` with Write/push permissions to the target GitHub repo, since those are the permissions necessary to create GitHub Releases.

**Comment by sudden6** [comment]
> Do you want a Latest Release ci-master-latest too?

yes, this would be needed so we can link from our README to these builds.

> Build releases on qTox's Travis-CI and publish them to some different repo's GitHub Releases

Is IMO the solution that makes most sense, because the scripts are in the main repo and we want to deploy what's in the main repo.

From the README of your tool:
> In order to use CI Release Publisher, you must create a new GitHub user, make that user a collaborator in a repository you wish to publish releases to, giving the user Write/push access to the repository which is required to create releases, generate an access token for that user and store it in an environment variable on Travis-CI. 

Is it really necessary to create an extra user? To me it seems that Github Deploy Keys (https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) would provide the same thing with the added benefit that all repo admins can delete the key easily in case something goes wrong.

**Comment by sudden6** [comment]
It seems I have misinterpreted the idea behind deploy keys and they don't allow access to the GH api, so we'll need to create an extra account for deploying. Seems like a small price to pay for the increased security.

**Comment by sudden6** [comment]
Nightly builds are implemented under https://github.com/qTox/qTox-nightly-releases
