### ISSUE TITLE
Release files for 1.16.2 version not contains *.asc file

### ISSUE THREAD

**Issue by EGD** [qTox/qTox#5252]
Archive with 1.16.2 version not signed.

**Comment by anthonybilinski** [comment]
Added .tar.lz and signature file to [v1.16.2 release](https://github.com/qTox/qTox/releases/tag/v1.16.2).

**Comment by EGD** [comment]
Thanks!

**Comment by quantumpacket** [comment]
@anthonybilinski I'm new to AppImage, but I could not find any documentation on verifying its integrity other than providing a signature file. https://github.com/AppImage/AppImageKit/issues/238 

Can we also have a sig file for it as well?  At this point it may make more sense to sha2 all release files and put that into a single file to be signed.

**Comment by anthonybilinski** [comment]
AppImage's are built by Travis CI, so unlike source where I can verify signatures of the commits, I can't verify integrity of the AppImage binary. There was some work to make reproducible builds so that maintainers could locally reproduce builds and sign that hashes match published artifacts (https://github.com/qTox/qTox/pull/5028 did some work towards that) but AFAIK this isn't yet complete. @tox-user is that accurate?

Based on that, at the current state I don't think signing a binary produced by a third party makes much sense.

**Comment by quantumpacket** [comment]
If that's the case, should we really be providing untrusted 3rd party binaries when tagging a new release? That's a sure footgun for installing a tampered qTox. :worried: I think that a release asset should not be provided if it can't be verified by a user. So maybe omit the AppImage file and/or others until they have a means of verification?

**Comment by anthonybilinski** [comment]
Let's move discussion to https://github.com/qTox/qTox/issues/5001 which covers the same issue.
The latest status is, if we want to sign binaries and have the signatures mean anything, we need reproducible builds and:
>Debian is working on this for years and they need quite a few patches to their toochain IIRC. See also https://wiki.debian.org/ReproducibleBuilds

You could make a similar argument there, I think it's valid input. IMO if our alternative is not providing any binary releases I think a not-completely-trusted binary is better until we have binary reproducible builds that we can have multiple maintainers independently reproduce and verify for each release.

**Comment by tox-user** [comment]
It's possible to build qTox and toxcore reproducibly on GNU/Linux. That's all I know.
