### ISSUE TITLE
broken file transfer, receiving file has no name by default and not saved

### ISSUE THREAD

**Issue by shalnoff** [qTox/qTox#5298]
##### Brief Description

files are not saved, being transferred with selection of target directory (but saved, when you have target directory predefined +  "Auto-accept files" activated. see WORKAROUND below)

OS: Linux Mint 19 Tara 32 bit
qTox version: 1.16.3
Commit hash:  
toxcore:  0.2.3
Qt:  5.11.1

Reproducible: Always

##### Steps to reproduce

1. initiate file transfer from another PC 
2. accept file transfer
3. select the target directory in opened dialogue (+ write the filename, since filename is empty by some reason and OPEN button is not active* this is another problem)
4. click OPEN to save file. 
5. resulting file is 0 bytes. 

WORKAROUND: predefine default "directory to save file" and switch "Auto-accept files" on. 
After that files start saving properly, until restart of the app, since the **settings are not saved**.

**Comment by anthonybilinski** [comment]
Testing on 0cb760dfa2b0c50efb0ae3137657a70ad94b8377, the file name is populated in the save file dialog automatically, and the saved file is the full size.

Looks like this has been fixed since it was opened. Please comment if you still have the problem with qTox nightly: https://github.com/qTox/qTox/releases/tag/nightly and I'll re-open.

Note that updating to the nightly will cause persistent history database updates, which will make your history incompatible with the older release version. Make a copy of your history db so that you can downgrade.
