### ISSUE TITLE
[Feature Request] Group Chat is essential for its futural popularity

### ISSUE THREAD

**Issue by CresentMoon** [qTox/qTox#5300]
Lastest version from the official website.

1. The latest qTox does not allow users to send pictures in Group Chat.
2. Once a user went offline, he would automatically leave the group.
3. The mobile version (antox) does not have group chat feature yet.
4. The mobile version should be able to share the same account with the PC version. 

If qTox have realized 1/2/3, users would have be much more willing to share some info about "you-know-what", at least in China.  As we all know, there are much topics which are not appropriate to discuss or share in public, where qTox are destined to be unrivally useful. And 4 will be of great help to those who often use computers as working tools.

**Comment by anthonybilinski** [comment]
1. File transfers are not supported in groups. This is a limitation by Toxcore, the library we use. I don't see a current issue regarding this in their repo, but "new groupchats" are currently being worked on which will change a lot of things about groups, possibly also including file transfers, at which point qTox will integrate the feature.
2. Also a limitation of Toxcore. Current PR in progress https://github.com/TokTok/c-toxcore/pull/1069 to address this in their repo, once merged qTox will prioritize integrating the feature.
3. Antox is completely separate from qTox, you can find their repo here: https://github.com/Antox/Antox
3.1 There's a seperate Android client, TRIfA, but it looks like it also doesn't have group support, you can find their repo here: https://github.com/zoff99/ToxAndroidRefImpl
4. It's not possible to use the same account/profile/key in two places at once.This is a Toxcore limitation: https://github.com/TokTok/c-toxcore/issues/466

These are all good points, but since all are being tracked upstream, there's nothing left actionable.

**Comment by CresentMoon** [comment]
Thank you for your reply!
