### ISSUE TITLE
how to use persistent chats?

### ISSUE THREAD

**Issue by whoizit** [qTox/qTox#5326]
I just have latest release toxcore-0.2.7 and qtox-1.16.3
I create new group chat, restart qtox and I can't see my new group chat after restart.

what I do wrong?

**Comment by anthonybilinski** [comment]
Groupchats are not persistent across client restart as of toxcore v0.2.7.

Minimal persistence (across disconnect, not across client restart) is almost finished: https://github.com/TokTok/c-toxcore/pull/1069. This works without any changes to qTox.

Full "new group chat" is farther off, there's a PR here https://github.com/TokTok/c-toxcore/pull/217 but looks like it's being tracked somewhere else.

Neither are merged in to Toxcore master yet.

Going to close since the question is answered and the issue itself is tracked by qTox here https://github.com/qTox/qTox/issues/896.
