### ISSUE TITLE
Feature Request: Expiring messages and mobile support

### ISSUE THREAD

**Issue by KevinMusgrave** [qTox/qTox#5342]
1. I'd like to have messages that disappear after a specified amount of time.

2. For Android, I use Antox. Is there a way for me to be logged into both qTox and Antox and receive the same messages?

**Comment by anthonybilinski** [comment]
1. It would be possible to delete local history after a certain amount of time automatically, is this what you're asking for? If you want want the message to also be deleted from your friend's history, that's not really ever going to be possible, since it relies on getting their device to do something they may not want it to do, which is possible in closed apps, but for FOSS software nothing stops someone from just ignoring that request.

2. Unfortunately no. The Tox protocol doesn't support the same profile being online in two places at once: https://github.com/TokTok/c-toxcore/issues/466. Attempting to do so with cause you to flicker online/offline from your friend's perspective, and not receive all messages. It's a widely requested feature and will be added at some point in the future, but probably not soon.

**Comment by KevinMusgrave** [comment]
2. Is the best way around this to make 1 account for my desktop, and 1 account for my mobile device, and then make a group conversation which includes both my desktop and mobile Tox accounts?

**Comment by anthonybilinski** [comment]
Groups aren't persistent, so closing either client means you'll need to be re-invited to the group. Again this is being worked on by Toxcore: https://github.com/TokTok/c-toxcore/pull/1162 and may be included soon.

AFAIK Antox also does not support groups in general.

One option is to just have two profiles, one for phone and one for desktop, and have the same friends added on both.

Another option (what I do for multiple desktops) is to have a single profile stored on network storage, then load that from different places, with only one running at a time. I'm not sure how possible this would be on a phone since I don't think they support loading from google drive or other network locations.

**Comment by KevinMusgrave** [comment]
I see, thanks for the suggestions!
