### ISSUE TITLE
Tox needs marketing share on Discord users

### ISSUE THREAD

**Issue by b7398564** [qTox/qTox#5353]
Many users are complaining about Discord close-source environment, and even security risks like Discord monitoring every process running are making users regret it. But you guys are not advertising tox anymore. 

Perhaps a "single-click" UI design stolen from Discord, and some proper group chat voice look would alone bring thousands of users to tox. It's not something far away from the current development here. Just change the default skin and do some marketing for opensource. Even FSF could help here.

**Comment by zetok** [comment]
>But you guys are not advertising tox anymore.

Advertising takes an effort and time.

qTox developers already spend all their energy on improving qTox. And arguably, this is the best use of time, as it directly improves qTox.

> Just change the default skin and do some marketing for opensource. Even FSF could help here.

Rather than telling already busy people what to do, why don't you do it? You can make a pull request with the "skin change", and "do some marketing". Even better, you could organize a group of people to advertise qTox.

I assure you that everyone would appreciate your help with those things :)

**Comment by b7398564** [comment]
I'm not telling you what to do.
If you think that, then there's a great reason why this project isn't growing in its best opportunity.

Fuck you.
