### ISSUE TITLE
New message notification doesn't include sender's name

### ISSUE THREAD

**Issue by jakieoymj-github** [qTox/qTox#5391]
##### Brief Description

OS: Ubuntu 18.04.1 LTS
qTox version: v1.16.3-123-gbdfa3938
Commit hash:  bdfa3938dad52287c6680f6c875d86cb0e84dd60
toxcore:  0.2.8
Qt:  5.11.1

Reproducible: Always
##### Steps to reproduce

1. Current chat form stay at friend A
2. Receive a message from B  

##### Observed Behavior
 The notification window inform 
`"qTox - A(online)" is ready`

##### Expected Behavior
Should be `"qTox - B(New message)" is ready`

**Comment by anthonybilinski** [comment]
Our current notification system just calls Qt's alert https://doc.qt.io/qt-5/qapplication.html#alert call, which "demands attention" on the Window. This shows "qTox - A(online)" is ready because the current title bar of the Window is "qTox - A(online)", not because we're mixing up A and B.

To fix this we would probably have to change our title bar with friend A accepted to "New message from B" before calling alert(). There's also a PR in progress to add a more rich notification system, allowing us to have custom messages: https://github.com/qTox/qTox/pull/5227

**Comment by jakieoymj-github** [comment]
OK, I got it.
