### ISSUE TITLE
Do not steal focus

### ISSUE THREAD

**Issue by PaladinTorrix** [qTox/qTox#5450]
qTox should not steal the focus when a message is received. I received a message in the middle of playing a flash game and I was automatically taken out of full screen mode and the focus switched to the qTox window. This could cause serious issues for people. And even if it's not serious, it is still annoying. Focus should only switch to the qTox window when the user deliberately initiates it.

I believe it is only the first message that switches the focus. Subsequent messages do not seem to steal the focus.

qTox should operate like Skype. Make a noise when a message is received and flash the taskbar icon. You could even offer the option of having a small popup message in the corner of the screen. But do NOT steal the focus.

OS: Windows 7
qTox version: 1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.3

Reproducible: Always

**Comment by anthonybilinski** [comment]
@PaladinTorrix is you settings -> user interface -> new message -> focus checked? If so try unchecking it. It was checked by default which was changed to be off by default in https://github.com/qTox/qTox/issues/5284, then removed completely in https://github.com/qTox/qTox/issues/4762 due to a different bug.

**Comment by anthonybilinski** [comment]
Going to close as duplicate assuming the suggestion worked. If you still experience the issue please comment here and I'll reopen the issue.
