### ISSUE TITLE
New qTox does not start on Windows XP

### ISSUE THREAD

**Issue by Abdula-2015** [qTox/qTox#5458]
Hi,

Uploaded   and installed a new qTox on Windows XP SP3 32 bit.
But does not start  and reports an error: 

**Missing bcrypt.dll**

What to do?

**Comment by anthonybilinski** [comment]
qTox doesn't support Windows XP, I'm sorry. XP security support ended over 4 years ago. Doing some quick googling, Windows XP doesn't include `bcrypt.dll`, only Vista and later do. There might be some system level hacks that are possible to get qTox running.

**Comment by username1565** [comment]
Yeap, Windows XP is alive, and will be alive. Too many software writted for this, while this was been popular. This had over 50% from all Desktops application, and even after drop support of this great system, this still alive. I using this over 13 years, and I'm happy. I wan't to update my Windows XP, because this working stable.

So, I recomment to download [uTox_winXP.exe](https://github.com/uTox/uTox/releases/download/v0.7.0/uTox_winxp.exe) and try **to compile this from source code**.
I have the separate branch: [uTox_winXP][https://github.com/username1565/uTox_winXP], where I got success of compilation. There I did include all libraries, so we can fix bugs there, and do developing uTox for XP.

Have a nice day.

**Comment by Diadlo** [comment]
@username1565 It's really hard to maintain an application with a backward compatibility code. Mostly nobody can test change on old systems. IMO, sometimes we need to break this compatibility, otherwise, systems will grow and become more complex. More old versions => more checks => more errors and untested cases.

**Comment by username1565** [comment]
I did found portable qTox here: https://www.upload.ee/files/9259832/qtox-1.12.1_x32_x64_portable.zip.7z.html
There is inside the zip-archive: setup-qtox-1.12.1_x32_portable.zip,
with the folder of portable qTox. And this is sucessfully workin on Windows XP!

Do you have the source code from this? Can I compile this, to portable executable, like this zip,
but from the source code?
We want to create different branch to supporting the backward compatibility with GREAT WINDOWS XP.

**Comment by anthonybilinski** [comment]
The source code of every release is in this git repo. Each release is tagged, so you can get the source of release v1.12.1 by just checking out that tag, with `git checkout v1.12.1`.

Yes you can compile the exe, they're cross compiled from Linux, instructions are here: https://github.com/qTox/qTox/blob/master/windows/cross-compile/README.md.

The missing dll on modern qTox is from a dependency from Qt. A better option that forking an old version of qTox might be to just downgrade the version of Qt, but keep using a modern qTox and toxcore.

**Comment by username1565** [comment]
@Abdula-2015,
I found this [bcrypt-6.3.9600.17031.zip](https://github.com/qTox/qTox/files/3923524/bcrypt-6.3.9600.17031.zip) here: https://download-dll.ru/skachat-bcrypt-dll.html
and this seems, like working, if unpack it into the folder with `qtox.exe`.
But on Windows XP, this show another error about
>not fund method EtwGetTraceLoggerHandle in ntdll.dll
Maybe need just to add some dll's to make this code full and working portable.

**Comment by anthonybilinski** [comment]
I strongly recommend not using a dll you found from an untrusted source online. The dll runs with your program, has access to your private key, has access to all of your chatlogs, and could steal any data you have in qTox. Using security chat software with untrusted dlls gives you no security.

Using an older version of Qt that doesn't require the dll, or even using an older version of qTox seems like a much safer option.

**Comment by username1565** [comment]
@anthonybilinski, ok, thanks.
As I understand, many software engeneers not supporting Windows XP, just because many libraries inside this are deprecated, and in newer versions of Windows,
this libraries exists and updated.
So I just found it, and I think now someone already writted bcrypt.dll for Windows XP in 2019.
But, you are right, will be better to decompile it, to see what this doing, and this need to do before using this, to be sure it really safely.
[It seems, like clear from virusses real microsoft product.](https://www.virustotal.com/gui/file/d77bac70582a2c6eb04cdb853a03cd6554c9fc45c3fcc849688b04e7b14fb67a/detection)
