### ISSUE TITLE
Persistent group chats are not saved in uTox-created .tox files

### ISSUE THREAD

**Issue by Monsterovich** [qTox/qTox#5468]
##### Brief Description

OS: Linux Mint 19
qTox version: v1.16.3-207-gea9f4298
Commit hash: ea9f4298382fb4f0a9693a20466e2a79a256edf9
toxcore: 0.2.8
Qt: 5.9.5

Reproducible: Always

##### Steps to reproduce

If you create a profile in uTox and then switch to qTox and join a group chat, it's not persisted in the .tox file across qTox restarts.

I found this out the hard way because I created my profile in uTox and then switched to qTox and wanted to test persistent group chats, only to find out that they do not work at all unless I switch to a completely new profile created in qTox.

**Comment by sudden6** [comment]
Did you build qTox against c-toxcore master? I can't tell because the version number could be the 0.2.8 tag or master.

What are the symptoms of your problem? Does the group not show up in the group list at all? (Would be a problem) Does the group show up in the contact list but contain no messages? (would be expected)

Does it work the other way round if you create a profile with qTox and a persistent group and then switch to uTox?

**Comment by Monsterovich** [comment]
> I can't tell because the version number could be the 0.2.8 tag or master.

It doesn't work with both.

>Does the group not show up in the group list at all?

No, it disappears after restart or logout.

**Comment by Monsterovich** [comment]
I figured out that it doesn't work even with clean .tox profile. It worked randomly then before I rebuilt qtox, after that it doesn't save groups anymore. Can you build qtox on linux and check it out?

**Comment by Monsterovich** [comment]
By the way, this problem is not present on windows, so it can be a linux-only issue.

**Comment by sudden6** [comment]
@Monsterovich If you close an issue please provide a reason why you closed it.

**Comment by Monsterovich** [comment]
I just rebuilt toxcore and it worked. I can't figure out why.
