### ISSUE TITLE
[Feature request] Add built-in Tor support

### ISSUE THREAD

**Issue by Nokia808** [qTox/qTox#5476]
Hi ! Happy new year for all !

I would like to suggest on you to add built-in support for Tor. It is applied in other application called "Retroshare" which available on:
http://retroshare.net/

I suggesting this on you after I found a Tox application on Android apply similar thing. This application called TRIFA which available at:
https://github.com/zoff99/ToxAndroidRefImpl

Please notice that I suggest on you some thing differ from TRIFA: TRIFA need Tor already installed on system to use it, while I suggest on you a built-in support for Tor like Retroshare so that user can connect use qTox to communicate over Tor network even Tor browser not installed.

Really if you add this feature, qTox will elevated to too higher level !

Please notice that Retroshare currently have 2 versions, one with Tor support & other without because they are still examine the feature, so the target is to have UNIFIED version with Tor support, & this is "UNIFIED VERSION with built-in Tor support what I suggesting on you.

Best.

**Comment by anthonybilinski** [comment]
qTox already has (non-builtin) Tor support, with instructions to configure it here: https://wiki.tox.chat/users/tox_over_tor_tot#qtox

I don't think bundling Tor with qTox makes sense, since it would increase our release work. For example, we would need to watch for Tor updates and release the bundled qTox at the same time. It would also duplicate Tor on the system, possibly at different versions, if the user already has Tor installed.

Is there a major benefit over using a localhost Tor proxy like we already support? If the only benefit is avoiding setting a couple settings, I don't think it's worth the effort at this time, when especially our release needs work (e.g. not having packages on all major distros).

**Comment by sudden6** [comment]
@anthonybilinski I fully agree with you here. We are already have so many deployment options that it's very hard to maintain them all.
