### ISSUE TITLE
Add signatures for AppImages builds

### ISSUE THREAD

**Issue by Nurmagoz** [qTox/qTox#5513]
verifying signatures for downloading appimages is important to check the downloaded images is the correct one without manipulation or changes. reading more details about it: 

https://www.qubes-os.org/security/verifying-signatures/

E.g of which project done that: 

https://keepassxc.org/download/#linux

**Comment by sudden6** [comment]
We won't provide signatures for things we're not able to verify, see https://github.com/qTox/qTox/issues/5001 for the discussion.

**Comment by Nurmagoz** [comment]
then why provide insecure/not certain things in the first place?

**Comment by anthonybilinski** [comment]
The packages aren't insecure, they just can't be independently verified by us maintainers. If TravisCI were to sign the builds, that would be fine. If one of us maintainers were to create a build and upload that signed, IMO that would be less trustworthy than TravisCI, because still other maintainers wouldn't be able to independently verify the contents, and the chance of one of us being corrupt or getting a virus are probably higher. Reproducible builds are being gradually worked on (I just opened https://github.com/qTox/qTox/pull/5524), and once finished multiple maintainers and the public could verify the build being distributed has not been tampered with, at which point the maintainers that verified signing it makes sense.
