### ISSUE TITLE
Question: Anything holding back the next release?

### ISSUE THREAD

**Issue by Hasshu** [qTox/qTox#5519]
v1.16.3 (AppImage) has the über-annoying [triple-click bug](/qTox/qTox/issues/5211), and it has been out for over 6 months at this point, so I was wondering: is there something that holds back the next release of qTox?

**Comment by sudden6** [comment]
Mostly just getting the release process running and collecting bugs that need to be solved.

**Comment by Hasshu** [comment]
I see. Any milestone/ETA?

**Comment by anthonybilinski** [comment]
IMO https://github.com/qTox/qTox/issues/5509 is pretty bad. Loaded groups fail to send any audio, without any UI indication. It looks like it will require a Toxcore change and I'm not sure how long that will take. It might be ok to either release with broken audio in persistent groups, or release with persistent groups disabled to avoid this bug.

**Comment by Hasshu** [comment]
I think it'd be worth waiting for a fix.

**Comment by anthonybilinski** [comment]
I've created a milestone to track issues (mostly either regressions or major issues) that should be fixed before 1.17.0, which include #5509 which depends on Toxcore v0.2.10 - which will probably be out soon: https://github.com/TokTok/c-toxcore/pull/1324.

I'll close this issue since the milestone can be referred to to see progress and what's left.
