### ISSUE TITLE
Loading of persistent group chat fails

### ISSUE THREAD

**Issue by Vort** [qTox/qTox#5559]
##### Brief Description

OS: Windows 7 SP1 x64
qTox version: v1.16.3-273
Commit hash: d2508e7eac26d731c746333b5d74e9a051d3f5b7
toxcore: 0.2.9
Qt: 5.9.3
Hardware: Desktop

Reproducible: Always _(for me)_

##### Steps to reproduce

1. Open qTox
2. Watch for user count for saved groups

##### Observed Behavior
Groups have 1 and 2 peers.

##### Expected Behavior
Groups have 4 and 16 peers.

##### Additional Info
When I send `invite 1` command to Groupbot, nothing happens.
Which, probably, means, that I am already invited to this chat.
Strange thing is that in one of chats, Groupbot is constantly going online and offline, changing user count from 1 to 2, from 2 to 1, ...
![qt1](https://user-images.githubusercontent.com/1242858/53186004-da342700-3608-11e9-9347-e473bf513704.png)
![qt2](https://user-images.githubusercontent.com/1242858/53186010-dc968100-3608-11e9-99dd-8e5a5431ffc3.png)

Log file: [qtox.txt](https://github.com/qTox/qTox/files/2890227/qtox.txt)

**Comment by Monsterovich** [comment]
I guess, this is a bot issue.

**Comment by Vort** [comment]
This particular chats was working some time ago. It is possible, that all users abandoned them, but this is highly unlikely. How to test if this is the same chats or different ones?

**Comment by anthonybilinski** [comment]
I agree that this looks like a bot issue. Even if all the users hadn't left the group, maybe the bot itself left the group and lost track of other group members. There isn't a good indication that this is a qTox-related issue.

The latest qTox release has persistent groups, meaning you'll be able to reconnect to the whole group by remembering any of the peers in it, rather than relying solely on the groupbot. If you see failures to reconnect to peers that you know are online in a persistent group, please comment and I'll re-open the issue.

**Comment by Vort** [comment]
The problem was reproducing without any interaction with group bot.
Groups themselves just was showing incorrectly.
And of course I know about persistent groups, since my reproduction steps using that feature.

But anyway, now I can't see that groups and can't see any groupbots online.
So this report was requiring testing year ago and not now.
