### ISSUE TITLE
Prints the message '{user} is now offline' sequentially, many times, for the same user

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5597]
This might be a ToxCore issue, but it sometimes prints this message many times, when the corresponding 'online' message is printed only twice.

rev.bef9d4b7 on FreeBSD

**Comment by sudden6** [comment]
Please fill out the issue template, especially the toxcore version.

**Comment by yurivict** [comment]
ToxCore version: toxcore-0.2.9_1,1
OS: FreeBSD 11.2 amd64

**Comment by anthonybilinski** [comment]
I'm guessing this was seen on v1.16.3 based on the date of the report (but again please include this info). We've had a lot of changes to our status update handling, and also a couple toxcore version updates since then, so it could be fixed unintentionally. I haven't seen this issue myself even before though.

Looking at code on v1.16.3, it's still a pretty direct line from toxcore saying the friend has gone offline to us adding that message to the chatlog, so I'd guess this would be a core issue.

@yurivict have you continued to see this issue?

**Comment by yurivict** [comment]
No, I didn't see this recently.

**Comment by anthonybilinski** [comment]
Ok I'll close it for now, but please comment or open a new issue if you see it again.
