### ISSUE TITLE
How to open profile.db database

### ISSUE THREAD

**Issue by Coool** [qTox/qTox#5655]
How can I open profile.db database? Is it SQLite?

**Comment by sudden6** [comment]
Yes, it's SQLite. If you have a password set you may need to remove that first before any SQLite editor can open it.

**Comment by Coool** [comment]
Do you mean profile password?

**Comment by anthonybilinski** [comment]
Yes, the profile password. It can be removed at the bottom of the profile settings page, accessed by clicking your avatar.

**Comment by Coool** [comment]
OK, I removed I can access DB. Have look through https://github.com/qTox/qTox/issues/3583 and still not getting how to unlock encrypted or password locked DB. How DB password is generated. Is DB password locked or encrypted?

P.S.
Short story. I'm fed up with Microsoft and Skype 8. Skype Classic (7) was working great. So I decide to switch. I want to import my old Skype chat history in qTox. As I understand most Tox clients using propertary chat saving method.  Question is if I import data in qTox new qTox releases will not break chat history. Because your current statement is what chat history is still in development and can be lost.

P.S.S.
Why you have not added partialy translated Latvian language?

**Comment by anthonybilinski** [comment]
The DB is encrypted using SQLCipher. The key is a combination of your profile password and your public key, then the encryption key is derived using toxcore's `tox_pass_key_derive_with_salt`. See https://github.com/qTox/qTox/blob/6522988e8c2ef408278c0602ac9fd756b235b77b/src/persistence/db/rawdatabase.cpp#L488.

> I want to import my old Skype chat history in qTox

that might not be too easy, but you can take a look at https://github.com/qTox/qTox/blob/master/src/persistence/history.cpp to see how we normally insert history and use the db.

> As I understand most Tox clients using propertary chat saving method

I wouldn't say "proprietary", our schema is totally public, but yes each Tox client uses its own method of history storage.

> Question is if I import data in qTox new qTox releases will not break chat history. Because your current statement is what chat history is still in development and can be lost.

I don't see that mentioned in the issue, but I might be missing it. We will preserve chat history. You can backup chat history in case of a bug causing loss, but we won't make an intentional change that removes history. DB schema will change, though.

>  Why you have not added partialy translated Latvian language?

The translations from weblate are only pulled in once in a while or before a release. The Latvian translations that have been added will be included before the next qTox release.

**Comment by Coool** [comment]
Can you suggest how best to do Skype chat history import coding. So developers of qTox can implement it later in qTox and add Skype chat history import button.

**Comment by anthonybilinski** [comment]
I don't know much about Skype's save format, but it looks like there's some kind of export functionality. qTox would need to be able to parse that and adapt the content to match our schema.

I think adding "import history from Skype" functionality is a low priority, and probably won't be worked on for a long time. Unfortunately there are many issue and features that need to be added.

**Comment by 2635599** [comment]
"I wouldn't say "proprietary", our schema is totally public, but yes each Tox client uses its own method of history storage."

not to mention where it saves profile, both of which are asinine. regardless of the fork both history and profile should be in the same locations. because of the mess having different locations between forks for profile i lost 2 contacts from a profile. they were there before i copies my profile to a baclup location, and still there when i finished making the copy, but when i reinstalled my os and qtox and restored my profile they were gone. the reason i'm commenting is that i want to know if i can open the db and manually add them there since the main app refuses to except them for whatever reason?

**Comment by Coool** [comment]
I can code Skype import functionality from Skype main.db SQLite database. I just need correct directions how best to do it. Clone qTox source and add function or Class?

**Comment by anthonybilinski** [comment]
@2635599 by "forks" do you mean different clients? Contacts are stored inside the <profile>.tox file, which unlike chat history, IS compatible between clients.

> but when i reinstalled my os and qtox and restored my profile they were gone. the reason i'm commenting is that i want to know if i can open the db and manually add them there since the main app refuses to except them for whatever reason?

restoring <profile>.tox should restore all contacts and your tox ID, restoring <profile>.db should restore your chat history, and qtox.ini should restore your client settings. It's strange that you lost any contacts after restoring <profile>.tox, if you still have the original <profile>.tox file, we could look into this.

What do you mean by qTox refusing to accept them? How are you trying to add the contacts, through a friend request?

@Coool qTox would need some new UI, maybe under "advanced" settings tab, it would need a new class to parse the input file and new History class support to inject friend history into the db. Also it will need some way for that chat history to be linked to a Tox ID of the same contact, so that we know which friend the history is for.

**Comment by Coool** [comment]
anthonybilinski, OK I will look at source and try to figure out. And play around. If I have questions ask here or make new Issue? Is qTox best option for Tox messaging protocol?

**Comment by 2635599** [comment]
@anthonybilinski no i do not mean different clients in mean different versions of qtox.  one version stores the user file in one location and another saves it in another location. as for where i'm trying to add the 2 missing contacts it's under the friends tab that should just add them back once their number is added back. if you have some way for only the dev group to look at the file sure i'll give you the original. thanks

**Comment by sudden6** [comment]
Personally I don't it makes sense to support importing chat histories from Skype into qTox. @Coool Do you have any special use case why you want to do that?

@2635599 which different versions of qTox do you mean exactly?

**Comment by 2635599** [comment]
lets see git, appimage, through synaptic. etc...

**Comment by Coool** [comment]
sudden6, I just offered. Nobody cares then I make SQL script my own use. Don't bother...

**Comment by sudden6** [comment]
@Coool If you make this an independent script we can link it from the wiki. I just don't see a big benefit of including it in the qTox code base at the moment.

**Comment by Coool** [comment]
OK, let's do it.

**Comment by sudden6** [comment]
@2635599 lets continue your problem in #5633 which you already opened.

**Comment by anthonybilinski** [comment]
I'll close off this issue since #5633 is handling the save locations and the original question here has been answered.
