### ISSUE TITLE
Reconnect button doesn't reconnect

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#5710]
qTox only goes offline, and never comes back online.

Enable UDP - on
Enable LAN discovery - on
No proxy

version 1.16.3.467 (rev.678fc51c) from a package.
FreeBSD 12

**Comment by Kribylet** [comment]
This is because the Qt signal connections that links the core events to the UI are made during Widget initialization, and reconnecting replaces the core instance without restoring these connections. The new core successfully connects, but the UI never realizes because it does not receive a "connected" signal.
