### ISSUE TITLE
Messages sometimes won't send for hours

### ISSUE THREAD

**Issue by CGM-games** [qTox/qTox#5736]
##### Brief Description

OS: Windows 10 (10.0)
qTox version: v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.9.6
Hardware: 
…

Reproducible: Sometimes
##### Steps to reproduce

1.  Chatting with a person can cause this.

##### Observed Behavior
Once in a while when chatting, it will take a long time to send the message. The sending circle goes on, and on. I once waited more than 12 hours for a message to send.

##### Expected Behavior
I expect to see the message sent the moment the enter key is pressed.
----

**Comment by anthonybilinski** [comment]
Unlike client-server chat where you can send a message to the server at any time, which can then deliver it to your friend next time they connect, with P2P communication like qTox, your message can only be sent when you and your friend are both online. If your friend is not online, it sits pending and automatically sends as soon as they come online. Could that be what you're seeing?

**Comment by CGM-games** [comment]
I don't remember this for certain, but my friend I believe was online when I sent the messages. But I'd assume my friend wasn't online. Another bug report (do I have to create a new bug report page to report this?) is that my friend is online, but it says that my friend is not online. I know my friend is online because we also use another chat service for special occasions. IDK why it does this. IDK anything about code. Thanks for the fast response by the way!

**Comment by anthonybilinski** [comment]
> is that my friend is online, but it says that my friend is not online.

Because Tox is distributed, your friends are stored in a DHT that's made up by the users of Tox. You have to search this DHT for each friend to see if they are online, so when you come online. The online status for yourself is more an indicator that you have connected to the DHT, rather than you have searched it fully, so you may not have found all of your friends that are online yet. Your different friends may appear online at slightly different times form each other when you first log on, but you should find each one in ~10s generally.

If your friend is seeing himself come online, you are seeing yourself as offline, but you are both seeing each other as offline for a short period - that is expected. You should see each other as online within generally around 10s, and should see each other become online at the same time as each other.

**Comment by CGM-games** [comment]
Okay, thanks! I'll try to keep that in mind.
