### ISSUE TITLE
Donate link

### ISSUE THREAD

**Issue by danrobi11** [qTox/qTox#5752]
Hello qTox Team
How the users can donate?
I did not find a way to donate and i feel bad now.
Flatpak qTox v1.16.3.
Thanks!

**Comment by anthonybilinski** [comment]
Hi @danrobi11, thanks for your interest. qTox doesn't have any kind of financial non-profit organization that could receive donations for the project as a whole. We also don't have serious expenses as an organization, since we use FOSS software, free hosting/CI, and volunteer time.

I talked briefly with @sudden6 about the idea of having a non-profit that distributes donations to contributors by some metric - but then the metric becomes important and a bit messy. I'll keep talking to maintainers about ways we could handle this in a consistent way. The time to set up a non-profit is about 2 months and costs about $400 (at least where I live), and I'm not sure on the international-ness of that.

I think for now your only option is donating to individuals (with no legal guarantee of how that money will be spent). If you're interested in that contacting them individually to get paypal/other payment options would be best. Sorry this isn't very straightforward..

**Comment by danrobi11** [comment]
Thank you, i understand. Im also aware of the donation issue that 
happened in the past. Of course, we dont want that to happen again. I 
just like Tox very much, i dont want Tox to go away.

**Comment by anthonybilinski** [comment]
We like it too - and as far as I know Tox isn't at risk of going away any time soon. Because it's distributed there's no server hosting costs and no company that can go bankrupt and take it down, and because it's free and open source, even if we maintainers abandon the project someone else can always start it back up. :smiley:

**Comment by danrobi11** [comment]
Hi
I was refering to the new crazy laws. Forcing developers to implement 
backdoors into their encryption or jail time. I've noclue how 
developers will be able to fight that.
They will need a lot of support from us, thats for sure. I hope they'll 
reach out.
Take care friend.
- 
<https://www.techdirt.com/articles/20181208/14440541184/australian-government-passes-law-forcing-tech-companies-to-break-encryption.shtml>
- <https://www.bbc.com/news/world-australia-46463029>
- <https://www.theregister.co.uk/2019/07/23/us_encryption_backdoor/>

**Comment by anthonybilinski** [comment]
Since qTox and toxcore are open source, forcing one of us maintainers to introduce backdoors would be easily caught by the community and other maintainers. If we do get pressure like that, I think appealing to outside resources like maybe the EFF or FSF would be a better option for us than trying to pay for a legal fight ourselves.

qTox doesn't have any legal or financial organization, so can't accept donations directly. If you still want to donate, contacting individual contributors or maintainers, sponsoring them on github, or sending them money in some other ways is all that's available, but note that that money would be going to them personally.

I'll close this ticket since I don't think we have any plans to form a financial qTox organization that could accept donations, since qTox the project doesn't really have any expenses.

**Comment by rolfverh** [comment]
hallo we are couple and are looking for nice peapels

**Comment by rolfverh** [comment]
you also
