### ISSUE TITLE
qTox Unable To Connect with DHT node(port forwording behind firewall)

### ISSUE THREAD

**Issue by rong-00gle** [qTox/qTox#5794]
##### Brief Description

OS: Windows / Linux
qTox version: Release v1.16.3
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.10
…

Reproducible: Always

nmap results port open, Antox, toxygen is also able to connect with DHT-Node, but qtox is unable to connect with my DHT-node.

tox-bootstrap daemon: [tox-bootstrap.conf](https://github.com/qTox/qTox/files/3523608/tox-bootstrap.conf.txt)
qtox client settings: [qtox.ini](https://github.com/qTox/qTox/files/3523897/qtox.ini.txt)

if qtox is unable to connect with dht if tox-bootstrap daemon is behind cisco-asa and natting is applied on firewall. otherwise qtox client connect successfully.

**Comment by anthonybilinski** [comment]
Mobile clients usually connect to relay nodes over TCP. Desktop clients like qTox don't relay through nodes, and instead act as full DHT nodes with direct peer to peer connections using UDP.

Following https://github.com/TokTok/c-toxcore/issues/1338#issuecomment-522859928, make sure to forward your UDP port to connect to your bootstrap node from outside the firewall.

**Comment by rong-00gle** [comment]
@anthonybilinski thanks for quick reply
**Edit: qtox client settings: qtox.ini added in question**

if forceTCP=true then client should make all connection with tcp only.

**Comment by anthonybilinski** [comment]
True. Could you post your qTox debug logs? particularly the parts like:
`Connecting to`
`Error bootstrapping from`
`Error adding TCP relay from`

They can be found in settings -> advanced.

**Comment by rong-00gle** [comment]
```
[07:27:15.171 UTC] core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
core/core.cpp:357 : Debug: "Connecting to A.B.C.D:1352 (node)"
core/toxlogger.cpp:57 : Warning: "ERROR:network.c:sendpacket:484: attempted to send message of length 113 on uninitialised socket"
core/core.cpp:357 : Debug: "Connecting to A.B.C.D:1352 (node)"
```

Complete log file - [qtox.log](https://github.com/qTox/qTox/files/3524090/qtox.log)

**Comment by anthonybilinski** [comment]
It looks like we're adding your node both a bootstrap (UDP) and TCP relay, since at version 1.16.3 we didn't differentiate in the nodes list. When we try to bootstrap off it https://github.com/qTox/qTox/blob/8eed684c37bd711de2ca4bd863f5f0509edcdc2d/src/core/core.cpp#L365 we don't get an error back, but toxcore logs that network error because it's configured to run in TCP only mode. It looks like adding your node as a TCP relay works without error, since this log isn't hit: https://github.com/qTox/qTox/blob/8eed684c37bd711de2ca4bd863f5f0509edcdc2d/src/core/core.cpp#L370

We then keep bootstrapping over and over because toxcore reports that we aren't connected to the DHT https://github.com/qTox/qTox/blob/8eed684c37bd711de2ca4bd863f5f0509edcdc2d/src/core/core.cpp#L310, which is why "Connecting to" keep getting logged forever.

Is your bootstrap node connected to a DHT, or is it totally isolated? It looks like qTox is correctly adding the TCP relay, but toxcore is never reporting that there are enough nodes to create the onion, so keeps reporting that we're offline, so we keep trying to bootstrap off the one provided node.

**Comment by rong-00gle** [comment]
I have created a tox-bootstrap daemon service leaving "bootstrap_nodes" list empty. (i don't know my bootstrap node is connected to dht or not)
In same way i have another node which is directly connected(no firewall), that one is working fine.

What should i do to make bootstrap node connected to a DHT?

**Comment by anthonybilinski** [comment]
If `bootstrap_nodes` is empty on your bootstrap node and there are no other nodes saved in its tox save from a previous run, and your qTox profile is only connecting to your bootstrap node, you'll end up with those two tox nodes connected to each other, and neither of them will have any way to connect to any other networks. Since you've effectively created a DHT of 2 nodes, toxcore can't create onion routes, so reports you as offline to qTox.

Is there a reason `bootstrap_nodes` is empty? I think if you were to add some nodes to it, your qTox would learn about them through your node and would come online.

**Comment by rong-00gle** [comment]
Now I add another self hosted node in bootstrap_nodes, so new architecture is like this:
```
          Node 1           Node 2          Node 3
 ----> A.B.C.D -----> B.C.D.E -----> A.D.D.E -----> A.B.C.D
```

uTox & Toxygen connected with my tox-bootstrap daemon A.B.C.D successfully.

`﻿{"last_scan":1537033322,"last_refresh":1537033325,"nodes":[{"ipv4":"A.B.C.D","ipv6":"-","port":1352,"tcp_ports":[1352],"public_key":"key","maintainer":"me","location":"me","status_udp":true,"status_tcp":true,"version":"2014101200","motd":"tox-bootstrapd","last_ping":1537033323}]}`

But qTox still unable to connect.

**Is there a reason bootstrap_nodes is empty?**
I wanna host my own network, i don't want any third party to be involved in. tox protocol is decentralized potential Sybil attack, looking for an option if i can host my own tox-bootstrap network and all my users only connect with this network only.

**Comment by anthonybilinski** [comment]
To summarize a Tox chat we had to look into the issue some more:
1) the other clients were sneaking out UDP connections, so their online status wasn't based just on the local bootstrap node, but on the whole DHT.
2) Toxcore seems to not consider itself online until it's connected to 6 other nodes it can use to construct onion routes: https://github.com/TokTok/c-toxcore/blob/7418174129dc4baecacbba3392c68435b3e49d3c/toxcore/onion_client.c#L1796

The toxcore guys would know best about how to create a fully isolated DHT, but for now @rong-00gle is going to test having 6 more nodes in his local DHT for qTox to connect to, to see if it's then "online" and can search for friends through its DHT.

**Comment by anthonybilinski** [comment]
Is more support needed for this, or can the issue be closed?
