### ISSUE TITLE
Graphical glitch when leaving groupchat

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#58]
Have no other contacts. Create a groupchat. Right click and quit the groupchat. Where the groupchat was is colored differently, and it disappears if you click another button (or take a screenshot, apparently.) Same on Windows and Linux. Tiny thing that'll likely never crop up in actual normal use but it's there.

**Comment by F1ynn** [comment]
Does the same thing happen when it's a friend instead of a group?

**Comment by ProMcTagonist** [comment]
Yep, just tested.

**Comment by F1ynn** [comment]
Should be fixed now, thanks for reporting it.

**Comment by ProMcTagonist** [comment]
Is it fixed in a PR or your fork? The problem still exists in the latest Jenkins build for Windows.

**Comment by F1ynn** [comment]
I added what I thought would fix it in my PR, but it looks like it's not actually working (calling the repaint / update methods on the widget doesn't actually make them repaint [since the issue here is that the background is left unpainted when the FriendWidget is removed]).

I'm working on an OSX build right now but I'll look into it again as soon as I have time.

**Comment by ProMcTagonist** [comment]
Alright, cool. Can't wait for an OS X build.

**Comment by F1ynn** [comment]
Should be fixed now, check it out and let me know.

**Comment by tux3** [comment]
Closing, please comment if you're still affected and I'll reopen.
