### ISSUE TITLE
[Feature request] Proper support for "Read receipts"

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#584]
Message should be marked as not delivered until read recipe confirms that it has been delivered. In similar manner to Toxic's:
![txcofom](https://cloud.githubusercontent.com/assets/3148759/4849381/5cbda5ca-6061-11e4-8635-8a51b800c98f.png)

Current implementation isn't flexible enough, and it doesn't consider situation with #583 in place.
![qTox fail recipe](https://cloud.githubusercontent.com/assets/3148759/4849439/bface6c8-6061-11e4-9258-e8b5c6a4e6b8.png)

Perhaps an optional switch in options to turn displaying it off.

**Comment by tux3** [comment]
Maybe we could have a small spinning throbber to the right that turns into a red cross if the message wasn't delivered correctly and disappears otherwise.

And then we could store in the history DB wich messages were sent or still need sending, and we get faux-offline for free. Just resent anything that needs resending the next time someone comes online.

**Comment by ProMcTagonist** [comment]
Sounds perfect.

**Comment by zetok** [comment]
Perhaps instead of disappearing it could turn into green `✔` when message is delivered successfully?

**Comment by ProMcTagonist** [comment]
I don't know about having a checkmark next to eery single message. Maybe if it was incredibly subtle, or faded to being incredibly subtle after a few seconds. I think it might be cleaner to just have an usnent mark until they're confirmed sent.

**Comment by tux3** [comment]
Done.
