### ISSUE TITLE
Future of qTox and ToxMe after toxme.io goes offline

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5897]
toxme.io has been taken offline permanently: https://github.com/LittleVulpix/toxme/commit/52c731993ad9bfb6eacde8ace91f896d718a2811

Given this, what should qTox do about ToxMe support? Theoretically someone with other domains or using the same domain could take over the hosting.

1) Remove ToxMe completely from qTox.
2) Support generic name@domain format addresses, and try to fetch a ToxID from whatever address is entered. Still remove registration on ToxMe our Profile form.
3) Something else?

It seems like an important part of info needed is: Is ToxMe a kind of protocol/spec, or just that specific website's API? If it is standardized, does this include account registration?

I'm personally leaning towards just taking ToxMe out of qTox completely. I never really liked the centralized nature and metadata disclosure of hosted name lookup, and there hasn't been any volunteers to take over hosting of toxme.io on IRC so far, meaning qTox will be left with a registration page and friend lookup that times out on every attempt for the foreseeable future, which is a poor user experience.

@qTox/core?

**Comment by anthonybilinski** [comment]
Sample PR to remove ToxMe from qTox is linked.

**Comment by Diadlo** [comment]
My first large PR in my first open-source project was integration ToxMe registration in qTox. Sorry to hear that ToxMe goes offline. I think it's ok to remove this feature completely

**Comment by sudden6** [comment]
>  Is ToxMe a kind of protocol/spec, or just that specific website's API? If it is standardized, does this include account registration?

IIRC the answer to both of these questions is "yes", with the drawback that toxme.io was the only known implementation. I don't think the general idea of this service is bad, because it makes Tox more accessible to users.

I'm ok though with removing the functionality from qTox, because it's probably much better to add it again should such a service re-appear, than to carry it as a dead dependency.

**Comment by anthonybilinski** [comment]
Some more input from IRC, when I asked about the API-ness of ToxMe:

> (09:37:28 PM) LittleVulpix: anthonybilinski: I believe there were others hosting their own mini instances. none were as utilized as toxme.io though. The api itself is however available and all of the other toxme servers were using it.
(09:40:35 PM) nurupo: anthonybilinski: it's open source and anyone can host their instance
(09:40:54 PM) nurupo: i don't really remember how api works though, i only remember it being rather weird
(09:41:48 PM) LittleVulpix: anthonybilinski:  see https://github.com/LittleVulpix/toxme
(09:42:29 PM) nurupo: i hope clients are authenticating toxme services though, because someone might buy toxme.io domain after LittleVulpix lets it go and host a hostile toxme instance
(09:42:48 PM) LittleVulpix: nurupo: yes we have a key
(09:44:30 PM) nurupo: i think toxme services have some instance-specific key, which clients can whitelist for popular toxme services and bundle the whitelist along with the client, and for less popular ones the keys could be cached by the client on the first use and then the user could be warned if the service changes its key
(09:45:15 PM) nurupo: at least it was supposed to work like that, no idea if clients support this
(09:46:03 PM) LittleVulpix: Yeah. Since you can "just ask" via the site itself and such, nothing stops a malicious 3rd party from submitting bogus tox IDs to people who query the service after the domain lease expires (if someone buys it)

In our ToxMe class, we fetch the pk from the server located at doamin/pk, but we just use that to encrypt the json data.. which seems rather pointless over an https connection. We don't have any form of key verification or TOFU mentioned. Although others could host an instance, it means qTox would be trusting whatever server the user punched in to provide the correct tox ID. Maybe the user would understand that they're trusting the server completely to give them the right tox ID back, but I feel like if someone is told "hey add me at domain/name", they add that domain/name, then connect to a random attacker - a lot of people would be surprised. This is part of my problem with toxme in the first place - handing over trust to the host.

Supporting small self-providers is kind of nice, but in that case having an API more like `GET domain/toxid/<name>` that just returns a toxid seems like a cleaner way to do it vs the fuller ToxMe API. Even with our support removed from qTox, anyone using a small provider can easily open the link and copy paste the tox ID in.

I'll go ahead with merging the removal of ToxMe support in qTox in a few days unless there's more input.

**Comment by nurupo** [comment]
Not sure why you want to remove ToxMe support just because toxme.io was taken down. There might be users hosting their own ToxMe instances that would be very surprised to find the feature being removed for such reason.

---

The way ToxMe support in clients was supposed to be implemented is that a client would store ToxMe service's public key on the first use, and would always verify that the service replies are signed with it. That way, if a particular ToxMe instance changes owners, e.g. the first owner abandons the service and the domain and a new (potentially hostile?) owner takes over the domain, which what might happen with toxme.io, the new service would use a different keypair - the clients that have accessed the service before it was taking over would notice signatures no longer verifying and would warn the user that something is not right and they probably should research about what happened to the ToxMe service before using it, allowing the user to accept the new key if they are sure. The whole thing is similar to how ssh server fingerprint verification works.

Ideally clients would be shipped with public keys of popular ToxMe services included, that way even if a user has never accesses a popular ToxMe service before, they would still notice the key change. Clients could also use blacklists, e.g. it might make sense to make a new qTox release with toxme.io being blacklisted, not allowing the user to accept the changed key.

---

>In our ToxMe class, we fetch the pk from the server located at doamin/pk, but we just use that to encrypt the json data.. which seems rather pointless over an https connection

Aren't only [Authenticated API](https://github.com/LittleVulpix/toxme/blob/master/doc/api.md) encrypted, to prove that you own the private key? Name lookup is in the Anonymous API section, which shouldn't be encrypted. At least that's my understanding of it, I'm not very familiar with it so I might be mistaking.

>it means qTox would be trusting whatever server the user punched in to provide the correct tox ID.

That's right, ToxMe are just centralized lookup services (phonebooks) used for convenience, you have to trust the service to return the correct ID. Of course it could replace someone's id in a name-to-id mapping with a NSA agent's ID and you wouldn't know any better when adding it.

>anyone using a small provider can easily open the link and copy paste the tox ID in.

That's a bad assumption, there is nothing saying that a ToxMe service must have a web UI, it just has to provide the API. [There are some implementations of ToxMe without the web ui](https://github.com/ovalseven8/ToxMe), as well as the web ui in https://github.com/LittleVulpix/toxme implementation could be disabled. So "easily open the link and paste the tox id in" doesn't hold true.

**Comment by sudden6** [comment]
> There might be users hosting their own ToxMe instances that would be very surprised to find the feature being removed for such reason.

IIRC the toxme.io domain was hardcoded, so if there were other users we would have had heard about them.

**Comment by Diadlo** [comment]
@sudden6 AFAIR it's not hardcoded. It's just one default value in the list.
[toxmeServersList](https://github.com/qTox/qTox/blob/85361393417d76875448ec9f25f21c13ca990b74/src/widget/form/profileform.ui#L337) it's editable combobox

**Comment by nurupo** [comment]
I thought it worked with any domain?

**Comment by sudden6** [comment]
Hmm, seems I'm misremembering that then.

**Comment by nurupo** [comment]
Yeah, I don't see any restrictions anywhere:

https://github.com/qTox/qTox/blob/17083b50ba3de2ddbb2e534f4c30509bedab016b/src/widget/form/addfriendform.cpp#L200-L211

https://github.com/qTox/qTox/blob/85361393417d76875448ec9f25f21c13ca990b74/src/net/toxme.cpp#L134-L151

https://github.com/qTox/qTox/blob/17083b50ba3de2ddbb2e534f4c30509bedab016b/src/net/toxmedata.cpp#L90-L98

**Comment by nurupo** [comment]
If you want to remove it because you don't like the idea of having to trust the service to return correct tox ids, then fair enough. However, removing it only because toxme.io has shut down doesn't make much sense to me.

**Comment by sudden6** [comment]
@nurupo do you know of any other (still running) toxme instances?

**Comment by anthonybilinski** [comment]
Agreed that it is still usable within qTox, and yes users can manually enter a domain. Good point about the services maybe not also running a web server.

I think if we do keep it, we should release with trusted keys (which would have been just toxme.io - now I guess none for the next release), and implement TOFU with a user prompt, like ssh fingerprints, and also make it more clear that the user is completely trusting the third party service to give them the right Tox ID back. Integrating it into our "add friend" UI in a way that makes it seem equivalent to a Tox ID seems like it gives it too much of an endorsement by qTox.

My motivation to remove it now was mostly because:
1) I don't like it conceptually (third party trust, metadata disclosure)
2) Most (probably?) existing addresses are now invalidated, or would be pointing at a possible new server that could be malicious.

If we want to keep it around to support smaller hosted services or self-hosted look ups, that's reasonable.

**Comment by nurupo** [comment]
>@nurupo do you know of any other (still running) toxme instances?

I do not, but then again I don't use Tox so unless someone mentions it on IRC I wouldn't know.
