### ISSUE TITLE
Are group invites exclusive to qtox friends?

### ISSUE THREAD

**Issue by je-vv** [qTox/qTox#5960]
##### Brief Description

OS: Arch GNU + Linux
qTox version: 0.2.10
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore:  0.2.10
Qt:  5.14.0
Hardware:  Mintbox2 mini-pc
Reproducible: Always

When inviting trifar tox friends (from f-droid), v. 1.0.27, the trifar friend never receives the invitation.  I'm not sure if this is due to qtox not being able to invite other friends than just qtox ones.  If that's the case, are there plans to support inviting non qtox friends, particularly trifa ones?  And if not, then I apologize for the issue.  Right now I'm not finding a way to integrate trifa friend into tox groups created by qtox.

**Comment by anthonybilinski** [comment]
The general Tox protocol supports 2 kinds of groups,
1) Text-only groups
2) Audio and text groups

When qTox creates a new groups, it creates type 2 (audio and text), since if you don't want audio you can just not start a call, but still have the option. qTox accepts invites of either kind though, so qTox still fully accepts being invited to a type 1 (text-only) group, it just won't create that type by default.

I believe TRIfA supports only type 1, meaning when qTox creates a group and invites (with type 2), TRIfA isn't able to accept it.

Can you try creating the group in TRIfA (type 1) and inviting qTox? qTox should support that fully.

**Comment by je-vv** [comment]
Trifa, at least the current version from f-droid (1.0.27), doesn't seem to be able to create a group, :(.  So I guess I'm out of luck...  Thanks a lot !

**Comment by anthonybilinski** [comment]
:(

From your other comment you mentioned "whereas Trifa and other clients only supporting type 1" - are you aware of other clients that only support text-only groups? qTox could add the option to create text only groups as a workaround if it was widespread among other clients, but since audio groups are part of the Tox spec, qTox's behaviour should work with any Tox spec fulfilling client.

**Comment by je-vv** [comment]
I also used Antox some time back, and it also used to ignore invites to join tox groups created on qtox.  However the Antox version available is pretty old, and I don't know if there are different plans.  Some time back I decided to move to Trifa for that reason, even though I find Antox's UI more pleasant.  I haven't used other clients, just those 3, qtox, trifa and antox...

**Comment by anthonybilinski** [comment]
As far as I know Antox doesn't support groups at all unfortunately, and is unmaintained for the last few years. There's another Android client, aTox which I use, but it also doesn't yet support groups, although is actively maintained.

**Comment by zoff99** [comment]
> :(
> 
> From your other comment you mentioned "whereas Trifa and other clients only supporting type 1" - are you aware of other clients that only support text-only groups? qTox could add the option to create text only groups as a workaround if it was widespread among other clients, but since audio groups are part of the Tox spec, qTox's behaviour should work with any Tox spec fulfilling client.

so qTox is NOT a Tox spec fulfilling client then, by your own words

**Comment by anthonybilinski** [comment]
In what way? qTox supports receiving invites to text group or audio groups, supports being in either, and supports inviting to either. qTox just doesn't present a UI option to create a new text only group, since creating an audio group and not sending audio frames is a superset of all functionality, and gives a better user experience since if a user later wants to use audio, they can just unmute instead of having to create a second group. The only motivation I see to adding this UI option to create text only groups would be to workaround TRIfA's lack of support for receiving audio group invites, which are in spec.

**Comment by je-vv** [comment]
No need for qtox to create text only groups, sort of defeaturing it.  Trifa should be able handle text+audio groups, or be able to create test only groups if that's the only thing it supports...  It's sad it doesn't.  I believe what's worth is getting Trifa to support text+audio groups, though I have no clue when that'll happen.

Thanks a lot, and sorry for the noise caused.  Now I understand much better what's really missing.

**Comment by zoff99** [comment]
@je-vv it will happen when there is a developer spending time coding it. are you volunteering?

**Comment by je-vv** [comment]
@zoff99, I can't, sorry.
