### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by quantumpacket** [qTox/qTox#5965]
I was looking through [flatpak/io.github.qtox.qTox.json](https://github.com/qTox/qTox/blob/master/flatpak/io.github.qtox.qTox.json) and noticed we are specifying to use [ffmpeg 4.0.1](https://ffmpeg.org/releases/ffmpeg-4.0.1.tar.bz2) which has [~60 CVEs](https://ffmpeg.org/security.html). The [dependencies table](https://github.com/qTox/qTox/blob/master/INSTALL.md#dependencies) lists an even older version of ffmpeg supported. Would updating it to the latest secure version break anything? If not, how about updating to at least the latest compatible version?

I haven't checked the other dependencies if they have any known CVEs, or where else we may be using _potentially_ vulnerable versions. Maybe it's time to do an audit of dependencies to see what needs to be updated?

**Comment by sudden6** [comment]
Note that the linked flatpak specification file is not used to build the qTox releases on Flathub, this one is: https://github.com/flathub/io.github.qtox.qTox/blob/master/io.github.qtox.qTox.json

Nevertheless the releases on our Github are built with that version, so we should probably update (and take the file from Flathub as reference). In addtiion, a complete evaluation of the dependencies and build commands for Windows, Linux AppImage, Linux Flatpack and MacOS is also good idea. As long as there weren't any API breaks this should be quite simple.

I would be happy if you can submit a PR. If you need some guidance just ask here.

**Comment by anthonybilinski** [comment]
Change to release procedure here: 12fc33ee23d2d7b5ef0e552626c7f0e6bcac44c0 should ensure each of our github releases has as up to date dependencies as the flathub build, so as long as they keep updating deps there this should be resolved for our releases.

ffmpeg specifically in the github release was updated prior to release v1.17.0: 71b5c50ac6c24bea6995ad3093a28376365aaab4

RE: the [dependencies table](https://github.com/qTox/qTox/blob/master/INSTALL.md#dependencies) I don't think we should artificially raise our minimum supported version of deps, since some LTS distros may use patched versions. I view this more as a "what range of packages could you use" not "should you use". Generally anyone with the ability to run whatever version of the deps should tend towards the upper end of supported versions.

@sudden6 do you remember what you meant by this?
> In addtiion, a complete evaluation of the dependencies and build commands for Windows, Linux AppImage, Linux Flatpack and MacOS is also good idea. As long as there weren't any API breaks this should be quite simple.

Basically that we should go over everything build related unrelated to the flatpak deps?

**Comment by sudden6** [comment]
> Basically that we should go over everything build related unrelated to the flatpak deps?

I think I was talking about making sure that the dependency versions defined in the build scripts are the latest possible ones, ie. the scripts executed for the release.

**Comment by quantumpacket** [comment]
Has this been resolved so it can be closed?
