### ISSUE TITLE
Nightly builds are not being published

### ISSUE THREAD

**Issue by anthonybilinski** [qTox/qTox#5985]
Reproducible: Always

##### Observed Behavior
1) The latest nightly at https://github.com/qTox/qTox-nightly-releases/releases is 17 days old at the time of opening this issue.
1) Sometimes OSX gets back a publishing error from the publishing tool:
```
09:05:04 * Creating a temporary store release with the tag name "ci-master-9198-13-tmp".
09:05:04 Creating a release with the tag name "_ci-master-9198-13-tmp".
09:05:05 Uploading artifacts to "_ci-master-9198-13-tmp" release.
09:05:05 Found 2 artifact(s) in "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/tmp.aIZg7h0e" directory.
09:05:05 	Storing "qTox.dmg" (80861318 bytes) artifact in the release.
09:05:08 	Storing "qTox.dmg.sha256" (75 bytes) artifact in the release.
09:05:08 GithubException: 422 {"message": "Validation Failed", "request_id": "D784:7927:128417:1813D7:5E50EEC4", "documentation_url": "https://developer.github.com/v3", "errors": [{"resource": "ReleaseAsset", "code": "already_exists", "field": "name"}]}
The command ".travis/cirp/store.sh "$ARTIFACTS_DIR"" exited with 1.
```
3) Sometimes Windows builds see a JSON decode error like in https://travis-ci.org/qTox/qTox/jobs/652236711
```
23:50:14 JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The command ".travis/cirp/cleanup1.sh" exited with 1.
0.01s$ .travis/cirp/store.sh "$ARTIFACTS_DIR"
Build has failed, skipping publishing
```
4) flatpak build is sometimes failing to install dependencies, but has been like that for a while, e.g. https://travis-ci.org/qTox/qTox/jobs/650892276 and just happened again on my most recent PR.
```
Error: While pulling runtime/org.kde.Sdk/x86_64/5.11 from remote flathub: Server returned status 503: Service Unavailable
error: Failed to install org.kde.Sdk: While pulling runtime/org.kde.Sdk/x86_64/5.11 from remote flathub: Server returned status 503: Service Unavailable
Error installing deps: running `flatpak --system install flathub -y org.kde.Sdk/x86_64/5.11`: Child process exited with code 1
The command "./flatpak/build-flatpak.sh" exited with 1.
```

##### Additional Info
I've tried deleting multiple half-finished releases from https://github.com/qTox/qTox-nightly-releases/releases thinking that maybe those were causing the conflict, but that doesn't seem to help.

We were getting errors from our `after_success` conditions in our travis config:
```
"/home/travis/.travis/functions: line 109: test: ==: unary operator expected
```
which if fixed by https://github.com/qTox/qTox/pull/5983. But they don't seem related.

That fix once merged to `master` will bump our master commit, which might help with the duplicate artifact errors.

I'll keep looking into this and keep notes here since it's starting to be a lot of different things.

**Comment by sudden6** [comment]
@nurupo any ideas what could cause this?

**Comment by nurupo** [comment]
1. As to why nightly builds are 17 days old - there were no new commits in 17 days. Nightly builds are Travis Cron Builds that run every day, but they are set up to publish a release only if there was a new commit made in the qTox repo -- we thought that publishing nightly release of the same qTox git commit hash every day was silly as they would be nearly identical.

    [`.travis/cirp/check_cache.sh`](https://github.com/qTox/qTox/blob/master/.travis/cirp/check_cache.sh) and [`.travis/cirp/update_cache.sh`](https://github.com/qTox/qTox/blob/master/.travis/cirp/update_cache.sh) are responsible for this. However, instead of being used in every job to skip building qTox needlessly, those scripts are used only in the last job - the publishing job, to skip publishing the nightly release, so all jobs still try to build qTox daily. This is because we don't want to update the cached git commit hash unless we actually publish a release (e.g. in case a build failure happens). For example, [here you can see](https://travis-ci.org/qTox/qTox/jobs/654032677#L332) the publishing job collecting build artifacts of all other jobs in the build and then deciding not to go through with creating a release as it's the same git commit hash as in the cache.

    Since the git commit hash is stored on Travis cache, you could force a nightly release if you clear the cache and restart the latest cron build.

2. Not sure what is happening here. It's an exception from the PyGithub library that wraps the GitHub API error saying that `qTox.dmg.sha256` file already exists in the draft release - which shouldn't be possible as this is a newly created draft release and this is the only job uploading files to it. It's either some bug on GitHub's side or the PyGithub library for some reason tried to upload the file twice (bad network condition on Travis-CI + re-try logic?).

    All I can suggest is to ignore it as it's likely to go away on the next day, or just to restart the build to try again.

3. `JSONDecodeError` - that's usually due to Travis-CI API returning an empty json response with HTTP 2xx code. [I have seen this happen](https://github.com/nurupo/ci-release-publisher#jsondecodeerror) only with the `/auth/github` endpoint, caused by a misconfiguration of a GitHub access token, but in your case it seems like some other endpoint is causing this. If your GitHub token was misconfigured the script would never have published anything, which is obviously not the case. Hard to tell which Travis-CI endpoint is doing this since the backtrace is intentionally disabled in the script as an attempt to prevent the GitHub access token from leaking. This is clearly some API bug on Travis-CI's side and it shouldn't be happening often.

    All I can suggest is to ignore it as it's likely to go away on the next day, or just to restart the build to try again.

4. Not related to the CIRP.

>I've tried deleting multiple half-finished releases from https://github.com/qTox/qTox-nightly-releases/releases thinking that maybe those were causing the conflict, but that doesn't seem to help.

Releases shouldn't cause any conflicts, half-finished or not. However, deleting a `ci-` release but keeping its `ci-` tag will cause the script to get confused. So **please delete the `ci-master-latest` and `ci-master-9173` tags**. Maybe it's something the script should learn to handle in the next version, huh. The script hasn't been confused by them yet, as it kept skipping publishing because there were no new commits for 17 days, and the worst that can happen is that the scrip won't publish any release and would fail the build.

The reason there were half-finished releases is because a build has failed, which caused all artifacts for that build to be deleted by a cleanup script, and then someone has restarted just 2 jobs in that build - the Flatpak job and the publishing job, so with other artifacts being deleted the publishing job only had the Flatpak build artifact to upload. The way CIRP is setup for qTox, the proper way to handle this would be to restart the whole build, instead of individual jobs. That would re-create the deleted build artifacts.

CIRP is flexible and you could configure it in such a way that would allow you to restart just the 2 mentioned jobs instead of the whole build. To get this behavior you need to remove the appropriate cleanup script calls so that build artifacts (the draft releases) don't get deleted on the build failure. That would result in draft releases littering the Releases page, but only repo owners can see them so it could be a reasonable compromise. The way CIRP is setup right now is to avoid leaving useless draft releases as soon as possible, so it deletes them as soon as a build fails, instead of keeping them around for the next build to delete them.

Btw, I brought up this half-finished releases issue on the qtox IRC a couple of days ago.

**Comment by anthonybilinski** [comment]
> As to why nightly builds are 17 days old - there were no new commits in 17 days

:man_facepalming: I considered that then saw that the last commit date was from 2019-10-10, and saw that -10 thinking it was 13 days ago from today so mustn't just be that. I should stop looking at issues late at night.

> However, deleting a ci- release but keeping its ci- tag will cause the script to get confused. So please delete the ci-master-latest and ci-master-9173 tags.

Thanks, done.

>The reason there were half-finished releases is because a build has failed, which caused all artifacts for that build to be deleted by a cleanup script, and then someone has restarted just 2 jobs in that build - the Flatpak job and the publishing job, so with other artifacts being deleted the publishing job only had the Flatpak build artifact to upload. The way CIRP is setup for qTox, the proper way to handle this would be to restart the whole build, to re-generate the deleted build artifacts of the succeeded jobs.

Ah I didn't realize this, for the many sporadic failures we see, I was just restarting the one failed task rather than the whole build. I'll change my workflow for that.

I was just starting to look in to CIRP when I posted this issue, I hadn't really followed the nightly release stuff when it went in. The behaviour it has now of deleting draft releases on failure seems better to me, even if only maintainers would see the clutter.

> Btw, I brought up this half-finished releases issue on the qtox IRC a couple of days ago.

I really need to keep up better on IRC and set up something always-on for home

Thanks for all the all the good info and the tool itself. Sounds like our next nightly should actually publish due to the basic branch merge from https://github.com/qTox/qTox/pull/5984 causing a new commit on `master`. Will keep this ticket around for the partial releases and to verify we do see the new release by tomorrow. The partial releases might also be related to me restarting individual tasks.

**Comment by sudden6** [comment]
@nurupo thank you very much for that writeup!

> eleting a ci- release but keeping its ci- tag will cause the script to get confused. So please delete the ci-master-latest and ci-master-9173 tags.

>  the proper way to handle this would be to restart the whole build, instead of individual jobs. 

@anthonybilinski we should write these two down somewhere, or we'll have the same problem in ~6months again :man_facepalming:

**Comment by nurupo** [comment]
>Will keep this ticket around for the partial releases and to verify we do see the new release by tomorrow.

[The new releases are in](https://github.com/qTox/qTox-nightly-releases/releases).
