### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by biglone** [qTox/qTox#6138]
##### Brief Description

OS: OS X (10.15.2)
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  
toxcore:  
Qt:  5.13.1

##### Steps to reproduce

When I cmake ,it aways failed with message:
CMake Error at /Users/liuyuanlong/Qt5.13.1/5.13.1/clang_64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "gl.h" in
  "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers".
Call Stack (most recent call first):
  /Users/liuyuanlong/Qt5.13.1/5.13.1/clang_64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:185 (include)
  cmake/Dependencies.cmake:27 (find_package)
  CMakeLists.txt:134 (include)

-- Configuring incomplete, errors occurred!

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by sudden6** [comment]
Looks like you're missing the development package for Qt.

**Comment by biglone** [comment]
> Looks like you're missing the development package for Qt.

But I have already install Qt v5.14.1 for sure, thanks for reply though.

**Comment by anthonybilinski** [comment]
https://github.com/qTox/qTox/blob/master/osx/qTox-Mac-Deployer-ULTIMATE.sh is used by our CI and builds qTox successfully on macOS, and it installs the packages through brew from https://github.com/qTox/qTox/blob/master/osx/Brewfile.

Note that if you do use qTox-Mac-Deployer-ULTIMATE.sh, take note of the issue and workaround here: https://github.com/qTox/qTox/issues/6207#issuecomment-673936910.

This must be a missing dependency in some way. I realize this issue is very old by this point, but if you're still interested give those a shot.
