### ISSUE TITLE
qTox crashed

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#617]
Probably related to 2 instances of qTox running at the same time, using different profiles.

https://gist.github.com/zetok/57b25dac7b3ac748f3df

Pls fix.

**Comment by tux3** [comment]
It crashed in add_data_end_of_buffer.

I know for a fact that this function or the way it's used is broken, the memory allocated here is sometimes never free'd (as reported by valgrind), but I haven't had the time to write a non crappy fix yet.

And since the crash was a corrupted double-linked list, it sounds very much like a bug in toxcore, although I can't prove that.

**Comment by tux3** [comment]
Does anyone still has this bug ?

I've tried running qTox through valgrind recently and toxcore doesn't seem to have the problem I mentioned. It might have been fixed.

**Comment by zetok** [comment]
Since no one seems to suffer from it, closing.
