### ISSUE TITLE
Stopped working on Gentoo.

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6183]
Hello, I have problem with qTox since this commit.
https://github.com/qTox/qTox/commit/f37813ff88e67c4e9b66cbb2f9357a0e3cf0305f
qtox-9999.ebuild compiles without errors, but the program itself does not start now, giving this error:
`qtox: error while loading shared libraries: libtranslations_library.so: cannot open shared object file: No such file or directory`

**Comment by sudden6** [comment]
@unnamed9 can you test if the fix proposed by @Chiitoo works for you? I can't reproduce the problem, but the fix might work.

@Chiitoo since I can't repro this problem, can you explain why this fix makes things work?

**Comment by ghost** [comment]
@sudden6 Yes, the patch helped and qTox now starts without any problems.

**Comment by Chiitoo** [comment]
Thanks for testing!

I had not bumped into this myself since I usually build qTox manually, but indeed, it will happen with the Gentoo ebuild because, by default, for all CMake builds 'BUILD_SHARED_LIBS ON' is set (as long as the 'cmake.eclass' is being used), which the qTox build happily takes but then produces this issue because the 'libtranslations_library.so' file isn't being installed.

One could have also worked around this by setting 'BUILD_SHARED_LIBS=OFF' in the ebuild, but fixing it on the build system level seems more appropriate.

So, to re-produce with a local build, running qTox from the build directory: set '-DBUILD_SHARED_LIBS=ON' and delete 'translations/libtranslations_library.so' after the build.
