### ISSUE TITLE
tox keeps "Connecting to a bootstrap node..."

### ISSUE THREAD

**Issue by houjaii** [qTox/qTox#6201]
##### Brief Description

OS: OS X Catalina
qTox version: v1.17.2
Commit hash:  465d82606813439ee14425f7462903bb39f2da30
toxcore:  0.2.11
Qt:  5.14.2
…

Reproducible: Always
I created a new profile in my friend's house two days ago (forgot the password of the old one), it was offline at first. When I changed to another WiFI, it got me online and added/chatted with friend successfully.

I opened and loaded profile at my place today, it stayed offline status with the red circle, so I tried to make a new profile or reinstall the qTox again and again, it didn't help. When I checked the debug log, it was saying "Connecting to a bootstrap node...".

##### Steps to reproduce

1. start qTox and load profile
2. wait the status turns into online
3. click the status button

##### Observed Behavior
no green light, remains red light, the status button no reaction

##### Expected Behavior
automatically turns into green light, the status button can be clicked and change status

##### Additional Info
**debug-log**
[03:57:49.133 UTC] platform/install_osx.cpp:101 : Debug: OS X: Old settings directory not detected
[03:57:49.133 UTC] persistence/settings.cpp:121 : Debug: "Loading settings from /Users/HouJai/Library/Application Support/Tox/qtox.ini"
[03:57:49.204 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  6146039671160072424
[03:57:49.205 UTC] main.cpp:308 : Debug: commit:  465d82606813439ee14425f7462903bb39f2da30
[04:00:38.298 UTC] persistence/profile.cpp:146 : Debug: Loading tox save  "/Users/HouJai/Library/Application Support/Tox/haoKaaa.tox"
[04:00:38.376 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/Users/HouJai/Library/Application Support/Tox/haoKaaa.ini"
[04:00:38.377 UTC] core/toxoptions.cpp:107 : Warning: Core starting without LAN discovery. Peers can only be found through DHT.
[04:00:38.377 UTC] core/toxoptions.cpp:110 : Debug: Core starting with IPv6 enabled
[04:00:38.454 UTC] persistence/db/rawdatabase.cpp:321 : Debug: Highest supported SQLCipher params on this system are "4.0 default"
[04:00:38.454 UTC] persistence/db/rawdatabase.cpp:292 : Debug: Setting SQLCipher "4.0 default" parameters
[04:00:38.455 UTC] persistence/db/rawdatabase.cpp:199 : Info: Opened database with SQLCipher "4.0 default" parameters
[04:00:38.466 UTC] persistence/settings.cpp:487 : Debug: Loading personal settings from "/Users/HouJai/Library/Application Support/Tox/haoKaaa.ini"
[04:00:38.467 UTC] persistence/settings.cpp:606 : Debug: "Saving global settings at /Users/HouJai/Library/Application Support/Tox/qtox.ini"
[04:00:38.471 UTC] nexus.cpp:86 : Debug: Starting up
[04:00:39.835 UTC] :0 : Warning: Populating font family aliases took 1173 ms. Replace uses of missing font family "Sans Serif" with one that exists to avoid this cost. 
[04:00:40.518 UTC] persistence/profile.cpp:318 : Debug: Self avatar not found, will broadcast empty avatar to friends
[04:00:40.945 UTC] :0 : Warning: Corrupt JPEG data: 73 extraneous bytes before marker 0xd9
[04:00:41.111 UTC] :0 : Warning: Corrupt JPEG data: 73 extraneous bytes before marker 0xd9
[04:00:41.814 UTC] net/updatecheck.cpp:89 : Info: qTox is up to date
[04:00:42.011 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:42.012 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:46.650 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:46.651 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:51.299 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:51.342 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:56.005 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:00:56.007 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:00.607 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:00.610 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:05.289 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:05.290 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:09.956 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:09.957 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:34.605 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:01:34.649 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:04:53.797 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:04:53.799 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:04:58.400 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:04:58.401 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:05:03.109 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:05:03.110 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:05:07.765 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:05:07.765 UTC] core/core.cpp:477 : Debug: "Connecting to a bootstrap node..."
[04:05:08.322 UTC] widget/form/settings/advancedform.cpp:115 : Debug: Found debug log for copying

**Comment by anthonybilinski** [comment]
Hi @houjaii, is it possible your network is being filtered? We have had reports of users in China having Tox bootstrap nodes be blocked, we have a section on it here: https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#avoiding-censorship.

If you think that's the case and don't want to use a proxy or VPN, there's been a feature added since version 1.17.2 so that is currently only available in a [nightly build](https://github.com/qTox/qTox-nightly-releases/releases) which adds the ability to add custom bootstrap nodes. If you have a friend who can connect to Tox, they could run a boostrap server: https://github.com/TokTok/c-toxcore/tree/master/other/bootstrap_daemon and give you the long term DHT key and IP, and you could add that to your [config file](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#bootstrap-nodes). Then when you start up you can connect to them, and they can give you info about the rest of the Tox network, which should let you get online even if you're having all the [public bootstrap nodes](https://nodes.tox.chat/) blocked.

Otherwise could you double check that in settings -> "Advanced" -> "Connection settings" that "Proxy type" is "None" in the dropdown? If it's on SOCKS5 or HTTP (or blank from an old bug) without an address filled, it will fail to connect for that reason.

**Comment by houjaii** [comment]
> Hi @houjaii, is it possible your network is being filtered? We have had reports of users in China having Tox bootstrap nodes be blocked, we have a section on it here: https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#avoiding-censorship.
> 
> If you think that's the case and don't want to use a proxy or VPN, there's been a feature added since version 1.17.2 so that is currently only available in a [nightly build](https://github.com/qTox/qTox-nightly-releases/releases) which adds the ability to add custom bootstrap nodes. If you have a friend who can connect to Tox, they could run a boostrap server: https://github.com/TokTok/c-toxcore/tree/master/other/bootstrap_daemon and give you the long term DHT key and IP, and you could add that to your [config file](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#bootstrap-nodes). Then when you start up you can connect to them, and they can give you info about the rest of the Tox network, which should let you get online even if you're having all the [public bootstrap nodes](https://nodes.tox.chat/) blocked.
> 
> Otherwise could you double check that in settings -> "Advanced" -> "Connection settings" that "Proxy type" is "None" in the dropdown? If it's on SOCKS5 or HTTP (or blank from an old bug) without an address filled, it will fail to connect for that reason.

Hi @anthonybilinski , I have double checked that the "Proxy type" is "None".

For the filtered network one, I am not sure that happened cause I download the utox which says out of date but it works fine, so I am wondering if there any other settings might affect my qTox status or connection?

**Comment by anthonybilinski** [comment]
The only settings that should be relevant are the ones under Connection Settings. It's quite strange that uTox is connecting and qTox isn't though, but also that we haven't seen other non-filtering related reports. It's possible that uTox has a slightly different list of bootstrap nodes, though I think we're both getting them from the same source.

I guess just to fully rule out the idea, could you try just TCP connecting, e.g. with `telnet` to `abilinski.com` port `33445`? Full command should be:
```
$ telnet abilinski.com 33445
Trying 172.103.164.206...
Connected to abilinski.com.
Escape character is '^]'.
```
then ctrl+] to close, and ctrl+d to exit. If it fails to connect it would indicate possible filtering since this is one of the bootstrap nodes.

If that connects no problem then looking into the difference with uTox and qTox seems like a good idea.

**Comment by houjaii** [comment]
> The only settings that should be relevant are the ones under Connection Settings. It's quite strange that uTox is connecting and qTox isn't though, but also that we haven't seen other non-filtering related reports. It's possible that uTox has a slightly different list of bootstrap nodes, though I think we're both getting them from the same source.
> 
> I guess just to fully rule out the idea, could you try just TCP connecting, e.g. with `telnet` to `abilinski.com` port `33445`? Full command should be:
> 
> ```
> $ telnet abilinski.com 33445
> Trying 172.103.164.206...
> Connected to abilinski.com.
> Escape character is '^]'.
> ```
> 
> then ctrl+] to close, and ctrl+d to exit. If it fails to connect it would indicate possible filtering since this is one of the bootstrap nodes.
> 
> If that connects no problem then looking into the difference with uTox and qTox seems like a good idea.

I just try it, and it seems like a blocking issue:

```
% telnet abilinski.com 33445                                                                                                    
Trying 172.103.164.206...
telnet: connect to address 172.103.164.206: Operation timed out
telnet: Unable to connect to remote host
```
so I should use proxy/vpn or use the custom bootstrap nodes features to make sure my qTox working, is that right?

**Comment by anthonybilinski** [comment]
Yes those three options should work. A proxy can hide your Tox traffic and can be configured in the network settings of qTox, a VPN can hide your whole system traffic, and using a custom bootstrap will just let you find out about some other Tox nodes and as far as we know non-bootstrap Tox nodes aren't blocked, so then you'll be able to connect to the whole network.

I would quickly run a bootstrap node for you to help get you on the network but my IPs are all blocked already :S

Another thing you could try is if your uTox client can connect, you could run qTox at the same time, and as long as both have local peer discovery enabled (in qTox by checking "Enable LAN discovery"), then uTox should be able to share some nodes with qTox to let qTox get connected.

I'm not familiar with the situation wherever you are, but just note that your ISP and government will be able to see that you are using a proxy or VPN.

**Comment by houjaii** [comment]
> Yes those three options should work. A proxy can hide your Tox traffic and can be configured in the network settings of qTox, a VPN can hide your whole system traffic, and using a custom bootstrap will just let you find out about some other Tox nodes and as far as we know non-bootstrap Tox nodes aren't blocked, so then you'll be able to connect to the whole network.
> 
> I would quickly run a bootstrap node for you to help get you on the network but my IPs are all blocked already :S
> 
> Another thing you could try is if your uTox client can connect, you could run qTox at the same time, and as long as both have local peer discovery enabled (in qTox by checking "Enable LAN discovery"), then uTox should be able to share some nodes with qTox to let qTox get connected.
> 
> I'm not familiar with the situation wherever you are, but just note that your ISP and government will be able to see that you are using a proxy or VPN.

Yea, I understand that using a proxy or VPN  is kind of visible. 

As I turn on the "Enable LAN discovery", qTox get connected, thanks for your help, so appreciate!

BTW, when I first time use qTox and create a new profile it works pretty good, as I change location or say different internet environment it is unable to connect any more, is there any reason that lead to this situation? Cause the IP or bootstrap node is tracked during the first time using, and after that the connection cannot be established anymore?

**Comment by anthonybilinski** [comment]
Great to hear that you got connected :+1: 

The first time you start a qTox profile, it has only the list of bootstrap nodes to use, which is saved in the client. On all subsequent starts, it has both the bootstrap list and also saved nodes from the last time it connected. These saved nodes aren't bootstrap nodes, just random users, so if those users close or restart their clients, the nodes DHT key will change and possibly so will their IP or port, so then you won't be able to connect to that saved node.

So qTox should be able to connect to bootstrap nodes on any start, and also be able to connect to other nodes on later starts, especially if qTox was recently running so that the saved nodes are more current and more likely to still be online.

As you're saving other nodes, other Tox users could also be saving you as a node, so theoretically when you change internet locations that could invalidate those others users saved state for you, which could explain differences in collectability, i.e. if you had 0 saved valid nodes, but someone somewhere had you saved and connected to you, which allowed you to learn about other nodes through them.

Possibly there's also just differences in the filtering you're seeing based on where you connect from, and your bootstrap nodes work in some places but not others.

**Comment by houjaii** [comment]
> Great to hear that you got connected 👍
> 
> The first time you start a qTox profile, it has only the list of bootstrap nodes to use, which is saved in the client. On all subsequent starts, it has both the bootstrap list and also saved nodes from the last time it connected. These saved nodes aren't bootstrap nodes, just random users, so if those users close or restart their clients, the nodes DHT key will change and possibly so will their IP or port, so then you won't be able to connect to that saved node.
> 
> So qTox should be able to connect to bootstrap nodes on any start, and also be able to connect to other nodes on later starts, especially if qTox was recently running so that the saved nodes are more current and more likely to still be online.
> 
> As you're saving other nodes, other Tox users could also be saving you as a node, so theoretically when you change internet locations that could invalidate those others users saved state for you, which could explain differences in collectability, i.e. if you had 0 saved valid nodes, but someone somewhere had you saved and connected to you, which allowed you to learn about other nodes through them.
> 
> Possibly there's also just differences in the filtering you're seeing based on where you connect from, and your bootstrap nodes work in some places but not others.
Thanks for the explanation, and I learn that the connection between user and bootstrap nodes is pretty important in the DHT network.

So my situation right now is that since the IPs are blocked, I am not be able to connect to bootstrap nodes, and I either use utox or proxy/VPN settings to help me get connected until some new IPs come out with the available bootstrap nodes to connect right?

**Comment by anthonybilinski** [comment]
Right, the bootstrap nodes are blocked, but their role is just to help you discover other nodes. Once you know any other nodes, they will share with you more nodes they know, and you'll quickly be able to find any node that's online. So if all of your bootstrap nodes are blocked, but uTox with maybe a different or older list has one that still works, uTox can effectively act as a bootstrap for qTox for you, sharing some nodes which qTox can connect to, which then share more nodes directly with qTox.

Once you're connected, you should be able to restart qTox without a proxy/VPN or uTox running and still connect through saved non-bootstrap nodes, but more and more of these will become invalid the longer qTox is closed.

**Comment by houjaii** [comment]
Hey @anthonybilinski , I try to use uTox for helping qTox geti online, and it looks like successful, however, I think that doesn't connect me to the DHT network. My friend use that solution too, when he says he is online, he's not online in my list, and I am offline in his list. So, does that mean I should use proxy/VPN as a solution and also the only solution?

Also, is there a way to test I am on the DHT network or literally onine?

**Comment by anthonybilinski** [comment]
When qTox reports that you're "online" it's really just checking that you see a few different nodes. There isn't a way that it can tell if you're _really_ connected to all online Tox nodes, or only some subsection of nodes.

It's normal to show as online and then not see your friend come online for maybe 10s after that, since even after you've connected to some nodes in the DHT, you have to find your friend in the DHT.

If you and your friend are both seeing yourselves as online, but not seeing each as online, and it stays like that long-term, probably you are both connected to some subsection of the DHT that isn't overlapping.

Yes I think a proxy or VPN would help in that case, since this is probably still because of network filtering or interference.
