### ISSUE TITLE
Is v1.16.3 safe to use (Debian uses the older version and not sure where else to ask because IRC didn't work)?

### ISSUE THREAD

**Issue by danmanrana** [qTox/qTox#6248]
I know this post very obviously doesn't belong here, but I have no idea where else to get the info. Reddit's Qtox community's basically dead and I couldn't message the IRC server for some reason.

**Comment by powerjungle** [comment]
I've emailed the qTox Debian package maintainer, we'll see what's up if there's a reply.

**Comment by powerjungle** [comment]
The final response was:

> Well you should be familiar with Debian release lifecycle and choose
> appropriate release for you. In short, use sid/testing for newer
> softwares.
> As for bpo, I have no interest in that.

By "bpo" I think it's meant "backports": https://backports.debian.org/

I think you should stay with stable, but just compile qTox for yourself to use the newest versions.

**Comment by danmanrana** [comment]
Thanks, though he didn't say if the older version's been updated with whatever security patches the new one might have, but yea, I can just compile it.

**Comment by antony-jr** [comment]
@pgenderson Just use an AppImage.

**Comment by powerjungle** [comment]
>though he didn't say if the older version's been updated with whatever security patches the new one might have

I don't think they have to be honest, but I haven't checked.

**Comment by powerjungle** [comment]
@antony-jr but what if the user wants qTox installed and not just a portable image?

**Comment by antony-jr** [comment]
@powerjungle I'm just suggesting a temporary thing.

**Comment by anthonybilinski** [comment]
AFAIK as a maintainer of qTox, version v1.16.3 doesn't have known attacks or exploits, or known security vulnerabilities. Toxcore, the generally more vulnerable network library that implements Tox and is used in qTox also does not have known security issues that have been fixed since version 0.2.9 which I believe Debian is using. I wouldn't be overly concerned about using qTox v1.16.3 on Debian.

That said, there have been many bug fixes in both qTox and toxcore since those versions (and in other dependencies of toxcore and qTox), and it's theoretically possible that some of those could be exploited. On the other hand the versions having been out for years with no security issues identified improves confidence in them.

It's generally the responsibility of the package maintainers to balance stability vs bug fixes, and I wouldn't say that in general newer software is safer, even if it has more known fixes, it also probably has new unknown bugs. I think if you are missing features that have been added to qTox since v1.16.3, or are hitting specific bugs that have been fixed then compiling yourself, using flatpak, or using appimage are good options, but if not continuing to use your distros version is safe.
