### ISSUE TITLE
qTox doesn't show that 1.17.3 is available

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6263]
The version 1.17.2 still shows that it is current:
![image](https://user-images.githubusercontent.com/271906/100213049-01491800-2ec3-11eb-872f-fb5e9bcd9e3a.png)

OS: FreeBSD 12.2

**Comment by yurivict** [comment]
When restarted the same qTox version shows that there is an update.

It needs to update when it is clicked on, or when it is opened after a long enough time.

**Comment by anthonybilinski** [comment]
If the update checker is enabled in cmake, it checks for update both on start and once per day when open.

**Comment by yurivict** [comment]
Somehow it didn't check. qTox stayed up for many days. Now when I clicked on the "About" tab it didn't show that the update is available.

**Comment by anthonybilinski** [comment]
The release was less than 24 hours ago, likely it had just not checked yet.

**Comment by anthonybilinski** [comment]
To double check my hypothesis, I checked to where the version number was still v1.17.2, disabled the check on open here: https://github.com/qTox/qTox/blob/12fc33ee23d2d7b5ef0e552626c7f0e6bcac44c0/src/widget/widget.cpp#L289 and changed the update timer from 24h to 2 minutes here: https://github.com/qTox/qTox/blob/12fc33ee23d2d7b5ef0e552626c7f0e6bcac44c0/src/net/updatecheck.cpp#L105 and then recompiled and opened qTox. Initially the About page showed nothing (including no "up to date :heavy_check_mark:" message) in the corner, and after two minutes the "Update available" button appeared.

I think this gives good confidence that it's working as intended and that your qTox had just not checked yet since it was still waiting the 1 day between each check.
