### ISSUE TITLE
Sorting from By Name to Activity under profiles with "Circles" causes qTox to become Unresponsive/Freeze/Hang

### ISSUE THREAD

**Issue by zellchristensen** [qTox/qTox#6291]
##### Brief Description

OS: Windows 7
qTox version: v1.17.3
Commit hash: c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f 
toxcore:  0.2.12
Qt:  5.12.9
…

Reproducible:  Almost Always 

##### Steps to reproduce

1. Change the contacts sort from By Name to Activity

##### Observed Behavior

qTox CPU usage becomes higher (about 12%) than normal and the entire client becomes unresponsive.  Other instances are unaffected.

##### Expected Behavior

The list sorts normally and reasonably quickly.

##### Additional Info
This seems to only happen on profiles with a good number of contacts, chat history, or actual activity.  On profiles with only a few contacts and very little chat history or activity, the list is sorted quickly.  A similar effect also happens when searching chat history but it usually comes back to normal after a few minutes.

I'll update this with how long it takes to finish sorting, if it ever finishes.

**Comment by zellchristensen** [comment]
Just an update, had two separate instances (out of 5) that suffered from this, and force closed one, while leaving the other running to see if it would ever complete.  It's still going about 2 days later still using about 12% cpu.

**Comment by anthonybilinski** [comment]
Sounds odd. I can't repro myself with lots of chat history on my profile and lots of friends, but I only have a few online which is maybe related, or maybe something about friend names or circles could be related.

I'd guess it's a bug stuck in a loop or doing something stupid rather than just sorting insanely inefficiently. Whatever the cause, it would be somewhere in https://github.com/qTox/qTox/blob/177f37b0a9586b96c23f9808d064812b38c01781/src/widget/friendlistwidget.cpp#L160.

**Comment by zellchristensen** [comment]
I think I found the cause.  It seems to be related to having "Circles" in your list.  One account had a circle that was empty, and the other account has two circles with friends added to it.  Both were profiles that had the same freezing issue.  As soon as I deleted the empty circle on one profile, sorting worked almost instantly without locking up.
