### ISSUE TITLE
qtox groups are only audio with TRIfA

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6292]
##### Brief Description

OS: replicant 6.0.0.3 and archlinux
qTox version:  1.17.3-1
TRIfA version: 1.0.91
…

When I create groups with qtox they work nicely with qtox and utox: group chats have both audio and text.
When I use these groups created with qtox with TRIfA, they have only audio.
When I create a group with TRIfA, I can create text or audio group, not groups which have both functionnalities.

**Comment by anthonybilinski** [comment]
For some background:

The Tox protocol has two types of groups, "text only" groups and "audio and text" groups.

qTox and uTox both treat "audio and text" groups the same, as a full text group where by default you're not sending audio and dropping any audio you receive, and then having a button to "join the call" which then starts sending audio and playing audio you receive.

TRIfA treats an audio group as an audio only group with push-to-talk. I've talked to the maintainer of TRIfA and he believes qTox should add the option to create text only groups to work with TRIfA, like uTox has the option for, but qTox only has the option to create audio and text groups now. I think generally having groups where you can do either and default to only text is more versatile and easy to use than having groups that only do one or the other, so I don't really see the value in complicating qTox's group creation, and to me this seem like an UI limitation in TRIfA, but we didn't come to an agreement.

Note that qTox does support joining both kinds of groups, so will work properly when invited to either kind.

It looks like TRIfA can create both "text only" and "audio and text" groups in the UI, but , but when trying that myself it's not joining the group itself or sending the invite :confused:.

So it sounds like your issue of "qTox groups are only audio with TRIfA" should really be "Tox audio groups are audio only with TRIfA", since this would happen with any audio Tox group, whether it's created by uTox or qTox.

The only part of this that's within qTox's control is the ability to create text-only groups, but that still wouldn't solve your issue of "not groups which have both functionalities". For that TRIfA would need to change their UI.
