### ISSUE TITLE
Arch package doesn't have notifications

### ISSUE THREAD

**Issue by asakura42** [qTox/qTox#6298]
##### Brief Description

OS: Arch Linux
qTox version: 1.17.3  
Commit hash:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d  
toxcore:  0.2.12  
Qt: 5.15.2  
…

Reproducible: Always

##### Steps to reproduce

1. Open qTox
2. Close to tray
3. Wait for message
4. No notification!

##### Additional Info

----

Found nothing related in logs, only connection info.

But Arch package depends only on: `desktop-file-utils  libxss  openal  ffmpeg  qrencode  qt5-svg  sqlcipher  libexif  toxcore  sonnet  libgl` maybe it's package issue?

**Comment by asakura42** [comment]
Also my Windows 10 friend says that he doesn't have any toast notifications too. What can we do?

**Comment by anthonybilinski** [comment]
Your commit 8eed684c37bd711de2ca4bd863f5f0509edcdc2d is v1.16.3, so not sure why you're seeing v1.17.3? Notifications using libsnore was added in 66e2c01029efad7f6195cebcf96175152ce2ce22 which should be present in v1.17.0 on-wards. It looks like your qTox is out of date.

The build option `DESKTOP_NOTIFICATIONS` also defaults to off, so that needs to be set on during the cmake step.

For Windows, it was added in 7409e6b4cc584f1d1737e180b4066be371303801 which is after the v1.17.0 release, so isn't present in any of v1.17.x. By the time v1.18.0 hits it may be removed and replaced due to https://github.com/qTox/qTox/issues/6238, so your friend unfortunately just has to wait.

**Comment by asakura42** [comment]
>Your commit 8eed684 is v1.16.3, so not sure why you're seeing v1.17.3?

Yep. Dunno too. But it is. https://files.catbox.moe/kwtic4.png

**Comment by anthonybilinski** [comment]
Looks like a bug in https://github.com/archlinux/svntogit-community/blob/packages/qtox/trunk/PKGBUILD. Their last few version updates updated `pkgver` which is used for the version in qTox through `DGIT_DESCRIBE`, but `_gitver` is unchanged from the v1.16.3 commit.

Once that is fixed they're still need to add the `-DDESKTOP_NOTIFICATIONS=ON` option, and include libsnore as a dependency.

**Comment by asakura42** [comment]
Interestingly how in the process of finding one bug, we found a whole package mismatch. I have already written to the maintainer, but in the meantime I will try to build it myself. If the notifications will work, I will close the issue.

**Comment by asakura42** [comment]
Yep! Thanks, with `-DDESKTOP_NOTIFICATIONS=ON` all works, thank you @anthonybilinski. And if you don't mind explain in a nutshell please, does the `DGIT_VERSION` parameter affect anything or is it just a commit hash that appears in `About` and has no practical value?

**Comment by anthonybilinski** [comment]
Great to hear that it works for you now. `GIT_VERSION` is what's displayed in the log and the UI for the git commit, but otherwise has no effect on qTox.

**Comment by farseerfc** [comment]
Sorry for the mismatched `GIT_VERSION` , I will build a new package w/ `-DDESKTOP_NOTIFICATIONS=ON` for Arch Linux soon
