### ISSUE TITLE
A thought on trust and built-in proxification

### ISSUE THREAD

**Issue by asakura42** [qTox/qTox#6299]
Sometimes we trust people. Sometimes we don't. Tox is designed to communicate with those to whom we trust one of our most valuable resource -- our IP address. Especially if it's static. Yes, despite the fact that qTox allows you to connect proxy e.g. through Tor, the average user won't do it. Moreover, "average users" often think that Tor is just a "browser for buying drugs".

Along with this, there is such a thing as "trust in the server". Or the lack of it. My idea is that you can trust either the server or the contact, but not both.

I perfectly understand that Tox is designed as a P2P messenger, but imagine if a user could send messages through some relay? Once he realized he was talking to someone he could trust, the user could switch the dialogue to P2P mode and continue communicating.

Recently @zoff99 showed his work, https://github.com/zoff99/ToxProxy and theoretically this code could have many uses. So let's discuss the theoretical possibility of built-in proxification for communicating with untrusted contacts.

It may also help to slightly smooth out security problems: https://github.com/TokTok/c-toxcore/issues/426. Too bad it can't solve it completely. But at least the Contact will have a chance to make sure that he is not talking to an Unknown, but to Someone he knows before showing his IP address.

**Comment by anthonybilinski** [comment]
Tox supports proxying messages through volunteer "TCP relays", most of which are listed here: https://nodes.tox.chat/. You can enable this in qTox by going to settings -> advanced and unchecking "Enabled UDP", then restarting qTox. This applies to your entire Tox connection though, so there isn't any way to toggle it on or off for specific friends.

Your IP is also hidden from users that send you a friend request until you've accepted it, so hopefully that gives some way to screen new contacts before revealing your IP address to them.

I don't think qTox should move to proxying connections by default, because like you said it requires trust in the server rather than the peer, and someone malicious could more easily run multiple TCP relays and collect metadata that way including both your and your friends IP address, without giving you the opportunity to vet them as trustworthy, unlike a friend invite that you accept. 

With proxying there's also either added administration overhead or cost. If you have many volunteers proxies then you to avoid mass metadata collection you'd need to vet them as different people and somewhat trustworthy like Tor already does which requires extensive administration, or you'd need a trusted central organization to pay for servers and to generate profit off the users somehow, and both the idea of a central organization and generating profit off users aren't something Tox can or wants to do.

If you want to run your own private TCP relay or use a trusted friends', you could do that now with qTox (added since last release, available either on tip or whenever v1.18.0 releases) by editing your bootstrap node list `~/.config/tox/bootstrapNodes.json` and including only your own node.

**Comment by zoff99** [comment]
@asakura42 ToxProxy is not a proxy. the name was maybe chosen poorly. it is used for offline messages (for 1-on-1 chats and group chats) and (almost ready) multidevice support.

if you are online messages are transmitted the usual way.

**Comment by asakura42** [comment]
@anthonybilinski Oh, thank you about this explanation. I didn't know I could already hide my IP. Honestly, I'm even ashamed that I didn't know this before, even though I've been looking at Tox for a few years now.
