### ISSUE TITLE
How to build the source code with Qt

### ISSUE THREAD

**Issue by DavidMax2006** [qTox/qTox#6316]
Sorry to interrupt you all.

First of all, I appreciate for open-sourcing of this powerful, fantastic project.

But what should I do to build and run it with Qt? 

Thank you all.

**Comment by DavidMax2006** [comment]
`Qt5` would be okay.

**Comment by anthonybilinski** [comment]
Check out https://github.com/qTox/qTox/blob/master/INSTALL.md for instructions for building on a variety of Linux distros and macOS. For building Windows executables, they need to be built from docker since we don't support msvc. See https://github.com/qTox/qTox/blob/master/windows/cross-compile/README.md for instructions on doing that.

Any build of qTox depends on Qt5, that should be installable from your OS's repos like mentioned in INSTALL.md, but can also be build from source from https://wiki.qt.io/Building_Qt_5_from_Git#Getting_the_source_code, as is done for our Windows builds.
