### ISSUE TITLE
AppImage missing GnuTLS 3.6.9

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#6339]
##### Brief Description

OS: AlmaLinux 8 (binary compatible with CentOS and RHEL)  
qTox version: 1.17.3  
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always (or Almost Always as, apparently, it worked for a while, but now it always exits with error)

##### Steps to reproduce

1. Try to run the AppImage (either double-click or terminal command)

##### Observed Behavior
When run either from double-click on file or from terminal, exits (before even opening the window) with error: "./qTox-v1.17.3.x86_64.AppImage: /tmp/.mount_qTox-vXNzspj/local/bin/../lib/libgnutls.so.30: version `GNUTLS_3_6_9' not found (required by /lib64/libglib-2.0.so.0)"
I have GnuTLS 3.6.14 installed (as well as the development packages for it), but AppImages are supposed to use embedded/static libraries for that, right?

##### Expected Behavior
Open the window.

##### Additional Info
![image](https://user-images.githubusercontent.com/82186931/120480804-cfd76a80-c385-11eb-8eb5-60e53d100fcb.png)
![image](https://user-images.githubusercontent.com/82186931/120480869-e54c9480-c385-11eb-8408-ca22aea373c5.png)

----
Logs (not really sure if those are helpful in this case, since linking problems usually lead to not entering/running the main function at all):
[qtox.txt](https://github.com/qTox/qTox/files/6584641/qtox.txt)
The logs probably contain messages from previous versions that ran successfully, or even from the flatpak version.

**Comment by anthonybilinski** [comment]
Verified on CentOS and Alma. The issue is that our AppImage isn't bundling every library it needs, just some of the libraries it needs, which works on some distros that happen to have the other libraries available system wide, but not on these distros.

What we should be doing is including every shared library that may be needed on any version of any distro that we want to support. Probably more practically, we should just include every shared library besides libc and linux-vdso.

That's easy enough to do by just running `ldd qtox` in the build environment and including all of those files, but we use `linuxdeployqt` which copies in some but not all libs. I'm trying to see if we are using it wrong or if we're just using the wrong tool and should handle including the libs ourselves manually.

**Comment by anthonybilinski** [comment]
Ah, misdiagnosed issue. Indeed `linuxdeployqt` doesn't bundle quite a few of the libs, but it carefully is omitting ones that truly aren't needed, and that isn't our issue here. Our issue is that our gnutls is too old for their system libglib. We're intentionally using an old build system, as recommended for appimage, for max compatibility, so our only option here is to manually add an old libglib too.

Doing that, the appimage then fails to start for a new reason, `error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory` which is a bit weird because it is bundled and ldd shows it twice and found one of the two times..
```
	libpcre.so.3 => not found
	libpcre.so.3 => /tmp/.mount_qTox-aSS7kEZ/local/bin/./../lib/libpcre.so.3 (0x00007f5ddc2c1000)
```

I'll look into this next.

**Comment by anthonybilinski** [comment]
So from the top,
* AppImage is missing GnuTLS on red hat based systemsm but is fine on all other distros
* real reason is that although we have GnuTLS bundled, it's too old for their system libglib
* packaging our old libglib should/does? fix this
* after that change, appImage fails to run on all non-debian-based systems with missing `libpcre.so.3`
* `linuxdeployqt` is correctly copying in `libpcre.so.3`, and correctly setting the rpath of qtox and copied libs to the local libs dir, according to verbose logs:
    ```
    Log: Checking rpath in "/build/appdir/usr/local/bin/qtox"
    Log: Changing rpath in "/build/appdir/usr/local/bin/qtox" to "$ORIGIN/../lib"
    ...
    Log:  copied: "/lib/x86_64-linux-gnu/libpcre.so.3"
    Log:  to "/build/appdir/usr/local/lib///libpcre.so.3"
    Log:  copied: "/usr/share/doc/libpcre32-3/copyright"
    Log:  to "/build/appdir/usr/local/share/doc/libpcre32-3/copyright"
    Log: Checking rpath in "/build/appdir/usr/local/lib/libpcre.so.3"
    Log: Changing rpath in "/build/appdir/usr/local/lib/libpcre.so.3" to "$ORIGIN"
    ```
* but, in the build container, running `ldd -v` on `/build/appdir/usr/local/bin/qtox` shows it finding the wrong `libpcre.so.3`:
    ```
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3
    ```
    * most other libs are resolving to the local library directory
    * why would this be resolving to the system library if the library is copied in to the local libs dir, and qtox's rpath is set there?
* with the built appimage, mounting it from arch or centos and checking `ldd` inside the mount on qtox there:
    * libpcre.so.3 shows up twice in the ldd output, not sure why
    * It's not found once, this would be expected since arch doesn't have any file called "libpcre.so.3" in its repos
    * but it's also found once at the correct bundled location. Still this stops the appimage from running.
    ```
    libpcre.so.3 => not found
	libpcre.so.3 => /tmp/.mount_qTox-aSS7kEZ/local/bin/./../lib/libpcre.so.3 (0x00007f5ddc2c1000)
    ```
    * On debian which has that lib present system wide, it shows up once in the output and resolves to the system lib:
    ```
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f3303c4f000)
    ```
* running LD_DEBUG=libs ldd -v qtox in the mounted dir shows it searching twice:
    * System wide, which will fail:
    ```
        1205160:     find library=libpcre.so.3 [0]; searching
        1205160:      search cache=/etc/ld.so.cache
        1205160:      search path=/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/x86_64/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/x86_64/x86_64:/usr/lib/x86_64:/usr/lib/x86_64:/usr/lib          (system search path)
        1205160:       trying file=/usr/lib/glibc-hwcaps/x86-64-v2/libpcre.so.3
        1205160:       trying file=/usr/lib/tls/x86_64/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/tls/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/tls/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/tls/libpcre.so.3
        1205160:       trying file=/usr/lib/x86_64/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/x86_64/libpcre.so.3
        1205160:       trying file=/usr/lib/libpcre.so.3
        1205160:
        1205160:     find library=libgomp.so.1 [0]; searching
        1205160:      search path=/tmp/.mount_qTox-cz4Jm3M/local/bin/./../lib                (RUNPATH from file ./qtox)
        1205160:       trying file=/tmp/.mount_qTox-cz4Jm3M/local/bin/./../lib/libgomp.so.1
    ```
    * Then again following the rpath:
    ```
    1205160:     find library=libpcre.so.3 [0]; searching
    1205160:      search path=/tmp/.mount_qTox-cz4Jm3M/local/bin/./../lib                (RUNPATH from file ./qtox)
    1205160:       trying file=/tmp/.mount_qTox-cz4Jm3M/local/bin/./../lib/libpcre.so.3
    ```
* So it seems like the problem lies with ld checking the system path at all, instead of just checking the rpath, but I don't see anything wrong with the lib being bundled or rpath being set.

**Comment by sphaerophoria** [comment]
Initially I was kind of hesitant to add glib2 to our base image to avoid this. In my mind glib is a pretty low level library and we depend on system libraries that depend on it. We work under the assumption that system libs should be newer than our appimage libs. If we add glib to our appimage we could break system libs that depend on it if they depend on features introduced in a newer glib minor version.

I ended up checking what system libs depend on it though, and I think it's just harfbuzz. I think there's a good chance we could just bundle glib and harfbuzz and things would work if we could figure out what's going on in the above (will take a look at that in a bit).

Due to the initial hesitancy I looked into exactly why this is happening. From my understanding the sequence is...

* FFMPEG links to gnutls so it can stream https videos
* linuxdeployqt sees that we need to bundle gnutls
* linuxdeployqt decides we don't need glib, I assume for a good reason but I haven't looked into that yet
    * Usually this should work just fine! Glib is a pretty low level library and I don't think it's that unreasonable to expect people to have it
* centos patches glib to use gnutls for compliance with us government regulations (see patch in https://vault.centos.org/8.1.1911/BaseOS/Source/SPackages/glib2-2.56.4-7.el8.src.rpm)
* Now all of a sudden we have an old gnutls from ubuntu 16.04 but centos depends on a newer one. Oh no!

So I think our options are to continue down the path @anthonybilinski  was on or to compile ffmpeg ourselves without tls support to dodge this

**Comment by anthonybilinski** [comment]
So for my problem, the issue was that although rpath was being set for all libraries copying by linuxdeployqt, libs we copied manually in addition didn't have rpath set, so couldn't find their own deps in the local bundle. pcre was already copied in by linuxdeployqt, but glib couldn't find it because glib didn't have its rpath set. Thanks @sphaerophoria for pointing that out, they're now all being patched to have an rpath that points to the local lib dir.

I generally agree with the idea that we should want to avoid providing libs that the system we're running on has libs that we use that depend on the libs we provided. Adding harfbuzz breaks the appimage on arch (and maybe other distros) though, due to a the system freetype being too new for harfbuzz - I think.

We have a few other libs that are in the same case as glib now (being bundled, but being used by system libs that we're using), which are libXdmcp, libICE, and freetype. I think trying to chase down the chain of dependencies will lead to us packaging a whole lot of stuff, and I think this is more of linuxdeployqt's job in the first place to make the call on where a reasonable cut off is. Based on that, I'd lean to just providing glib and allowing the system harfbuzz to depend on our bundled glib, even though that's not ideal.

RE: compiling ffmpeg from source and removing its tls dep, I think it would be cleaner for this one case, but only because we happen to have a dep that we can remove deps from easily in the case of gnutls. We'd still have other distro libs depending on our bundled libs even in that case, so it doesn't seem like it really puts us in a much better spot.

Bundling just _everything_ is an option too, and that would be guaranteed safe at the price of a bigger binary, but again I feel like linuxdeployqt are the experts in that domain, and given that they don't even offer an option to do that, I feel like we probably shouldn't.

PR's opened to just add glib: https://github.com/qTox/qTox/pull/6407
