### ISSUE TITLE
Caching DHT nodes

### ISSUE THREAD

**Issue by xuefer** [qTox/qTox#6343]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  
qTox version: (version numbers in menu `Settings → About`)  
Commit hash:  8c34fa8f7d34e6555533f392925164b47da12d8c
toxcore:  0.2.12
Qt:  5.12.10
…

Reproducible: Always

##### Steps to reproduce

1. simply restart qTox

##### Observed Behavior
Connecting to bootstrap node 16 (something)

##### Expected Behavior
Connecting to bootstrap cached node

##### Additional Info

as stated in https://wiki.tox.chat/users/nodes, the client should cache nodes
most torrent clients that support DHT cache not only the bootstrap nodes but also peer nodes so it can bootstrap from the cache instead of just the ones from official list

----

[qtox.zip](https://github.com/qTox/qTox/files/6598226/qtox.zip)

**Comment by anthonybilinski** [comment]
qTox does cache peer DHT nodes and use those on next start as well. Toxcore saves recent nodes in the \.tox savefile, which are automatically contacted to when started, which is why you don't see any qTox logs about them. qTox still adds the static bootstrap nodes to the list, since we don't know if the saved peer nodes are old or unavailable, and instead of waiting a minute to see if we come online without bootstrap nodes then only bootstrapping in that case, we just bootstrap right away in parallel. I just tested this by returning early here: https://github.com/qTox/qTox/blob/8c34fa8f7d34e6555533f392925164b47da12d8c/src/core/core.cpp#L814 and my client was still online and connected to friends after a few seconds.

Regarding the wiki saying:
> we strongly advise you to cache the list of nodes your application downloads on user side, in order to reduce the number of requests our servers are getting.

I think it's talking about the bootstrap node list, which is cached inside the qTox binary, rather than being fetched from https://nodes.tox.chat on each start. But you're still right that caching peer nodes is a good thing to do.

**Comment by xuefer** [comment]
Thanks for the answer. Good to know it cache. I'm having hard time connecting but that may be because lacking of users arround here instead of without caching

**Comment by anthonybilinski** [comment]
If you're having problems connecting from China, Tox bootstrap nodes seem to be blocked in general in China, see [Avoiding Censorship](https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#avoiding-censorship) in our user manual regarding that.
