### ISSUE TITLE
qtox threat ip 5.196.247.6 connection attempt

### ISSUE THREAD

**Issue by ceroblabla** [qTox/qTox#6351]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)  Windows
qTox version: (version numbers in menu `Settings → About`)  Last
Commit hash:  
toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce Almost always

##### Steps to reproduce

1. just run the app
2. 
3. …

##### Observed Behavior

firewaal blocked ip 5.196.247.6 connection attempt from qtox.exe

##### Expected Behavior

this ip is reported as threat

##### Additional Info
(links, images, etc go here)

----

E.g., include log located in `~/.cache/Tox/qTox/` / `%APPDATA%\tox\`.
To include it, rename it from `.log` to `.txt`, or zip it.

Tip: use `v4l-info` and `v4l2-ctl --all` to get webcam info on Linux.

More information on how to write good bug reports in the wiki:
https://github.com/qTox/qTox/wiki/Writing-Useful-Bug-Reports.

Please remove any unnecessary template section before submitting.

**Comment by anthonybilinski** [comment]
Tox in general is peer-to-peer, so when you use it your client contacts other Tox users. It does this to create a DHT, similar to other peer-to-peer systems like bittorrent, and it uses this DHT to search for your friends, which it then directly connects with.

Any IP could be part of this DHT, but the only thing Tox is doing is asking for other public nodes, or providing public nodes to that IP, which your antivirus doesn't understand and assumes that a malicious server is at that IP that Tox is communicating with.

Ultimately there's nothing that we can do about this. The individual node being blocked shouldn't cause any problems for qTox, since it can just talk to other nodes in the DHT instead to find your friends.

**Comment by ceroblabla** [comment]
ok, thanks for the info. As I want to use it as a lan messenger I will then block outbound traffic from qtox.
Regards

**Comment by anthonybilinski** [comment]
That should work as long as you're on the same subnet since Toxcore uses broadcast messages for LAN discovery. If your peers aren't reachable by broadcast, you could add custom bootstrap nodes on your LAN https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md#bootstrap-nodes (though this requires running a nightly build, since it was added since the last release).
