### ISSUE TITLE
Update ffmpeg and possibly other dependencies in our CI

### ISSUE THREAD

**Issue by sudden6** [qTox/qTox#6352]
FFmpeg is at 2.8.5 while http://www.ffmpeg.org/olddownload.html shows 2.8.11

**Comment by anthonybilinski** [comment]
Our Windows dep is at 4.3.2 which is good since users actually use that one, but yeah we're building from source for our ubuntu build here https://github.com/qTox/qTox/blob/8af9d0905f1dede01974dbce28c34f748221c971/.travis/build-ubuntu-16-04.sh#L59 and it hasn't been updated in ages.

Might as well keep it in sync with the Windows version, but we should also re-evaluate if we even need to be building it from source as part of CI

Looks like it was added 6 years ago as "use newer ffmpeg version to compile against - 2.8.5".. so if our goal is "newer" we might as well just use the OS's version in CI.

**Comment by anthonybilinski** [comment]
This was resolved by https://github.com/qTox/qTox/pull/6413. All manual downloads of ffmpeg use the version from https://github.com/qTox/qTox/blob/master/buildscripts/download/download_ffmpeg.sh, and our ubuntu build just uses the one from repos instead of the ancient version from source like before.
