### ISSUE TITLE
Group Chat aTox & qTox

### ISSUE THREAD

**Issue by fajarmotor** [qTox/qTox#6356]
##### Brief Description

OS: Windows 10 (10.0)
qTox version: v1.17.3
Commit hash: c0e9a3b79609681e5b9f6bbf8f9a36cb1993dc5f
toxcore: 0.2.12
Qt: 5.12.9
Hardware: 
…

Cannot add group between from qTox to aTox

**Comment by anthonybilinski** [comment]
I don't think aTox has implemented groups yet. qTox groups are generic Tox groups, so when aTox does add group support they should work together no problem, but for now there's nothing qTox can do.

**Comment by fajarmotor** [comment]
Yeah

**Comment by fajarmotor** [comment]
Communication between single account both aTox and qTox can be done. Unfortunately, this is the only app that can detect LAN, WLan, and Android

**Comment by anthonybilinski** [comment]
aTox is being actively worked on, so hopefully groups will be added there soon. I'll close the issue here since there's nothing that qTox can do here, but you can open an issue at https://github.com/evilcorpltd/aTox if you want, although I'm sure their devs are already aware that they should implement groups
