### ISSUE TITLE
qtox.dmg fails to install on OSX-10.11.6

### ISSUE THREAD

**Issue by davidfavor** [qTox/qTox#6365]
##### Brief Description

OS: Windows / OS X / Linux (include version and/or distro)

imac> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G22010

qTox version: (version numbers in menu `Settings → About`)  
Commit hash:

https://github.com/qTox/qTox/releases/download/v1.17.3/qTox.dmg is link.

Since qTox never installs, I guess the answer is v1.17.3 for version involved.

toxcore:  
Qt:  
…

Reproducible: Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce

##### Steps to reproduce

1. Download https://github.com/qTox/qTox/releases/download/v1.17.3/qTox.dmg
2. Double click qTox.dmg
3. Message: qTox.dmg - no mountable file systems

Request a work around.

**Comment by anthonybilinski** [comment]
Support for macOS up to 10.13 was removed in qTox 1.17.3 while adding support for macOS 10.16/11.0, since AFIK anything older than macOS 10.14 is EOL by Apple and not receiving security updates.

There's a good chance that we're not handling backwards compatibility properly, and maybe be able to support both 10.16 and 10.13 simultaneously, or worst case we could make two release binaries.

The change was done in commit a93c5994971a9a0dfe28fc1e916f13e7e0a1280 right before 1.17.3, so using 1.17.2 should still work.

There's an issue open already to improve or at least figure out our macOS backwards compatibility limitations #6260 so there may be improvements after then, but also possibly not. Until that's figured out, going with qTox 1.17.2 is probably your best bet if you're not able to update your OS.

**Comment by davidfavor** [comment]
Thanks for the update.

I'll be upgrading my OS shortly + will retest.
