### ISSUE TITLE
Doc Error

### ISSUE THREAD

**Issue by tsingi** [qTox/qTox#6393]
##### Brief Description

Section 1.1 / Pg  4  says not for Android then lists two Android apps.

For Windows, Linux, OS X, FreeBSD.
**Not for iOS, Android etc..**
Nowadays, every government seems to be interested in what we're saying online. qTox is built on a "privacy goes first"
agenda, and we make no compromises. Your safety is our top priority, and there isn't anything in the world that will
change that.
Tox - P2P protocol with user-id from Distributed Hash Table (DHT).
Clients for Tox e.g.
qTox (continued in development).
**App Antox for Android.
TRIfA Tox Client for Android.**
Antidote for iPhon.

**Comment by Chiitoo** [comment]
Where is this text from?

I can find some references to a pdf on third-party sites, but I can't find all of this in the current qTox/Tox sites or GitHub repositories.

Further, the parts which include the Android clients read to me like they're talking about clients that use the Tox protocol in general, not what platforms qTox is built for.

**Comment by anthonybilinski** [comment]
I also don't see the issue here, qTox is for Linux, FreeBSD, macOS, Windows as mentioned on our site https://qtox.github.io, but e.g. https://tox.chat covers more clients than just qTox, and some of those other clients support additional platforms.

Doing some searching for the exact phrasing, it looks like you saw this info here: http://www.at-wi.de/down/qTox_User_Manual.pdf. This site is unaffiliated with qTox, so we aren't able to make any corrections or clarifications there.
