### ISSUE TITLE
History is gone after update from v1.17.3-399-gda5c165f to 1.17.4

### ISSUE THREAD

**Issue by yurivict** [qTox/qTox#6425]
I was using the intermediate revision v1.17.3-399-gda5c165f for a while. Now I tried to update to 1.17.4 and the history is gone.

The executable from v1.17.3-399-gda5c165f still shows history.

Why doesn't 1.17.4 show the history that v1.17.3-399-gda5c165f was showing?

**Comment by anthonybilinski** [comment]
v1.17.3-399-gda5c165f is on master branch, whereas v1.17.4 is based directly on v1.17.3 on the v1.17-dev branch. On master since v1.17.0 there have been database schema updates which v1.17.4 has no support for, since the patch releases are all based on the last minor release.

Since your database has been upgraded to version 7: https://github.com/qTox/qTox/blob/da5c165f4116dce736def63b1b917523b848db09/src/persistence/history.cpp#L30 from v1.17.3-399-gda5c165f, only commits at or above 7 will support opening history. Current master is now at version 8, so upgrading to i.e. v1.17.4-gcea54c17 would work, but v1.17.4 would not.

**Comment by yurivict** [comment]
Thanks for the explanation.
