### ISSUE TITLE
Chat History Database No Longer Loads.

### ISSUE THREAD

**Issue by ECToo** [qTox/qTox#6431]
I updated to version 1.17.4 of qTox for Windows 64-bit from the releases page, and the chat history is no longer displayed in the message window nor will it load from the "load chat history" menu .  The <username>.db file which contains the chat history is still present in the directory with the INI files, but it has not been changed since I updated to v1.17.4 from the May 4, 2021 development release of qTox (qTox version v1.17.3-66-g8c34fa8).

Reverting just the qtox.exe executable from qTox version v1.17.3-66-g8c34fa8 fixes the problem, but that is obviously not a proper fix for this issue.

**Comment by anthonybilinski** [comment]
You're seeing the same issue as https://github.com/qTox/qTox/issues/6425.

v1.17.3-66-g8c34fa8 is on master branch, whereas v1.17.4 is based right off v1.17.3. Master branch has some database updates that v1.17.x don't know about, which is why history isn't being loaded.

You could grab the latest artifact from CI built off master branch here https://github.com/qTox/qTox/actions/runs/1643694055#artifacts that's post-v1.17.4, that will have both the toxcore update and understand your newer history format than what v1.17.3 or v1.17.4 are aware of.

**Comment by ECToo** [comment]
> You're seeing the same issue as #6425.
Thanks for the reply.  Before I posted I didn't notice that Github had filtered out the closed issues so I did not see that one.
