### ISSUE TITLE
Crashing after updating to latest master build when loading existing profile

### ISSUE THREAD

**Issue by hart0** [qTox/qTox#6485]
##### Brief Description

OS: Fedora 35
qTox version: Latest (as of this post)
Commit hash: I think it's 56eed63fdebd09f832a5eefd397f07fa26c1d71f  
toxcore:  [v0.2.15]
Qt:  

Reproducible: Always

##### Steps to reproduce

1. Have a profile on an older version, in my case an older nightly
2. Compile the current master
3. When trying to load the profile, nothing happens; when doing so after launching via terminal, it shows the error below

##### Additional Info

qtox: /tmp/qTox/qTox/src/core/toxpk.cpp:88: ToxPk::ToxPk(const QString&)::<lambda()>: Assertion `!"ToxPk constructed with invalid length string"' failed.
Aborted (core dumped)

I can create a new profile and signing in to that doesn't cause any crashes, only profiles I had prior to this update.

I tried to compile with the "fix(core): Fix missed ToxId to ToxPk constructions" patch since it seemed like it could be related but that didn't seem to help.

**Comment by anthonybilinski** [comment]
Thanks for the report. This should be fixed by https://github.com/qTox/qTox/pull/6474, you could try running that and see if it resolves it. Note that the linked PR makes non-backwards-compatible changes to your history database, so you may want to copy `~/.config/tox/<profile>.db` elsewhere during update in case it doesn't resolve your problem, which will let you replace it and run on an older version again.

**Comment by hart0** [comment]
> Thanks for the report. This should be fixed by #6474, you could try running that and see if it resolves it. Note that the linked PR makes non-backwards-compatible changes to your history database, so you may want to copy `~/.config/tox/<profile>.db` elsewhere during update in case it doesn't resolve your problem, which will let you replace it and run on an older version again.

Thanks, that appears to fix the crash
