### ISSUE TITLE
qTox 1.17.6 no longer runs on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by CommieChan** [qTox/qTox#6594]
##### Brief Description

OS: MacOS Mojave 10.14.6
qTox version: 1.17.6

…

Reproducible: Always 
##### Steps to reproduce

Click to start the application 

##### Observed Behavior
Diallog box:

You can’t use this version of the application “qTox” with this version of macOS.
You have macOS 10.14.6. The application requires macOS 10.15 or later.

##### Expected Behavior

Normal execution

##### Additional Info
<img width="410" alt="image" src="https://user-images.githubusercontent.com/11252889/160243042-9c4efc2f-d6ef-4b05-ad6e-502e17cbc2c9.png">

Release 1.17.4 is the last known version to work with MacOS 10.14.6.

**Comment by anthonybilinski** [comment]
We unfortunately had to remove support for macOS 10.14 prior to v1.17.6 in commit c282c6e96f06206a8806265bcd12cbaccc87ba0b.

Because macOS 10.14 is not supported my Apple anymore, homebrew also does not support it, and we require homebrew packages to make our macOS release.

qTox should work on macOS 10.15 or newer, so if an option, upgrade your OS.

For specifically v1.17.4 to v1.17.6 - there's no real change to the macOS version, so you can continue to use v1.17.4. But going forward with e.g. v1.18.0, there will be lots of missing updates.

**Comment by CommieChan** [comment]
Oh that's too bad.  I'll stick with version 1.17.4 for the Mojave machines. 
At least the base features still continue to work. eg; text, voice, file xfer. 
Thank you for following up with this.
