### ISSUE TITLE
Add GUI option to change chat font size

### ISSUE THREAD

**Issue by DanTheBritish** [qTox/qTox#672]

**Comment by suhr** [comment]
And also option to just change font.

**Comment by darkman088** [comment]
+1 voice on that from me !! uTox already has the DPI function, but with the font itself it will be perfect!!

**Comment by TheLastProject** [comment]
What about replacing "Emoticon size" with "font size"? I can't think of people making only emoticons smaller/larger, but I know people who want to increase the font-size, and it'd be logical if emoticons scale up with the font.

**Comment by darkman088** [comment]
I fully agree with you!

**Comment by ghost** [comment]
As someone who is vision impaired, this would be great. Even being able to increase fonts just 25% would help so much, thanks!

**Comment by morpheusbeing** [comment]
I am not visually challenged, but the font display in mine is about 30mm (1.25") high
Far too big and takes up lots of screen realestate and makes reading difficult

**Comment by morpheusbeing** [comment]
For the developers information, I am running Debian XFCE4 latest version.

**Comment by morpheusbeing** [comment]
By the way, I solved my problem of excessively large text by settings->appearance->fonts and changing from newspaper 20 to liberation sans 10. going to increase to 12 as it is a bit small

**Comment by jamesrobb** [comment]
This is an issue for me as well. It seems like a rather basic thing to fix. It would make the user experience that much more rich.

Is there any time line or owner on this issue?

**Comment by agilob** [comment]
Duplicate https://github.com/tux3/qTox/issues/1166#issuecomment-121093788 (read discussion)

**Comment by TheSpiritXIII** [comment]
Improved high DPI support in Qt is [not coming until Qt 5.6 unfortunately](http://lists.qt-project.org/pipermail/development/2015-June/021631.html) which is currently scheduled for a December release.

@agilob I'm not sure if CSS is a good way to go. It seems annoying to have to find and modify a file in order to change the font size.

The issue is that most GUI elements in qTox have a fixed size in pixels, so this wouldn't play nicely. For instance, the friend widget was hardcoded in style and size due to a bug. In my chatform branch, I added the ability to adjust the columns in chat forms but due to the aforementioned issue, changing the font size is still not completely possible.

**Comment by darkman088** [comment]
uTox has 3 settings to scale up (down) everything - I think 100%, 125% and 150%. This is perfectly enough, so why don't you take the same approach ? Thanks for considering this ;-)

**Comment by stal888** [comment]
+1

**Comment by ProMcTagonist** [comment]
> @TheLastProject What about replacing "Emoticon size" with "font size"? I can't think of people making only emoticons smaller/larger, but I know people who want to increase the font-size, and it'd be logical if emoticons scale up with the font.

+1

**Comment by mqds** [comment]
+1

**Comment by darkman088** [comment]
Pluses are welcome, but we already went past December +2 months. Did the desired Qt version come out as expected ? Could somebody be so kind and update us on the status of this ? Thanks!

**Comment by DanTheBritish** [comment]
QT 5.6 did indeed come out.

**Comment by darkman088** [comment]
Then I really hope that we can see the desired functionality in the foreseeable future :-)
Thanks a million!

**Comment by photonometric** [comment]
Excellent! Sounds like this is much-wanted. I barely need new glasses and have been accused of drunkenness because of the just-slightly-smallness. x3

If this might be a while, it would be awesome to have just a few of the key CSS text modifiers that @agilob et al found in #1882. That process would be an ordeal to find even if I was great at CSS these days ^^;;;

Thanks!

**Comment by Fohroer** [comment]
+1

**Comment by suhr** [comment]
> +1

Github have a special button now, you know.

**Comment by darkman088** [comment]
Hello, is it possible to have some update of the status, please ? This is now 1.5 years old...
Many thanks in advance!

**Comment by zetok** [comment]
> Hello, is it possible to have some update of the status, please ?

Well, its status is ~same as other issues tagged with [`help wanted`](https://github.com/tux3/qTox/labels/help%20wanted) – anyone is free to take a stab at fixing it, and when there will be a working fix, it will be merged.

**Comment by photonometric** [comment]
Well a friend just asked me to switch to tox, and after the initial elation of encryption I now have a headache. So I'll help by being slightly annoying and pointing out that the libraries are very clearly spelled out:

[# Text QML Type](http://doc.qt.io/qt-5/qml-qtquick-text.html): starts with a list of real easy stuff like `font.pixelSize`, or the question of whether it should be `font.pointSize : real` so as to be device-independent. I think this issue is mislabeled pretty dramatically. "Help needed?" This isn't a conundrum about encryption issues....a dev with knowledge of where the text code lives needs to drop in a few classes that are readable my non-programmers. 

Given how many devs have agreed about the importance in the past, I'm confused about the reluctance u_u Please Please! It would really fix a basic and long-standing UI issue that is more than annoying for some of us.......

> > - [High DPI Displays](http://doc.qt.io/qt-5/highdpi.html): discusses not only the original problem, but also clipping that occurs because of tiny text on big displays.
> > - QFontMetrics(http://doc.qt.io/qt-5/qfontmetrics.html): some talk of screen (non-printer) and other text metrics, much of it extraneous to current needs.
> > - QPainter Class(http://doc.qt.io/qt-5/qpainter.html) graphical discussion of some of the issues, again with most of the work completed.<<

**Comment by darkman088** [comment]
And again, a lot of opinions, a lot of stong requests to implement this and still nothing...
Does really no developer show interest in managing this task, which on top of its
importance also seems to be quite easy ???

**Comment by antis81** [comment]
> And again, a lot of opinions, a lot of stong requests to implement this and still nothing...

Probably because minority are/were actual coders here. If you like to contribute, feel free to open a PR. Other than that, I will definitely have a look into this and maybe add some "zoom" shortcuts or something like that.

**Comment by Fohroer** [comment]
I know that in new version for Linux font size changes according to GTK font size settings. But that's not the solution of this issue.

**Comment by antis81** [comment]
> I know that in new version for Linux font size changes according to GTK font size settings. But that's not the solution of this issue.

Right. It's fine as a default though.

If I understand the issue right, it's all about changing the chat's font size in settings (maybe zoom via ctrl +/- keys or mouse ctrl+wheel) @zetok right?

**Comment by Fohroer** [comment]
> If I understand the issue right, it's all about changing the chat's font size in settings (maybe zoom via ctrl +/- keys or mouse ctrl+wheel) @zetok right?

Yes.

**Comment by photonometric** [comment]
I remember people in one of the earlier threads were talking about changing it via CSS, then dismissing the idea as absurdly awkward. I would settle for something like that, but I've let my linux go for like a decade >_>

**Comment by antis81** [comment]
> I remember people in one of the earlier threads were talking about changing it via CSS, then dismissing the idea as absurdly awkward.

With my PR, this is actually now possible by adding some minor tweeks. ^^ However, I recommend keeping it simple. So setting a base font & size in qTox settings does the job very well.
