### ISSUE TITLE
[Feature Request] Blinking tray Icon until message is read (friend to friend only)

### ISSUE THREAD

**Issue by towlie** [qTox/qTox#700]
This is usefull when qtox is minimized into tray and you have "Focus qtox when a message is received" disabled.
I personally would only use this kind as notification for new messages. (and the blinking qtox taskbar icon on windows)

**Comment by ProMcTagonist** [comment]
Related?

#666

#483

I'd like this too.

**Comment by ghost** [comment]
I made this poc version (includes implementation ofc): ![blink](https://cloud.githubusercontent.com/assets/7602544/5357894/5f401a8e-7fb6-11e4-8428-eb169bb2f180.gif)
But obviously it does not work with new icons (img/taskbar/taskbar_*.png) because there are no versions that could display a notification. @ItsDuke maybe you could come up with notification icons too?

**Comment by zetok** [comment]
How about something like ![highlighting on new message](https://cloud.githubusercontent.com/assets/3148759/5375573/8f76f1f2-8063-11e4-9171-4bac6e40926d.png) ? (ofc it should blink)

**Comment by ItsDuke** [comment]
@novist @zetok I like both of those, actually. Here are a few I was toying with. They're simple 2-frame animations because I'm not sure how many frames I have at my disposal, so I figured I'd keep it simple for now.

![1](https://cloud.githubusercontent.com/assets/7714365/5389359/12e5708a-80c9-11e4-9001-e9593c4e706e.gif) A simple inset stroke.

![2](https://cloud.githubusercontent.com/assets/7714365/5389360/12e58002-80c9-11e4-8d0a-4bfc9b4d6d67.gif) Swapping of the colors.

![3](https://cloud.githubusercontent.com/assets/7714365/5389361/12e831b2-80c9-11e4-9f2b-31a3f79a68d0.gif) Swapping of the lock color (shown against a blue background for visibility)

**Comment by ghost** [comment]
Tbh to me they all look bit odd. How about the way skype does it? Orange circle with white number of unread messages in it. I suppose that can be even dynamically implemented, meaning drawing circle and number procedurally on current icon.

Also you can check out the way i implemented blinking currently: https://github.com/novist/qTox/tree/tray-new-message-notification. At the moment it is alternating between light and dark icon just like in last image from you @ItsDuke.

**Comment by ProMcTagonist** [comment]
Why is this closed?

**Comment by dubslow** [comment]
...because the tray icon blinks upon notification?

**Comment by ProMcTagonist** [comment]
Neat. Usually it's closed from a commit when that happens, my bad.

**Comment by dubslow** [comment]
The person who wrote the commit has to put a note in the commit message. Putting a note in the pull request unfortunately isn't sufficient. In many cases the author doesn't know or otherwise forgets to put the correct note in the commit message for GitHub to recognize.
