### ISSUE TITLE
Exporting profile does not work

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#716]
There have been instances where I've removed the data folder after exporting a profile but nothing is actually exported.

**Comment by dubslow** [comment]
You mean you export the file to elsewhere on your filesystem, but after removing the tox folder the elsewhere-file disappears as well?

**Comment by bricky149** [comment]
Export to somewhere else. My backup doesn't get updated unless I copy the file manually to the backup location.

**Comment by tux3** [comment]
> My backup doesn't get updated

Well, yes. When you export your profiles, it just makes a copy, it doesn't get continuously updated.
Did you think that qTox would keep updating the backup after you exported it ?

**Comment by bricky149** [comment]
If exporting the profile to a location with a file that exists of the same name it doesn't do anything? That's basically what's happening.

**Comment by dubslow** [comment]
So the issue here is that it's not overwriting the target file if it exists?

For the record, the [code involved](https://github.com/tux3/qTox/blob/master/src/widget/form/settings/identityform.cpp#L163-L171) is _very_ simple:

```
void IdentityForm::onExportClicked()
{
    QString current = bodyUI->profiles->currentText() + Core::TOX_EXT;
    QString path = QFileDialog::getSaveFileName(this, tr("Export profile", "save dialog title"),
                    QDir::home().filePath(current), 
                    tr("Tox save file (*.tox)", "save dialog filter"));
    if (!path.isEmpty())
        QFile::copy(QDir(Settings::getSettingsDirPath()).filePath(current), path);
}
```

Edit: Looked at the docs, copy doesn't overwrite. Fix in a few minutes. Should there be a warning from qTox if the user selects an existing file?
