### ISSUE TITLE
Emoticons button in chat is visible even when the "enable emoticon" is off

### ISSUE THREAD

**Issue by neko259** [qTox/qTox#766]
I go to the settings and disable emoticons. But the button that allows to enter them is still active.

**Comment by tux3** [comment]
Well, it'll just enter a text emoticon.

I'm not sure why we should disable it. It's not very useful, but it's not really a bug.

**Comment by neko259** [comment]
Because if I disabled emoticons, why do I see some emoticons pack to enter? Disabled is disabled, IMO.

**Comment by tux3** [comment]
Yes, I guess.

**Comment by TheLastProject** [comment]
Maybe just replace the icons in the pack with their first text representations in the emoticon list? Seems the prettiest way to solve this case.

Example:
![snapshot107](https://cloud.githubusercontent.com/assets/1885159/5059682/eb9342a8-6d24-11e4-92ec-6bf86b6a045b.png)

(Not sure what to do about emoticons with text representations like :facepalm:, though. Those should probably not be listed?)

**Comment by tux3** [comment]
I think I'll just disable the button entirely instead of showing the text version, otherwise it might get unreadable quick. And the text representations still depend on a particular emoticon pack..

**Comment by zetok** [comment]
It's ugly with text instead of emoticons.

Also, disabling emoticons' box disables one of qTox features which is ability to easily enter some unicode emotes.

I really like that box with emoticons to enter, even though I have emoticons disabled.

@tux3 Please don't remove functionality from qTox.

@neko259 If you say that they should be removed completely, then what do you propose instead, that:
a) wouldn't look ugly (less important)
b) would provide same functionality?

Note that you can't just display emotes in place of emoticons, since e.g. I (and probably many other people) don't have in my system fonts that cover all emotes, which means that in place of them in the box there would be only squares, which isn't the case when box has proper emoticons.

**Comment by neko259** [comment]
@zetok I propose either to remove the button. I simply don't need it, I enter emoticons as text directly. What's the point of keeping a button I won't need?

**Comment by TheLastProject** [comment]
@neko259 Others may need/like to use the functionality. It makes more sense for you to ignore the button if you don't want to use it, than to gray it out for everyone.

**Comment by tux3** [comment]
I agree with @zetok and @TheLastProject, you should just ignore the button, there's no reason to remove that functionality.

Closing for now.

**Comment by neko259** [comment]
@TheLastProject If they want to use the functionality, why do they disable it in settings? This does not make any sense.
I agree it can be closed for now as I cannot imaging a good replacement that will make the button usable for the people that don't want emoticons in any way.
