### ISSUE TITLE
Auto-accept and corresponding folder not being remembered.

### ISSUE THREAD

**Issue by raisingw** [qTox/qTox#775]
Using the GUI to apply auto-accept and the folder is forgotten after closing and reopening. Manually specifying these settings in settings.ini does work and they show on next load. Ubuntu 14.10.

**Comment by dubslow** [comment]
Do you mean the settings page button, or right clicking on contacts? I'm going to guess the former.

**Comment by raisingw** [comment]
Settings page, yes. Contacts right click is remembered.

**Comment by dubslow** [comment]
Err... this patch (move the global settings after the per-friend loop) seems to fix the issue.

```
git diff
diff --git a/src/misc/settings.cpp b/src/misc/settings.cpp
index 0770c42..012fa82 100644
--- a/src/misc/settings.cpp
+++ b/src/misc/settings.cpp
@@ -317,10 +317,10 @@ void Settings::save(QString path)
     s.endGroup();

     s.beginGroup("AutoAccept");
-        s.setValue("autoSaveEnabled", autoSaveEnabled);  
-        s.setValue("globalAutoAcceptDir", globalAutoAcceptDir);
         for (auto& id : autoAccept.keys())
             s.setValue(id, autoAccept.value(id));
+        s.setValue("autoSaveEnabled", autoSaveEnabled);
+        s.setValue("globalAutoAcceptDir", globalAutoAcceptDir);
```

I have no idea what the problem is or why this fix works. I did check that at least one friend's individual folder is also correctly written with this patch.

@tux3 Merge this manually I guess if this doesn't bother you

**Comment by apprb** [comment]
problem is in these lines:

```
for (auto& id : autoAccept.keys())
    s.setValue(id, autoAccept.value(id));
```

and

```
for (auto& key : s.childKeys())
   autoAccept[key] = s.value(key).toString();
```

because `autoSaveEnabled` and `globalAutoAcceptDir` params are also stored in `autoAccept`.

**Comment by dubslow** [comment]
Ah, when I added the AutoAccept group I meant for it to stay separate specifically because of that issue lol.

As long as we put any further items after the for loop in the writing case, I'm inclined to just use the patch above.

Otherwise we can condition the loop body, or maybe move some of these settings to a different group.

**Comment by zetok** [comment]
8f3e1c2ef3c4c5b7af184979940da02b00b8cd9b didn't fix it, since setting still wasn't saved on 0608989f16a2787cadbb11bb1adf8b292d2c96b5; after update to 33cb5a03ec6a41327e47acf0eb20c70deb8a299a I had to (again) set auto accept directory for **contact**.

**Comment by zetok** [comment]
Hm, I think that I know why it didn't work. Directory to which it should have been saved didn't exist after qTox restart, when dir still exists it works.

Makes me wonder though whether there should be some warning/info about it..

**Comment by dubslow** [comment]
Should be easy ~two lines of code, I'll add tomorrow

**Comment by tux3** [comment]
Bump, I guess.

**Comment by zetok** [comment]
I could not reproduce on newest qTox - looks like issue was fixed, thus closing.

Please comment for reopen if you still have this issue.
