### ISSUE TITLE
Renaming users and group chats are inconsistent

### ISSUE THREAD

**Issue by TheLastProject** [qTox/qTox#780]
To rename an user:
1. Right click user in friend list
2. Click "set alias"
3. Type new alias

To rename a group chat:
1. Click on group chat in friend list
2. Click group chat title
3. Enter new title

It would be nice if both had a right-click menu and a click-able name.

**Comment by dubslow** [comment]
I got the aliasing to work the same way as group titles.

apprb mentioned that the only reason he did the menu thing in the first place was because of a bug that I've since fixed.

So would anybody mind if I just removed the ability to set alias from menu, instead of adding group titles to the menu?

**Comment by tux3** [comment]
Well, I like the menu but I dont mind if it goes away either. I guess I'd keep it if I really had to chose. Not sure how others feel.

**Comment by TheLastProject** [comment]
Although clicking the name looks nicer aesthetically, the right-click menu makes the option much easier to find for new users. Personally, I feel it's best to have it in both right-click menus too.
