### ISSUE TITLE
Setting doge as title doesn't seem to work

### ISSUE THREAD

**Issue by zetok** [qTox/qTox#782]
![title doge disappoint](https://cloud.githubusercontent.com/assets/3148759/5062566/98f2a630-6dbd-11e4-9417-8f80ecff1d81.png)
Doge:

```
░░░░░░░░░▄░░░░░░░░░░░░░░▄
░░░░░░░░▌▒█░░░░░░░░░░░▄▀▒▌
░░░░░░░░▌▒▒█░░░░░░░░▄▀▒▒▒▐
░░░░░░░▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐
░░░░░▄▄▀▒░▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐
░░░▄▀▒▒▒░░░▒▒▒░░░▒▒▒▀██▀▒▌
░░▐▒▒▒▄▄▒▒▒▒░░░▒▒▒▒▒▒▒▀▄▒▒▌
░░▌░░▌█▀▒▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐
░▐░░░▒▒▒▒▒▒▒▒▌██▀▒▒░░░▒▒▒▀▄▌
░▌░▒▄██▄▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▌
▀▒▀▐▄█▄█▌▄░▀▒▒░░░░░░░░░░▒▒▒
```

**Comment by tux3** [comment]
After some testing, it appears that this is a core issue !

**Comment by zetok** [comment]
Yes, to my knowledge groupchat title is limited (IIRC 128 characters?), which means that qTox shouldn't show doge as set title, but only the part that was actually set.

**Comment by tux3** [comment]
No, that's not a problem with the Doge ascii art being too long.

If you try to set a title that is too long, it will not be set at all.
Your doge text is accepted by toxcore (if it wasn't nothing would happen), but not received correctly on the other side.

**Comment by dubslow** [comment]
Something is wrong here; core should definitely have rejected anything longer than 128 bytes.

Zetok, just how many bytes is that?

Edit: I just checked, and core definitely returns -1 if it's too long, and qTox definitely checks the return as well.

Also, what the hell lol.

**Comment by zetok** [comment]
![gentoo says it's a qTox issue..](https://cloud.githubusercontent.com/assets/3148759/5063206/d5997700-6dd4-11e4-97cb-469223803f6c.png)

**Comment by zetok** [comment]
I've checked, and µTox doesn't seem to display it correctly.

**Comment by tux3** [comment]
µTox shows the same bug on my end. The end of the title is ░▌▒█░░░ (on both qTox and µTox), wich is part of the second line (doge's left ear), so clearly µTox tries to show more than one line, but didn't receive all of it.

@irungentoo, if it works for you, could you post a screenshot of what you're seeing so that I can try to reproduce ?

![image18](https://cloud.githubusercontent.com/assets/5155966/5063339/ce213c20-6de2-11e4-98b8-771f8971ecc3.jpg)

**Comment by dubslow** [comment]
So it definitely is under 128 bytes?
