### ISSUE TITLE
[Trivial] Contact list width changes when you go to settings

### ISSUE THREAD

**Issue by bricky149** [qTox/qTox#786]
My contact list is wider than the default so when I go to the settings it sets it back to the minimum width (and can't be changed) but when I go back to a contact/group it resets the width to what it was before.

**Comment by TheLastProject** [comment]
I can't seem to reproduce this myself. I can make my contact list as wide as it goes, then go to settings and have it remain that wide. It does mean I get a horizontal scrollbar in settings, though, which is bad too.

**Comment by tux3** [comment]
The settings have a bigger minimum size than the chat, so it pushes back the contact list a little.

We can't really do anything about that, and it depends on what style you use. Before we did that, it caused the contact list to disappear entirely sometimes because there just wasn't enough room.

I think this can be closed because there really isn't a better solution, unless I don't understand what you're saying ?

**Comment by bricky149** [comment]
The width also resets upon restarting qTox too.

**Comment by tux3** [comment]
Closing because the current behavior is by design.
