### ISSUE TITLE
Splitter improvement

### ISSUE THREAD

**Issue by msteinbeck** [qTox/qTox#79]
The currently implemented splitter has two, in my mind not very useful "features":
1. The friend list and chat/add friends/settings (i will simply name it chat widget) widgets have a minimal width. If the main widgets width is very small it feels somehow uncomfortable since you cannot really move the slider to adjust the widgets to your needs. A minimal width for the friend list widget should be ok because it contains some buttons at the bottom which needs a minimal width to be rendered correctly. After "fixing" #77 and #78 the chat widget does not need a minimal width and thus it should be removed.
2. If I resize the friend list widget using the slider the buttons at the bottom will also move and increase the gap between them but should stay at the left (or at the center).

**Comment by F1ynn** [comment]
1)   It's virtually impossible to read anything in the chat if it gets much smaller than the current minimum, I'm not sure why you would want that. Could you perhaps expand on your use case a little bit? We could make the splitter panes collapsible, but that goes against what I've seen of the mockup.

2)   That's by design, I thought it looked significantly better than leaving them in the center or on either edge (both of which I tried first).

**Comment by msteinbeck** [comment]
> It's virtually impossible to read anything in the chat if it gets much smaller than the current minimum, I'm not sure why you would want that. Could you perhaps expand on your use case a little bit? We could make the splitter panes collapsible, but that goes against what I've seen of the mockup.

I think GUIs should support a users behavior, not restrict it. If someone (why ever) wants to resize the chat view to a very small width, than he should be allowed to do it (customizability). The only reasons to restrict customizability are (in my mind):
1. Not implementable 
2. You cannot (or it's very hard and makes things to complex) ensure data correctness

Since 1 and 2 are not given, we should allow this feature.

> That's by design, I thought it looked significantly better than leaving them in the center or on either edge (both of which I tried first).

If users prefer this behavior, we should keep it. My personal opinion is to leave icons at the left :).

**Comment by F1ynn** [comment]
I respectfully disagree with you on the first part, I think having a minimum window size is perfectly reasonable (and a concept used by most applications).

Both of these are trivial to change, and both ultimately up to Tux3. I'll stand down here and let you two figure it out.

**Comment by msteinbeck** [comment]
>  (and a concept used by most applications)

A concept, I hate in most applications :D. 

Please do not misunderstand my comment. I didn't want to fight your point of view. Moreover it was just an idea.

**Comment by tux3** [comment]
> If someone (why ever) wants to resize the chat view to a very small width, than he should be allowed to do it (customizability)

I agree that not allowing it for the sake of not allowing it is silly and frustrating when you do want/need it. I'm fine with a lower minimum width, as long as it doesn't break anything. Right now if you grow the friendlist all the way to the right, the widgets of the chat form will happilly overflow past the edge of the window instead of just shrinking.

> If I resize the friend list widget using the slider the buttons at the bottom will also move and increase the gap between them but should stay at the left (or at the center).

And I'm gonna agree with Flynn on this one. In my opinion it looks really weird no matter what when you scale up the window and the buttons can't scale, but I personnally think it makes more sense to keep them like this.

That said, I have no tastes, and if more people disagree with this I'll happilly change it :)

**Comment by msteinbeck** [comment]
> That said, I have no tastes, and if more people disagree with this I'll happilly change it :)

I think keeping it open one day or two should be fair enough. If no one leaves a comment just close this ticket and I'm fine with it :)

**Comment by tux3** [comment]
Sure

**Comment by msteinbeck** [comment]
I think we can close this ticket as invalid
