### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by tux3** [qTox/qTox#795]
Reported by sda

<blockquote><pre>
visual: blurry button icons, I just like how uTox chat window looks, it's more compact than qTox's, more content, just looks better imo; uTox has also prettier file transfer widget, qTox's one feels a bit too large and the icons are blurry and a bit misaligned, the progress bar color and height look better in uTox
also, settings tab icons don't fit the overall design
non-visual: I like the desktop sharing feature
and use it a lot

<blockquote>Too much space between text ? The window can't be downsized enough ?</blockquote>

both

uTox has also smaller text size
and uses a smaller font for timestamps

also, the chat window looks a bit ugly when selected
http://a.pomf.se/nmokrz.png
</pre></blockquote>

**Comment by zetok** [comment]
Smaller font size isn't a feature.

**Comment by ghost** [comment]
But if you let the user choose the font (size), that would be a feature. :smile:

**Comment by DanTheBritish** [comment]
Oh lord I seriously need a larger font, not smaller. Refer: #530 for screenshots of how it looks on my monitor.

**Comment by dubslow** [comment]
Honestly the main reason I don't leave tox open all the time is because the chat form is a _lot_ less compact than my IRC client, i.e. sda is totally right :P

For the same area, my IRC client fits twice the number of text/lines as qTox.

And yet obviously, many people have the exact opposite reaction lol.

For me, I think what bothers me is the line spacing much more than the font size. I would prefer single spaced lines with a larger font to what we have currently.

@krepa098 things to consider for new chat form :P

**Comment by apprb** [comment]
@LapFox qTox uses a system wide default font, as every other application, if you need something bigger tune your system settings (change system font, change dpi, etc.)

**Comment by DanTheBritish** [comment]
@apprb Well that's not very user friendly for users who may be on other high-dpi devices (Surface Pro anybody?) so whilst it's a temporary solution for now, there should be an option in qTox for it.

**Comment by krepa098** [comment]
> And yet obviously, many people have the exact opposite reaction lol.

Yeah I like non crowded chat logs :) It's not an IRC client after all. As for high-dpi, I think the toolkit (Qt) should handle that and it seems like Qt 5.4 is providing the necessary bits and pieces. 
(see http://blog.davidedmundson.co.uk/blog/kde_apps_high_dpi)

**Comment by agilob** [comment]
please close(?)
