### ISSUE TITLE
Windows compilation instructions incomplete

### ISSUE THREAD

**Issue by QuantumRipple** [qTox/qTox#843]
Instructions for windows compilation end (linux instructions begin) immediately after explaining dependency compilation without explaining how to actually compile qTox.

Furthermore, there may be more dependencies or a mistake in the instructions for the dependencies. After running qmake and make with qtox.pro, the project failed to find the following libraries while linking: jpeg, tiff, png, jasper, IlmImf, Half.

qtox.pro file also needs to be modified to update the opencv version number from 248 to 249: "-lopencv_core249 -lopencv_highgui249 -lopencv_imgproc249"

**Comment by dubslow** [comment]
@tux3, maybe you can add some notes about your setup?

**Comment by tux3** [comment]
Unfortunately, compiling qTox on Windows is not easy. Or rather, gathering all the dependencies is not easy.

What I did is that I cross-compiled the dependencies once using <a href="http://mxe.cc/">MXE</a> on Linux, and then link with those when I compile qTox on Windows. I put all the dependencies in the "libs" subfolder so that qmake can find them.
I usually use  QtCreator to compile qTox on Windows.

You can simply download my version of the compiled dependencies <a href="https://mega.co.nz/#!osZl2S5J!_BfI2hNNCum4EV1P6X-FPSMNIfcdgwa9igEYWzckl8Y">here</a> but this might not work depending on your exact compiler version and the phase of the moon.

If you still want to compile the dependencies, but not do it on Linux with MXE (which usually takes at least half a day), you can try compiling each dependency on Windows directly by going through the respective documentations of every dependency (although that can be tricky). I don't have detailed steps for that at the moment.

> qtox.pro file also needs to be modified to update the opencv version number from 248 to 249: "-lopencv_core249 -lopencv_highgui249 -lopencv_imgproc249"

Note that any version of OpenCV >= 2.3 should work, I just happen to have 248 on my system.

**Comment by cebe** [comment]
> Note that any version of OpenCV >= 2.3 should work, I just happen to have 248 on my system.

I can confirm that, qTox works fine with 2.3.1 for me.

**Comment by ghost** [comment]
Actually more detailed windows build instructions would be really nice. Like cross-compiling how-to. No need for everyone to go through pains of figuring it out. Core has nice basic how-to how to cross-compile it all. If qTox had that it would really help testing stuff on windows (for me at least).

**Comment by QuantumRipple** [comment]
Your uploaded binary libraries helped with the libraries not mentioned in the existing instructions, although instructions on how to [cross] compile these would still be appreciated.

After using the bootstrap.bat script to get the latest tox core from http://jenkins.libtoxcore.so/job/libtoxcore-win32-i686/lastSuccessfulBuild/artifact/libtoxcore-win32-i686.zip, it appears that I have all the library dependencies, but the build still fails. Is this the right place to grab from?

I get undefined references to the following functions from within tox core (libtoxcore.a, libtoxencryptsave.a, libtoxdns.a):
crypto_box_keypair
crypto_hash_sha256
crypto_pwhash_scryptsalsa208sha256
sodium_memzero
randombytes
crypto_box_afternm
crypto_box_open_afternm
crypto_box_beforenm
crypto_verify_16
crypto_verify_32
GetAdaptersInfo@8

They appear to (at least the ones I checked) be a part of libsodium. I've tried both the libsodium included in your upload and the version included with the tox core binary, but no dice.
Any thoughts?

**Comment by tux3** [comment]
I think that the toxcore you got from http://jenkins.libtoxcore.so/job/libtoxcore-win32-i686/lastSuccessfulBuild/artifact/libtoxcore-win32-i686.zip is not compatible with the other libraries. As in, not the same compiler version/phase of the moon.

Try building toxcore yourself with the same compiler maybe. I can't really help more without the compile log. Maybe you just need to change the linking order.
