### ISSUE TITLE
Minimum window size is too large

### ISSUE THREAD

**Issue by dubslow** [qTox/qTox#867]
I can't fit qTox into one corner/quarter of my laptop screen...

**Comment by tux3** [comment]
Note that if we make it too small, the main QSplitter will have graphical glitches (e.g. hide the contact list completely because there's not enough room to show it anymore).

**Comment by dubslow** [comment]
I doubt that will be an issue -- there's plenty of horizontal space to spare in the main part, and vertically there's obviously also tons of leeway.

http://imgur.com/a/fX6FO

The bottom is my normal workflow, the top is with oversized-yet-minimal qTox in the way :P

**Comment by tux3** [comment]
It actually is an issue in the settings form.

The more room there is to move the main slider (=resize the contact list), the more you can reduce the minimum size without causing bugs.
Try to move the main slider in the settings form, you shouldn't be able to move it much if at all, because the settings form's actual minimum minimum size is just a tiny bit less than qTox's minimum size to avoid the bug.

**Comment by zetok** [comment]
Should be solved with #1938, which lets detached windows to be quite small.

**Comment by zetok** [comment]
#1938 was merged, thus closing.
