### ISSUE TITLE
Avatars displaying with colored backgrounds should be optional

### ISSUE THREAD

**Issue by ProMcTagonist** [qTox/qTox#944]
The top image gets a blue background. Another png preview of an svg with a transparent background does not. Not sure why.
![avatar transparency glitch](https://cloud.githubusercontent.com/assets/4358079/5481444/52b1990e-8606-11e4-8fc0-c70ec3378ab6.png)

The two images are here in case of GitHub doing anything to them.
http://a.pomf.se/rysqjl.tar.gz

**Comment by dubslow** [comment]
Is deliberate -- the background color is chosen to best contrast the avatar.

**Comment by ProMcTagonist** [comment]
I see now...
![smart background](https://cloud.githubusercontent.com/assets/4358079/5481766/ecb3782a-860a-11e4-93a0-5ffdd8f6c779.png)

I think most of those would look better with the dark grey background they're already over. Is this a client-side thing or is the image modified?

**Comment by zetok** [comment]
@dubslow in effect it looks disgusting (at least for me)

**Comment by dubslow** [comment]
Client side @krepa098

**Comment by krepa098** [comment]
We already had this discussion (#334). The solution was quite simple: Don't use a transparent background if you're unhappy with qTox's choice. There is no way to calculate the perfect background color although the luminosity component of the color needs some tweaks...

**Comment by dubslow** [comment]
Ah yes, forgot that. Making your own background color works great :)

**Comment by ProMcTagonist** [comment]
A red orb doesn't need a blue background to be visible on dark grey or white. You're meddling with people's avatars and it's confusing and most of the time completely unnecessary. Every example I posted would look better without the background meddling. As of now you have completely denied users the ability to have non-roundrect avatars.

**Comment by dubslow** [comment]
Many avatars are equally useless with white backgrounds, ditto black/grey backgrounds. For any background color we choose, there will always be perfectly good avatars for which that particular background is a terrible choice. The original issue has some extensive discussion on the matter. This is the best alternative, and frankly using an image that isn't transparent is very simple and renders the whole subject moot.

**Comment by zetok** [comment]
> We already had this discussion (#334). The solution was quite simple: Don't use a transparent background if you're unhappy with qTox's choice. There is no way to calculate the perfect background color although the luminosity component of the color needs some tweaks...

:/

> The solution
> Don't use a transparent background if you're unhappy with qTox's choice.

Why are you telling user what to do? You know that it **results in really bad UX** when program does some weird and ugly shit with their and their friends' images? If it was nicely done, most of people wouldn't care _too much_ about that, but you admit that it's impossible to do it in sane way:

> There is no way to calculate the perfect background color

# 

> Many avatars are equally useless with white backgrounds, ditto black/grey backgrounds.

Do you really think that people are too stupid to notice that their avatar is not visible? Why do you insist on treating them like complete morons unable to perform basic task called thinking?

> This is the best alternative (…)

@dubslow 
Why do you think that doing some weird thing **against users' will** is the best possible course of action?

If you care about alternative, let user choose whether they want that "feature".

Edit: pls reopen, since it's still not fixed and causes visual problems

**Comment by suhr** [comment]
cast @ItsDuke

**Comment by ItsDuke** [comment]
@suhr haha, not sure what you're expecting from me, but @zetok got it right. The user (in my opinion) should be allowed to upload their own image, and if the background is transparent, then honor that transparency, and not force a color upon them.

**Comment by zetok** [comment]
https://img.bi/#/thR0gR5!jHYSR3YU2PaOVPIV9YHNFMeAUeNprNtjWRUtofiq  qTox | µTox
↑ here's a screenshot where apparently it works nicely, so I think that an option to turn it off/on would be the best.

**Comment by Zer0-One** [comment]
I agree with zetok on this. The user should be able to toggle this feature on and off.

**Comment by ProMcTagonist** [comment]
I don't agree that @zetok's example is of it working nicely. That screenshot shows qTox lying to a user about what their avatar looks like to their friends, potentially causing confusion. It works well in that it looks good, yes, but that hides how different (possibly bad) it looks to everyone else.
If there has to be an option, it should be between doing nothing to the image and sending the colored background version to contacts, in my opinion.

**Comment by agilob** [comment]
> Is deliberate -- the background color is chosen to best contrast the avatar.

Bug by design ;)

**Comment by rugk** [comment]
I also completely agree to @zetok (see https://github.com/tux3/qTox/issues/2165 for more info).

If I want to use a transparent background then I'm doing this because the parts should be transparent (and showing the customizable background colour of the qTox window). If I want to work around this I currently have to use a colour picker and pick the colour of the window and add it. That's uncomfortable!

**Comment by Getron** [comment]
+1
