### ISSUE TITLE
Some contacts are lost when qtox is restarted

### ISSUE THREAD

**Issue by ghost** [qTox/qTox#977]
Every time I restart qtox all except my first contact are lost.
I have to add this contact again to have it in my contact list or add them using utox which adds them in a persistant manner.

I've recorded the behaviour: http://youtu.be/uxuFAhFwuLE

**Comment by dubslow** [comment]
Can you test an alternate client? What about if you change your status? It looks like you've used uTox before, can you say what's in the profile drop down on the identity settings tab? Finally, can you `ls ~/.config/tox/` and post (pastebin or gist) the contents of qtox.ini in that folder?

**Comment by ghost** [comment]
With utox (the first client I tried - therefore utox also created the config files) new contacts are preserved across application restarts - even qtox successfully loads and preserved contacts added using utox.
It seems also other modifications are not stored. My profile comment is still "toxing on utox", when I change it to "toxing on qtox" it is lost after qtox is closed and opened again.

My qtox.ini: http://pastebin.com/XjSR6JKJ
folder-contents of .config/tox: http://pastebin.com/hgZsXd6z

Furthermore, I have to start qtox with the following command-line flag, otherwise it doesn't open my profile:
qtox -P 4D2748651E7E9EB5D5E1D3283D75E1E92D002EE864BB01E5B5E24ED11D097550

**Comment by dubslow** [comment]
Hmm, _seems_ to be a bug in the code that decides which file to load from; it's reading the tox_save file from uTox, rather than ceisserer.rox like it's supposed to (and where the changes are saved). Additionally, you are passing a profile that doesn't exist on the command-line... should probably check that and warn... unfortunately I can't really do any development currently... Can you post the contents of qtox.log (or perhaps just the last couple of runs...), and also try it without passing the -P flag?

Thanks for your help.

**Comment by ghost** [comment]
Sure, please find the qtox.log here: http://pastebin.com/3i5NUcgP

Indeed the cause of the problem was specifiying another profile - very strange.
I remember I had to specify that option, otherwise qtox wouldn't read my profile created with utox - however now it doesn't seem to be nescessary and everything works as expected.

**Comment by dubslow** [comment]
So it works now, and the only thing that needs to happen is error handling the -P option?

@tux3 the log above shows consistent threading issues when he stops a call...

**Comment by tux3** [comment]
@dubslow That timer threading issue should now be fixed.
